import {expect,test,type Page} from '@playwright/test';
import {dashboardConformanceReferences as reference} from '../apps/dashboard/src/design-conformance';
async function notesSetup(page:Page,role='staff',theme='light') {
 let granted=true,enabled=true,fail=0;const writes:any[]=[];const requests:string[]=[];
 const sections={version:1,revision:0,notesEnabled:true,summaryEnabled:true,filesEnabled:true};
 const activity={id:'activity',title:'Synthetic service',serviceDate:'2026-09-10',revision:2,archived:false,impactRelevant:true};
 const notes:any[]=[{id:'note',activityId:'activity',text:'<script>private note</script>',revision:0,archived:false,authorUserId:'synthetic-author',createdAt:'2026-09-10T12:00:00Z',updatedAt:'2026-09-10T12:00:00Z'}];
 await page.addInitScript(value=>localStorage.setItem('lancerlogin-theme',value),theme);
 await page.route('**/setup/status',r=>r.fulfill({json:{configured:true,installation:{authMode:'local'},settings:{organizationName:'Synthetic Documentation',primaryColor:reference.brand.primary,secondaryColor:reference.brand.secondary,appearance:theme}}}));
 await page.route('**/auth/session',r=>r.fulfill({json:{user:{id:'synthetic',role}}}));
 await page.route('**/admin/setup/progress',r=>r.fulfill({json:{completedSteps:['branding','roster','pair-kiosk','fingerprint-test','confirm-attendance'].map(step=>({step}))}}));
 await page.route('**/platform/modules',r=>r.fulfill({json:{capabilities:granted&&enabled?['documentation.manage']:[],modules:[{id:'hour-tracking',enabled,capabilities:['hours.manage'],navigation:{path:'/hours',label:'Hour Tracking'}},{id:'activity-documentation',enabled,capabilities:['documentation.manage'],navigation:{path:'/documentation',label:'Activity Documentation'}}]}}));
 await page.route('**/admin/documentation/**',async r=>{const req=r.request(),url=new URL(req.url()),path=url.pathname.replace('/admin/documentation','');requests.push(url.pathname+url.search);
 if(req.method()!=='GET'){const body=req.postDataJSON();writes.push(body);if(fail){await r.fulfill({status:fail,json:{error:'Synthetic conflict'}});return;}if(path==='/sections'){Object.assign(sections,body,{revision:sections.revision+1});await r.fulfill({json:sections});return;}let n=path.startsWith('/notes/')?notes.find(n=>n.id===path.split('/')[2]):undefined;if(n)Object.assign(n,body,{revision:n.revision+1});else{n={...notes[0],...body,id:'created',revision:0};notes.push(n);}await r.fulfill({json:{note:n}});return;}
 if(!granted||!enabled){await r.fulfill({status:403,json:{error:'Unavailable'}});return;}
 if(path==='/sections'){await r.fulfill({json:sections});return;}
 if(path==='/activities'){await r.fulfill({json:{activities:[activity],next:url.searchParams.has('after')?null:'next-activity'}});return;}
 if(path==='/activities/activity'){await r.fulfill({json:{...activity,readOnly:activity.archived||!activity.impactRelevant,sectionRevision:sections.revision,...(sections.summaryEnabled?{summary:{countedMinutes:0,distinctParticipants:0}}:{})}});return;}
 if(path==='/activities/activity/notes'){await r.fulfill({json:{notes,next:url.searchParams.has('after')?null:'next-note',readOnly:activity.archived||!activity.impactRelevant||!sections.notesEnabled,activityRevision:activity.revision,sectionRevision:sections.revision}});return;}
 if(path.endsWith('/history')){await r.fulfill({json:{revisions:[{revision:url.searchParams.has('after')?1:0,text:'<b>Original text</b>',archived:false,createdAt:'2026-09-10'}],next:url.searchParams.has('after')?null:0}});return;}
 await r.fulfill({json:{note:notes.find(n=>n.id===path.split('/')[2])}});
 });
 return {sections,activity,notes,writes,requests,revoke:()=>granted=false,disable:()=>enabled=false,fail:(status:number)=>fail=status};
}
async function contextSetup(page:Page,role='staff',theme='light'){
 const docs=await notesSetup(page,role,theme);let fail=0;const writes:any[]=[];const reads:string[]=[];
 const activity={activityId:'activity',title:'Synthetic service',revision:2,archived:false,impactRelevant:true};
 const items:any[]=[{id:'first',title:'Synthetic initiative',narrative:'<b>Private narrative</b>',revision:0,archived:false,createdAt:'2026-09-10',updatedAt:'2026-09-10',activities:[activity]},{id:'second',title:'Shared initiative',narrative:'Second narrative',revision:0,archived:false,activities:[activity]}];
 await page.route('**/admin/documentation/initiatives**',async route=>{const req=route.request(),url=new URL(req.url()),path=url.pathname.replace('/admin/documentation/initiatives','');reads.push(path+url.search);const item=items.find(i=>i.id===path.split('/')[1]);
 const total=(selected:any[])=>{const eligible=selected.some(i=>!i.archived)&&!activity.archived&&activity.impactRelevant;return {linkedActivityCount:selected.some(i=>i.activities.length)?1:0,eligibleActivityCount:eligible&&selected.some(i=>i.activities.length)?1:0,omittedActivityCount:!eligible&&selected.some(i=>i.activities.length)?1:0,...(docs.sections.summaryEnabled?{summary:{countedMinutes:eligible&&selected.some(i=>i.activities.length)?90:0,distinctParticipants:eligible&&selected.some(i=>i.activities.length)?2:0}}:{})};};
 if(path==='/summary'){const ids=req.postDataJSON().initiativeIds;if(ids.some((value:string)=>!items.some(i=>i.id===value))){await route.fulfill({status:404,json:{error:'Unavailable'}});return;}await route.fulfill({json:total(items.filter(i=>ids.includes(i.id)))});return;}
 if(req.method()!=='GET'){const body=req.postDataJSON();writes.push(body);if(fail){await route.fulfill({status:fail,json:{error:'Conflict'}});return;}const value=item??{id:'created',revision:-1,archived:false,activities:[]};const members=body.activities?.map((a:any)=>({...activity,...a}))??value.activities;Object.assign(value,body,{activities:members,revision:value.revision+1});if(!item)items.push(value);await route.fulfill({json:{initiative:value}});return;}
 if(path.endsWith('/history')){await route.fulfill({json:{revisions:[{revision:url.searchParams.has('after')?1:0,title:'Original title',narrative:'<script>Historical narrative</script>',archived:false,createdAt:'2026-09-10',activityIds:['activity'],activities:[{activityId:'activity',title:'Current synthetic service title'}]}],next:url.searchParams.has('after')?null:0}});return;}
 if(!path){await route.fulfill({json:{initiatives:items.filter(i=>url.searchParams.get('archival')==='true'||!i.archived),next:url.searchParams.has('after')?null:'next'}});return;}
 if(!item){await route.fulfill({status:404,json:{error:'Unavailable'}});return;}
 await route.fulfill({json:{initiative:item,activities:item.activities.map((a:any)=>({...a,archived:activity.archived,impactRelevant:activity.impactRelevant})),readOnly:item.archived,...total([item])}});
 });
 return {...docs,items,activity,writes,reads,fail:(value:number)=>fail=value};
}
async function setup(page:Page,role='staff',theme='light'){
 const ctx=await contextSetup(page,role,theme);const writes:any[]=[];const requests:string[]=[];let fail=0,readback=false;
 const activity={activityId:'activity',title:'Synthetic service',revision:2,eligible:true};const initiative={initiativeId:'first',title:'Synthetic initiative',revision:0,eligible:true};
 const records:any[]=[{id:'artifact',title:'Synthetic evidence',kind:'external-link',caption:'<b>Synthetic caption</b>',url:'https://example.test/evidence',originalUrl:'https://example.test/evidence',review:null,authorUserId:'synthetic-author',revision:0,archived:false,createdAt:'2026-09-10T12:00:00Z',updatedAt:'2026-09-10T12:00:00Z',activities:[activity],initiatives:[initiative]}];
 await page.route('**/admin/documentation/artifacts**',async route=>{const req=route.request(),url=new URL(req.url()),path=url.pathname.replace('/admin/documentation/artifacts','');requests.push(path+url.search);const record=records.find(item=>item.id===path.split('/')[1]);
 if(req.method()!=='GET'){const body=req.postDataJSON();writes.push(body);if(fail){await route.fulfill({status:fail,json:{error:'Synthetic conflict'}});return;}const value=record??{...records[0],id:'created',revision:-1};const review=path.endsWith('/review')?{decision:body.decision,reviewedRevision:value.revision,reviewerUserId:'synthetic-reviewer',reviewedAt:'2026-09-10T13:00:00Z'}:null;Object.assign(value,body,{review,revision:value.revision+1,activities:body.activities?.map((item:any)=>({...activity,...item}))??value.activities,initiatives:body.initiatives?.map((item:any)=>({...initiative,...item}))??value.initiatives});if(!record)records.push(value);await route.fulfill({json:{artifact:value}});return;}
 if(!path){await route.fulfill({json:{artifacts:records.filter(item=>url.searchParams.get('archival')==='true'||!item.archived),next:url.searchParams.has('after')?null:'next-artifact'}});return;}
 if(path.endsWith('/history')){await route.fulfill({json:{artifactId:'artifact',authorUserId:'synthetic-author',createdAt:'2026-09-10T12:00:00Z',revisions:[{...records[0],kind:undefined,id:undefined,authorUserId:undefined,updatedAt:undefined,review:null,revision:url.searchParams.has('after')?1:0,caption:'<script>Historical caption</script>',activities:[{...activity,title:'Current historical activity'}],initiatives:[{...initiative,title:'Current historical initiative'}]}],next:url.searchParams.has('after')?null:0}});return;}
 if(!record||readback&&writes.length){await route.fulfill({status:404,json:{error:'Unavailable'}});return;}
 await route.fulfill({json:{artifact:record,activities:record.activities,initiatives:record.initiatives,readOnly:record.archived||!ctx.sections.filesEnabled,filesEnabled:ctx.sections.filesEnabled,sectionRevision:ctx.sections.revision}});
 });return {...ctx,records,activity,initiative,writes,requests,fail:(value:number)=>fail=value,readback:(value:boolean)=>readback=value};
}
async function enter(page:Page){await page.goto('/documentation');await page.getByRole('button',{name:'Artifacts',exact:true}).click();}
async function fill(page:Page){await page.getByLabel('Artifact title',{exact:true}).fill('New synthetic artifact');await page.getByLabel('Caption',{exact:true}).fill('Synthetic caption');await page.getByLabel('Source URL',{exact:true}).fill('https://example.test/new');}
test('retained ineligible contexts allow independent edits and removal with pagination',async({page})=>{const f=await setup(page);f.activity.eligible=false;f.initiative.eligible=false;await enter(page);await page.getByRole('button',{name:'Next artifacts page'}).click();await expect.poll(()=>f.requests.some(p=>p.includes('after=next-artifact'))).toBe(true);await page.getByRole('button',{name:'Open Synthetic evidence',exact:true}).click();await expect(page.getByText('Synthetic service · Activity · Currently ineligible',{exact:true})).toBeVisible();await page.getByLabel('Caption',{exact:true}).fill('Revised independent method');await page.getByRole('button',{name:'Save artifact',exact:true}).click();await expect(page.getByText('Saved and confirmed',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Remove Synthetic service'}).click();await page.getByRole('button',{name:'Remove Synthetic initiative'}).click();await page.getByRole('button',{name:'Save artifact',exact:true}).click();await expect.poll(()=>f.writes.length).toBe(2);expect(f.writes[1]).toMatchObject({activities:[],initiatives:[]});await page.getByRole('button',{name:'Next activities choices page'}).click();await expect(page.getByRole('button',{name:'Next activities choices page'})).toHaveCount(0);await page.getByRole('button',{name:'Next initiatives choices page'}).click();await expect(page.getByRole('button',{name:'Next initiatives choices page'})).toHaveCount(0);});
test('conflict and uncertain readback preserve drafts and require explicit reload',async({page})=>{const f=await setup(page);await enter(page);await page.getByRole('button',{name:'Open Synthetic evidence',exact:true}).click();await page.getByLabel('Caption',{exact:true}).fill('2.000');f.fail(409);await page.getByRole('button',{name:'Save artifact',exact:true}).click();await expect(page.getByRole('alert')).toContainText('No write is retried');await expect(page.getByRole('button',{name:'Save artifact',exact:true})).toBeDisabled();f.fail(0);await page.getByRole('button',{name:'Reload artifacts'}).click();await expect(page.getByLabel('Caption',{exact:true})).toHaveValue('2.000');f.readback(true);await page.getByRole('button',{name:'Save artifact',exact:true}).click();await expect(page.getByRole('alert')).toBeVisible();f.readback(false);await page.getByRole('button',{name:'Reload artifacts'}).click();await expect(page.getByRole('button',{name:'Save artifact',exact:true})).toBeEnabled();expect(f.writes).toHaveLength(2);});
for(const role of ['operator','staff'])test(role+' without Documentation grant denied artifacts',async({page})=>{const f=await setup(page,role);f.revoke();await page.goto('/documentation');await expect(page.getByRole('heading',{name:'Workspace unavailable'})).toBeVisible();expect(f.requests).toHaveLength(0);});
for(const kind of ['grant','module'])test(kind+' removal clears artifact draft',async({page})=>{const f=await setup(page);await enter(page);await page.getByRole('button',{name:'Open Synthetic evidence',exact:true}).click();await page.getByLabel('Caption',{exact:true}).fill('Private draft');kind==='grant'?f.revoke():f.disable();await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByRole('heading',{name:'Workspace unavailable'})).toBeVisible();await expect(page.getByLabel('Caption',{exact:true})).toHaveCount(0);});
test('delayed artifact read cannot restore content after access revocation',async({page})=>{const f=await setup(page);let release=()=>{};const gate=new Promise<void>(resolve=>release=resolve);await page.route('**/admin/documentation/artifacts/artifact',async r=>{await gate;await r.fallback();});await enter(page);await page.getByRole('button',{name:'Open Synthetic evidence',exact:true}).click();f.revoke();await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByRole('heading',{name:'Workspace unavailable'})).toBeVisible();release();await expect(page.getByLabel('Caption',{exact:true})).toHaveCount(0);});
test('delayed write remains serialized during access refresh',async({page})=>{const f=await setup(page);let release=()=>{};const gate=new Promise<void>(resolve=>release=resolve);await page.route('**/admin/documentation/artifacts/artifact',async r=>{if(r.request().method()==='PATCH')await gate;await r.fallback();});await enter(page);await page.getByRole('button',{name:'Open Synthetic evidence',exact:true}).click();const requested=page.waitForRequest(r=>r.method()==='PATCH');await page.getByRole('button',{name:'Save artifact',exact:true}).click();await requested;await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByRole('button',{name:'Reload artifacts'})).toBeDisabled();release();await expect(page.getByRole('button',{name:'Reload artifacts'})).toBeEnabled();await expect(page.getByRole('button',{name:'Save artifact',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Reload artifacts'}).click();await expect(page.getByRole('button',{name:'Save artifact',exact:true})).toBeEnabled();expect(f.writes).toHaveLength(1);});
test('new activity losing eligibility must be removed from draft',async({page})=>{await setup(page);await enter(page);await page.getByRole('button',{name:'Create artifact',exact:true}).click();await fill(page);await page.getByLabel('Associate Synthetic service').check();await page.route('**/admin/documentation/activities/activity',r=>r.fulfill({status:404,json:{error:'Unavailable'}}));await page.getByRole('button',{name:'Reload artifacts'}).click();await expect(page.getByText('Unavailable new association; remove before saving',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'Save artifact',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Remove Synthetic service'}).click();await expect(page.getByRole('button',{name:'Save artifact',exact:true})).toBeEnabled();});
async function keyboardSave(page:Page){
 // Opening performs asynchronous reads and then a passive heading-focus effect.
 // The page h1 exists before both finish and is not an editor readiness signal.
 await expect(page.getByRole('heading',{name:'Edit artifact',exact:true})).toBeFocused();
 const save=page.getByRole('button',{name:'Save artifact',exact:true});
 await expect(save).toBeEnabled();
 // Exercise keyboard modality rather than programmatic focus after an unrelated Tab.
 for(let step=0;step<64;step++){
  await page.keyboard.press('Tab');
  if(await save.evaluate(element=>element===document.activeElement))break;
 }
 await expect(save).toBeFocused();
 await expect.poll(()=>save.evaluate(element=>element.matches(':focus-visible')&&getComputedStyle(element).outlineStyle!=='none')).toBe(true);
 return save;
}

test('artifact editor keyboard readiness waits for delayed detail read',async({page})=>{
 await setup(page);
 let release!:()=>void;
 const gate=new Promise<void>(resolve=>{release=resolve;});
 await page.route('**/admin/documentation/artifacts/artifact',async route=>{await gate;await route.fallback();});
 await enter(page);
 const requested=page.waitForRequest(request=>new URL(request.url()).pathname.endsWith('/artifacts/artifact'));
 await page.getByRole('button',{name:'Open Synthetic evidence',exact:true}).click();
 await requested;
 let ready=false;
 const pending=keyboardSave(page).then(()=>{ready=true;});
 try{
  await expect(page.getByRole('button',{name:'Save artifact',exact:true})).toHaveCount(0);
  expect(ready).toBe(false);
 }finally{release();}
 await pending;
 expect(ready).toBe(true);
});
for(const viewport of reference.viewports)for(const theme of reference.themes)test('artifacts visual '+viewport.width+' '+theme,async({page})=>{await setup(page,'staff',theme);await page.setViewportSize(viewport);await enter(page);await page.getByRole('button',{name:'Open Synthetic evidence',exact:true}).click();await expect(page.locator('main h1')).toHaveCount(1);const save=await keyboardSave(page);expect((await save.boundingBox())!.height).toBeGreaterThanOrEqual(44);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.locator('main b')).toHaveCount(0);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:test.info().outputPath('artifacts.png'),fullPage:true});});

test('association limit applies across both context types',async({page})=>{const f=await setup(page);f.records[0].activities=Array.from({length:99},(_,index)=>({...f.activity,activityId:'bounded-'+index,title:'Bounded activity '+index}));await enter(page);await page.getByRole('button',{name:'Open Synthetic evidence',exact:true}).click();await expect(page.getByLabel('Associate Shared initiative')).toBeDisabled();await page.getByRole('button',{name:'Remove Bounded activity 0',exact:true}).click();await page.getByLabel('Associate Shared initiative').check();await expect(page.getByLabel('Associate Synthetic service')).toBeDisabled();await page.getByRole('button',{name:'Save artifact',exact:true}).click();await expect.poll(()=>f.writes.length).toBe(1);expect(f.writes[0].activities.length+f.writes[0].initiatives.length).toBe(100);});

for(const role of ['admin','staff'])test(role+' artifact create review rejection edit archive history',async({page})=>{const f=await setup(page,role);await enter(page);await page.getByRole('button',{name:'Create artifact',exact:true}).click();await expect(page.getByRole('heading',{name:'New artifact'})).toBeFocused();await fill(page);await page.getByRole('button',{name:'Save artifact',exact:true}).click();await expect(page.getByText('Saved and confirmed',{exact:false})).toBeVisible();expect(f.writes[0]).toMatchObject({title:'New synthetic artifact',activities:[],initiatives:[],sectionRevision:0});await page.getByRole('button',{name:'Review saved revision 0',exact:true}).click();await expect(page.getByText('Reviewed saved revision 0',{exact:false})).toBeVisible();expect(f.writes[1]).toEqual({revision:0,sectionRevision:0,decision:'reviewed'});await page.getByRole('button',{name:'Reject saved revision 1',exact:true}).click();await expect(page.getByText('Rejected saved revision 1',{exact:false})).toBeVisible();await page.getByLabel('Caption',{exact:true}).fill('Revised draft');await expect(page.getByRole('button',{name:'Review saved revision 2',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Archive artifact',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Discard artifact draft',exact:true}).click();await page.getByLabel('Associate Synthetic service').check();await page.getByLabel('Associate Synthetic initiative').check();await page.getByRole('button',{name:'Save artifact',exact:true}).click();await expect(page.getByText('Unreviewed',{exact:true})).toBeVisible();expect(f.writes[3]).toMatchObject({revision:2,activities:[{activityId:'activity',revision:2}],initiatives:[{initiativeId:'first',revision:0}]});await page.getByRole('button',{name:'View artifact history'}).click();await expect(page.getByText('<script>Historical caption</script>',{exact:true})).toBeVisible();await expect(page.getByText('Current historical initiative',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Next artifact history page'}).click();await expect(page.getByRole('heading',{name:'Revision 1',exact:true})).toBeVisible();await page.getByRole('button',{name:'Archive artifact',exact:true}).click();await expect(page.getByLabel('Caption',{exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Unarchive artifact',exact:true}).click();await expect(page.getByLabel('Caption',{exact:true})).toBeVisible();expect(f.writes.at(-1)).toEqual({revision:4,sectionRevision:0,archived:false});});
test('invalid URLs are never fetched and section-off records remain readable',async({page})=>{const f=await setup(page);let fetches=0;await page.route('https://example.test/**',r=>{fetches++;return r.abort();});await enter(page);await page.getByRole('button',{name:'Open Synthetic evidence',exact:true}).click();for(const url of ['http://example.test','https://name:secret@example.test','https://example.test/a b','javascript:alert(1)']){await page.getByLabel('Source URL',{exact:true}).fill(url);await expect(page.getByRole('button',{name:'Save artifact',exact:true})).toBeDisabled();}f.sections.filesEnabled=false;f.sections.revision++;await page.getByRole('button',{name:'Reload artifacts'}).click();await expect(page.getByText('Files section is disabled.',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'Review saved revision 0'})).toBeDisabled();await page.getByRole('button',{name:'View artifact history'}).click();await expect(page.getByRole('heading',{name:'Immutable artifact history'})).toBeVisible();expect(fetches).toBe(0);});
test('files toggle preserves independent section flags',async({page})=>{const f=await setup(page,'admin');f.sections.notesEnabled=false;await page.goto('/documentation');await page.getByLabel('Enable files and external-link artifacts').click();await expect.poll(()=>f.sections.filesEnabled).toBe(false);expect(f.sections.notesEnabled).toBe(false);expect(f.sections.summaryEnabled).toBe(true);});

test('review conflict pins saved revision and requires explicit reload',async({page})=>{const f=await setup(page);await enter(page);await page.getByRole('button',{name:'Open Synthetic evidence',exact:true}).click();f.fail(409);await page.getByRole('button',{name:'Review saved revision 0',exact:true}).click();await expect(page.getByRole('alert')).toContainText('No write is retried');expect(f.writes).toEqual([{revision:0,sectionRevision:0,decision:'reviewed'}]);f.fail(0);f.records[0].revision=1;f.records[0].review={decision:'rejected',reviewedRevision:0,reviewerUserId:'another-synthetic-reviewer',reviewedAt:'2026-09-10T13:00:00Z'};await page.getByRole('button',{name:'Reload artifacts'}).click();await expect(page.getByText('Rejected saved revision 0',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'Review saved revision 1',exact:true})).toBeEnabled();expect(f.writes).toHaveLength(1);});

test('Files disable during write readback locks mutation and preserves draft',async({page})=>{const f=await setup(page);await page.route('**/admin/documentation/artifacts/artifact',async route=>{if(route.request().method()==='GET'&&f.writes.length){f.sections.filesEnabled=false;f.sections.revision=1;}await route.fallback();});await enter(page);await page.getByRole('button',{name:'Open Synthetic evidence',exact:true}).click();await page.getByLabel('Caption',{exact:true}).fill('Preserved changed caption');await page.getByRole('button',{name:'Save artifact',exact:true}).click();await expect(page.getByRole('alert')).toContainText('No write is retried');await expect(page.getByRole('button',{name:'Save artifact',exact:true})).toBeDisabled();await expect(page.getByLabel('Caption',{exact:true})).toHaveValue('Preserved changed caption');await page.getByRole('button',{name:'Reload artifacts'}).click();await expect(page.getByText('Files section is disabled.',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'Save artifact',exact:true})).toBeDisabled();expect(f.writes).toHaveLength(1);});

test('file artifact curation retains member provenance and immutable original URL',async({page})=>{const f=await setup(page);const a=f.records[0];Object.assign(a,{kind:'file',authorUserId:null,contributor:{kind:'member',source:'public'},url:'https://drive.google.com/file/d/synthetic-file/view',originalUrl:'https://drive.google.com/file/d/synthetic-file/view',file:{id:'synthetic-file',rootId:'root',generation:'generation',sha256:'a'.repeat(64),byteLength:100,mime:'text/plain',validationOutcome:'linked-only'}});await page.goto('/documentation');await page.getByRole('button',{name:'Artifacts',exact:true}).click();await page.getByRole('button',{name:'Open Synthetic evidence'}).click();await expect(page.getByText('Member contribution · Public form',{exact:false})).toBeVisible();await expect(page.getByLabel('Source URL',{exact:true})).toHaveCount(0);await expect(page.getByRole('link',{name:'Open private original in Drive (opens a new tab)'})).toHaveAttribute('href',a.originalUrl);await page.getByLabel('Caption',{exact:true}).fill('Staff curated caption');await page.getByRole('button',{name:'Save artifact',exact:true}).click();await expect(page.getByText('Saved and confirmed',{exact:false})).toBeVisible();expect(f.writes[0]).not.toHaveProperty('url');await page.getByRole('button',{name:'View artifact history'}).click();await expect(page.getByRole('heading',{name:'Immutable artifact history'})).toBeVisible();await page.getByRole('button',{name:'Review saved revision 1',exact:true}).click();await expect(page.getByText('Reviewed saved revision 1',{exact:false}).first()).toBeVisible();});
for(const outcome of ['native','embedded'] as const)test(`preserved Drive ${outcome} provenance survives metadata edits and history`,async({page})=>{const f=await setup(page),r=f.records[0];Object.assign(r,{kind:'preserved-drive',url:'https://drive.google.com/file/d/synthetic-copy/view',originalUrl:'https://drive.google.com/file/d/synthetic-copy/view',preservedDrive:{id:'synthetic-copy',rootId:'root',generation:'generation',mime:outcome==='native'?'application/vnd.google-apps.document':'application/pdf',sourceId:'synthetic-source',sourceVersion:'7',copiedAt:'2026-09-11T10:00:00Z',validation:{outcome},...(outcome==='embedded'?{byteLength:42,sha256:'a'.repeat(64)}:{})}});await enter(page);await page.getByRole('button',{name:'Open Synthetic evidence',exact:true}).click();await expect(page.getByLabel('Source URL',{exact:true})).toHaveCount(0);await expect(page.getByText('Source synthetic-source · Version 7',{exact:false})).toBeVisible();await expect(page.getByText(outcome==='native'?'No binary checksum or byte size is claimed.':'42 bytes',{exact:false})).toBeVisible();await page.getByLabel('Caption',{exact:true}).fill('Updated copy caption');await page.getByRole('button',{name:'Save artifact',exact:true}).click();await expect(page.getByText('Saved and confirmed from current server records.')).toBeVisible();expect(f.writes[0]).not.toHaveProperty('url');await page.getByRole('button',{name:'View artifact history'}).click();await expect(page.getByRole('heading',{name:'Immutable artifact history'})).toBeVisible();await expect(page.getByText('Source synthetic-source · Version 7',{exact:false})).toHaveCount(2);});
