import {expect,test,type Page} from '@playwright/test';
import {dashboardConformanceReferences as reference} from '../apps/dashboard/src/design-conformance';
async function notesSetup(page:Page,role='staff',theme='light') {
 let granted=true,enabled=true,fail=0;const writes:any[]=[];const requests:string[]=[];
 const sections={version:1,revision:0,notesEnabled:true,summaryEnabled:true,filesEnabled:true};
 const activity={id:'activity',title:'Synthetic service',serviceDate:'2026-09-10',revision:2,archived:false,impactRelevant:true};
 const notes:any[]=[{id:'note',activityId:'activity',text:'<script>private note</script>',revision:0,archived:false,authorUserId:'synthetic-author',createdAt:'2026-09-10T12:00:00Z',updatedAt:'2026-09-10T12:00:00Z'}];
 await page.addInitScript(value=>localStorage.setItem('lancerlogin-theme',value),theme);
 await page.route('**/setup/status',r=>r.fulfill({json:{configured:true,installation:{authMode:'local'},settings:{organizationName:'Synthetic Documentation',primaryColor:reference.brand.primary,secondaryColor:reference.brand.secondary,appearance:theme}}}));
 await page.route('**/auth/session',r=>r.fulfill({json:{user:{id:'synthetic',role}}}));
 await page.route('**/admin/setup/progress',r=>r.fulfill({json:{completedSteps:['branding','roster','pair-kiosk','fingerprint-test','confirm-attendance'].map(step=>({step}))}}));
 await page.route('**/platform/modules',r=>r.fulfill({json:{capabilities:granted&&enabled?['documentation.manage']:[],modules:[{id:'hour-tracking',enabled,capabilities:['hours.manage'],navigation:{path:'/hours',label:'Hour Tracking'}},{id:'activity-documentation',enabled,capabilities:['documentation.manage'],navigation:{path:'/documentation',label:'Activity Documentation'}}]}}));
 await page.route('**/admin/documentation/**',async r=>{const req=r.request(),url=new URL(req.url()),path=url.pathname.replace('/admin/documentation','');requests.push(url.pathname+url.search);
 if(req.method()!=='GET'){const body=req.postDataJSON();writes.push(body);if(fail){await r.fulfill({status:fail,json:{error:'Synthetic conflict'}});return;}if(path==='/sections'){Object.assign(sections,body,{revision:sections.revision+1});await r.fulfill({json:sections});return;}let n=path.startsWith('/notes/')?notes.find(n=>n.id===path.split('/')[2]):undefined;if(n)Object.assign(n,body,{revision:n.revision+1});else{n={...notes[0],...body,id:'created',revision:0};notes.push(n);}await r.fulfill({json:{note:n}});return;}
 if(!granted||!enabled){await r.fulfill({status:403,json:{error:'Unavailable'}});return;}
 if(path==='/sections'){await r.fulfill({json:sections});return;}
 if(path==='/activities'){await r.fulfill({json:{activities:[activity],next:url.searchParams.has('after')?null:'next-activity'}});return;}
 if(path==='/activities/activity'){await r.fulfill({json:{...activity,readOnly:activity.archived||!activity.impactRelevant,sectionRevision:sections.revision,...(sections.summaryEnabled?{summary:{countedMinutes:0,distinctParticipants:0}}:{})}});return;}
 if(path==='/activities/activity/notes'){await r.fulfill({json:{notes,next:url.searchParams.has('after')?null:'next-note',readOnly:activity.archived||!activity.impactRelevant||!sections.notesEnabled,activityRevision:activity.revision,sectionRevision:sections.revision}});return;}
 if(path.endsWith('/history')){await r.fulfill({json:{revisions:[{revision:url.searchParams.has('after')?1:0,text:'<b>Original text</b>',archived:false,createdAt:'2026-09-10'}],next:url.searchParams.has('after')?null:0}});return;}
 await r.fulfill({json:{note:notes.find(n=>n.id===path.split('/')[2])}});
 });
 return {sections,activity,notes,writes,requests,revoke:()=>granted=false,disable:()=>enabled=false,fail:(status:number)=>fail=status};
}
async function setup(page:Page,role='staff',theme='light'){
 const base=await notesSetup(page,role,theme);let fail=0;const writes:any[]=[];const reads:string[]=[];const time='2026-09-10T12:00:00Z';
 const definition={id:'definition',title:'Community definition',definition:'<b>Original definition</b>',source:'Synthetic source',revision:2,archived:false,createdAt:time,updatedAt:time};
 const definitions:any[]=[definition];const metric={id:'metric',title:'Exact metric',revision:3,archived:false,value:'1.2500',unit:'items',kind:'outcomes',basis:'estimated',source:'<script>Metric source</script>',method:'Original method',periodStart:'2026-09-01',periodEnd:'2026-09-10',createdAt:time};const artifact={id:'artifact',title:'Private artifact',revision:2,archived:false,caption:'<b>Original caption</b>',url:'https://example.invalid/private',originalUrl:'https://example.invalid/private',review:{decision:'rejected',reviewedRevision:0,reviewedAt:time},createdAt:time};
 const catalogs:any={activities:[{...base.activity}],teams:[{id:'team',name:'Synthetic team',title:'Synthetic team',revision:1,archived:false}],initiatives:[{id:'initiative',title:'Synthetic initiative',revision:1,archived:false}],artifacts:[artifact],metrics:[metric]};
 const record:any={id:'claim',title:'Synthetic claim',definitionId:'definition',definitionRevision:0,periodStart:'2026-09-01',periodEnd:'2026-09-10',rationale:'<b>Private rationale</b>',revision:0,archived:false,review:null,createdAt:time,updatedAt:time,activities:[],teams:[],initiatives:[],artifacts:[],metrics:[]};const records=[record];const histories=new Map<string,any[]>([['claim',[structuredClone(record)]]]);
 function detail(r:any){return {claim:r,definition:{...definition,revision:r.definitionRevision,currentRevision:definition.revision,changed:definition.revision!==r.definitionRevision},...Object.fromEntries(Object.keys(catalogs).map(type=>[type,r[type].map((pin:any)=>{const key=type==='activities'?'activityId':type==='teams'?'teamId':type==='initiatives'?'initiativeId':type==='artifacts'?'artifactId':'metricId',item=catalogs[type].find((i:any)=>i.id===pin[key]);return {...item,...pin,currentRevision:item.revision,currentArchived:item.archived,currentTitle:item.title,eligible:!item.archived&&(type!=='activities'||item.impactRelevant),changed:item.revision!==pin.revision||item.archived,...(['artifacts','metrics'].includes(type)?{selectedArchived:false,selectedReview:item.review??null}:{})};})])),readOnly:r.archived,dependencyChanged:true,incompleteness:{rationaleMissing:!r.rationale,contextsMissing:!r.activities.length&&!r.teams.length&&!r.initiatives.length,evidenceMissing:!r.artifacts.length&&!r.metrics.length}};}
 await page.route('**/admin/documentation/**',async route=>{const req=route.request(),url=new URL(req.url()),parts=url.pathname.replace('/admin/documentation/','').split('/'),type=parts[0];if(!['claims','definitions',...Object.keys(catalogs)].includes(type))return route.fallback();reads.push(url.pathname+url.search);const rows=type==='claims'?records:type==='definitions'?definitions:catalogs[type],item=rows.find((r:any)=>r.id===parts[1]);
 if(req.method()!=='GET'){const body=req.postDataJSON();writes.push({type,path:url.pathname,body});if(fail){if(fail===599)return route.abort();return route.fulfill({status:fail,json:{error:'Synthetic failure'}});}const value=item??(type==='claims'?{...record,id:'created',revision:-1,review:null}: {...definition,id:'created',revision:-1});if(item&&body.revision!==item.revision)return route.fulfill({status:409,json:{error:'Conflict'}});const before=value.revision;Object.assign(value,body,{revision:before+1,review:parts[2]==='review'?{decision:body.decision,reviewedRevision:before,reviewedAt:time}:null});if(!item)rows.push(value);if(type==='claims'){histories.set(value.id,[...(histories.get(value.id)??[]),structuredClone(value)]);}await route.fulfill({json:{[type==='claims'?'claim':'definition']:value}});return;}
 if(parts[2]==='history'){let revisions:any[];if(type==='claims')revisions=histories.get(item.id)!.map(r=>{const d=detail(r);for(const p of d.metrics){delete p.source;delete p.method;}for(const p of d.artifacts){delete p.url;delete p.caption;}return {...r,...d};});else revisions=[{...item,revision:0},{...item,revision:item.revision}];const after=Number(url.searchParams.get('after')??-1);revisions=revisions.filter(r=>r.revision>after);if(url.searchParams.get('limit')==='1')revisions=revisions.slice(0,1);await route.fulfill({json:{revisions,next:url.searchParams.has('after')?null:0}});return;}
 if(parts[1]){if(!item)return route.fulfill({status:404,json:{error:'Unavailable'}});await route.fulfill({json:type==='claims'?detail(item):type==='activities'?item:{[type==='definitions'?'definition':type==='metrics'?'metric':type==='artifacts'?'artifact':'initiative']:item}});return;}
 await route.fulfill({json:{[type]:rows.filter((r:any)=>url.searchParams.get('archival')==='true'||!r.archived).map((r:any)=>type==='claims'?detail(r):r),next:url.searchParams.has('after')?null:'next'}});
 });
 return {...base,definition,definitions,record,records,metric,artifact,catalogs,writes,reads,fail:(value:number)=>fail=value};
}
async function enter(page:Page,kind='Claims'){await page.goto('/documentation');await page.getByRole('button',{name:kind,exact:true}).click();await expect(page.getByRole('heading',{name:kind,exact:true})).toBeVisible();}
async function open(page:Page){await page.getByRole('button',{name:'Open Synthetic claim',exact:true}).click();await expect(page.getByLabel('Claim title')).toHaveValue('Synthetic claim');}
test('definition edits, archival, pure unarchive and history pagination preserve plain text',async({page})=>{const f=await setup(page);await enter(page,'Definitions');await page.getByRole('button',{name:'Next definitions page',exact:true}).click();await expect.poll(()=>f.reads.some(p=>p.includes('/definitions?')&&p.includes('after=next'))).toBe(true);await page.getByRole('button',{name:'Open Community definition',exact:true}).click();await page.getByLabel('Definition source').fill('Updated plain source');await expect(page.getByRole('button',{name:'Archive definition',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Save definition',exact:true}).click();await page.getByRole('button',{name:'View definition history'}).click();await page.getByRole('button',{name:'Next definition history page'}).click();await expect.poll(()=>f.reads.some(p=>p.includes('/definitions/definition/history?limit=25&after=0'))).toBe(true);await page.getByRole('button',{name:'Archive definition',exact:true}).click();await page.getByRole('button',{name:'Unarchive definition',exact:true}).click();await expect(page.getByLabel('Definition source')).toHaveValue('Updated plain source');expect(f.writes[2].body).toEqual({revision:4,archived:false});});
test('new contexts losing relevance are blocked after reload while retained pins remain removable',async({page})=>{const f=await setup(page);await enter(page);await open(page);await page.getByRole('button',{name:'Choose activities',exact:true}).click();await page.getByLabel('Associate Synthetic service').check();f.catalogs.activities[0].impactRelevant=false;await page.getByRole('button',{name:'Reload claims'}).click();await expect(page.getByRole('button',{name:'Save claim',exact:true})).toBeDisabled();await expect(page.getByText('Retained, currently unavailable',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Remove Synthetic service'}).click();await expect(page.getByRole('button',{name:'Save claim',exact:true})).toBeEnabled();});
test('existing ineligible context and archived definition can remain while rationale changes',async({page})=>{const f=await setup(page);f.record.activities=[{activityId:'activity',revision:2}];f.catalogs.activities[0].impactRelevant=false;f.definition.archived=true;await enter(page);await open(page);await page.getByLabel('Rationale').fill('Independent edit');await page.getByRole('button',{name:'Save claim',exact:true}).click();await expect(page.getByText('Saved and confirmed',{exact:false})).toBeVisible();expect(f.writes[0].body.activities).toEqual([{activityId:'activity',revision:2}]);});
test('independent claims work with notes, files and summary switches disabled',async({page})=>{const f=await setup(page);f.sections.notesEnabled=false;f.sections.filesEnabled=false;f.sections.summaryEnabled=false;await enter(page);await open(page);await page.getByRole('button',{name:'Mark claim reviewed'}).click();await expect.poll(()=>f.writes.length).toBe(1);});
test('combined hundred-link limit spans all types and removal restores choices',async({page})=>{const f=await setup(page);f.catalogs.teams=Array.from({length:99},(_,i)=>({id:'team-'+i,name:'Team '+i,title:'Team '+i,revision:1,archived:false}));f.record.teams=f.catalogs.teams.map((r:any)=>({teamId:r.id,revision:1}));f.record.activities=[{activityId:'activity',revision:2}];await enter(page);await open(page);await page.getByRole('button',{name:'Choose metrics',exact:true}).click();await expect(page.getByRole('button',{name:'Choose revision of Exact metric'})).toBeDisabled();await page.getByRole('button',{name:'Remove Synthetic service'}).click();await expect(page.getByRole('button',{name:'Choose revision of Exact metric'})).toBeEnabled();});
test('list read failure has an actionable reload and no automatic write',async({page})=>{await setup(page);let fail=true;await page.route('**/admin/documentation/claims?**',r=>fail?r.fulfill({status:503,json:{error:'Unavailable'}}):r.fallback());await enter(page);await expect(page.getByRole('button',{name:'Create claim',exact:true})).toBeDisabled();fail=false;await page.getByRole('button',{name:'Reload claims'}).click();await expect(page.getByRole('button',{name:'Open Synthetic claim',exact:true})).toBeVisible();});
test('claim and selector pagination use explicit cursors without retargeting pins',async({page})=>{const f=await setup(page);await enter(page);await page.getByRole('button',{name:'Next claims page',exact:true}).click();await open(page);await page.getByRole('button',{name:'Choose metrics',exact:true}).click();await page.getByRole('button',{name:'Next metrics choices page'}).click();await page.getByRole('button',{name:'Choose revision of Exact metric'}).click();await page.getByRole('button',{name:'Next revision choices page'}).click();await expect(page.getByRole('heading',{name:'Select a revision of Exact metric'})).toBeFocused();await page.getByRole('button',{name:'Select revision 3',exact:true}).click();await expect(page.getByRole('button',{name:'Choose revision of Exact metric'})).toBeFocused();await page.getByRole('button',{name:'Save claim',exact:true}).click();await expect.poll(()=>f.writes.length).toBe(1);expect(f.writes[0].body.metrics[0]).toEqual({metricId:'metric',revision:3,currentRevision:3});});
test('Doc-only Staff creates definition, selects historical definition, saves incomplete claim and reviews independently',async({page})=>{const f=await setup(page);await enter(page,'Definitions');await page.getByRole('button',{name:'Create definition',exact:true}).click();await page.getByLabel('Definition title').fill('New definition');await page.getByLabel('Definition text',{exact:true}).fill('<script>Plain definition</script>');await page.getByRole('button',{name:'Save definition',exact:true}).click();await expect(page.getByText('Saved and confirmed',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Close definition',exact:true}).click();await page.getByRole('button',{name:'Claims',exact:true}).click();await page.getByRole('button',{name:'Create claim',exact:true}).click();await page.getByLabel('Claim title').fill('Incomplete claim');await page.getByLabel('Period start').fill('2026-09-01');await page.getByLabel('Period end').fill('2026-09-10');await page.getByRole('button',{name:'Choose revision of Community definition'}).click();await page.getByRole('button',{name:'Select revision 0',exact:true}).click();await page.getByRole('button',{name:'Save claim',exact:true}).click();await expect(page.getByText('Saved and confirmed',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Mark claim reviewed'}).click();await expect.poll(()=>f.writes.length).toBe(3);expect(f.writes[1].body.rationale).toBe('');expect(f.writes[1].body.definitionRevision).toBe(0);expect(f.writes[2].body).toEqual({revision:0,decision:'reviewed'});await page.getByRole('button',{name:'View claim history'}).click();await expect(page.getByRole('heading',{name:'Immutable claim history'})).toBeVisible();await expect(page.locator('main script')).toHaveCount(0);});
test('Admin pins all context types and exact historical evidence with separate current fence; immutable evidence expands',async({page})=>{const f=await setup(page,'admin');await enter(page);await open(page);for(const [type,label] of [['activities','Synthetic service'],['teams','Synthetic team'],['initiatives','Synthetic initiative']]){await page.getByRole('button',{name:'Choose '+type,exact:true}).click();await page.getByLabel('Associate '+label).check();}for(const [type,label] of [['metrics','Exact metric'],['artifacts','Private artifact']]){await page.getByRole('button',{name:'Choose '+type,exact:true}).click();await page.getByRole('button',{name:'Choose revision of '+label}).click();await page.getByRole('button',{name:'Select revision 0',exact:true}).click();}await expect(page.getByText('1.2500 items · outcomes · estimated')).toBeVisible();await expect(page.getByText('Artifact revision rejected. This is separate from claim review.')).toBeVisible();await page.getByRole('button',{name:'Save claim',exact:true}).click();await expect.poll(()=>f.writes.length).toBe(1);expect(f.writes[0].body.metrics).toEqual([{metricId:'metric',revision:0,currentRevision:3}]);expect(f.writes[0].body.artifacts).toEqual([{artifactId:'artifact',revision:0,currentRevision:2}]);await page.getByRole('button',{name:'View claim history'}).click();await page.getByRole('button',{name:'Read pinned details for Exact metric at claim revision 1'}).click();await expect(page.getByText('Method: Original method').last()).toBeVisible();expect(f.reads.some(p=>p.endsWith('/metrics/metric/history?limit=1'))).toBe(true);await expect(page.locator('main b, main script')).toHaveCount(0);});
test('dirty archive/review prevent draft loss; pure unarchive and explicit rejection retain history',async({page})=>{const f=await setup(page);await enter(page);await open(page);await page.getByLabel('Rationale').fill('Unsaved draft');await expect(page.getByRole('button',{name:'Archive claim',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Mark claim reviewed'})).toBeDisabled();await page.getByRole('button',{name:'Discard claim draft',exact:true}).click();await page.getByRole('button',{name:'Archive claim',exact:true}).click();await expect(page.getByRole('button',{name:'Unarchive claim',exact:true})).toBeVisible();await expect(page.getByLabel('Rationale')).toHaveCount(0);await page.getByRole('button',{name:'Unarchive claim',exact:true}).click();await page.getByRole('button',{name:'Reject claim',exact:true}).click();await expect.poll(()=>f.writes.length).toBe(3);expect(f.writes.map(w=>w.body)).toEqual([{revision:0,archived:true},{revision:1,archived:false},{revision:2,decision:'rejected'}]);});
for(const status of [409,599])test('uncertain or stale claim requires explicit reload '+status,async({page})=>{const f=await setup(page);await enter(page);await open(page);await page.getByLabel('Rationale').fill('Preserved draft');f.fail(status);await page.getByRole('button',{name:'Save claim',exact:true}).click();await expect(page.getByRole('button',{name:'Save claim',exact:true})).toBeDisabled();await expect(page.getByLabel('Rationale')).toHaveValue('Preserved draft');expect(f.writes).toHaveLength(1);f.fail(0);await page.getByRole('button',{name:'Reload claims'}).click();await expect(page.getByRole('button',{name:'Save claim',exact:true})).toBeEnabled();expect(f.writes).toHaveLength(1);});
test('delayed read cannot restore revoked private content',async({page})=>{const f=await setup(page);let release=()=>{};const gate=new Promise<void>(resolve=>release=resolve);await page.route('**/admin/documentation/claims/claim',async r=>{await gate;await r.fallback();});await enter(page);await page.getByRole('button',{name:'Open Synthetic claim',exact:true}).click();f.revoke();await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByRole('heading',{name:'Workspace unavailable'})).toBeVisible();release();await expect(page.getByLabel('Rationale')).toHaveCount(0);});
test('delayed write stays serialized across access refresh',async({page})=>{const f=await setup(page);let release=()=>{};const gate=new Promise<void>(resolve=>release=resolve);await page.route('**/admin/documentation/claims/claim',async r=>{if(r.request().method()==='PATCH')await gate;await r.fallback();});await enter(page);await open(page);const requested=page.waitForRequest(r=>r.method()==='PATCH');await page.getByRole('button',{name:'Save claim',exact:true}).click();await requested;await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByRole('button',{name:'Reload claims'})).toBeDisabled();release();await expect(page.getByRole('button',{name:'Reload claims'})).toBeEnabled();await expect(page.getByRole('button',{name:'Save claim',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Reload claims'}).click();await expect(page.getByRole('button',{name:'Save claim',exact:true})).toBeEnabled();expect(f.writes).toHaveLength(1);});
test('disabled modules deny Documentation entry',async({page})=>{const f=await setup(page);f.disable();await page.goto('/documentation');await expect(page.getByRole('heading',{name:'Workspace unavailable'})).toBeVisible();await expect(page.getByRole('button',{name:'Claims',exact:true})).toHaveCount(0);});
for(const role of ['staff','operator'])test('non-documentation authority denied '+role,async({page})=>{const f=await setup(page,role);f.revoke();await page.goto('/documentation');await expect(page.getByRole('heading',{name:'Workspace unavailable'})).toBeVisible();});
for(const viewport of reference.viewports)for(const theme of reference.themes)test('claims visual '+viewport.width+' '+theme,async({page})=>{await setup(page,'staff',theme);await page.setViewportSize(viewport);await enter(page);await open(page);await expect(page.locator('main h1')).toHaveCount(1);const save=page.getByRole('button',{name:'Save claim',exact:true});await page.keyboard.press('Tab');await save.focus();await expect(save).toBeFocused();expect(await save.evaluate(e=>getComputedStyle(e).outlineStyle)).not.toBe('none');expect((await save.boundingBox())!.height).toBeGreaterThanOrEqual(44);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:test.info().outputPath('claims.png'),fullPage:true});await page.getByRole('button',{name:'Close claim',exact:true}).click();await page.getByRole('button',{name:'Definitions',exact:true}).click();await page.getByRole('button',{name:'Open Community definition',exact:true}).click();await expect(page.getByLabel('Definition text',{exact:true})).toHaveValue('<b>Original definition</b>');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:test.info().outputPath('definitions.png'),fullPage:true});});
