import {test,expect} from '@playwright/test';
for(const theme of ['light','dark'])for(const width of [1280,390])test(`temporary database unavailable ${theme} ${width}`,async({page})=>{
 await page.setViewportSize({width,height:width===390?844:900});await page.emulateMedia({reducedMotion:'reduce'});await page.addInitScript(theme=>localStorage.setItem('lancerlogin-theme',theme),theme);let calls=0;
 await page.route('**/setup/status',route=>{calls++;return route.fulfill({status:503,json:{error:'synthetic-private-provider-SQL',code:'database_temporarily_unavailable'}});});await page.goto('/');await expect(page.getByRole('heading',{name:'Service temporarily unavailable',exact:true})).toBeVisible();await expect(page.getByRole('main')).toContainText('Please wait and reload this page later.');await expect(page.getByRole('main')).not.toContainText('workflow');await expect(page.getByRole('main')).not.toContainText('synthetic-private');await expect(page.getByRole('button',{name:'Create Admin'})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const count=calls;await page.screenshot({path:`.provision/database-unavailable-${theme}-${width}.png`});expect(calls).toBe(count);
});
test('unknown setup failure retains existing fallback; local sign-in 503 is not a password error',async({page})=>{
 await page.route('**/setup/status',route=>route.fulfill({status:500,json:{error:'synthetic-private'}}));await page.goto('/');await expect(page.getByRole('heading',{name:'Setup service unavailable'})).toBeVisible();
 await page.route('**/setup/status',route=>route.fulfill({json:{configured:true,installation:{authMode:'local'},settings:{organizationName:'Synthetic quota test',primaryColor:'#5b21b6',secondaryColor:'#0f766e',appearance:'light'}}}));await page.route('**/auth/session',route=>route.fulfill({status:401,json:{error:'Unauthorized'}}));await page.route('**/auth/local',route=>route.fulfill({status:503,json:{error:'synthetic-private-provider-SQL'}}));await page.reload();await page.getByLabel('Username', {exact:true}).fill('synthetic');await page.getByLabel('Password',{exact:true}).fill('synthetic-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByText('The sign-in service is temporarily unavailable. Please try again later.')).toBeVisible();await expect(page.getByText('Invalid username or password.',{exact:false})).toHaveCount(0);await expect(page.getByText('synthetic-private-provider-SQL')).toHaveCount(0);await expect(page.getByLabel('Username',{exact:true})).toHaveAttribute('aria-invalid','false');await expect(page.getByLabel('Password',{exact:true})).toHaveAttribute('aria-invalid','false');
});
