import {expect,test,type Page} from '@playwright/test';
import {dashboardConformanceReferences as reference} from '../apps/dashboard/src/design-conformance';
export async function setup(page:Page,role='staff',theme='light') {
 let granted=true,enabled=true,fail=0;const writes:any[]=[];const requests:string[]=[];
 const sections={version:1,revision:0,notesEnabled:true,summaryEnabled:true,filesEnabled:true};
 const activity={id:'activity',title:'Synthetic service',serviceDate:'2026-09-10',revision:2,archived:false,impactRelevant:true};
 const provenance={kind:'staff',userId:'synthetic-author',memberId:null,source:'staff',attribution:'staff',currentMemberLabel:null};
 const notes:any[]=[{contributor:provenance,review:null,id:'note',activityId:'activity',text:'<script>private note</script>',revision:0,archived:false,authorUserId:'synthetic-author',createdAt:'2026-09-10T12:00:00Z',updatedAt:'2026-09-10T12:00:00Z'}];
 await page.addInitScript(value=>localStorage.setItem('lancerlogin-theme',value),theme);
 await page.route('**/setup/status',r=>r.fulfill({json:{configured:true,installation:{authMode:'local'},settings:{organizationName:'Synthetic Documentation',primaryColor:reference.brand.primary,secondaryColor:reference.brand.secondary,appearance:theme}}}));
 await page.route('**/auth/session',r=>r.fulfill({json:{user:{id:'synthetic',role}}}));
 await page.route('**/admin/setup/progress',r=>r.fulfill({json:{completedSteps:['branding','roster','pair-kiosk','fingerprint-test','confirm-attendance'].map(step=>({step}))}}));
 await page.route('**/platform/modules',r=>r.fulfill({json:{capabilities:granted&&enabled?['documentation.manage']:[],modules:[{id:'hour-tracking',enabled,capabilities:['hours.manage'],navigation:{path:'/hours',label:'Hour Tracking'}},{id:'activity-documentation',enabled,capabilities:['documentation.manage'],navigation:{path:'/documentation',label:'Activity Documentation'}}]}}));
 await page.route('**/admin/documentation/**',async r=>{const req=r.request(),url=new URL(req.url()),path=url.pathname.replace('/admin/documentation','');requests.push(url.pathname+url.search);
 if(req.method()!=='GET'){const body=req.postDataJSON();writes.push(body);if(fail){await r.fulfill({status:fail,json:{error:'Synthetic conflict'}});return;}if(path==='/sections'){Object.assign(sections,body,{revision:sections.revision+1});await r.fulfill({json:sections});return;}let n=path.startsWith('/notes/')?notes.find(n=>n.id===path.split('/')[2]):undefined;if(n)Object.assign(n,body,{revision:n.revision+1,review:path.endsWith('/review')?{decision:body.decision,reviewedRevision:n.revision,reviewerUserId:'synthetic-reviewer',reviewedAt:'2026-09-10T13:00:00Z'}:null});else{n={...notes[0],...body,id:'created',revision:0};notes.push(n);}await r.fulfill({json:{note:n}});return;}
 if(!granted||!enabled){await r.fulfill({status:403,json:{error:'Unavailable'}});return;}
 if(path==='/sections'){await r.fulfill({json:sections});return;}
 if(path==='/activities'){await r.fulfill({json:{activities:[activity],next:url.searchParams.has('after')?null:'next-activity'}});return;}
 if(path==='/activities/activity'){await r.fulfill({json:{...activity,readOnly:activity.archived||!activity.impactRelevant,sectionRevision:sections.revision,...(sections.summaryEnabled?{summary:{countedMinutes:0,distinctParticipants:0}}:{})}});return;}
 if(path==='/activities/activity/notes'){await r.fulfill({json:{notes,next:url.searchParams.has('after')?null:'next-note',readOnly:activity.archived||!activity.impactRelevant||!sections.notesEnabled,activityRevision:activity.revision,sectionRevision:sections.revision}});return;}
 if(path.endsWith('/history')){await r.fulfill({json:{noteId:'note',authorUserId:notes[0].authorUserId,contributor:notes[0].contributor,createdAt:notes[0].createdAt,revisions:[{actorUserId:notes[0].authorUserId,contributor:notes[0].contributor,review:null,revision:url.searchParams.has('after')?1:0,text:'<b>Original text</b>',archived:false,createdAt:'2026-09-10'}],next:url.searchParams.has('after')?null:0}});return;}
 await r.fulfill({json:{note:notes.find(n=>n.id===path.split('/')[2])}});
 });
 return {sections,activity,notes,writes,requests,revoke:()=>granted=false,disable:()=>enabled=false,fail:(status:number)=>fail=status};
}
for(const role of ['staff','admin'])test(role+' notes create, edit, archive and preserved history',async({page})=>{
 const f=await setup(page,role);await page.goto('/documentation');await page.getByRole('button',{name:'Open Synthetic service'}).click();
 await expect(page.getByRole('link',{name:'Hour Tracking',exact:true})).toHaveCount(0);await expect(page.getByText('0 counted minutes · 0 distinct participants')).toBeVisible();
 await page.getByLabel('New note text').fill('Synthetic contribution');await page.getByRole('button',{name:'Add note',exact:true}).click();await expect(page.getByText('Saved and confirmed', {exact:false})).toBeVisible();expect(f.writes[0]).toEqual({activityRevision:2,sectionRevision:0,text:'Synthetic contribution'});
 await page.getByRole('button',{name:'Edit note 0',exact:true}).first().click();await page.getByLabel('Edit note text').fill('Revised text');await page.getByRole('button',{name:'Save note',exact:true}).click();await expect(page.getByText('Revised text',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Archive note 1',exact:true}).click();await expect(page.getByRole('heading',{name:'Archived note (preserved) · revision 2'})).toBeVisible();await page.getByRole('button',{name:'History for note 2'}).click();await expect(page.getByText('<b>Original text</b>',{exact:true})).toBeVisible();await expect(page.locator('.documentation-workspace b')).toHaveCount(0);await page.getByRole('button',{name:'Next history page'}).click();await expect(page.getByRole('heading',{name:'Revision 1',exact:true})).toBeVisible();
 if(role==='staff')await expect(page.getByLabel('Enable notes', {exact:true})).toHaveCount(0);
});
test('conflict and uncertain write preserve draft and require explicit reload',async({page})=>{const f=await setup(page);await page.goto('/documentation');await page.getByRole('button',{name:'Open Synthetic service'}).click();await page.getByLabel('New note text').fill('Preserved draft');for(const status of [409,500]){f.fail(status);await page.getByRole('button',{name:'Add note',exact:true}).click();await expect(page.getByRole('alert')).toContainText('could not be confirmed');await expect(page.getByRole('button',{name:'Add note',exact:true})).toBeDisabled();await expect(page.getByLabel('New note text')).toHaveValue('Preserved draft');f.fail(0);await page.getByRole('button',{name:'Reload current records'}).click();await expect(page.getByRole('button',{name:'Add note',exact:true})).toBeEnabled();}expect(f.writes).toHaveLength(2);});
test('archival, section controls, disabled summary and cursor pages',async({page})=>{const f=await setup(page,'admin');await page.goto('/documentation');await page.getByLabel('Include archival').check();await page.getByRole('button',{name:'Next activities page'}).click();await page.getByRole('button',{name:'Open Synthetic service'}).click();await page.getByRole('button',{name:'Next notes page'}).click();await expect.poll(()=>f.requests.some(p=>p.includes('after=next-note'))).toBe(true);await page.getByLabel('Enable participant/hour summaries').click();await expect(page.getByText('Participant/hour summary is disabled.')).toBeVisible();await expect(page.getByText('0 counted minutes',{exact:false})).toHaveCount(0);await page.getByLabel('Enable notes',{exact:true}).click();await expect(page.getByLabel('New note text')).toHaveCount(0);await page.getByRole('button',{name:'History for note 0'}).click();await expect(page.getByRole('heading',{name:'Immutable note history'})).toBeVisible();f.activity.archived=true;await page.getByRole('button',{name:'Reload current records'}).click();await expect(page.getByText('Read-only activity:',{exact:false})).toBeVisible();});
for(const reason of ['grant','module'])test(reason+' revocation hides private records and draft',async({page})=>{const f=await setup(page);await page.goto('/documentation');await page.getByRole('button',{name:'Open Synthetic service'}).click();await page.getByLabel('New note text').fill('Private draft');reason==='grant'?f.revoke():f.disable();await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByRole('heading',{name:'Workspace unavailable'})).toBeVisible();await expect(page.getByText('<script>private note</script>')).toHaveCount(0);});
for(const role of ['operator','staff'])test(role+' without documentation grant denied',async({page})=>{const f=await setup(page,role);f.revoke();await page.goto('/documentation');await expect(page.getByRole('heading',{name:'Workspace unavailable'})).toBeVisible();expect(f.requests).toHaveLength(0);});
for(const viewport of reference.viewports)for(const theme of reference.themes)test('documentation visual '+viewport.width+' '+theme,async({page})=>{await setup(page,'staff',theme);await page.setViewportSize(viewport);await page.goto('/documentation');const open=page.getByRole('button',{name:'Open Synthetic service'});await open.focus();await expect(open).toBeFocused();expect(await open.evaluate(e=>getComputedStyle(e).outlineStyle)).not.toBe('none');await open.press('Enter');await page.getByLabel('New note text').fill('Synthetic notes ready for staff review.');await expect(page.locator('main h1')).toHaveCount(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect((await page.getByRole('button',{name:'Add note',exact:true}).boundingBox())!.height).toBeGreaterThanOrEqual(44);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:test.info().outputPath('documentation.png'),fullPage:true});});


test('delayed note read cannot restore private state after revocation',async({page})=>{const f=await setup(page);let release:()=>void=()=>{};const gate=new Promise<void>(resolve=>release=resolve);await page.route('**/admin/documentation/activities/activity/notes?*',async route=>{await gate;await route.fulfill({json:{notes:f.notes,next:null,readOnly:false,activityRevision:2,sectionRevision:0}});});await page.goto('/documentation');await page.getByRole('button',{name:'Open Synthetic service'}).click();f.revoke();await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByRole('heading',{name:'Workspace unavailable'})).toBeVisible();release();await expect(page.getByText('<script>private note</script>',{exact:true})).toHaveCount(0);});
test('nonimpact preserved activity blocks notes and validates UTF16 text',async({page})=>{const f=await setup(page);await page.goto('/dashboard');await expect(page.getByText('Open Activity Documentation to curate',{exact:false})).toBeVisible();await page.getByRole('link',{name:'Activity Documentation',exact:true}).click();await page.getByRole('button',{name:'Open Synthetic service'}).click();await page.getByLabel('New note text').fill(String.fromCodePoint(0x1f600).repeat(4000));await expect(page.getByText('8000/8000.',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'Add note',exact:true})).toBeEnabled();f.activity.impactRelevant=false;await page.getByRole('button',{name:'Reload current records'}).click();await expect(page.getByText('no longer impact-relevant',{exact:false}).last()).toBeVisible();await expect(page.getByLabel('New note text')).toHaveCount(0);});

test('explicit reload recovers initial activity list failure',async({page})=>{await setup(page);let fail=true;await page.route('**/admin/documentation/activities?*',route=>fail?route.fulfill({status:500,json:{error:'Unavailable'}}):route.fallback());await page.goto('/documentation');await expect(page.getByRole('alert')).toContainText('could not be confirmed');fail=false;await page.getByRole('button',{name:'Reload current records'}).click();await expect(page.getByRole('button',{name:'Open Synthetic service'})).toBeVisible();});

test('focus during delayed mutation keeps writes serialized until readback',async({page})=>{const f=await setup(page);let release:()=>void=()=>{};const gate=new Promise<void>(resolve=>release=resolve);await page.route('**/admin/documentation/activities/activity/notes',async route=>{if(route.request().method()==='POST')await gate;await route.fallback();});await page.goto('/documentation');await page.getByRole('button',{name:'Open Synthetic service'}).click();await page.getByLabel('New note text').fill('Pending write');const requested=page.waitForRequest(request=>request.method()==='POST');await page.getByRole('button',{name:'Add note',exact:true}).click();await requested;await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByRole('button',{name:'Reload current records'})).toBeDisabled();release();await expect(page.getByRole('button',{name:'Reload current records'})).toBeEnabled();await expect(page.getByRole('button',{name:'Add note',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Reload current records'}).click();await expect(page.getByText('Pending write',{exact:true}).first()).toBeVisible();expect(f.writes).toHaveLength(1);});

test('member provenance, saved review and immutable review history never show IDs',async({page})=>{const f=await setup(page);f.notes[0].authorUserId=null;f.notes[0].contributor={kind:'member',userId:null,memberId:'hidden-member-id',source:'public',attribution:'self_asserted',currentMemberLabel:'Synthetic Contributor'};await page.goto('/documentation');await page.getByRole('button',{name:'Open Synthetic service'}).click();await expect(page.getByText('Self-asserted member contribution')).toBeVisible();await expect(page.getByText('Current member name: Synthetic Contributor.',{exact:false})).toBeVisible();await expect(page.getByText('hidden-member-id')).toHaveCount(0);await page.getByRole('button',{name:'Review saved note 0'}).click();await expect(page.getByText('Staff review: Reviewed · content revision 0',{exact:false})).toBeVisible();expect(f.writes[0]).toEqual({activityRevision:2,sectionRevision:0,revision:0,decision:'reviewed'});await page.getByRole('button',{name:'Edit note 1'}).click();await page.getByLabel('Edit note text').fill('Changed member text');await expect(page.getByRole('button',{name:'Reject saved note 1'})).toBeDisabled();await page.getByRole('button',{name:'Save note',exact:true}).click();await expect(page.getByText('Not currently reviewed')).toBeVisible();await expect(page.getByText('Self-asserted member contribution')).toBeVisible();});
test('archived note can be purely unarchived without a review payload',async({page})=>{const f=await setup(page);f.notes[0].archived=true;await page.goto('/documentation');await page.getByRole('button',{name:'Open Synthetic service'}).click();await expect(page.getByRole('button',{name:'Review saved note 0'})).toBeDisabled();await page.getByRole('button',{name:'Unarchive note 0'}).click();expect(f.writes[0]).toEqual({activityRevision:2,sectionRevision:0,revision:0,archived:false});await expect(page.getByRole('button',{name:'Review saved note 1'})).toBeEnabled();});
test('review conflict is never replayed and locks further writes',async({page})=>{const f=await setup(page);await page.goto('/documentation');await page.getByRole('button',{name:'Open Synthetic service'}).click();f.fail(409);await page.getByRole('button',{name:'Reject saved note 0'}).click();await expect(page.getByRole('alert')).toContainText('could not be confirmed');await expect(page.getByRole('button',{name:'Review saved note 0'})).toBeDisabled();expect(f.writes).toHaveLength(1);});

test('notes disable between mutation and readback preserves draft and locks controls',async({page})=>{const f=await setup(page);await page.goto('/documentation');await page.getByRole('button',{name:'Open Synthetic service'}).click();await page.getByRole('button',{name:'Edit note 0'}).click();await page.getByLabel('Edit note text').fill('Preserved after changed section');await page.route('**/admin/documentation/notes/note',async r=>{if(r.request().method()==='GET'){f.sections.notesEnabled=false;f.sections.revision++;}await r.fallback();});await page.getByRole('button',{name:'Save note',exact:true}).click();await expect(page.getByRole('alert')).toContainText('could not be confirmed');await expect(page.getByLabel('Edit note text')).toHaveValue('Preserved after changed section');await expect(page.getByRole('button',{name:'Review saved note 0'})).toBeDisabled();expect(f.writes).toHaveLength(1);});
test('history renders actual member and staff review DTO without actor IDs',async({page})=>{const f=await setup(page);const member={kind:'member',userId:null,memberId:'private-member-id',source:'discord',attribution:'linked_discord',currentMemberLabel:'Synthetic Contributor'},staff={kind:'staff',userId:'private-actor-id',memberId:null,source:'staff',attribution:'staff',currentMemberLabel:null};Object.assign(f.notes[0],{authorUserId:null,contributor:member,revision:1,review:{decision:'rejected',reviewedRevision:0,reviewerUserId:'private-actor-id',reviewedAt:'2026-09-10T13:00:00Z'}});await page.route('**/admin/documentation/notes/note/history?*',r=>r.fulfill({json:{noteId:'note',authorUserId:null,contributor:member,createdAt:f.notes[0].createdAt,revisions:[{revision:0,actorUserId:null,contributor:member,review:null,text:'Original member text',archived:false,createdAt:f.notes[0].createdAt},{revision:1,actorUserId:'private-actor-id',contributor:staff,review:f.notes[0].review,text:'Original member text',archived:false,createdAt:'2026-09-10T13:00:00Z'}],next:null}}));await page.goto('/documentation');await page.getByRole('button',{name:'Open Synthetic service'}).click();await page.getByRole('button',{name:'History for note 1'}).click();await expect(page.getByRole('heading',{name:'Immutable note history'})).toBeVisible();await expect(page.getByText('Original member text')).toHaveCount(2);await expect(page.getByText('private-actor-id')).toHaveCount(0);await expect(page.getByText('private-member-id')).toHaveCount(0);await expect(page.getByText('Staff contribution',{exact:true})).toBeVisible();});
