import {test,expect,type Page} from '@playwright/test';
import {createHash} from 'node:crypto';
const file={name:'synthetic.txt',mimeType:'text/plain',buffer:Buffer.alloc(262145,65)};
async function setup(page:Page,{staff=false,theme='light',drop=''}={}){
 const writes:{path:string;body:string|null}[]=[],chunks:Buffer[]=[];let state='uploading',nextChunk=0,dropped=false;const reference='synthetic-upload',ticket='a'.repeat(64),status=()=>({reference,state,nextChunk,chunkSize:262144,maxBytes:4194304,expiresAt:Date.now()+1800000,saved:state==='saved'});
 await page.addInitScript(t=>localStorage.setItem('lancerlogin-theme',t),theme);
 await page.route('**/setup/status',r=>r.fulfill({json:{configured:true,installation:{authMode:'local'},settings:{organizationName:'Synthetic Evidence',primaryColor:'#7c3aed',secondaryColor:'#0f766e',appearance:theme}}}));
 await page.route('**/auth/session',r=>r.fulfill({json:{user:{id:'staff',role:'staff'}}}));
 await page.route('**/admin/setup/progress',r=>r.fulfill({json:{completedSteps:[]}}));
 await page.route('**/platform/modules',r=>r.fulfill({json:{capabilities:['documentation.manage'],modules:[{id:'hour-tracking',enabled:true,capabilities:['hours.manage'],navigation:{path:'/hours',label:'Hour Tracking'}},{id:'activity-documentation',enabled:true,capabilities:['documentation.manage'],navigation:{path:'/documentation',label:'Activity Documentation'}}]}}));
 const activity={id:'activity',title:'Synthetic service',serviceDate:'2020-01-01',mode:'event',revision:2,archived:false,impactRelevant:true};
 await page.route('**/public/documentation/**',r=>r.fulfill({json:{available:false}}));
 await page.route('**/admin/documentation/**',r=>{const p=new URL(r.request().url()).pathname;return r.fulfill({json:p.endsWith('/sections')?{version:1,revision:0,notesEnabled:false,summaryEnabled:true,filesEnabled:true}:p.endsWith('/activities')?{activities:[activity],next:null}:{artifacts:[],next:null}});});
 await page.route('**/documentation/uploads**',async r=>{const req=r.request(),u=new URL(req.url()),p=u.pathname.split('/uploads')[1];if(req.method()==='GET'){if(p==='/context')return r.fulfill({json:{available:true,sectionRevision:0}});if(p==='/activities')return r.fulfill({json:{activities:[activity],next:null,sectionRevision:0}});if(!p)return r.fulfill({json:{operations:[{...status(),state:'reconciling',saved:false,title:'Stored synthetic original',source:'public'}],next:null}});return r.fulfill({json:status()});}
 writes.push({path:p,body:req.postData()});if(!p){if(drop==='admission'&&!dropped){dropped=true;return r.abort('failed');}return r.fulfill({json:{...status(),ticket}});}expect(req.headers()['x-lancerlogin-upload-ticket']??(staff?ticket:'')).toBe(ticket);
 if(p.includes('/chunks/')){chunks.push(req.postDataBuffer()!);nextChunk=Number(p.split('/').at(-1))+1;if(drop==='chunk'&&!dropped){dropped=true;return r.abort('failed');}}
 else if(p.endsWith('/seal'))state='validating';else if(p.endsWith('/reconcile'))state='saved';else state=state==='validating'?'ready':state==='ready'?'preserving':'saved';return r.fulfill({json:status()});});
 return {writes,chunks};
}
async function choose(page:Page,staff=false){if(!staff)await page.getByLabel('File contributor member ID').fill('00123');await page.getByLabel('Evidence file').setInputFiles(file);await page.getByLabel('File activity',{exact:true}).selectOption('activity');}
test('public file succeeds with Notes disabled and preserves exact bytes independently',async({page})=>{const f=await setup(page);await page.goto('/submit-documentation');await expect(page.getByRole('heading',{name:'Note submission unavailable'})).toBeVisible();await choose(page);await page.getByRole('button',{name:'Upload file',exact:true}).click();await expect(page.getByRole('heading',{name:'File saved privately'})).toBeVisible();const input=JSON.parse(f.writes[0].body!);expect(input.memberId).toBe('00123');expect(input.sha256).toBe(createHash('sha256').update(file.buffer).digest('hex'));expect(Buffer.concat(f.chunks)).toEqual(file.buffer);expect(f.writes.filter(w=>w.path==='')).toHaveLength(1);expect(await page.evaluate(()=>JSON.stringify({...localStorage,...sessionStorage}))).not.toContain('00123');});
test('unconfirmed admission retries its exact frozen body only on explicit action',async({page})=>{const f=await setup(page,{drop:'admission'});await page.goto('/submit-documentation');await choose(page);await page.getByRole('button',{name:'Upload file',exact:true}).click();await expect(page.getByRole('alert')).toContainText('unconfirmed');expect(f.writes).toHaveLength(1);await expect(page.getByLabel('Evidence file')).toBeDisabled();await page.getByRole('button',{name:'Retry this submission',exact:true}).click();await expect(page.getByRole('heading',{name:'File saved privately'})).toBeVisible();expect(f.writes[1].body).toBe(f.writes[0].body);});
test('lost chunk response checks current operation then continues without new admission',async({page})=>{const f=await setup(page,{drop:'chunk'});await page.goto('/submit-documentation');await choose(page);await page.getByRole('button',{name:'Upload file',exact:true}).click();await expect(page.getByRole('alert')).toContainText('unconfirmed');await page.getByRole('button',{name:'Check this upload'}).click();await expect(page.getByText('Current upload checked.',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Continue this upload'}).click();await expect(page.getByRole('heading',{name:'File saved privately'})).toBeVisible();expect(f.writes.filter(w=>w.path==='')).toHaveLength(1);expect(f.chunks).toHaveLength(2);});
test('staff uploads and explicitly reconciles existing inventory',async({page})=>{const f=await setup(page,{staff:true});await page.goto('/documentation');await page.getByRole('button',{name:'File uploads',exact:true}).click();await page.getByRole('button',{name:'Reconcile Stored synthetic original'}).click();await expect(page.getByText('Original file confirmed and artifact saved.')).toBeVisible();expect(f.writes[0].path).toContain('/reconcile');});
for(const [width,height,theme,staff] of [[390,844,'dark',false],[1280,900,'light',false],[390,844,'light',true],[1280,900,'dark',true]] as const)test(`file interface visual ${width} ${theme} ${staff}`,async({page})=>{await setup(page,{staff,theme});await page.setViewportSize({width,height});await page.goto(staff?'/documentation':'/submit-documentation');if(staff)await page.getByRole('button',{name:'File uploads',exact:true}).click();await choose(page,staff);const button=page.getByRole('button',{name:'Upload file',exact:true});await page.keyboard.press('Tab');await button.focus();await expect(button).toBeFocused();expect(await button.evaluate(e=>getComputedStyle(e).outlineStyle)).not.toBe('none');expect((await button.boundingBox())!.height).toBeGreaterThanOrEqual(44);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:test.info().outputPath('file-interface.png'),fullPage:true});});

test('staff focus recheck preserves selected file and uncertain admission identity',async({page})=>{
 const f=await setup(page,{staff:true,drop:'admission'});await page.goto('/documentation');await page.getByRole('button',{name:'File uploads',exact:true}).click();await choose(page,true);
 await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByRole('button',{name:'Upload file',exact:true})).toBeEnabled();expect(await page.getByLabel('Evidence file').evaluate((e:HTMLInputElement)=>e.files?.[0]?.name)).toBe(file.name);
 await page.getByRole('button',{name:'Upload file',exact:true}).click();await expect(page.getByRole('alert')).toContainText('unconfirmed');await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByRole('button',{name:'Retry this submission',exact:true})).toBeEnabled();await expect(page.getByLabel('Evidence file')).toBeDisabled();expect(f.writes).toHaveLength(1);
 await page.getByRole('button',{name:'Retry this submission',exact:true}).click();await expect(page.getByRole('heading',{name:'File saved privately'})).toBeVisible();expect(f.writes.filter(w=>w.path==='')).toHaveLength(2);expect(f.writes[1].body).toBe(f.writes[0].body);
});
