import {test,expect,type Page} from '@playwright/test';
async function setup(page:Page,theme='light',drop=false,terminalState='reconciling'){
 let selected=false,dropped=false,state='ready';const writes:{path:string;body:string|null}[]=[];
 const operation=()=>({reference:'synthetic-copy',title:'Synthetic original',state,saved:state==='saved',artifactId:state==='saved'?'artifact':null,requiresReconciliation:state==='reconciling'});
 await page.addInitScript(t=>localStorage.setItem('lancerlogin-theme',t),theme);
 await page.route('**/setup/status',r=>r.fulfill({json:{configured:true,installation:{authMode:'local'},settings:{organizationName:'Synthetic Copies',primaryColor:'#7c3aed',secondaryColor:'#0f766e',appearance:theme}}}));
 await page.route('**/auth/session',r=>r.fulfill({json:{user:{id:'staff',role:'staff'}}}));
 await page.route('**/admin/setup/progress',r=>r.fulfill({json:{completedSteps:[]}}));
 await page.route('**/platform/modules',r=>r.fulfill({json:{capabilities:['documentation.manage'],modules:[{id:'hour-tracking',enabled:true,capabilities:['hours.manage'],navigation:{path:'/hours',label:'Hour Tracking'}},{id:'activity-documentation',enabled:true,capabilities:['documentation.manage'],navigation:{path:'/documentation',label:'Activity Documentation'}}]}}));
 await page.route('**/admin/documentation/**',r=>{const p=new URL(r.request().url()).pathname;return r.fulfill({json:p.endsWith('/sections')?{version:1,revision:3,notesEnabled:true,summaryEnabled:true,filesEnabled:true}:p.endsWith('/activities')?{activities:[{id:'activity',title:'Synthetic service',revision:2,archived:false,impactRelevant:true}],next:null}:{initiatives:[],next:null}});});
 await page.route('**/admin/connections/google/drive/**',r=>{const p=new URL(r.request().url()).pathname;
 if(p.endsWith('/status')){expect(new URL(r.request().url()).searchParams.get('purpose')).toBe('documentation-source');return r.fulfill({json:{revision:4,configRevision:1,configured:true,rootName:'Private root',intent:{id:'intent',purpose:'documentation-source',status:selected?'selected':'ready'}}});}
 if(p.endsWith('/claim'))return r.fulfill({json:{intentId:'intent',purpose:'documentation-source',scope:'https://www.googleapis.com/auth/drive.file',accessToken:'synthetic-only-token',expiresAt:Date.now()+60000,projectNumber:'123456',browserKey:'synthetic_browser_key_0000'}});
 if(p.endsWith('/selection')){selected=true;return r.fulfill({json:{selected:true,purpose:'documentation-source',name:'Synthetic source',mimeType:'application/vnd.google-apps.document',intentId:'intent'}});}return r.fulfill({status:400,json:{error:'Unexpected'}});});
 await page.route('**/documentation/drive-copies**',r=>{const p=new URL(r.request().url()).pathname.split('/drive-copies')[1];if(r.request().method()==='GET')return r.fulfill({json:p?operation():{operations:[],next:null}});writes.push({path:p,body:r.request().postData()});if(!p&&drop&&!dropped){dropped=true;return r.abort('failed');}if(p.endsWith('/advance'))state=terminalState;if(p.endsWith('/reconcile'))state='saved';return r.fulfill({status:202,json:operation()});});
 await page.addInitScript(()=>{class View{setMode(){return this;}}class Builder{callback:any;addView(){return this;}setOAuthToken(){return this;}setDeveloperKey(){return this;}setAppId(){return this;}setOrigin(){return this;}setCallback(c:any){this.callback=c;return this;}build(){return {dispose(){},setVisible:(visible:boolean)=>{if(visible)setTimeout(()=>this.callback({action:'picked',docs:[{id:'synthetic-source'}]}),0);}}}}(window as any).gapi={load(_n:string,o:any){o.callback();}};(window as any).google={picker:{DocsView:View,DocsViewMode:{LIST:'list'},PickerBuilder:Builder,Action:{PICKED:'picked',CANCEL:'cancel'}}};});
 return {writes};
}
async function choose(page:Page){await page.goto('/documentation?drivePicker=ready');await page.getByRole('button',{name:'Open Google Picker'}).click();await expect(page.getByText('Drive source selected.',{exact:true})).toBeVisible();await page.getByLabel('Copy title',{exact:true}).fill('Synthetic original');await page.getByLabel('Associate Synthetic service').check();}
test('staff selected copy freezes ambiguous admission and explicitly reconciles same operation',async({page})=>{const f=await setup(page,'light',true);await choose(page);await expect(page.getByLabel('Google Cloud project number')).toHaveCount(0);await page.getByRole('button',{name:'Preserve selected original'}).click();await expect(page.getByRole('alert')).toContainText('unconfirmed');await expect(page.getByLabel('Copy title',{exact:true})).toBeDisabled();expect(f.writes).toHaveLength(1);await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await page.getByRole('button',{name:'Retry this same copy request'}).click();await expect(page.getByRole('heading',{name:'Ready to preserve',exact:true})).toBeVisible();expect(f.writes[0].body).toBe(f.writes[1].body);expect(JSON.parse(f.writes[0].body!).activities).toEqual([{activityId:'activity',revision:2}]);await page.getByRole('button',{name:'Continue Synthetic original'}).click();await expect(page.getByRole('heading',{name:'Copy needs reconciliation'})).toBeVisible();expect(f.writes).toHaveLength(3);await page.getByRole('button',{name:'Check Synthetic original'}).click();expect(f.writes).toHaveLength(3);await page.getByRole('button',{name:'Reconcile Synthetic original'}).click();await expect(page.getByRole('heading',{name:'Private copy saved'})).toBeVisible();expect(f.writes.filter(x=>x.path==='')).toHaveLength(2);expect(await page.evaluate(()=>JSON.stringify({...localStorage,...sessionStorage}))).not.toContain('synthetic-only-token');});
for(const theme of ['light','dark'])for(const width of [1280,390])test(`Drive copy layout ${theme} ${width}`,async({page})=>{await setup(page,theme);await page.setViewportSize({width,height:width===390?844:900});await choose(page);await expect(page.getByRole('heading',{level:1})).toHaveCount(1);const button=page.getByRole('button',{name:'Preserve selected original'});await page.keyboard.press('Tab');await button.focus();await expect(button).toBeFocused();expect(await button.evaluate(e=>getComputedStyle(e).outlineStyle)).not.toBe('none');expect((await button.boundingBox())!.height).toBeGreaterThanOrEqual(44);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:test.info().outputPath('drive-copy.png'),fullPage:true});});



for(const state of ['saved','failed'])test(`confirmed ${state} copy allows navigation and failed source replacement`,async({page})=>{const f=await setup(page,'light',false,state);await choose(page);await page.getByRole('button',{name:'Preserve selected original'}).click();await page.getByRole('button',{name:'Continue Synthetic original'}).click();await expect(page.getByRole('heading',{name:state==='saved'?'Private copy saved':'Copy not accepted',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Artifacts',exact:true})).toBeEnabled();if(state==='failed'){await page.getByRole('button',{name:'Choose a different original'}).click();await expect(page.getByLabel('Copy title',{exact:true})).toBeEnabled();await expect(page.getByLabel('Copy title',{exact:true})).toHaveValue('');await expect(page.getByRole('heading',{name:'Choose a Drive original'})).toBeVisible();expect(f.writes.filter(x=>x.path==='')).toHaveLength(1);}await page.getByRole('button',{name:'Artifacts',exact:true}).click();await expect(page.getByRole('heading',{name:'Artifacts',exact:true})).toBeVisible();});
