import {test,expect,type Page} from '@playwright/test';
import {dashboardConformanceReferences as reference} from '../apps/dashboard/src/design-conformance';
const scope='https://www.googleapis.com/auth/drive.file';
const area=(page:Page)=>page.getByRole('heading',{name:'Shared Drive storage',exact:true}).locator('..');
async function setup(page:Page,theme='light'){
 let ready=true,fail=0,uncertain=false,denied=false;const writes:any[]=[];let state:any={configured:true,revision:2,rootId:'saved-root',rootName:'Saved private root',verifiedAt:null,verifiedForConnection:false};let intent:any={id:'selected-root',purpose:'root',status:'selected'};
 await page.addInitScript(value=>localStorage.setItem('lancerlogin-theme',value),theme);
 await page.route('**/setup/status',route=>route.fulfill({json:{configured:true,installation:{authMode:'local'},settings:{organizationName:'Synthetic Picker Team',primaryColor:reference.brand.primary,secondaryColor:reference.brand.secondary,appearance:theme}}}));
 await page.route('**/admin/connections/google/storage',async route=>{if(denied){await route.fulfill({status:403,json:{error:'Unavailable'}});return;}if(route.request().method()==='PUT'){writes.push(route.request().postDataJSON());if(fail){await route.fulfill({status:fail,json:{error:'Conflict'}});return;}state={...state,revision:state.revision+1,rootName:'New private root',rootId:'new-root',verifiedAt:'2026-09-10T13:00:00Z',verifiedForConnection:true};intent=null;if(uncertain){await route.abort();return;}await route.fulfill({json:{saved:true,revision:state.revision}});return;}await route.fulfill({json:state});});
 await page.route('**/admin/connections/google/drive/status',route=>route.fulfill({json:{revision:1,configRevision:1,configured:true,rootName:'Transient feasibility root',intent}}));
 await page.route('**/admin/connections/google/drive/picker/claim',route=>{intent={...intent,status:'claimed'};return route.fulfill({json:{intentId:'selected-root',purpose:'root',scope,accessToken:'synthetic-drive-only-token',expiresAt:Date.now()+1500,projectNumber:'123456',browserKey:'synthetic_browser_key_0000'}});});
 await page.route('**/admin/connections/google/drive/selection',route=>{intent={...intent,status:'selected'};return route.fulfill({json:{selected:true}});});
 await page.route('**/admin/integrations',route=>route.fulfill({json:{integrations:[]}}));
 await page.route('**/admin/integrations/discord/channel-manager',route=>route.fulfill({json:{enabled:false,contestWindowHours:24}}));
 await page.route('**/admin/integrations/discord/anomaly-reports',route=>route.fulfill({json:{enabled:false,channelId:''}}));
 await page.route('**/admin/connections/google',route=>route.fulfill({json:{revision:1,mode:'shared',active:{generation:'synthetic',loginEnabled:false,loginVerified:false,calendarEnabled:false,driveEnabled:true,organizationAuthorized:true,grantedScopes:[scope],calendarReady:false,driveReady:ready,calendarSelected:false},candidate:null,callbackUri:'https://fixture.test/api/admin/connections/google/callback',loginCallbackUri:'https://fixture.test/api/auth/google/callback'}}));
 return {writes,state,setReady:(value:boolean)=>ready=value,setFail:(value:number)=>fail=value,setUncertain:()=>uncertain=true,deny:()=>denied=true,readyIntent:()=>intent={id:'selected-root',purpose:'root',status:'ready'}};
}

async function select(page:Page){await page.getByRole('button',{name:'Select shared storage folder',exact:true}).click();await expect(page.getByRole('button',{name:'Verify and save shared folder',exact:true})).toBeEnabled();}
test('durable inventory is distinct from selection and saved only explicitly',async({page})=>{const f=await setup(page);await page.goto('/settings/integrations');const view=area(page);await expect(view).toContainText('Saved private root');await expect(view).toContainText('Saved inventory only');await select(page);await expect(view).not.toContainText('Transient feasibility root');expect(f.writes).toHaveLength(0);await view.getByRole('button',{name:'Verify and save shared folder'}).click();await expect(view).toContainText('New private root');await expect(view).toContainText('not a fresh folder privacy check');expect(f.writes).toEqual([{revision:2,pickerIntentId:'selected-root',connectionRevision:1}]);await expect(view.getByRole('button',{name:'Verify and save shared folder'})).toBeDisabled();});
test('uncertain consumed selection reloads inventory without replay',async({page})=>{const f=await setup(page);f.setUncertain();await page.goto('/settings/integrations');await select(page);await page.getByRole('button',{name:'Verify and save shared folder'}).click();await expect(area(page).getByRole('alert')).toBeFocused();await expect(area(page)).toContainText('No write is retried automatically');await page.getByRole('button',{name:'Reload shared storage'}).click();await expect(area(page)).toContainText('New private root');await expect(page.getByRole('button',{name:'Verify and save shared folder'})).toBeDisabled();expect(f.writes).toHaveLength(1);});
test('conflict requires reloading and fresh selection; denied reload clears inventory',async({page})=>{const f=await setup(page);await page.goto('/settings/integrations');await select(page);f.setFail(409);await page.getByRole('button',{name:'Verify and save shared folder'}).click();await expect(page.getByRole('button',{name:'Select shared storage folder'})).toBeDisabled();f.deny();await page.getByRole('button',{name:'Reload shared storage'}).click();await expect(area(page)).not.toContainText('Saved private root');expect(f.writes).toHaveLength(1);});
test('unavailable Drive still shows restored inventory and no Picker writes',async({page})=>{const f=await setup(page);f.setReady(false);await page.goto('/settings/integrations');await expect(area(page)).toContainText('Saved private root');await expect(area(page)).toContainText('Drive capability is unavailable');await expect(page.getByRole('button',{name:'Select shared storage folder'})).toBeDisabled();expect(f.writes).toHaveLength(0);});
for(const mode of ['cancel','expiry'])test('storage Picker '+mode+' cannot save',async({page})=>{const f=await setup(page);f.readyIntent();await page.addInitScript(mode=>{class View{setMode(){return this;}setIncludeFolders(){return this;}setSelectFolderEnabled(){return this;}setMimeTypes(){return this;}}class Builder{callback:any;addView(){return this;}setOAuthToken(){return this;}setDeveloperKey(){return this;}setAppId(){return this;}setOrigin(){return this;}setCallback(value:any){this.callback=value;return this;}build(){const callback=this.callback;return {dispose(){},setVisible(value:boolean){if(value&&mode==='cancel')setTimeout(()=>callback({action:'cancel'}),0);}};}}(window as any).gapi={load(_name:string,options:any){options.callback();}};(window as any).google={picker:{DocsView:View,DocsViewMode:{LIST:'list'},PickerBuilder:Builder,Action:{PICKED:'picked',CANCEL:'cancel'}}};},mode);await page.goto('/settings/integrations');await page.getByRole('button',{name:'Select shared storage folder'}).click();await page.getByRole('button',{name:'Open Google Picker'}).click();await expect(area(page)).toContainText(mode==='cancel'?'Selection cancelled':'Picker authorization expired');await expect(page.getByRole('button',{name:'Verify and save shared folder'})).toBeDisabled();expect(f.writes).toHaveLength(0);});
for(const viewport of reference.viewports)for(const theme of reference.themes)test('storage visual '+viewport.width+' '+theme,async({page})=>{await setup(page,theme);await page.setViewportSize(viewport);await page.goto('/settings/integrations');await select(page);const view=area(page),button=view.getByRole('button',{name:'Verify and save shared folder'});await page.keyboard.press('Tab');await button.focus();await expect(button).toBeFocused();expect(await button.evaluate(e=>getComputedStyle(e).outlineStyle)).not.toBe('none');expect((await button.boundingBox())!.height).toBeGreaterThanOrEqual(44);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:test.info().outputPath('storage.png'),fullPage:true});});

test('late failure from replaced Picker cannot clear a new selected folder',async({page})=>{await setup(page);let release=()=>{};const gate=new Promise<void>(resolve=>release=resolve);let first=true;await page.route('**/admin/connections/google/drive/status',async route=>{if(first){first=false;await gate;await route.fulfill({status:409,json:{error:'Old request failed'}});return;}await route.fallback();});await page.goto('/settings/integrations');await page.getByRole('button',{name:'Select shared storage folder'}).click();await expect.poll(()=>first).toBe(false);await page.getByRole('button',{name:'Select shared storage folder'}).click();await expect(page.getByRole('button',{name:'Verify and save shared folder'})).toBeEnabled();release();await expect(page.getByRole('heading',{name:'Choose shared storage folder',level:3})).toBeVisible();await expect(page.getByRole('button',{name:'Verify and save shared folder'})).toBeEnabled();});
