import { expect, test, type Page } from '@playwright/test';
import { selectCivilTime, addCalendarDays } from '../packages/shared/src/civil-time';
import { dashboardConformanceReferences as reference } from '../apps/dashboard/src/design-conformance';
const activity={id:'event',revision:0,archived:false,categoryId:'event-category',mode:'event',teamId:null,serviceDate:'2025-11-02',title:'Synthetic service day',description:'',location:'',planningTimeZone:'America/New_York',startsAt:null,endsAt:null,impactRelevant:false};
const category={id:'event-category',revision:0,archived:false,name:'Event',mode:'event',impactDefault:false};
const team={id:'team',revision:0,archived:false,name:'Synthetic team',number:'00123',organization:'',program:'',historicalDescriptors:''};
const initial={id:'entry',memberId:'member',activityId:'event',serviceDate:'2025-11-02',timeZone:'America/New_York',startLocal:'01:30',endLocal:'01:30',endNextDay:false,startOccurrence:'earlier',endOccurrence:'later',startMs:Date.parse('2025-11-02T05:30Z'),endMs:Date.parse('2025-11-02T06:30Z'),startOffsetSeconds:-14400,endOffsetSeconds:-18000,durationMinutes:60,taskNotes:'Synthetic note',status:'counted',channel:'staff',attribution:'staff_recorded',revision:0,createdAt:'2025-11-03T12:00:00Z',updatedAt:'2025-11-03T12:00:00Z'};
async function setup(page:Page,theme='light',role='staff') {
 let records:any[]=[{...initial}],history:any[]=[{entryId:'entry',revision:0,action:'created',reason:'',createdAt:initial.createdAt,snapshot:{...initial}}],windows:any[]=[];let activityDate=activity.serviceDate,wrongReceiptDate=false;let zone='America/New_York',fail=false,malformed=false,dropCreate=false,deny=false,failDetail=false,badReceipt=false;let config={revision:0,reportingDays:7,reopenHours:24};const writes:any[]=[],requests:string[]=[],receipts=new Map();
 await page.clock.setFixedTime(new Date('2026-09-09T16:00:00Z'));
 await page.addInitScript(value=>localStorage.setItem('lancerlogin-theme',value),theme);
 await page.route('**/setup/status',r=>r.fulfill({json:{configured:true,installation:{authMode:'local'},settings:{organizationName:'Synthetic Hours',primaryColor:reference.brand.primary,secondaryColor:reference.brand.secondary,appearance:theme}}}));
 await page.route('**/auth/session',r=>r.fulfill({json:{user:{id:'staff',role}}}));
 await page.route('**/admin/setup/progress',r=>r.fulfill({json:{completedSteps:['branding','roster','pair-kiosk','fingerprint-test','confirm-attendance'].map(step=>({step}))}}));
 await page.route('**/platform/modules',r=>r.fulfill({json:{capabilities:deny?[]:['hours.manage'],modules:[{id:'hour-tracking',enabled:!deny,capabilities:['hours.manage'],navigation:{path:'/hours',label:'Hour Tracking'}}]}}));
 await page.route('**/admin/hours/**',async r=>{
  const req=r.request(),url=new URL(req.url()),[kind,id,action]=url.pathname.split('/admin/hours/')[1].split('/');requests.push(url.pathname+url.search);const get=req.method()==='GET';const body=get?null:req.postDataJSON();if(body)writes.push({kind,id,action,body});
  if(deny)return r.fulfill({status:403,json:{error:'Denied'}});if(!get&&fail)return r.fulfill({status:409,json:{error:'Synthetic conflict'}});if(get&&malformed)return r.fulfill({json:{}});
  const pageOf=(items:any[])=>{const after=url.searchParams.get('after');const rows=items.filter(v=>!after||v.id>after);return {items:rows.slice(0,50),nextCursor:rows.length>50?rows[49].id:null};};
  if(kind==='attendance-sources')return r.fulfill({json:{items:[],nextCursor:null,timeZone:zone}});
  if(kind==='member-choices'){const members=[{id:'member',label:'Synthetic member',externalId:'00017',active:true},{id:'inactive',label:'Synthetic former member',externalId:'00018',active:false}];return r.fulfill({json:id?members.find(v=>v.id===id):pageOf(members.filter(v=>(url.searchParams.get('active')==='all'||v.active)&&(!url.searchParams.get('q')||v.label.includes(url.searchParams.get('q')!))))});}
  if(['activities','categories','teams'].includes(kind)){const values=kind==='activities'?[{...activity,serviceDate:activityDate}]:kind==='teams'?[team]:[category,{...category,id:'task-category',name:'Other service',mode:'task'},{...category,id:'team-category',name:'Team support',mode:'team'}];return r.fulfill({json:id?values.find(v=>v.id===id)??{...activity,id,title:'Synthetic dated service'}:pageOf(values)});}
  if(kind==='entry-settings'){if(!get){config={...config,...body,revision:config.revision+1};return r.fulfill({json:config});}return r.fulfill({json:{...config,timeZone:zone,today:'2026-09-09'}});}
  if(kind==='entries'){
   if(get){if(id&&failDetail)return r.fulfill({json:{}});if(action==='history')return r.fulfill({json:{items:history.filter(v=>v.entryId===id&&v.revision>Number(url.searchParams.get('after')??-1)),nextCursor:null}});return r.fulfill({json:id?records.find(v=>v.id===id):pageOf(records.filter(v=>(!url.searchParams.get('status')||v.status===url.searchParams.get('status'))))});}
   if(!id&&receipts.has(body.idempotencyKey))return r.fulfill({status:201,json:receipts.get(body.idempotencyKey)});
   const old=id?records.find(v=>v.id===id):undefined;if(body.activityId&&body.serviceDate!==activityDate)return r.fulfill({status:400,json:{error:'Use the activity service date'}});if(!id&&body.expectedTimeZone!==zone)return r.fulfill({status:409,json:{error:'Zone changed'}});
   const value:any={...initial,...old,...(!old?{startOccurrence:null,endOccurrence:null}:{}),...body,id:id??'new-entry',activityId:body.activityId??old?.activityId??'event',serviceDate:body.serviceDate??old?.serviceDate??activity.serviceDate,timeZone:old?.timeZone??zone,revision:old?old.revision+1:0,status:action==='void'?'void':'counted'};
   const start=selectCivilTime({date:value.serviceDate,time:value.startLocal,timeZone:value.timeZone},value.startOccurrence??undefined),end=selectCivilTime({date:addCalendarDays(value.serviceDate,Number(value.endNextDay)),time:value.endLocal,timeZone:value.timeZone},value.endOccurrence??undefined);if(action!=='void')Object.assign(value,{startMs:start.epochMilliseconds,endMs:end.epochMilliseconds,startOffsetSeconds:start.offsetSeconds,endOffsetSeconds:end.offsetSeconds,durationMinutes:(end.epochMilliseconds-start.epochMilliseconds)/60000});records=[...records.filter(v=>v.id!==value.id),value];history.push({entryId:value.id,revision:value.revision,action:action==='void'?'voided':old?'corrected':'created',reason:body.reason??'',createdAt:value.updatedAt,snapshot:{...value}});
   if(!id){const receipt:any={};for(const key of ['id','activityId','serviceDate','timeZone','startLocal','endLocal','endNextDay','startOccurrence','endOccurrence','startMs','endMs','startOffsetSeconds','endOffsetSeconds','durationMinutes','taskNotes','createdAt'])receipt[key.replace(/[A-Z]/g,c=>'_'+c.toLowerCase())]=value[key];receipt.end_next_day=Number(receipt.end_next_day);if(badReceipt)receipt.duration_minutes=999;if(wrongReceiptDate){receipt.service_date=addCalendarDays(receipt.service_date,1);receipt.start_ms+=86400000;receipt.end_ms+=86400000;}receipts.set(body.idempotencyKey,receipt);if(dropCreate){dropCreate=false;return r.abort();}return r.fulfill({status:201,json:receipt});}return r.fulfill({json:{id,revision:value.revision,status:value.status}});
  }
  if(kind==='reopen-windows'){if(get)return r.fulfill({json:id?windows.find(v=>v.id===id):pageOf(windows)});const old=windows.find(v=>v.id===id);const value={id:id??'window',activityId:body.activityId??null,startsMs:Date.parse('2026-09-09T16:00Z'),expiresMs:Date.parse('2026-09-10T16:00Z'),revoked:false,active:true,createdAt:'2026-09-09T16:00Z',...old,...body,revision:old?old.revision+1:0};if(value.revoked)value.active=false;windows=[...windows.filter(v=>v.id!==value.id),value];return r.fulfill({json:{id:value.id,revision:value.revision}});}
  return r.fulfill({status:404,json:{error:'Missing fixture'}});
 });
 return {writes,requests,activityDate:(value:string)=>activityDate=value,wrongReceiptDate:()=>wrongReceiptDate=true,detail:(v=true)=>failDetail=v,badReceipt:()=>badReceipt=true,fail:(v=true)=>fail=v,malformed:(v=true)=>malformed=v,drop:()=>dropCreate=true,zone:(v:string)=>zone=v,deny:()=>deny=true,records:(values:any[])=>{records=values;history=values.map(value=>({entryId:value.id,revision:value.revision,action:'created',reason:'',createdAt:value.createdAt,snapshot:{...value}}));}};
}
async function entries(page:Page){await page.goto('/hours');await page.getByRole('button',{name:'Entries',exact:true}).click();await expect(page.getByRole('button',{name:'Record hours',exact:true})).toBeEnabled();}
async function createForm(page:Page){await page.getByRole('button',{name:'Record hours',exact:true}).click();await page.getByLabel('Member',{exact:true}).selectOption('member');await page.getByLabel('Dated activity',{exact:true}).selectOption('event');await page.getByLabel('Start time',{exact:true}).fill('10:00');await page.getByLabel('End time',{exact:true}).fill('11:00');}
test('staff records inactive historical member and corrects/voids with immutable history',async({page})=>{
 const f=await setup(page);await entries(page);await createForm(page);await page.getByLabel('Include inactive members').check();await page.getByLabel('Member',{exact:true}).selectOption('inactive');await page.getByRole('button',{name:'Record completed hours'}).click();await expect(page.getByText('Original submission accepted.',{exact:false})).toBeVisible();expect(f.writes[0].body).toMatchObject({memberId:'inactive',expectedTimeZone:'America/New_York',endNextDay:false});expect(f.writes[0].body.idempotencyKey).toHaveLength(36);
 await page.getByRole('button',{name:'Correct entry',exact:true}).click();await expect(page.getByRole('heading',{name:'Correct entry'})).toBeFocused();await page.getByLabel('Correction reason').fill('Synthetic correction');await page.getByLabel('End time',{exact:true}).fill('11:30');await page.getByRole('button',{name:'Save correction'}).click();await expect(page.getByText('90 minutes (1.50 hours)',{exact:false})).toBeVisible();expect(f.writes[1].body).not.toHaveProperty('expectedTimeZone');
 await page.getByRole('button',{name:'Void entry',exact:true}).click();await page.getByLabel('Void reason').fill('Synthetic duplicate');await page.getByRole('button',{name:'Confirm void'}).click();await expect(page.getByText('Void is terminal.',{exact:false})).toBeVisible();await page.getByRole('button',{name:'View history'}).click();await expect(page.getByRole('heading',{name:'Immutable history'})).toBeVisible();await expect(page.getByText('Reason: Synthetic correction')).toBeVisible();await expect(page.getByText('Names below are current',{exact:false})).toBeVisible();
});
test('uncertain creation freezes payload/key and explicit retry reads current state once',async({page})=>{const f=await setup(page);await entries(page);await createForm(page);f.drop();await page.getByRole('button',{name:'Record completed hours'}).click();await expect(page.getByRole('alert')).toContainText('No change is retried automatically');await expect(page.getByLabel('Task notes')).toBeDisabled();expect(f.writes).toHaveLength(1);await page.getByRole('button',{name:'Retry exact submission'}).click();await expect(page.getByText('Original submission accepted.',{exact:false})).toBeVisible();expect(f.writes).toHaveLength(2);expect(f.writes[1].body).toEqual(f.writes[0].body);});
test('saved zone corrections preserve independent folds; gaps and fractional minutes block',async({page})=>{await setup(page);await entries(page);await page.getByRole('button',{name:'Review entry 1'}).click();await page.getByRole('button',{name:'Correct entry',exact:true}).click();await expect(page.getByLabel('Start time occurrence')).toHaveValue('earlier');await expect(page.getByLabel('End time occurrence')).toHaveValue('later');await page.getByLabel('Correction reason').fill('Synthetic');await page.getByLabel('End time',{exact:true}).fill('02:30:00.001');await expect(page.getByRole('button',{name:'Save correction'})).toBeDisabled();await page.getByLabel('Activity selection').selectOption('canonical');await page.getByLabel('Entry category',{exact:true}).selectOption('task-category');await page.getByLabel('Service date',{exact:true}).fill('2025-03-09');await page.getByLabel('Start time',{exact:true}).fill('02:30');await expect(page.getByText('This local time does not exist',{exact:false}).first()).toBeVisible();});
test('canonical team service uses local clocks and explicit next day',async({page})=>{const f=await setup(page);await entries(page);await page.getByRole('button',{name:'Record hours',exact:true}).click();await page.getByLabel('Member',{exact:true}).selectOption('member');await page.getByLabel('Activity selection').selectOption('canonical');await page.getByLabel('Entry category',{exact:true}).selectOption('team-category');await page.getByLabel('Supported team',{exact:true}).selectOption('team');await page.getByLabel('Service date',{exact:true}).fill('2025-11-01');await page.getByLabel('Start time',{exact:true}).fill('23:30');await page.getByLabel('End time',{exact:true}).fill('00:30');await expect(page.getByRole('button',{name:'Record completed hours'})).toBeDisabled();await page.getByLabel('End on the next calendar day').check();await page.getByRole('button',{name:'Record completed hours'}).click();expect(f.writes[0].body).toMatchObject({activityId:null,categoryId:'team-category',teamId:'team',serviceDate:'2025-11-01',endNextDay:true});});
test('settings and windows require readback and preserve explicit all-event scope',async({page})=>{const f=await setup(page);await page.goto('/hours');await page.getByRole('button',{name:'Reporting windows',exact:true}).click();await page.getByLabel('Reporting days').fill('10');await page.getByRole('button',{name:'Save reporting settings'}).click();await expect(page.getByText('Reporting settings confirmed',{exact:false})).toBeVisible();await page.getByLabel('Reopening scope').selectOption('all');await page.getByRole('button',{name:'Open reporting window'}).click();expect(f.writes.at(-1).body.activityId).toBeNull();await expect(page.getByRole('heading',{name:'Last confirmed window'})).toBeVisible();await page.getByRole('button',{name:'Revoke window ending',exact:false}).click();await expect(page.getByText('Window revocation confirmed',{exact:false})).toBeVisible();f.fail();await page.getByRole('button',{name:'Save reporting settings'}).click();await expect(page.getByRole('alert')).toBeFocused();await expect(page.getByRole('button',{name:'Open reporting window'})).toBeDisabled();f.fail(false);await page.getByRole('button',{name:'Reload reporting windows'}).click();await expect(page.getByRole('button',{name:'Save reporting settings'})).toBeEnabled();});
test('malformed reads and revoked access close entry mutations',async({page})=>{const f=await setup(page);await entries(page);f.malformed();await page.getByRole('button',{name:'Reload entries',exact:true}).click();await expect(page.getByRole('button',{name:'Record hours',exact:true})).toBeDisabled();f.malformed(false);await page.getByRole('button',{name:'Reload entries',exact:true}).click();await expect(page.getByRole('button',{name:'Record hours',exact:true})).toBeEnabled();f.deny();await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByRole('heading',{name:'Workspace unavailable'})).toBeVisible();});
test('entry paging retains applied filters until explicit apply',async({page})=>{const f=await setup(page);f.records(Array.from({length:51},(_,i)=>({...initial,id:'entry-'+String(i).padStart(3,'0')})));await entries(page);await page.getByLabel('Entry status').selectOption('void');await page.getByRole('button',{name:'Next entries page'}).click();await expect(page.getByText('1 entries on this page.',{exact:false})).toBeVisible();expect(f.requests.filter(v=>v.includes('/entries?')).at(-1)).not.toContain('status=');await page.getByRole('button',{name:'Apply entry filters'}).click();await expect(page.getByText('No entries match')).toBeVisible();});
for(const theme of ['light','dark'])for(const width of [1280,390])test(`entry form ${theme} ${width} keyboard and branding`,async({page},info)=>{await page.setViewportSize({width,height:width===390?844:900});await page.emulateMedia({colorScheme:theme as 'light'|'dark',reducedMotion:'reduce'});await setup(page,theme);await entries(page);await page.getByRole('button',{name:'Review entry 1'}).click();await page.getByRole('button',{name:'Correct entry',exact:true}).click();await expect(page.getByRole('heading',{name:'Correct entry'})).toBeFocused();await page.keyboard.press('Tab');await expect(page.getByLabel('Find roster name or ID')).toBeFocused();expect(await page.getByRole('heading',{level:1}).count()).toBe(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);for(const button of await page.locator('.hours-workspace button').all())if(await button.isVisible())expect((await button.boundingBox())!.height).toBeGreaterThanOrEqual(44);await page.screenshot({path:info.outputPath(`entries-${theme}-${width}.png`),fullPage:true});});


test('known receipt failure recovers through GET only and malformed receipt stays locked',async({page})=>{const f=await setup(page);await entries(page);await createForm(page);f.detail();await page.getByRole('button',{name:'Record completed hours'}).click();await expect(page.getByRole('alert')).toBeVisible();await expect(page.getByRole('button',{name:'Retry exact submission'})).toHaveCount(0);f.detail(false);await page.getByRole('button',{name:'Reload current entries'}).click();await expect(page.getByText('Original submission accepted.',{exact:false})).toBeVisible();expect(f.writes).toHaveLength(1);await page.getByRole('button',{name:'Close entry',exact:true}).click();await createForm(page);f.badReceipt();await page.getByRole('button',{name:'Record completed hours'}).click();await expect(page.getByRole('alert')).toBeVisible();await expect(page.getByLabel('Task notes')).toBeDisabled();});

test('stale zone and correction conflicts require reload without automatic writes',async({page})=>{const f=await setup(page);await entries(page);await createForm(page);f.zone('Asia/Tokyo');await page.getByRole('button',{name:'Record completed hours'}).click();await expect(page.getByRole('alert')).toContainText('changed organization time zone');expect(f.writes).toHaveLength(1);await page.getByRole('button',{name:'Discard draft and review entries'}).click();await page.getByRole('button',{name:'Reload current entries'}).click();await page.getByRole('button',{name:'Review entry 1'}).click();await page.getByRole('button',{name:'Correct entry',exact:true}).click();await expect(page.getByText('Clock zone:',{exact:false})).toContainText('America/New_York');await page.getByLabel('Correction reason').fill('Synthetic conflict');f.fail();await page.getByRole('button',{name:'Save correction'}).click();await expect(page.getByRole('alert')).toBeFocused();expect(f.writes).toHaveLength(2);f.fail(false);await page.getByRole('button',{name:'Reload current entries'}).click();await expect(page.getByRole('heading',{name:'Current entry'})).toBeVisible();expect(f.writes).toHaveLength(2);});

for(const theme of ['light','dark'])for(const width of [1280,390])test(`reporting controls ${theme} ${width} layout`,async({page},info)=>{await page.setViewportSize({width,height:width===390?844:900});await page.emulateMedia({colorScheme:theme as 'light'|'dark',reducedMotion:'reduce'});await setup(page,theme);await page.goto('/hours');await page.getByRole('button',{name:'Reporting windows',exact:true}).click();await expect(page.getByLabel('Reporting days')).toBeEnabled();await page.getByLabel('Past event',{exact:true}).selectOption('event');await page.getByRole('button',{name:'Open reporting window'}).click();await expect(page.getByRole('heading',{name:'Last confirmed window'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath(`windows-${theme}-${width}.png`),fullPage:true});});


test('recorded offsets survive different browser zone rules for history and void',async({page})=>{const f=await setup(page);const saved={...initial,timeZone:'America/New_York',startLocal:'10:00',endLocal:'11:00',startOccurrence:null,endOccurrence:null,startMs:Date.parse('2025-11-02T14:00Z'),endMs:Date.parse('2025-11-02T15:00Z'),startOffsetSeconds:-14400,endOffsetSeconds:-14400};f.records([saved]);await entries(page);await page.getByRole('button',{name:'Review entry 1'}).click();await expect(page.getByText(/Counted.*60 minutes/)).toBeVisible();await page.getByRole('button',{name:'View history'}).click();await expect(page.getByRole('heading',{name:'Immutable history'})).toBeVisible();await page.getByRole('button',{name:'Correct entry',exact:true}).click();await expect(page.getByText('Current browser time-zone rules differ',{exact:false})).toBeVisible();await page.getByLabel('Correction reason').fill('Synthetic review');await expect(page.getByRole('button',{name:'Save correction'})).toBeDisabled();await page.getByRole('button',{name:'Close entry form'}).click();await page.getByRole('button',{name:'Review entry 1'}).click();await page.getByRole('button',{name:'Void entry',exact:true}).click();await page.getByLabel('Void reason').fill('Synthetic void');await page.getByRole('button',{name:'Confirm void'}).click();expect(f.writes[0].body).toEqual({revision:0,reason:'Synthetic void'});await expect(page.getByText('Void is terminal.',{exact:false})).toBeVisible();});


test('existing activity date is fenced in drafts and validated in every receipt',async({page})=>{const f=await setup(page);await entries(page);await createForm(page);f.activityDate('2025-11-03');await page.getByRole('button',{name:'Record completed hours'}).click();await expect(page.getByRole('alert')).toBeVisible();expect(f.writes[0].body.serviceDate).toBe('2025-11-02');await page.getByRole('button',{name:'Discard draft and review entries'}).click();await page.getByRole('button',{name:'Reload current entries'}).click();await createForm(page);await expect(page.getByLabel('Service date',{exact:true})).toHaveValue('2025-11-03');f.wrongReceiptDate();await page.getByRole('button',{name:'Record completed hours'}).click();await expect(page.getByRole('alert')).toBeVisible();await expect(page.getByLabel('Task notes')).toBeDisabled();});
