import { expect, test, type Page } from '@playwright/test';
import { publicationDetail } from '../apps/dashboard/src/hour-publication-contract';
const activity = {id:'event',revision:4,archived:false,categoryId:'category',mode:'event',teamId:null,serviceDate:'2027-11-07',title:'Synthetic event',description:'PRIVATE synthetic notes',location:'PRIVATE synthetic location',planningTimeZone:'America/New_York',startsAt:null,endsAt:null,impactRelevant:false,responsibleStaffIds:['private-staff'],partnerTeamIds:[],sourceMeetingId:null};
const target = (provider:string) => ({ready:true,key:(provider==='google'?'a':'b').repeat(64),destination:provider==='google'?'synthetic-calendar@example.invalid':'111111111111111111',applicationId:provider==='google'?'':'222222222222222222'});
const intent = (provider:string) => ({provider,enabled:false,revision:0,generation:0,needsReview:false,reviewedActivityRevision:null,snapshot:null,target:target(provider),operations:[]});
const operation = (changes={}) => ({generation:1,destination:target('google').destination,applicationId:'',eventId:'llh'+'a'.repeat(32),abandoned:false,action:'upsert',revision:2,status:'complete',phase:'known',error:null,attempts:1,...changes});
async function setup(page:Page,theme='light',brand=false) {
  await page.clock.setFixedTime(new Date('2026-09-10T12:00:00Z'));
  let detail:any={activityId:'event',activityRevision:4,archived:false,providers:[intent('google'),intent('discord')]},record:any={...activity},failure=false,malformed=false,deny=false;
  let accessWait:Promise<void>|undefined; const writes:{path:string;method:string;body:any}[]=[];
  await page.addInitScript(v=>localStorage.setItem('lancerlogin-theme',v),theme);
  await page.route('**/setup/status',r=>r.fulfill({json:{configured:true,installation:{authMode:'local'},settings:{organizationName:'Synthetic Hours',primaryColor:brand?'#6a367f':'#0057b8',secondaryColor:brand?'#b96b13':'#eebf00',appearance:theme}}}));
  await page.route('**/auth/session',r=>r.fulfill({json:{user:{id:'staff',role:'staff'}}}));
  await page.route('**/admin/setup/progress',r=>r.fulfill({json:{completedSteps:[]}}));
  await page.route('**/platform/modules',async r=>{if(accessWait)await accessWait;await r.fulfill({json:{revision:0,capabilities:deny?[]:['hours.manage'],modules:[{id:'hour-tracking',enabled:!deny,capabilities:['hours.manage'],navigation:{path:'/hours',label:'Hour Tracking'}}]}});});
  await page.route('**/admin/hours/**',async r=>{
    const request=r.request(),path=new URL(request.url()).pathname;
    if(path.endsWith('/attendance-sources'))return r.fulfill({json:{items:[],nextCursor:null,timeZone:'America/New_York'}});
    if(!path.includes('/publications'))return r.fulfill({json:path.endsWith('/event')?record:{items:[record],nextCursor:null}});
    if(request.method()==='GET')return r.fulfill({json:malformed?{}:detail});
    const body=request.postDataJSON();writes.push({path,method:request.method(),body});
    if(failure)return r.fulfill({status:409,json:{error:'Synthetic conflict'}});
    const p=detail.providers.find((v:any)=>path.includes('/'+v.provider));
    if(path.endsWith('/retry')){const o=p.operations.find((v:any)=>v.generation===body.generation&&v.action===body.action);o.revision++;o.status='pending';}
    else {p.enabled=body.enabled;p.revision++;p.reviewedActivityRevision=detail.activityRevision;p.needsReview=false;if(body.enabled){p.generation ||=1;p.snapshot={...body.snapshot,serviceDate:record.serviceDate,timeZone:record.planningTimeZone};p.operations=[operation({destination:p.target.destination,applicationId:p.target.applicationId,eventId:null,status:'pending',phase:'ready'})];}else{p.operations=[...p.operations.map((v:any)=>({...v,abandoned:true})),operation({action:'delete',status:'pending',abandoned:true})];}}
    return r.fulfill({json:malformed?{}:detail});
  });
  return {writes,get detail(){return detail;},set detail(v:any){detail=v;},get record(){return record;},set record(v:any){record=v;},fail:(v=true)=>failure=v,malformed:(v=true)=>malformed=v,deny:()=>deny=true,holdAccess:()=>{let release!:()=>void;accessWait=new Promise<void>(resolve=>release=resolve);return ()=>{accessWait=undefined;release();};}};
}
async function open(page:Page){await page.goto('/hours');await page.getByRole('button',{name:'Publication for Synthetic event'}).click();await expect(page.getByRole('heading',{name:'Event publication',exact:true})).toBeFocused();await expect(page.getByLabel('Publish to Google Calendar',{exact:true})).toBeEnabled();}
async function google(page:Page){await page.getByLabel('Publish to Google Calendar',{exact:true}).check();await page.getByLabel('Public Google Calendar title',{exact:true}).fill('Public synthetic event');await page.getByLabel('I reviewed this public content and the current Google Calendar destination').check();}
test('saved events open independent off-default publication, blank public fields and fenced all-day save',async({page})=>{
 const f=await setup(page);await open(page);expect(f.writes).toHaveLength(0);await expect(page.getByLabel('Publish to Discord',{exact:true})).not.toBeChecked();await page.getByLabel('Publish to Google Calendar',{exact:true}).check();
 for(const field of ['title','description','location'])await expect(page.getByLabel(`Public Google Calendar ${field}`,{exact:true})).toHaveValue('');
 await expect(page.getByRole('button',{name:'Save Google Calendar publication'})).toBeDisabled();await page.getByLabel('Public Google Calendar title',{exact:true}).fill('Public synthetic event');await page.getByLabel('I reviewed this public content and the current Google Calendar destination').check();await page.getByLabel('Public Google Calendar description',{exact:true}).fill('Explicit public description');await expect(page.getByLabel('I reviewed this public content and the current Google Calendar destination')).not.toBeChecked();await page.getByLabel('I reviewed this public content and the current Google Calendar destination').check();await page.getByRole('button',{name:'Save Google Calendar publication'}).click();await expect(page.getByRole('status').filter({hasText:'Publication request saved'})).toBeFocused();
 expect(f.writes).toEqual([{path:'/admin/hours/activities/event/publications/google',method:'PUT',body:{revision:0,activityRevision:4,enabled:true,targetKey:'a'.repeat(64),snapshot:{title:'Public synthetic event',description:'Explicit public description',location:'',startsAt:null,endsAt:null}}}]);await expect(page.getByLabel('Publish to Discord',{exact:true})).not.toBeChecked();expect(JSON.stringify(f.writes)).not.toContain('PRIVATE');await expect(page.getByRole('heading',{name:'Generation 1 · Publish event · pending'})).toBeVisible();
 await page.getByLabel('Publish to Google Calendar',{exact:true}).uncheck();await page.getByRole('button',{name:'Turn off Google Calendar publication'}).click();await expect(page.getByRole('heading',{name:'Generation 1 · Delete owned event · pending'})).toBeVisible();expect(f.writes[1].body).toEqual({revision:1,activityRevision:4,enabled:false});
 await page.getByRole('button',{name:'Close publication'}).click();await expect(page.getByRole('button',{name:'Publication for Synthetic event'})).toBeFocused();
});
test('Discord requires explicit future civil times, location and independent fold choices',async({page})=>{
 const f=await setup(page);await open(page);await page.getByLabel('Publish to Discord',{exact:true}).check();await page.getByLabel('Public Discord title',{exact:true}).fill('Public Discord event');await page.getByLabel('Discord start time',{exact:true}).fill('01:30');await page.getByLabel('Discord end time',{exact:true}).fill('01:30');await expect(page.getByRole('button',{name:'Save Discord publication'})).toBeDisabled();await page.getByLabel('Discord start time occurrence').selectOption('earlier');await page.getByLabel('Discord end time occurrence').selectOption('later');await page.getByLabel('I reviewed this public content and the current Discord destination').check();await expect(page.getByRole('button',{name:'Save Discord publication'})).toBeDisabled();await page.getByLabel('Public Discord location',{exact:true}).fill('Public hall');await page.getByLabel('I reviewed this public content and the current Discord destination').check();await page.getByRole('button',{name:'Save Discord publication'}).click();await expect(page.getByRole('status').filter({hasText:'Publication request saved'})).toBeVisible();expect(f.writes[0].body).toEqual({revision:0,activityRevision:4,enabled:true,targetKey:'b'.repeat(64),snapshot:{title:'Public Discord event',description:'',location:'Public hall',startsAt:'2027-11-07T05:30:00.000Z',endsAt:'2027-11-07T06:30:00.000Z'}});
});
test('uncertain writes lock both providers and recover through GET without a replay',async({page})=>{
 const f=await setup(page);await open(page);await google(page);f.fail();await page.getByRole('button',{name:'Save Google Calendar publication'}).click();await expect(page.getByRole('alert').filter({hasText:'could not be confirmed'})).toBeFocused();await expect(page.getByLabel('Publish to Discord',{exact:true})).toBeDisabled();f.fail(false);await page.getByRole('button',{name:'Reload publication'}).click();await expect(page.getByLabel('Publish to Google Calendar',{exact:true})).not.toBeChecked();expect(f.writes).toHaveLength(1);
 f.malformed();await page.getByRole('button',{name:'Reload publication'}).click();await expect(page.getByLabel('Publish to Google Calendar',{exact:true})).toBeDisabled();expect(f.writes).toHaveLength(1);
});
test('old destinations and uncertain creation retain ownership history without retarget or blind retry',async({page})=>{
 const f=await setup(page);Object.assign(f.detail.providers[0],{generation:3,operations:[operation({status:'review',destination:'old-calendar@example.invalid',abandoned:true,action:'delete'}),operation({generation:2,status:'review',phase:'create_dispatched',eventId:null}),operation({generation:3,status:'failed',action:'delete',abandoned:true})]});await open(page);await expect(page.getByText('Original destination: old-calendar@example.invalid',{exact:false})).toBeVisible();await expect(page.getByText('Creation is uncertain.',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:/Retry Google Calendar/})).toHaveCount(1);await page.getByRole('button',{name:'Retry Google Calendar cleanup generation 3'}).click();await expect(page.getByRole('status').filter({hasText:'Publication request saved'})).toBeVisible();expect(f.writes[0]).toEqual({path:'/admin/hours/activities/event/publications/google/retry',method:'POST',body:{generation:3,action:'delete',revision:2}});
});
test('access refresh fences drafts until explicit reload; revoked access removes the panel',async({page})=>{
 const f=await setup(page);await open(page);await google(page);const release=f.holdAccess();await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByRole('button',{name:'Save Google Calendar publication'})).toBeDisabled();release();await expect(page.getByRole('button',{name:'Reload publication'})).toBeEnabled();await expect(page.getByRole('button',{name:'Save Google Calendar publication'})).toBeDisabled();await page.getByRole('button',{name:'Reload publication'}).click();await expect(page.getByLabel('Publish to Google Calendar',{exact:true})).not.toBeChecked();expect(f.writes).toHaveLength(0);f.deny();await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByRole('heading',{name:'Workspace unavailable'})).toBeVisible();
});
test('archived events allow turning off but cannot publish; unavailable targets keep cleanup visible',async({page})=>{
 const f=await setup(page);f.record={...f.record,archived:true};f.detail.archived=true;Object.assign(f.detail.providers[0],{enabled:true,generation:1,revision:2,snapshot:{title:'Reviewed public title',description:'',location:'',serviceDate:activity.serviceDate,timeZone:activity.planningTimeZone,startsAt:null,endsAt:null},target:{ready:false},operations:[operation({action:'delete',status:'review',abandoned:true})]});await open(page);await expect(page.getByRole('button',{name:'Save Google Calendar publication'})).toBeDisabled();await expect(page.getByLabel('Publish to Discord',{exact:true})).toBeDisabled();await page.getByLabel('Publish to Google Calendar',{exact:true}).uncheck();await page.getByRole('button',{name:'Turn off Google Calendar publication'}).click();expect(f.writes[0].body).toEqual({revision:2,activityRevision:4,enabled:false});
});
test('publication contract rejects malformed, duplicate, oversized and cross-activity authority',()=>{
 const valid=()=>({activityId:'event',activityRevision:4,archived:false,providers:[intent('google'),intent('discord')]} as any);
 expect(publicationDetail(valid(),'event').providers).toHaveLength(2);
 const changes:((v:any)=>void)[]=[v=>v.activityId='other',v=>v.activityRevision=-1,v=>v.archived=0,v=>v.providers.pop(),v=>v.providers[1]=v.providers[0],v=>v.providers[0].target.key='wrong',v=>v.providers[1].target.applicationId='',v=>v.providers[0].enabled=true,v=>v.providers[0].generation=21,v=>v.providers[0].snapshot=[],v=>v.providers[0].snapshot={title:'bad'},v=>v.providers[0].operations=[operation()],v=>{v.providers[0].generation=1;v.providers[0].operations=[operation(),operation()];},v=>{v.providers[0].generation=1;v.providers[0].operations=[operation({status:'delivered'})];},v=>v.providers[0].target.destination='x'.repeat(1025)];
 for(const change of changes){const value=valid();change(value);expect(()=>publicationDetail(value,'event')).toThrow('Invalid publication response');}
 const value=valid();value.providers[0].snapshot={};expect(publicationDetail(value,'event').providers[0].snapshot).toBeNull();
});
test('a changed activity clears prior public timing and prevents a stale draft from publishing',async({page})=>{
 const f=await setup(page);Object.assign(f.detail.providers[1],{enabled:true,generation:1,revision:3,needsReview:true,snapshot:{title:'Prior reviewed public title',description:'',location:'Public hall',serviceDate:'2027-11-06',timeZone:activity.planningTimeZone,startsAt:'2027-11-06T14:00:00Z',endsAt:'2027-11-06T15:00:00Z'}});await open(page);await expect(page.getByLabel('Discord start time',{exact:true})).toHaveValue('');await expect(page.getByLabel('Public Discord title',{exact:true})).toHaveValue('Prior reviewed public title');await expect(page.getByText('Review required: the activity, access or provider connection changed.',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'Save Discord publication'})).toBeDisabled();
 f.record={...f.record,revision:5};await page.getByRole('button',{name:'Reload publication'}).click();await expect(page.getByRole('alert').filter({hasText:'could not be confirmed'})).toBeVisible();await expect(page.getByLabel('Publish to Google Calendar',{exact:true})).toBeDisabled();expect(f.writes).toHaveLength(0);
});
test('nonexistent civil times and past Discord starts never queue publication',async({page})=>{
 const f=await setup(page);f.record={...f.record,serviceDate:'2027-03-14'};await open(page);await page.getByLabel('Publish to Discord',{exact:true}).check();await page.getByLabel('Public Discord title',{exact:true}).fill('Public event');await page.getByLabel('Public Discord location',{exact:true}).fill('Public hall');await page.getByLabel('Discord start time',{exact:true}).fill('02:30');await page.getByLabel('Discord end time',{exact:true}).fill('04:00');await expect(page.getByText('This local time does not exist',{exact:false})).toBeVisible();await expect(page.getByRole('group',{name:'Discord publication times'})).toHaveAccessibleDescription(/Choose valid ordered times/);await page.getByLabel('I reviewed this public content and the current Discord destination').check();await expect(page.getByRole('button',{name:'Save Discord publication'})).toBeDisabled();await page.getByLabel('Discord start time',{exact:true}).fill('03:30');await page.clock.setFixedTime(new Date('2028-01-01T00:00:00Z'));await page.getByLabel('I reviewed this public content and the current Discord destination').check();await expect(page.getByRole('button',{name:'Save Discord publication'})).toBeDisabled();expect(f.writes).toHaveLength(0);
});
for(const [width,height,theme,brand] of [[1280,900,'light',false],[1280,900,'dark',true],[390,844,'light',true],[390,844,'dark',false]] as const)test(`publication native controls and layout ${width} ${theme} brand=${brand}`,async({page},info)=>{
 await page.setViewportSize({width,height});await page.emulateMedia({reducedMotion:'reduce'});const f=await setup(page,theme,brand);f.detail.providers[0].target.destination='synthetic-'+ 'calendar'.repeat(35)+'@example.invalid';await open(page);await google(page);await page.getByRole('button',{name:'Save Google Calendar publication'}).focus();await page.keyboard.press('Tab');await expect(page.getByLabel('Publish to Discord',{exact:true})).toBeFocused();expect(await page.getByLabel('Publish to Discord',{exact:true}).evaluate(el=>getComputedStyle(el).outlineStyle)).not.toBe('none');await page.keyboard.press('Space');await expect(page.getByLabel('Publish to Discord',{exact:true})).toBeChecked();
 expect(await page.evaluate(()=>Array.from(document.querySelectorAll('[aria-label="Event publication"] *')).filter(e=>e.getBoundingClientRect().right>innerWidth).map(e=>({tag:e.tagName,cls:e.className,width:e.getBoundingClientRect().width})).slice(0,12))).toEqual([]);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 for(const box of await page.locator('[aria-label="Event publication"] button:visible,[aria-label="Event publication"] input:not([type=checkbox]):visible,[aria-label="Event publication"] .hours-check:visible').evaluateAll(els=>els.map(e=>({width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height})))){expect(box.width).toBeGreaterThanOrEqual(44);expect(box.height).toBeGreaterThanOrEqual(44);}
 await page.screenshot({path:info.outputPath(`publication-${width}-${theme}.png`),fullPage:true});expect(f.writes).toHaveLength(0);
});
