import { expect, test, type Page } from '@playwright/test';
import { selectCivilTime, addCalendarDays } from '../packages/shared/src/civil-time';
import { dashboardConformanceReferences as reference } from '../apps/dashboard/src/design-conformance';
const activity={id:'event',revision:0,archived:false,categoryId:'event-category',mode:'event',teamId:null,serviceDate:'2025-11-02',title:'Synthetic service day',description:'',location:'',planningTimeZone:'America/New_York',startsAt:null,endsAt:null,impactRelevant:false};
const category={id:'event-category',revision:0,archived:false,name:'Event',mode:'event',impactDefault:false};
const team={id:'team',revision:0,archived:false,name:'Synthetic team',number:'00123',organization:'',program:'',historicalDescriptors:''};
const initial={id:'entry',memberId:'member',activityId:'event',serviceDate:'2025-11-02',timeZone:'America/New_York',startLocal:'01:30',endLocal:'01:30',endNextDay:false,startOccurrence:'earlier',endOccurrence:'later',startMs:Date.parse('2025-11-02T05:30Z'),endMs:Date.parse('2025-11-02T06:30Z'),startOffsetSeconds:-14400,endOffsetSeconds:-18000,durationMinutes:60,taskNotes:'Synthetic note',status:'counted',channel:'staff',attribution:'staff_recorded',revision:0,createdAt:'2025-11-03T12:00:00Z',updatedAt:'2025-11-03T12:00:00Z'};
const original={id:'request',channel:'public',attribution:'self_asserted',requesterMemberId:'member',claimedMemberId:'00017',claimedReceiptId:'<img src=x onerror=alert(1)>',claimedActivityId:'claimed-event',claimedServiceDate:'2025-11-02',message:'Synthetic request <script>not executable</script>',status:'open',revision:0,createdAt:'2026-09-08T12:00:00Z',resolvedAt:null};
async function setup(page:Page,theme='light',role='staff'){
 let requests:any[]=[{...original}],records:any[]=[{...initial}],deny=false,malformed=false,fail=false,drop=false,badDetail=false,wrongResolution=false;const writes:any[]=[],reads:string[]=[];
 await page.clock.setFixedTime(new Date('2026-09-09T16:00:00Z'));
 await page.addInitScript(value=>localStorage.setItem('lancerlogin-theme',value),theme);
 await page.route('**/setup/status',r=>r.fulfill({json:{configured:true,installation:{authMode:'local'},settings:{organizationName:'Synthetic Hours',primaryColor:reference.brand.primary,secondaryColor:reference.brand.secondary,appearance:theme}}}));
 await page.route('**/auth/session',r=>r.fulfill({json:{user:{id:'staff',role}}}));
 await page.route('**/admin/setup/progress',r=>r.fulfill({json:{completedSteps:['branding','roster','pair-kiosk','fingerprint-test','confirm-attendance'].map(step=>({step}))}}));
 await page.route('**/platform/modules',r=>r.fulfill({json:{capabilities:deny?[]:['hours.manage'],modules:[{id:'hour-tracking',enabled:!deny,capabilities:['hours.manage'],navigation:{path:'/hours',label:'Hour Tracking'}}]}}));
 await page.route('**/admin/hours/**',async r=>{
  const req=r.request(),url=new URL(req.url()),[kind,id]=url.pathname.split('/admin/hours/')[1].split('/');const get=req.method()==='GET';reads.push(url.pathname+url.search);const body=get?undefined:req.postDataJSON();if(body)writes.push(body);if(deny)return r.fulfill({status:403,json:{error:'Denied'}});if(malformed)return r.fulfill({json:{}});if(!get&&fail)return r.fulfill({status:409,json:{error:'Synthetic conflict'}});
  const pageOf=(rows:any[])=>{const found=rows.filter(v=>!url.searchParams.get('after')||v.id>url.searchParams.get('after')!);const limit=Number(url.searchParams.get('limit')??50);return {items:found.slice(0,limit),nextCursor:found.length>limit?found[limit-1].id:null};};
  if(kind==='attendance-sources')return r.fulfill({json:{items:[],nextCursor:null,timeZone:'America/New_York'}});
  if(kind==='entry-settings')return r.fulfill({json:{revision:0,reportingDays:7,reopenHours:24,timeZone:'America/New_York',today:'2026-09-09'}});
  if(kind==='member-choices'){const m={id:'member',label:'Synthetic member',externalId:'00017',active:false};return r.fulfill({json:id?m:pageOf([m])});}
  if(['activities','categories','teams'].includes(kind)){const values=kind==='activities'?[activity]:kind==='teams'?[team]:[category];return r.fulfill({json:id?values.find(v=>v.id===id):pageOf(values)});}
  if(kind==='entries')return r.fulfill({json:id?(badDetail?{}:records.find(v=>v.id===id)):pageOf(records)});
  if(kind==='correction-requests'){
   if(get){if(id){const value=requests.find(v=>v.id===id);return r.fulfill({json:badDetail?{}:{...value,resolution:value.resolution??null}});}const status=url.searchParams.get('status');return r.fulfill({json:pageOf(requests.filter(v=>status==='all'||v.status===status))});}
   const old=requests.find(v=>v.id===id);if(!old||old.status==='resolved'||body.revision!==old.revision)return r.fulfill({status:409,json:{error:'Terminal'}});const matched=records.find(v=>v.id===body.entryId);if(matched&&body.entryRevision!==matched.revision)return r.fulfill({status:409,json:{error:'Entry changed'}});
   let changed:any;if(['corrected','voided'].includes(body.action)){
    changed={...matched,...body.correction,revision:matched.revision+1,status:body.action==='voided'?'void':'counted'};if(body.correction){if(body.correction.activityId&&body.correction.serviceDate!==activity.serviceDate)return r.fulfill({status:400,json:{error:'Date changed'}});const start=selectCivilTime({date:changed.serviceDate,time:changed.startLocal,timeZone:changed.timeZone},changed.startOccurrence??undefined),end=selectCivilTime({date:addCalendarDays(changed.serviceDate,Number(changed.endNextDay)),time:changed.endLocal,timeZone:changed.timeZone},changed.endOccurrence??undefined);Object.assign(changed,{startMs:start.epochMilliseconds,endMs:end.epochMilliseconds,startOffsetSeconds:start.offsetSeconds,endOffsetSeconds:end.offsetSeconds,durationMinutes:(end.epochMilliseconds-start.epochMilliseconds)/60000});}records=[changed];
   }
   Object.assign(old,{status:'resolved',revision:1,resolvedAt:'2026-09-09T16:00:00Z',resolution:{requestId:id,action:wrongResolution?'dismissed':body.action,note:body.note,actorUserId:'staff',entryId:body.entryId??null,entryRevision:changed?.revision??body.entryRevision??null,createdAt:'2026-09-09T16:00:00Z'}});if(drop){drop=false;return r.abort();}return r.fulfill({json:{id,revision:1,status:'resolved',...(changed?{entry:{id:changed.id,revision:changed.revision,status:changed.status}}:{})}});
  }
  if(kind==='reports'){const groupBy=url.searchParams.get('groupBy'),after=url.searchParams.get('after');return r.fulfill({json:{from:url.searchParams.get('from'),to:url.searchParams.get('to'),groupBy,teamAttribution:'primary',totals:{minutes:125,entryCount:3,distinctParticipants:1},items:[{id:groupBy==='team'?(after?'team':null):groupBy==='member'?'member':groupBy==='category'?'event-category':'event',minutes:after?65:60,entryCount:after?2:1,distinctParticipants:1}],nextCursor:after?null:groupBy==='team'?'0':'1'+(groupBy==='member'?'member':groupBy==='category'?'event-category':'event')}});}
  return r.fulfill({status:404,json:{error:'Missing fixture'}});
 });
 return {writes,reads,deny:()=>deny=true,malformed:(v=true)=>malformed=v,fail:(v=true)=>fail=v,drop:()=>drop=true,badDetail:(v=true)=>badDetail=v,wrongResolution:()=>wrongResolution=true,requests:(v:any[])=>requests=v,records:(v:any[])=>records=v};
}
async function inbox(page:Page){await page.goto('/hours');await page.getByRole('button',{name:'Corrections',exact:true}).click();await expect(page.getByRole('button',{name:'Review request 1',exact:true})).toBeEnabled();}
async function review(page:Page){await inbox(page);await page.getByRole('button',{name:'Review request 1',exact:true}).click();await expect(page.getByRole('heading',{name:'Review correction request'})).toBeFocused();}
async function match(page:Page){await page.getByRole('button',{name:'Find entries',exact:true}).click();await page.getByRole('button',{name:'Review matching entry 1',exact:true}).click();await expect(page.getByRole('heading',{name:'Selected current entry'})).toBeVisible();}
async function report(page:Page){await page.goto('/hours');await page.getByRole('button',{name:'Reports',exact:true}).click();await page.getByLabel('Report from service date').fill('2025-01-01');await page.getByLabel('Report through service date').fill('2025-12-31');await page.getByRole('button',{name:'Run report',exact:true}).click();await expect(page.getByRole('heading',{name:'Whole period totals'})).toBeFocused();}
test('unverified claims are text; explicit acknowledgement is terminal and read back',async({page})=>{const f=await setup(page);await review(page);await expect(page.getByText('Self-asserted, unverified identity',{exact:true})).toBeVisible();await expect(page.getByText(original.claimedReceiptId,{exact:true})).toBeVisible();await expect(page.locator('.hours-workspace img,.hours-workspace script')).toHaveCount(0);await page.getByLabel('Review note').fill('Synthetic reviewed claim');await page.getByRole('button',{name:'Confirm resolution'}).click();await expect(page.getByRole('status')).toContainText('Resolution saved and confirmed');await expect(page.getByRole('status')).toBeFocused();expect(f.writes).toEqual([{revision:0,action:'acknowledged',note:'Synthetic reviewed claim'}]);await expect(page.getByLabel('Review note')).toHaveCount(0);await expect(page.getByRole('heading',{name:'Saved resolution'})).toBeVisible();});
test('correct and resolve use one atomic request with saved zone, date and independent folds',async({page})=>{const f=await setup(page);await review(page);await match(page);await page.getByRole('button',{name:'Correct selected entry and resolve'}).click();await expect(page.getByRole('heading',{name:'Correct entry'})).toBeFocused();await expect(page.getByLabel('Start time occurrence')).toHaveValue('earlier');await expect(page.getByLabel('End time occurrence')).toHaveValue('later');await page.getByLabel('Correction reason').fill('Synthetic clock correction');await page.getByLabel('End time',{exact:true}).fill('02:00');await page.getByRole('button',{name:'Save correction',exact:true}).click();await expect(page.getByRole('heading',{name:'Saved resolution'})).toBeVisible();expect(f.writes).toHaveLength(1);expect(f.writes[0]).toMatchObject({revision:0,action:'corrected',entryId:'entry',entryRevision:0,note:'Synthetic clock correction',correction:{serviceDate:'2025-11-02',activityId:'event',startOccurrence:'earlier'}});expect(f.writes[0].correction).not.toHaveProperty('revision');expect(f.writes[0].correction).not.toHaveProperty('expectedTimeZone');await expect(page.getByText('Counted · 90 minutes (1.50 hours)',{exact:true})).toBeVisible();});
test('void preserves historical offset timing and reads current changed entry',async({page})=>{const f=await setup(page);f.records([{...initial,startLocal:'10:00',endLocal:'11:00',startOccurrence:null,endOccurrence:null,startMs:Date.parse('2025-11-02T14:00Z'),endMs:Date.parse('2025-11-02T15:00Z'),startOffsetSeconds:-14400,endOffsetSeconds:-14400}]);await review(page);await match(page);await page.getByLabel('Resolution action').selectOption('voided');await page.getByLabel('Review note').fill('Synthetic duplicate');await page.getByRole('button',{name:'Confirm resolution'}).click();await expect(page.getByText('Voided · 60 minutes (1.00 hours)',{exact:true})).toBeVisible();expect(f.writes[0]).toEqual({revision:0,action:'voided',note:'Synthetic duplicate',entryId:'entry',entryRevision:0});});
test('dropped response recovers with GET only; conflicting and malformed results lock',async({page})=>{const f=await setup(page);await review(page);await page.getByLabel('Resolution action').selectOption('dismissed');await page.getByLabel('Review note').fill('Synthetic dismissal');f.drop();await page.getByRole('button',{name:'Confirm resolution'}).click();await expect(page.getByRole('alert')).toBeFocused();await expect(page.getByRole('button',{name:'Confirm resolution'})).toBeDisabled();await page.getByRole('button',{name:'Reload current request'}).click();await expect(page.getByText('Current saved resolution loaded.',{exact:false})).toBeVisible();expect(f.writes).toHaveLength(1);await expect(page.getByRole('heading',{name:'Saved resolution'})).toBeVisible();});
test('stale reviewed entry failure permits new action only after explicit current read',async({page})=>{const f=await setup(page);await review(page);await match(page);f.records([{...initial,revision:1}]);await page.getByLabel('Review note').fill('Synthetic stale review');await page.getByRole('button',{name:'Confirm resolution'}).click();await expect(page.getByRole('alert')).toBeVisible();expect(f.writes).toHaveLength(1);await page.getByRole('button',{name:'Reload current request'}).click();await expect(page.getByText('The request is still open.',{exact:false})).toBeVisible();await expect(page.getByRole('heading',{name:'Selected current entry'})).toHaveCount(0);expect(f.writes).toHaveLength(1);});
test('correction pages retain applied filters until Apply',async({page})=>{const f=await setup(page);f.requests(Array.from({length:51},(_,i)=>({...original,id:'request-'+String(i).padStart(3,'0')})));await inbox(page);await page.getByLabel('Correction status').selectOption('resolved');await page.getByRole('button',{name:'Next correction page'}).click();await expect(page.getByRole('button',{name:'Review request 1',exact:true})).toBeVisible();expect(f.reads.filter(v=>v.includes('/correction-requests?')).at(-1)).toContain('status=open');await page.getByRole('button',{name:'Apply correction filters'}).click();await expect(page.getByText('No correction requests match')).toBeVisible();});
test('report totals stay global, team null is explicit and paging retains applied period/group',async({page})=>{const f=await setup(page);await report(page);await page.getByLabel('Group report by').selectOption('team');await page.getByRole('button',{name:'Run report',exact:true}).click();await expect(page.getByRole('heading',{name:'No primary supported team'})).toBeVisible();await expect(page.getByRole('region',{name:'Whole period totals'})).toContainText('125 minutes (2.08 hours)');await page.getByLabel('Group report by').selectOption('activity');await page.getByLabel('Report from service date').fill('2024-01-01');await page.getByRole('button',{name:'Next report page'}).click();expect(f.reads.filter(v=>v.includes('/reports?')).at(-1)).toContain('from=2025-01-01');expect(f.reads.filter(v=>v.includes('/reports?')).at(-1)).toContain('groupBy=team');await expect(page.getByRole('region',{name:'Whole period totals'})).toContainText('3 counted entries · 1 distinct participants');await expect(page.getByText('65 minutes (1.08 hours)',{exact:true})).toBeVisible();});
test('period limit and malformed report fail closed without retaining totals',async({page})=>{const f=await setup(page);await report(page);await page.getByLabel('Report through service date').fill('2040-01-01');await expect(page.getByRole('button',{name:'Run report',exact:true})).toBeDisabled();f.malformed();await page.getByRole('button',{name:'Reload applied report'}).click();await expect(page.getByRole('alert')).toBeFocused();await expect(page.getByRole('region',{name:'Whole period totals'})).toHaveCount(0);f.malformed(false);await page.getByRole('button',{name:'Reload applied report'}).click();await expect(page.getByRole('region',{name:'Whole period totals'})).toBeVisible();});
test('revoked module capability removes private review data',async({page})=>{const f=await setup(page);await review(page);f.deny();await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByRole('heading',{name:'Workspace unavailable'})).toBeVisible();await expect(page.getByText(original.message,{exact:true})).toHaveCount(0);expect(f.writes).toHaveLength(0);});
test('linked identity is distinct from approval; malformed detail blocks review',async({page})=>{const f=await setup(page,'light','admin');f.requests([{...original,channel:'discord',attribution:'linked_discord',claimedMemberId:null}]);await review(page);await expect(page.getByText('Linked Discord identity',{exact:true})).toBeVisible();await expect(page.getByText('The linked account identifies the requester;', {exact:false})).toBeVisible();f.badDetail();await page.getByRole('button',{name:'Reload current request'}).click();await expect(page.getByRole('alert')).toBeVisible();await expect(page.getByLabel('Review note')).toBeDisabled();expect(f.writes).toHaveLength(0);});
test('mismatched saved resolution never claims successful confirmation',async({page})=>{const f=await setup(page);await review(page);f.wrongResolution();await page.getByLabel('Review note').fill('Synthetic acknowledgement');await page.getByRole('button',{name:'Confirm resolution'}).click();await expect(page.getByRole('alert')).toBeVisible();await expect(page.getByText('Resolution saved and confirmed',{exact:false})).toHaveCount(0);await page.getByRole('button',{name:'Reload current request'}).click();await expect(page.getByRole('heading',{name:'Saved resolution'})).toBeVisible();expect(f.writes).toHaveLength(1);});
test('matching entry pages retain applied named filters',async({page})=>{const f=await setup(page);f.records(Array.from({length:21},(_,i)=>({...initial,id:'entry-'+String(i).padStart(3,'0')})));await review(page);await page.getByLabel('Match member',{exact:true}).selectOption('member');await page.getByRole('button',{name:'Find entries',exact:true}).click();await page.getByLabel('Match member',{exact:true}).selectOption('');await page.getByRole('button',{name:'Next matching entries page'}).click();await expect(page.getByRole('button',{name:'Review matching entry 1',exact:true})).toBeVisible();expect(f.reads.filter(v=>v.includes('/entries?')).at(-1)).toContain('memberId=member');});
test('resolved request explains current linked entry when later revisions exist',async({page})=>{const f=await setup(page);f.requests([{...original,status:'resolved',revision:1,resolvedAt:'2026-09-09T16:00:00Z',resolution:{requestId:'request',action:'acknowledged',note:'Synthetic review',actorUserId:'staff',entryId:'entry',entryRevision:0,createdAt:'2026-09-09T16:00:00Z'}}]);f.records([{...initial,revision:2}]);await page.goto('/hours');await page.getByRole('button',{name:'Corrections',exact:true}).click();await page.getByLabel('Correction status').selectOption('resolved');await page.getByRole('button',{name:'Apply correction filters'}).click();await page.getByRole('button',{name:'Review request 1',exact:true}).click();await expect(page.getByText('The entry has changed since this resolution.',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'Confirm resolution'})).toHaveCount(0);});
test('all report groupings and named filters retain their applied context',async({page})=>{const f=await setup(page);await report(page);await page.getByText('Filter report records',{exact:true}).click();await page.getByLabel('Report category filter',{exact:true}).selectOption('event-category');for(const group of ['activity','category','team']){await page.getByLabel('Group report by').selectOption(group);await page.getByRole('button',{name:'Run report',exact:true}).click();await expect(page.getByRole('region',{name:'Whole period totals'})).toContainText('Category: Event');expect(f.reads.filter(v=>v.includes('/reports?')).at(-1)).toContain('categoryId=event-category');}await page.getByLabel('Report category filter',{exact:true}).selectOption('');await page.getByRole('button',{name:'Next report page'}).click();await expect(page.getByRole('region',{name:'Whole period totals'})).toContainText('Category: Event');expect(f.reads.filter(v=>v.includes('/reports?')).at(-1)).toContain('categoryId=event-category');});
for(const theme of ['light','dark'])for(const width of [1280,390])test(`review and report ${theme} ${width} keyboard and brand`,async({page},info)=>{await page.setViewportSize({width,height:width===390?844:900});await page.emulateMedia({colorScheme:theme as 'light'|'dark',reducedMotion:'reduce'});await setup(page,theme);await review(page);await page.keyboard.press('Tab');await expect(page.getByRole('button',{name:'Reload current request'})).toBeFocused();expect(await page.getByRole('heading',{level:1}).count()).toBe(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath(`review-${theme}-${width}.png`),fullPage:true});await page.getByRole('button',{name:'Back to correction inbox'}).click();await report(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);for(const button of await page.locator('.hours-workspace button').all())if(await button.isVisible())expect((await button.boundingBox())!.height).toBeGreaterThanOrEqual(44);await page.screenshot({path:info.outputPath(`report-${theme}-${width}.png`),fullPage:true});});
