import {expect,test,type Page} from '@playwright/test';
import {dashboardConformanceReferences as reference} from '../apps/dashboard/src/design-conformance';
async function notesSetup(page:Page,role='staff',theme='light') {
 let granted=true,enabled=true,fail=0;const writes:any[]=[];const requests:string[]=[];
 const sections={version:1,revision:0,notesEnabled:true,summaryEnabled:true,filesEnabled:true};
 const activity={id:'activity',title:'Synthetic service',serviceDate:'2026-09-10',revision:2,archived:false,impactRelevant:true};
 const notes:any[]=[{id:'note',activityId:'activity',text:'<script>private note</script>',revision:0,archived:false,authorUserId:'synthetic-author',createdAt:'2026-09-10T12:00:00Z',updatedAt:'2026-09-10T12:00:00Z'}];
 await page.addInitScript(value=>localStorage.setItem('lancerlogin-theme',value),theme);
 await page.route('**/setup/status',r=>r.fulfill({json:{configured:true,installation:{authMode:'local'},settings:{organizationName:'Synthetic Documentation',primaryColor:reference.brand.primary,secondaryColor:reference.brand.secondary,appearance:theme}}}));
 await page.route('**/auth/session',r=>r.fulfill({json:{user:{id:'synthetic',role}}}));
 await page.route('**/admin/setup/progress',r=>r.fulfill({json:{completedSteps:['branding','roster','pair-kiosk','fingerprint-test','confirm-attendance'].map(step=>({step}))}}));
 await page.route('**/platform/modules',r=>r.fulfill({json:{capabilities:granted&&enabled?['documentation.manage']:[],modules:[{id:'hour-tracking',enabled,capabilities:['hours.manage'],navigation:{path:'/hours',label:'Hour Tracking'}},{id:'activity-documentation',enabled,capabilities:['documentation.manage'],navigation:{path:'/documentation',label:'Activity Documentation'}}]}}));
 await page.route('**/admin/documentation/**',async r=>{const req=r.request(),url=new URL(req.url()),path=url.pathname.replace('/admin/documentation','');requests.push(url.pathname+url.search);
 if(req.method()!=='GET'){const body=req.postDataJSON();writes.push(body);if(fail){await r.fulfill({status:fail,json:{error:'Synthetic conflict'}});return;}if(path==='/sections'){Object.assign(sections,body,{revision:sections.revision+1});await r.fulfill({json:sections});return;}let n=path.startsWith('/notes/')?notes.find(n=>n.id===path.split('/')[2]):undefined;if(n)Object.assign(n,body,{revision:n.revision+1});else{n={...notes[0],...body,id:'created',revision:0};notes.push(n);}await r.fulfill({json:{note:n}});return;}
 if(!granted||!enabled){await r.fulfill({status:403,json:{error:'Unavailable'}});return;}
 if(path==='/sections'){await r.fulfill({json:sections});return;}
 if(path==='/activities'){await r.fulfill({json:{activities:[activity],next:url.searchParams.has('after')?null:'next-activity'}});return;}
 if(path==='/activities/activity'){await r.fulfill({json:{...activity,readOnly:activity.archived||!activity.impactRelevant,sectionRevision:sections.revision,...(sections.summaryEnabled?{summary:{countedMinutes:0,distinctParticipants:0}}:{})}});return;}
 if(path==='/activities/activity/notes'){await r.fulfill({json:{notes,next:url.searchParams.has('after')?null:'next-note',readOnly:activity.archived||!activity.impactRelevant||!sections.notesEnabled,activityRevision:activity.revision,sectionRevision:sections.revision}});return;}
 if(path.endsWith('/history')){await r.fulfill({json:{revisions:[{revision:url.searchParams.has('after')?1:0,text:'<b>Original text</b>',archived:false,createdAt:'2026-09-10'}],next:url.searchParams.has('after')?null:0}});return;}
 await r.fulfill({json:{note:notes.find(n=>n.id===path.split('/')[2])}});
 });
 return {sections,activity,notes,writes,requests,revoke:()=>granted=false,disable:()=>enabled=false,fail:(status:number)=>fail=status};
}
async function setup(page:Page,role='staff',theme='light'){
 const docs=await notesSetup(page,role,theme);let fail=0;const writes:any[]=[];const reads:string[]=[];
 const activity={activityId:'activity',title:'Synthetic service',revision:2,archived:false,impactRelevant:true};
 const items:any[]=[{id:'first',title:'Synthetic initiative',narrative:'<b>Private narrative</b>',revision:0,archived:false,createdAt:'2026-09-10',updatedAt:'2026-09-10',activities:[activity]},{id:'second',title:'Shared initiative',narrative:'Second narrative',revision:0,archived:false,activities:[activity]}];
 await page.route('**/admin/documentation/initiatives**',async route=>{const req=route.request(),url=new URL(req.url()),path=url.pathname.replace('/admin/documentation/initiatives','');reads.push(path+url.search);const item=items.find(i=>i.id===path.split('/')[1]);
 const total=(selected:any[])=>{const eligible=selected.some(i=>!i.archived)&&!activity.archived&&activity.impactRelevant;return {linkedActivityCount:selected.some(i=>i.activities.length)?1:0,eligibleActivityCount:eligible&&selected.some(i=>i.activities.length)?1:0,omittedActivityCount:!eligible&&selected.some(i=>i.activities.length)?1:0,...(docs.sections.summaryEnabled?{summary:{countedMinutes:eligible&&selected.some(i=>i.activities.length)?90:0,distinctParticipants:eligible&&selected.some(i=>i.activities.length)?2:0}}:{})};};
 if(path==='/summary'){const ids=req.postDataJSON().initiativeIds;if(ids.some((value:string)=>!items.some(i=>i.id===value))){await route.fulfill({status:404,json:{error:'Unavailable'}});return;}await route.fulfill({json:total(items.filter(i=>ids.includes(i.id)))});return;}
 if(req.method()!=='GET'){const body=req.postDataJSON();writes.push(body);if(fail){await route.fulfill({status:fail,json:{error:'Conflict'}});return;}const value=item??{id:'created',revision:-1,archived:false,activities:[]};const members=body.activities?.map((a:any)=>({...activity,...a}))??value.activities;Object.assign(value,body,{activities:members,revision:value.revision+1});if(!item)items.push(value);await route.fulfill({json:{initiative:value}});return;}
 if(path.endsWith('/history')){await route.fulfill({json:{revisions:[{revision:url.searchParams.has('after')?1:0,title:'Original title',narrative:'<script>Historical narrative</script>',archived:false,createdAt:'2026-09-10',activityIds:['activity'],activities:[{activityId:'activity',title:'Current synthetic service title'}]}],next:url.searchParams.has('after')?null:0}});return;}
 if(!path){await route.fulfill({json:{initiatives:items.filter(i=>url.searchParams.get('archival')==='true'||!i.archived),next:url.searchParams.has('after')?null:'next'}});return;}
 if(!item){await route.fulfill({status:404,json:{error:'Unavailable'}});return;}
 await route.fulfill({json:{initiative:item,activities:item.activities.map((a:any)=>({...a,archived:activity.archived,impactRelevant:activity.impactRelevant})),readOnly:item.archived,...total([item])}});
 });
 return {...docs,items,activity,writes,reads,fail:(value:number)=>fail=value};
}
async function enter(page:Page){await page.goto('/documentation');await page.getByRole('button',{name:'Initiatives',exact:true}).click();}
for(const role of ['admin','staff'])test(role+' initiative CRUD, retained membership and history',async({page})=>{const f=await setup(page,role);f.sections.notesEnabled=false;await enter(page);await page.getByRole('button',{name:'Create initiative',exact:true}).click();await expect(page.getByRole('heading',{name:'New initiative'})).toBeFocused();await page.getByLabel('Initiative title', {exact:true}).fill('Empty initiative');await page.getByLabel('Shared narrative',{exact:true}).fill('Plain narrative');await page.getByRole('button',{name:'Save initiative',exact:true}).click();await expect(page.getByText('Saved and confirmed',{exact:false})).toBeVisible();expect(f.writes[0].activities).toEqual([]);await page.getByLabel('Associate Synthetic service').check();await page.getByRole('button',{name:'Save initiative',exact:true}).click();await expect.poll(()=>f.writes.length).toBe(2);expect(f.writes[1]).toMatchObject({revision:0,activities:[{activityId:'activity',revision:2}]});await page.getByRole('button',{name:'View initiative history'}).click();await expect(page.getByText('<script>Historical narrative</script>',{exact:true})).toBeVisible();await expect(page.getByText('Current synthetic service title',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Next initiative history page'}).click();await expect(page.getByRole('heading',{name:'Revision 1',exact:true})).toBeVisible();await page.getByRole('button',{name:'Archive initiative',exact:true}).click();await expect(page.getByLabel('Initiative title',{exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Unarchive initiative',exact:true}).click();await expect(page.getByLabel('Initiative title',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Remove Synthetic service'}).click();await page.getByRole('button',{name:'Save initiative',exact:true}).click();await expect.poll(()=>f.writes.at(-1).activities).toEqual([]);});
test('union summary, omitted activity, disabled summary and cursor pages',async({page})=>{const f=await setup(page);await enter(page);await page.getByLabel('Include Synthetic initiative in combined summary').check();await page.getByLabel('Include Shared initiative in combined summary').check();await page.getByRole('button',{name:'Calculate combined summary'}).click();await expect(page.getByText('90 counted minutes · 2 distinct participants')).toBeVisible();await page.getByRole('button',{name:'Next initiatives page'}).click();await expect.poll(()=>f.reads.some(p=>p.includes('after=next'))).toBe(true);f.activity.archived=true;await page.getByRole('button',{name:'Calculate combined summary'}).click();await expect(page.getByText('1 linked activities · 0 eligible · 1 omitted')).toBeVisible();f.sections.summaryEnabled=false;await page.getByRole('button',{name:'Calculate combined summary'}).click();await expect(page.getByText('Participant/hour summary is disabled.')).toBeVisible();await expect(page.getByText('counted minutes',{exact:false})).toHaveCount(0);await page.getByRole('button',{name:'Open Synthetic initiative',exact:true}).click();await expect(page.getByText('Synthetic service · Archived',{exact:true}).last()).toBeVisible();await page.getByRole('button',{name:'Next eligible activities page'}).click();await expect(page.getByRole('button',{name:'Next eligible activities page'})).toHaveCount(0);});
test('stale or uncertain write preserves draft until explicit reload and never retries',async({page})=>{const f=await setup(page);await enter(page);await page.getByRole('button',{name:'Open Synthetic initiative',exact:true}).click();await page.getByLabel('Shared narrative',{exact:true}).fill('Preserved draft');for(const status of [409,500]){f.fail(status);await page.getByRole('button',{name:'Save initiative',exact:true}).click();await expect(page.getByRole('alert')).toContainText('No write is retried');await expect(page.getByRole('button',{name:'Save initiative',exact:true})).toBeDisabled();await expect(page.getByLabel('Shared narrative',{exact:true})).toHaveValue('Preserved draft');f.fail(0);await page.getByRole('button',{name:'Reload initiatives'}).click();await expect(page.getByRole('button',{name:'Save initiative',exact:true})).toBeEnabled();}expect(f.writes).toHaveLength(2);});
test('unknown summary selections fail visibly and can be cleared',async({page})=>{const f=await setup(page);await enter(page);await page.getByLabel('Include Synthetic initiative in combined summary').check();f.items.splice(0,1);await page.getByRole('button',{name:'Calculate combined summary'}).click();await expect(page.getByRole('alert')).toContainText('summary selections');await page.getByRole('button',{name:'Clear summary selection'}).click();await page.getByRole('button',{name:'Reload initiatives'}).click();await expect(page.getByRole('button',{name:'Create initiative',exact:true})).toBeEnabled();});
for(const role of ['operator','staff'])test(role+' without Documentation grant cannot open initiatives',async({page})=>{const f=await setup(page,role);f.revoke();await page.goto('/documentation');await expect(page.getByRole('heading',{name:'Workspace unavailable'})).toBeVisible();expect(f.reads).toEqual([]);});
test('delayed read after revocation cannot restore private initiative',async({page})=>{const f=await setup(page);let release=()=>{};const gate=new Promise<void>(resolve=>release=resolve);await page.route('**/admin/documentation/initiatives/first',async r=>{await gate;await r.fallback();});await enter(page);await page.getByRole('button',{name:'Open Synthetic initiative',exact:true}).click();f.revoke();await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByRole('heading',{name:'Workspace unavailable'})).toBeVisible();release();await expect(page.getByLabel('Shared narrative',{exact:true})).toHaveCount(0);});
test('delayed write during focus refresh remains locked until explicit readback',async({page})=>{const f=await setup(page);let release=()=>{};const gate=new Promise<void>(resolve=>release=resolve);await page.route('**/admin/documentation/initiatives/first',async r=>{if(r.request().method()==='PATCH')await gate;await r.fallback();});await enter(page);await page.getByRole('button',{name:'Open Synthetic initiative',exact:true}).click();const requested=page.waitForRequest(r=>r.method()==='PATCH');await page.getByRole('button',{name:'Save initiative',exact:true}).click();await requested;await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByRole('button',{name:'Reload initiatives'})).toBeDisabled();release();await expect(page.getByRole('button',{name:'Reload initiatives'})).toBeEnabled();await expect(page.getByRole('button',{name:'Save initiative',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Reload initiatives'}).click();await expect(page.getByRole('button',{name:'Save initiative',exact:true})).toBeEnabled();expect(f.writes).toHaveLength(1);});
async function keyboardSave(page:Page){
 // Opening performs asynchronous reads and then a passive heading-focus effect.
 // The page h1 exists before both finish and is not an editor readiness signal.
 await expect(page.getByRole('heading',{name:'Edit initiative',exact:true})).toBeFocused();
 const save=page.getByRole('button',{name:'Save initiative',exact:true});
 await expect(save).toBeEnabled();
 // Exercise keyboard modality rather than programmatic focus after an unrelated Tab.
 for(let step=0;step<64;step++){
  await page.keyboard.press('Tab');
  if(await save.evaluate(element=>element===document.activeElement))break;
 }
 await expect(save).toBeFocused();
 await expect.poll(()=>save.evaluate(element=>element.matches(':focus-visible')&&getComputedStyle(element).outlineStyle!=='none')).toBe(true);
 return save;
}

test('initiative editor keyboard readiness waits for delayed detail read',async({page})=>{
 await setup(page);
 let release!:()=>void;
 const gate=new Promise<void>(resolve=>{release=resolve;});
 await page.route('**/admin/documentation/initiatives/first',async route=>{await gate;await route.fallback();});
 await enter(page);
 const requested=page.waitForRequest(request=>new URL(request.url()).pathname.endsWith('/initiatives/first'));
 await page.getByRole('button',{name:'Open Synthetic initiative',exact:true}).click();
 await requested;
 let ready=false;
 const pending=keyboardSave(page).then(()=>{ready=true;});
 try{
  await expect(page.getByRole('button',{name:'Save initiative',exact:true})).toHaveCount(0);
  expect(ready).toBe(false);
 }finally{release();}
 await pending;
 expect(ready).toBe(true);
});
for(const viewport of reference.viewports)for(const theme of reference.themes)test('initiative visual '+viewport.width+' '+theme,async({page})=>{await setup(page,'staff',theme);await page.setViewportSize(viewport);await enter(page);await page.getByRole('button',{name:'Open Synthetic initiative',exact:true}).click();await expect(page.locator('main h1')).toHaveCount(1);const save=await keyboardSave(page);expect((await save.boundingBox())!.height).toBeGreaterThanOrEqual(44);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.locator('main b')).toHaveCount(0);await page.screenshot({path:test.info().outputPath('initiatives.png'),fullPage:true});});

test('module disable removes initiative draft and title/narrative limits are UTF16',async({page})=>{const f=await setup(page);await enter(page);await page.getByRole('button',{name:'Create initiative',exact:true}).click();await page.getByLabel('Initiative title',{exact:true}).fill('x'.repeat(200));await page.getByLabel('Shared narrative',{exact:true}).fill(String.fromCodePoint(0x1f600).repeat(4000));await expect(page.getByRole('button',{name:'Save initiative',exact:true})).toBeEnabled();await expect(page.getByText('8000/8000.',{exact:false})).toBeVisible();f.disable();await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByRole('heading',{name:'Workspace unavailable'})).toBeVisible();await expect(page.getByLabel('Shared narrative',{exact:true})).toHaveCount(0);});
test('new association losing relevance is retained as draft but cannot be saved',async({page})=>{const f=await setup(page);await enter(page);await page.getByRole('button',{name:'Create initiative',exact:true}).click();await page.getByLabel('Initiative title',{exact:true}).fill('Draft');await page.getByLabel('Associate Synthetic service').check();await page.route('**/admin/documentation/activities/activity',route=>route.fulfill({status:404,json:{error:'Unavailable'}}));await page.getByRole('button',{name:'Reload initiatives'}).click();await expect(page.getByText('Unavailable new association; remove before saving',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'Save initiative',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Remove Synthetic service'}).click();await expect(page.getByRole('button',{name:'Save initiative',exact:true})).toBeEnabled();expect(f.writes).toHaveLength(0);});

test('archive cannot discard unsaved narrative or membership changes',async({page})=>{const f=await setup(page);await enter(page);await page.getByRole('button',{name:'Open Synthetic initiative',exact:true}).click();await page.getByLabel('Shared narrative',{exact:true}).fill('Unsaved narrative');await page.getByRole('button',{name:'Remove Synthetic service'}).click();await expect(page.getByRole('button',{name:'Archive initiative',exact:true})).toBeDisabled();await expect(page.getByText('Save or discard your draft before archiving this initiative.')).toBeVisible();expect(f.writes).toHaveLength(0);await page.getByRole('button',{name:'Discard initiative draft'}).click();await expect(page.getByLabel('Shared narrative',{exact:true})).toHaveValue('<b>Private narrative</b>');await expect(page.getByRole('button',{name:'Remove Synthetic service'})).toBeVisible();await expect(page.getByRole('button',{name:'Archive initiative',exact:true})).toBeEnabled();});
