import {expect,test,type Page} from '@playwright/test';
import {dashboardConformanceReferences as reference} from '../apps/dashboard/src/design-conformance';
async function notesSetup(page:Page,role='staff',theme='light') {
 let granted=true,enabled=true,fail=0;const writes:any[]=[];const requests:string[]=[];
 const sections={version:1,revision:0,notesEnabled:true,summaryEnabled:true,filesEnabled:true};
 const activity={id:'activity',title:'Synthetic service',serviceDate:'2026-09-10',revision:2,archived:false,impactRelevant:true};
 const notes:any[]=[{id:'note',activityId:'activity',text:'<script>private note</script>',revision:0,archived:false,authorUserId:'synthetic-author',createdAt:'2026-09-10T12:00:00Z',updatedAt:'2026-09-10T12:00:00Z'}];
 await page.addInitScript(value=>localStorage.setItem('lancerlogin-theme',value),theme);
 await page.route('**/setup/status',r=>r.fulfill({json:{configured:true,installation:{authMode:'local'},settings:{organizationName:'Synthetic Documentation',primaryColor:reference.brand.primary,secondaryColor:reference.brand.secondary,appearance:theme}}}));
 await page.route('**/auth/session',r=>r.fulfill({json:{user:{id:'synthetic',role}}}));
 await page.route('**/admin/setup/progress',r=>r.fulfill({json:{completedSteps:['branding','roster','pair-kiosk','fingerprint-test','confirm-attendance'].map(step=>({step}))}}));
 await page.route('**/platform/modules',r=>r.fulfill({json:{capabilities:granted&&enabled?['documentation.manage']:[],modules:[{id:'hour-tracking',enabled,capabilities:['hours.manage'],navigation:{path:'/hours',label:'Hour Tracking'}},{id:'activity-documentation',enabled,capabilities:['documentation.manage'],navigation:{path:'/documentation',label:'Activity Documentation'}}]}}));
 await page.route('**/admin/documentation/**',async r=>{const req=r.request(),url=new URL(req.url()),path=url.pathname.replace('/admin/documentation','');requests.push(url.pathname+url.search);
 if(req.method()!=='GET'){const body=req.postDataJSON();writes.push(body);if(fail){await r.fulfill({status:fail,json:{error:'Synthetic conflict'}});return;}if(path==='/sections'){Object.assign(sections,body,{revision:sections.revision+1});await r.fulfill({json:sections});return;}let n=path.startsWith('/notes/')?notes.find(n=>n.id===path.split('/')[2]):undefined;if(n)Object.assign(n,body,{revision:n.revision+1});else{n={...notes[0],...body,id:'created',revision:0};notes.push(n);}await r.fulfill({json:{note:n}});return;}
 if(!granted||!enabled){await r.fulfill({status:403,json:{error:'Unavailable'}});return;}
 if(path==='/sections'){await r.fulfill({json:sections});return;}
 if(path==='/activities'){await r.fulfill({json:{activities:[activity],next:url.searchParams.has('after')?null:'next-activity'}});return;}
 if(path==='/activities/activity'){await r.fulfill({json:{...activity,readOnly:activity.archived||!activity.impactRelevant,sectionRevision:sections.revision,...(sections.summaryEnabled?{summary:{countedMinutes:0,distinctParticipants:0}}:{})}});return;}
 if(path==='/activities/activity/notes'){await r.fulfill({json:{notes,next:url.searchParams.has('after')?null:'next-note',readOnly:activity.archived||!activity.impactRelevant||!sections.notesEnabled,activityRevision:activity.revision,sectionRevision:sections.revision}});return;}
 if(path.endsWith('/history')){await r.fulfill({json:{revisions:[{revision:url.searchParams.has('after')?1:0,text:'<b>Original text</b>',archived:false,createdAt:'2026-09-10'}],next:url.searchParams.has('after')?null:0}});return;}
 await r.fulfill({json:{note:notes.find(n=>n.id===path.split('/')[2])}});
 });
 return {sections,activity,notes,writes,requests,revoke:()=>granted=false,disable:()=>enabled=false,fail:(status:number)=>fail=status};
}
async function contextSetup(page:Page,role='staff',theme='light'){
 const docs=await notesSetup(page,role,theme);let fail=0;const writes:any[]=[];const reads:string[]=[];
 const activity={activityId:'activity',title:'Synthetic service',revision:2,archived:false,impactRelevant:true};
 const items:any[]=[{id:'first',title:'Synthetic initiative',narrative:'<b>Private narrative</b>',revision:0,archived:false,createdAt:'2026-09-10',updatedAt:'2026-09-10',activities:[activity]},{id:'second',title:'Shared initiative',narrative:'Second narrative',revision:0,archived:false,activities:[activity]}];
 await page.route('**/admin/documentation/initiatives**',async route=>{const req=route.request(),url=new URL(req.url()),path=url.pathname.replace('/admin/documentation/initiatives','');reads.push(path+url.search);const item=items.find(i=>i.id===path.split('/')[1]);
 const total=(selected:any[])=>{const eligible=selected.some(i=>!i.archived)&&!activity.archived&&activity.impactRelevant;return {linkedActivityCount:selected.some(i=>i.activities.length)?1:0,eligibleActivityCount:eligible&&selected.some(i=>i.activities.length)?1:0,omittedActivityCount:!eligible&&selected.some(i=>i.activities.length)?1:0,...(docs.sections.summaryEnabled?{summary:{countedMinutes:eligible&&selected.some(i=>i.activities.length)?90:0,distinctParticipants:eligible&&selected.some(i=>i.activities.length)?2:0}}:{})};};
 if(path==='/summary'){const ids=req.postDataJSON().initiativeIds;if(ids.some((value:string)=>!items.some(i=>i.id===value))){await route.fulfill({status:404,json:{error:'Unavailable'}});return;}await route.fulfill({json:total(items.filter(i=>ids.includes(i.id)))});return;}
 if(req.method()!=='GET'){const body=req.postDataJSON();writes.push(body);if(fail){await route.fulfill({status:fail,json:{error:'Conflict'}});return;}const value=item??{id:'created',revision:-1,archived:false,activities:[]};const members=body.activities?.map((a:any)=>({...activity,...a}))??value.activities;Object.assign(value,body,{activities:members,revision:value.revision+1});if(!item)items.push(value);await route.fulfill({json:{initiative:value}});return;}
 if(path.endsWith('/history')){await route.fulfill({json:{revisions:[{revision:url.searchParams.has('after')?1:0,title:'Original title',narrative:'<script>Historical narrative</script>',archived:false,createdAt:'2026-09-10',activityIds:['activity'],activities:[{activityId:'activity',title:'Current synthetic service title'}]}],next:url.searchParams.has('after')?null:0}});return;}
 if(!path){await route.fulfill({json:{initiatives:items.filter(i=>url.searchParams.get('archival')==='true'||!i.archived),next:url.searchParams.has('after')?null:'next'}});return;}
 if(!item){await route.fulfill({status:404,json:{error:'Unavailable'}});return;}
 await route.fulfill({json:{initiative:item,activities:item.activities.map((a:any)=>({...a,archived:activity.archived,impactRelevant:activity.impactRelevant})),readOnly:item.archived,...total([item])}});
 });
 return {...docs,items,activity,writes,reads,fail:(value:number)=>fail=value};
}
async function setup(page:Page,role='staff',theme='light'){
 const ctx=await contextSetup(page,role,theme);const writes:any[]=[];const requests:string[]=[];let fail=0,readback=false;
 const activity={activityId:'activity',title:'Synthetic service',revision:2,eligible:true};const initiative={initiativeId:'first',title:'Synthetic initiative',revision:0,eligible:true};
 const records:any[]=[{id:'metric',title:'Synthetic outcome',kind:'outcomes',value:'1.2500',unit:'items',periodStart:'2026-09-01',periodEnd:'2026-09-10',source:'<b>Synthetic source</b>',method:'Synthetic method',basis:'measured',revision:0,archived:false,createdAt:'2026-09-10T12:00:00Z',updatedAt:'2026-09-10T12:00:00Z',activities:[activity],initiatives:[initiative]}];
 await page.route('**/admin/documentation/metrics**',async route=>{const req=route.request(),url=new URL(req.url()),path=url.pathname.replace('/admin/documentation/metrics','');requests.push(path+url.search);const record=records.find(item=>item.id===path.split('/')[1]);
 if(req.method()!=='GET'){const body=req.postDataJSON();writes.push(body);if(fail){await route.fulfill({status:fail,json:{error:'Synthetic conflict'}});return;}const value=record??{...records[0],id:'created',revision:-1};Object.assign(value,body,{revision:value.revision+1,activities:body.activities?.map((item:any)=>({...activity,...item}))??value.activities,initiatives:body.initiatives?.map((item:any)=>({...initiative,...item}))??value.initiatives});if(!record)records.push(value);await route.fulfill({json:{metric:value}});return;}
 if(!path){await route.fulfill({json:{metrics:records.filter(item=>url.searchParams.get('archival')==='true'||!item.archived),next:url.searchParams.has('after')?null:'next-metric'}});return;}
 if(path.endsWith('/history')){await route.fulfill({json:{metricId:'metric',revisions:[{...records[0],revision:url.searchParams.has('after')?1:0,value:'1.2500',source:'<script>Historical source</script>',activities:[{...activity,title:'Current historical activity'}],initiatives:[{...initiative,title:'Current historical initiative'}]}],next:url.searchParams.has('after')?null:0}});return;}
 if(!record||readback&&writes.length){await route.fulfill({status:404,json:{error:'Unavailable'}});return;}
 await route.fulfill({json:{metric:record,activities:record.activities,initiatives:record.initiatives,readOnly:record.archived}});
 });return {...ctx,records,activity,initiative,writes,requests,fail:(value:number)=>fail=value,readback:(value:boolean)=>readback=value};
}
async function enter(page:Page){await page.goto('/documentation');await page.getByRole('button',{name:'Metrics',exact:true}).click();}
async function fill(page:Page){await page.getByLabel('Metric title',{exact:true}).fill('New synthetic metric');await page.getByLabel('Metric value',{exact:true}).fill('-999999999999999.123400');await page.getByLabel('Unit',{exact:true}).fill('items');await page.getByLabel('Period start',{exact:true}).fill('2026-09-01');await page.getByLabel('Period end',{exact:true}).fill('2026-09-10');await page.getByLabel('Source',{exact:true}).fill('Synthetic source');await page.getByLabel('Method',{exact:true}).fill('Synthetic method');await page.getByRole('combobox',{name:'Metric kind',exact:true}).selectOption('outcomes');await page.getByRole('combobox',{name:'Measurement basis',exact:true}).selectOption('estimated');}
for(const role of ['admin','staff'])test(role+' metrics create exact decimal, associations, history and archive',async({page})=>{const f=await setup(page,role);f.sections.notesEnabled=false;f.sections.summaryEnabled=false;await enter(page);await page.getByRole('button',{name:'Create metric',exact:true}).click();await expect(page.getByRole('heading',{name:'New metric'})).toBeFocused();await fill(page);await page.getByRole('button',{name:'Save metric',exact:true}).click();await expect(page.getByText('Saved and confirmed',{exact:false})).toBeVisible();expect(f.writes[0]).toMatchObject({value:'-999999999999999.123400',basis:'estimated',activities:[],initiatives:[]});await page.getByLabel('Associate Synthetic service').check();await page.getByLabel('Associate Synthetic initiative').check();await page.getByRole('button',{name:'Save metric',exact:true}).click();await expect.poll(()=>f.writes.length).toBe(2);expect(f.writes[1]).toMatchObject({revision:0,activities:[{activityId:'activity',revision:2}],initiatives:[{initiativeId:'first',revision:0}]});await page.getByRole('button',{name:'View metric history'}).click();await expect(page.getByText('Source: <script>Historical source</script>',{exact:true})).toBeVisible();await expect(page.getByText('Current historical initiative',{exact:true})).toBeVisible();await expect(page.locator('main script')).toHaveCount(0);await page.getByRole('button',{name:'Next metric history page'}).click();await expect(page.getByRole('heading',{name:'Revision 1',exact:true})).toBeVisible();await page.getByRole('button',{name:'Archive metric',exact:true}).click();await expect(page.getByLabel('Metric value',{exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Unarchive metric',exact:true}).click();await expect(page.getByLabel('Metric value',{exact:true})).toHaveValue('-999999999999999.123400');});
test('decimal and real inclusive period validation prevent invalid writes',async({page})=>{const f=await setup(page);await enter(page);await page.getByRole('button',{name:'Open Synthetic outcome',exact:true}).click();for(const value of ['1e3','01','-0','-0.000000','1.1234567','+1',' 1']){await page.getByLabel('Metric value',{exact:true}).fill(value);await expect(page.getByRole('button',{name:'Save metric',exact:true})).toBeDisabled();await expect(page.getByLabel('Metric value',{exact:true})).toHaveAttribute('aria-invalid','true');}await page.getByLabel('Metric value',{exact:true}).fill('1.00');await page.getByLabel('Period end',{exact:true}).fill('2026-08-31');await expect(page.getByRole('button',{name:'Save metric',exact:true})).toBeDisabled();await page.getByLabel('Period end',{exact:true}).fill('2026-09-01');await page.getByRole('button',{name:'Save metric',exact:true}).click();await expect.poll(()=>f.writes.length).toBe(1);expect(f.writes[0].value).toBe('1.00');});
test('dirty metric archive blocked and explicit discard restores exact saved scale',async({page})=>{const f=await setup(page);await enter(page);await page.getByRole('button',{name:'Open Synthetic outcome',exact:true}).click();await page.getByLabel('Metric value',{exact:true}).fill('1.25');await page.getByRole('button',{name:'Remove Synthetic service'}).click();await expect(page.getByRole('button',{name:'Archive metric',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Close and discard metric draft'})).toBeVisible();await page.getByRole('button',{name:'Discard metric draft',exact:true}).click();await expect(page.getByLabel('Metric value',{exact:true})).toHaveValue('1.2500');await expect(page.getByRole('button',{name:'Remove Synthetic service'})).toBeVisible();expect(f.writes).toHaveLength(0);});
test('retained ineligible contexts allow independent edits and removal with pagination',async({page})=>{const f=await setup(page);f.activity.eligible=false;f.initiative.eligible=false;await enter(page);await page.getByRole('button',{name:'Next metrics page'}).click();await expect.poll(()=>f.requests.some(p=>p.includes('after=next-metric'))).toBe(true);await page.getByRole('button',{name:'Open Synthetic outcome',exact:true}).click();await expect(page.getByText('Synthetic service · Activity · Currently ineligible',{exact:true})).toBeVisible();await page.getByLabel('Method',{exact:true}).fill('Revised independent method');await page.getByRole('button',{name:'Save metric',exact:true}).click();await expect(page.getByText('Saved and confirmed',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Remove Synthetic service'}).click();await page.getByRole('button',{name:'Remove Synthetic initiative'}).click();await page.getByRole('button',{name:'Save metric',exact:true}).click();await expect.poll(()=>f.writes.length).toBe(2);expect(f.writes[1]).toMatchObject({activities:[],initiatives:[]});await page.getByRole('button',{name:'Next activities choices page'}).click();await expect(page.getByRole('button',{name:'Next activities choices page'})).toHaveCount(0);await page.getByRole('button',{name:'Next initiatives choices page'}).click();await expect(page.getByRole('button',{name:'Next initiatives choices page'})).toHaveCount(0);});
test('conflict and uncertain readback preserve drafts and require explicit reload',async({page})=>{const f=await setup(page);await enter(page);await page.getByRole('button',{name:'Open Synthetic outcome',exact:true}).click();await page.getByLabel('Metric value',{exact:true}).fill('2.000');f.fail(409);await page.getByRole('button',{name:'Save metric',exact:true}).click();await expect(page.getByRole('alert')).toContainText('No write is retried');await expect(page.getByRole('button',{name:'Save metric',exact:true})).toBeDisabled();f.fail(0);await page.getByRole('button',{name:'Reload metrics'}).click();await expect(page.getByLabel('Metric value',{exact:true})).toHaveValue('2.000');f.readback(true);await page.getByRole('button',{name:'Save metric',exact:true}).click();await expect(page.getByRole('alert')).toBeVisible();f.readback(false);await page.getByRole('button',{name:'Reload metrics'}).click();await expect(page.getByRole('button',{name:'Save metric',exact:true})).toBeEnabled();expect(f.writes).toHaveLength(2);});
for(const role of ['operator','staff'])test(role+' without Documentation grant denied metrics',async({page})=>{const f=await setup(page,role);f.revoke();await page.goto('/documentation');await expect(page.getByRole('heading',{name:'Workspace unavailable'})).toBeVisible();expect(f.requests).toHaveLength(0);});
for(const kind of ['grant','module'])test(kind+' removal clears metric draft',async({page})=>{const f=await setup(page);await enter(page);await page.getByRole('button',{name:'Open Synthetic outcome',exact:true}).click();await page.getByLabel('Source',{exact:true}).fill('Private draft');kind==='grant'?f.revoke():f.disable();await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByRole('heading',{name:'Workspace unavailable'})).toBeVisible();await expect(page.getByLabel('Source',{exact:true})).toHaveCount(0);});
test('delayed metric read cannot restore content after access revocation',async({page})=>{const f=await setup(page);let release=()=>{};const gate=new Promise<void>(resolve=>release=resolve);await page.route('**/admin/documentation/metrics/metric',async r=>{await gate;await r.fallback();});await enter(page);await page.getByRole('button',{name:'Open Synthetic outcome',exact:true}).click();f.revoke();await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByRole('heading',{name:'Workspace unavailable'})).toBeVisible();release();await expect(page.getByLabel('Metric value',{exact:true})).toHaveCount(0);});
test('delayed write remains serialized during access refresh',async({page})=>{const f=await setup(page);let release=()=>{};const gate=new Promise<void>(resolve=>release=resolve);await page.route('**/admin/documentation/metrics/metric',async r=>{if(r.request().method()==='PATCH')await gate;await r.fallback();});await enter(page);await page.getByRole('button',{name:'Open Synthetic outcome',exact:true}).click();const requested=page.waitForRequest(r=>r.method()==='PATCH');await page.getByRole('button',{name:'Save metric',exact:true}).click();await requested;await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByRole('button',{name:'Reload metrics'})).toBeDisabled();release();await expect(page.getByRole('button',{name:'Reload metrics'})).toBeEnabled();await expect(page.getByRole('button',{name:'Save metric',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Reload metrics'}).click();await expect(page.getByRole('button',{name:'Save metric',exact:true})).toBeEnabled();expect(f.writes).toHaveLength(1);});
test('new activity losing eligibility must be removed from draft',async({page})=>{await setup(page);await enter(page);await page.getByRole('button',{name:'Create metric',exact:true}).click();await fill(page);await page.getByLabel('Associate Synthetic service').check();await page.route('**/admin/documentation/activities/activity',r=>r.fulfill({status:404,json:{error:'Unavailable'}}));await page.getByRole('button',{name:'Reload metrics'}).click();await expect(page.getByText('Unavailable new association; remove before saving',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'Save metric',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Remove Synthetic service'}).click();await expect(page.getByRole('button',{name:'Save metric',exact:true})).toBeEnabled();});
for(const viewport of reference.viewports)for(const theme of reference.themes)test('metrics visual '+viewport.width+' '+theme,async({page})=>{await setup(page,'staff',theme);await page.setViewportSize(viewport);await enter(page);await page.getByRole('button',{name:'Open Synthetic outcome',exact:true}).click();await expect(page.locator('main h1')).toHaveCount(1);await page.keyboard.press('Tab');const save=page.getByRole('button',{name:'Save metric',exact:true});await save.focus();await expect(save).toBeFocused();expect(await save.evaluate(e=>getComputedStyle(e).outlineStyle)).not.toBe('none');expect((await save.boundingBox())!.height).toBeGreaterThanOrEqual(44);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.locator('main b')).toHaveCount(0);await page.screenshot({path:test.info().outputPath('metrics.png'),fullPage:true});});

test('association limit applies across both context types',async({page})=>{const f=await setup(page);f.records[0].activities=Array.from({length:99},(_,index)=>({...f.activity,activityId:'bounded-'+index,title:'Bounded activity '+index}));await enter(page);await page.getByRole('button',{name:'Open Synthetic outcome',exact:true}).click();await expect(page.getByLabel('Associate Shared initiative')).toBeDisabled();await page.getByRole('button',{name:'Remove Bounded activity 0',exact:true}).click();await page.getByLabel('Associate Shared initiative').check();await expect(page.getByLabel('Associate Synthetic service')).toBeDisabled();await page.getByRole('button',{name:'Save metric',exact:true}).click();await expect.poll(()=>f.writes.length).toBe(1);expect(f.writes[0].activities.length+f.writes[0].initiatives.length).toBe(100);});
