import { readFileSync } from 'node:fs';
import { test,expect,type Page } from '@playwright/test';
import { selectCivilTime,addCalendarDays } from '../packages/shared/src/civil-time';
import { dashboardConformanceReferences as design } from '../apps/dashboard/src/design-conformance';

async function setup(page:Page,theme='light'){
 // Serve the unchanged bundled fonts when a development node_modules junction lies outside Vite's root.
 await page.route(/\/@fs\/.*\/@fontsource\/(roboto|bebas-neue)\/files\/[^/?]+\.woff2?$/,async r=>{const match=new URL(r.request().url()).pathname.match(/\/@fontsource\/(roboto|bebas-neue)\/files\/([a-z0-9-]+\.woff2?)$/);if(!match)return r.continue();await r.fulfill({body:readFileSync(new URL('../node_modules/@fontsource/'+match[1]+'/files/'+match[2],import.meta.url)),contentType:match[2].endsWith('woff2')?'font/woff2':'font/woff'});});
 await page.clock.install({time:new Date('2026-09-09T16:00:00Z')});
 const paths:string[]=[],writes:{path:string;body:any}[]=[],saved=new Map<string,any>();let off=false,status=0,drop=false,bad=false,eventDate='2026-09-08',pageMany=false;
 await page.addInitScript(()=>{const original=window.fetch; (window as any).__publicCalls=[];window.fetch=(input,init)=>{(window as any).__publicCalls.push({url:String(input),credentials:init?.credentials});return original(input,init);};});
 await page.context().addCookies([{name:'lancerlogin_session',value:'synthetic-session-only',domain:'127.0.0.1',path:'/'}]);
 await page.route('**/setup/status',r=>r.fulfill({json:{configured:true,settings:{organizationName:'Synthetic Community Service',primaryColor:design.brand.primary,secondaryColor:design.brand.secondary,appearance:theme}}}));
 await page.route('**/public/hours/**',async r=>{
  const u=new URL(r.request().url()),kind=u.pathname.split('/').at(-1)!;paths.push(u.pathname+u.search);
  if(r.request().method()==='GET'){
   if(status)return r.fulfill({status,headers:{'Retry-After':'1','access-control-expose-headers':'Retry-After'},json:{error:'do not display raw errors'}});
   if(kind==='context')return r.fulfill({json:off?{available:false}:{available:true,timeZone:'America/New_York',today:'2026-09-09',earliestServiceDate:'2026-09-03',reportingDays:7}});
   let items:any[]=kind==='categories'?[{id:'event-category',name:'Service event',mode:'event'},{id:'team-category',name:'Team support',mode:'team'},{id:'task-category',name:'Other service',mode:'task'}]:kind==='teams'?[{id:'team',name:'Synthetic team',number:'0017',program:'FTC'}]:[{id:'event',categoryId:'event-category',title:'Synthetic service event',serviceDate:u.searchParams.get('date')??eventDate}];
   if(kind==='events'&&pageMany)items=[{...items[0],id:u.searchParams.has('after')?'event-second':'event'}];
   return r.fulfill({json:{items,nextCursor:kind==='events'&&pageMany&&!u.searchParams.has('after')?'event':null}});
  }
  const body=r.request().postDataJSON();writes.push({path:u.pathname,body});
  if(status)return r.fulfill({status,headers:{'Retry-After':'1','access-control-expose-headers':'Retry-After'},json:{error:'do not display raw errors',code:'submission_not_accepted'}});
  let result=saved.get(body.idempotencyKey);
  if(!result){if(kind==='correction-requests')result={accepted:true,reference:'synthetic-request'};else{
   const a=selectCivilTime({date:body.serviceDate,time:body.startLocal,timeZone:body.expectedTimeZone},body.startOccurrence),b=selectCivilTime({date:addCalendarDays(body.serviceDate,Number(body.endNextDay)),time:body.endLocal,timeZone:body.expectedTimeZone},body.endOccurrence);
   result={id:'synthetic-receipt',activity_id:body.activityId??'canonical-activity',service_date:body.serviceDate,time_zone:body.expectedTimeZone,start_local:body.startLocal,end_local:body.endLocal,end_next_day:Number(body.endNextDay),start_occurrence:body.startOccurrence??null,end_occurrence:body.endOccurrence??null,start_ms:a.epochMilliseconds,end_ms:b.epochMilliseconds,start_offset_seconds:a.offsetSeconds,end_offset_seconds:b.offsetSeconds,duration_minutes:(b.epochMilliseconds-a.epochMilliseconds)/60000,task_notes:body.taskNotes,created_at:'2026-09-09T16:00:00Z'};
  }saved.set(body.idempotencyKey,result);}
  if(drop){drop=false;return r.abort();}return r.fulfill({json:bad?{...result,service_date:'2020-01-01'}:result,status:kind==='entries'?201:202});
 });
 return {paths,writes,off:()=>off=true,status:(v:number)=>status=v,drop:()=>drop=true,bad:(v=true)=>bad=v,eventDate:(v:string)=>eventDate=v,many:()=>pageMany=true};
}
async function open(page:Page){await page.goto('/submit-hours');await expect(page.getByLabel('Member ID',{exact:true})).toBeVisible();}
async function fill(page:Page,mode='task'){
 await page.getByLabel('Member ID',{exact:true}).fill('00017');await page.getByLabel('Service category',{exact:true}).selectOption(mode+'-category');
 if(mode==='event')await page.getByLabel('Dated event',{exact:true}).selectOption('event');
 else{if(mode==='team')await page.getByLabel('Supported team',{exact:true}).selectOption('team');await page.getByLabel('Service date',{exact:true}).fill('2026-09-08');}
 await page.getByLabel('Start time',{exact:true}).fill('09:00');await page.getByLabel('End time',{exact:true}).fill('10:00');await page.getByLabel('Task notes (optional)').fill('Synthetic service notes');
}
for(const mode of ['event','team','task'])test(`anonymous ${mode} submission preserves string identity and original receipt`,async({page})=>{
 const f=await setup(page);await open(page);await fill(page,mode);await page.getByRole('button',{name:'Submit completed hours'}).click();await expect(page.getByRole('heading',{name:'Original submission receipt'})).toBeVisible();expect(f.writes).toHaveLength(1);expect(f.writes[0].body).toMatchObject({memberId:'00017',serviceDate:'2026-09-08',expectedTimeZone:'America/New_York'});expect(f.writes[0].body).not.toHaveProperty('channel');expect(f.writes[0].body).not.toHaveProperty('label');await expect(page.getByText('Submitted notes: Synthetic service notes',{exact:true})).toBeVisible();await expect(page.getByText(mode==='task'?'Other service':mode==='team'?'Team support · 0017 · Synthetic team · FTC':'Service event · 2026-09-08 · Synthetic service event',{exact:true})).toBeVisible();
 const calls=await page.evaluate(()=>(window as any).__publicCalls);expect(calls.every((v:any)=>v.credentials==='omit'&&(/\/setup\/status$|\/public\/hours\//.test(v.url)))).toBeTruthy();expect(f.paths.some(v=>v.includes('00017')||v.includes('synthetic-receipt'))).toBeFalsy();expect(await page.evaluate(()=>Object.keys(localStorage))).toEqual([]);
 await page.reload();await expect(page.getByRole('heading',{name:'Original submission receipt'})).toHaveCount(0);expect(f.writes).toHaveLength(1);
});
test('uncertain entry freezes the exact payload and key until explicit retry',async({page})=>{
 const f=await setup(page);await open(page);await fill(page);f.drop();await page.getByRole('button',{name:'Submit completed hours'}).click();await expect(page.getByRole('heading',{name:'Frozen submission'})).toBeVisible();await expect(page.getByLabel('Member ID',{exact:true})).toBeDisabled();await expect(page.getByRole('alert').first()).toBeFocused();expect(f.writes).toHaveLength(1);await page.getByRole('button',{name:'Retry exact submission'}).click();await expect(page.getByRole('heading',{name:'Original submission receipt'})).toBeVisible();expect(f.writes[1].body).toEqual(f.writes[0].body);
});
test('generic rejection offers correction without disclosing records; correction retry is exact',async({page})=>{
 const f=await setup(page);await open(page);await fill(page);f.status(409);await page.getByRole('button',{name:'Submit completed hours'}).click();await expect(page.getByRole('alert').first()).toContainText('You can request a correction');await expect(page.getByText('do not display raw errors')).toHaveCount(0);await page.getByRole('button',{name:'Discard frozen draft'}).click();f.status(0);await page.getByRole('button',{name:'Request a correction',exact:true}).click();await page.getByLabel('Member ID',{exact:true}).fill('00017');await page.getByLabel('What should staff review?').fill('Synthetic missing service');f.drop();await page.getByRole('button',{name:'Send correction request'}).click();await expect(page.getByRole('button',{name:'Retry exact submission'})).toBeVisible();await page.getByRole('button',{name:'Retry exact submission'}).click();await expect(page.getByRole('heading',{name:'Correction acknowledgement'})).toBeVisible();expect(f.writes[2].body).toEqual(f.writes[1].body);expect(f.paths.some(v=>v.includes('member-choices')||v.includes('history'))).toBeFalsy();
});
test('429 waits without automatic retry, then preserves original key',async({page})=>{
 const f=await setup(page);await open(page);await fill(page);f.status(429);await page.getByRole('button',{name:'Submit completed hours'}).click();await expect(page.getByRole('button',{name:'Retry exact submission'})).toBeDisabled();await page.clock.runFor(1500);expect(f.writes).toHaveLength(1);f.status(0);await expect(page.getByRole('button',{name:'Retry exact submission'})).toBeEnabled();await page.getByRole('button',{name:'Retry exact submission'}).click();expect(f.writes[1].body).toEqual(f.writes[0].body);
});
test('malformed receipt stays uncertain and disabled context offers no form',async({page})=>{
 const f=await setup(page);await open(page);await fill(page);f.bad();await page.getByRole('button',{name:'Submit completed hours'}).click();await expect(page.getByRole('heading',{name:'Original submission receipt'})).toHaveCount(0);await expect(page.getByRole('heading',{name:'Frozen submission'})).toBeVisible();f.off();await page.reload();await expect(page.getByRole('heading',{name:'Hour submission unavailable'})).toBeVisible();await expect(page.getByLabel('Member ID',{exact:true})).toHaveCount(0);expect(f.writes).toHaveLength(1);
});
test('event paging preserves applied date; DST folds, gaps, next day and precision are explicit',async({page})=>{
 const f=await setup(page);f.eventDate('2025-11-02');f.many();await open(page);await fill(page,'event');await page.getByLabel('Start time',{exact:true}).fill('01:30');await page.getByLabel('End time',{exact:true}).fill('01:30');await expect(page.getByRole('button',{name:'Submit completed hours'})).toBeDisabled();await page.getByLabel('Start time occurrence').selectOption('earlier');await page.getByLabel('End time occurrence').selectOption('later');await expect(page.getByText('Calculated duration: 60 minutes',{exact:false})).toBeVisible();await page.getByLabel('End time',{exact:true}).fill('02:30:00.001');await expect(page.getByRole('button',{name:'Submit completed hours'})).toBeDisabled();await page.getByLabel('Find events on date (optional)').fill('2025-03-09');await page.getByRole('button',{name:'Apply event date'}).click();await page.getByLabel('Dated event',{exact:true}).selectOption('event');await page.getByLabel('Start time',{exact:true}).fill('02:30');await expect(page.getByText('This local time does not exist',{exact:false}).first()).toBeVisible();await page.getByLabel('Find events on date (optional)').fill('2025-04-01');await page.getByRole('button',{name:'Next dated event page'}).click();expect(f.paths.at(-1)).toContain('date=2025-03-09');await page.getByLabel('Dated event',{exact:true}).selectOption('event-second');await page.getByLabel('Start time',{exact:true}).fill('23:00');await page.getByLabel('End time',{exact:true}).fill('01:00');await page.getByLabel('End on the next calendar day').check();await expect(page.getByText('Calculated duration: 120 minutes',{exact:false})).toBeVisible();
});
test('future completion and historical task dates cannot be submitted',async({page})=>{await setup(page);await open(page);await fill(page);await page.getByLabel('Service date',{exact:true}).fill('2026-09-09');await page.getByLabel('End time',{exact:true}).fill('23:00');await expect(page.getByRole('button',{name:'Submit completed hours'})).toBeDisabled();await page.getByLabel('Service date',{exact:true}).fill('2025-11-02');await expect(page.getByRole('button',{name:'Submit completed hours'})).toBeDisabled();});
for(const theme of ['light','dark'])for(const width of [390,1280])test(`public form ${theme} ${width} branding and keyboard`,async({page},info)=>{
 await setup(page,theme);await page.setViewportSize({width,height:width===390?844:900});await open(page);await fill(page,'team');await page.getByLabel('Member ID',{exact:true}).focus();await page.keyboard.press('Tab');await expect(page.getByLabel('Service category',{exact:true})).toBeFocused();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();expect(await page.locator('h1').count()).toBe(1);expect(await page.getByLabel('Service category',{exact:true}).evaluate(el=>el.getBoundingClientRect().height)).toBeGreaterThanOrEqual(44);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:info.outputPath(`public-${theme}-${width}.png`),fullPage:true});
});
