import {test,expect,type Page} from '@playwright/test';
import {dashboardConformanceReferences as design} from '../apps/dashboard/src/design-conformance';
async function setup(page:Page,theme='light'){
 let off=false,status=0,malformed=false,drop=false,section=0;const bodies:string[]=[],requests:string[]=[],saved=new Map<string,string>();
 await page.addInitScript(()=>{const original=window.fetch;(window as any).__calls=[];window.fetch=(input,init)=>{(window as any).__calls.push({url:String(input),credentials:init?.credentials});return original(input,init);};});
 await page.route('**/setup/status',r=>r.fulfill({json:{configured:true,settings:{organizationName:'Synthetic Community',primaryColor:design.brand.primary,secondaryColor:design.brand.secondary,appearance:theme}}}));
 await page.route('**/public/documentation/**',async r=>{const u=new URL(r.request().url());requests.push(u.pathname+u.search);if(r.request().method()==='GET'){if(status)return r.fulfill({status,headers:{'Retry-After':'1','access-control-expose-headers':'Retry-After'},json:{error:'private error'}});if(u.pathname.endsWith('/context'))return r.fulfill({json:off?{available:false}:{available:true,sectionRevision:section}});return r.fulfill({json:{activities:[{id:u.searchParams.has('after')?'old-activity':'activity',title:u.searchParams.has('after')?'Earlier service':'Synthetic service',serviceDate:'2020-01-01',mode:'event',revision:2}],next:u.searchParams.has('after')?null:'activity',sectionRevision:section}});}
 const raw=r.request().postData()!;bodies.push(raw);const b=JSON.parse(raw);if(status)return r.fulfill({status,headers:{'Retry-After':'1','access-control-expose-headers':'Retry-After'},json:{error:'private error'}});if(!saved.has(b.idempotencyKey))saved.set(b.idempotencyKey,'synthetic-ack');if(drop){drop=false;return r.abort('failed');}return r.fulfill({json:malformed?{accepted:true,reference:'bad',text:'private'}:{accepted:true,reference:saved.get(b.idempotencyKey)}});
 });return {bodies,requests,saved,off:()=>off=true,status:(s:number)=>status=s,malformed:()=>malformed=true,drop:()=>drop=true,section:()=>section++};
}
async function fill(page:Page){await page.getByLabel('Member ID',{exact:true}).fill('00123');await page.getByLabel('Activity',{exact:true}).selectOption('activity');await page.getByLabel('Activity note',{exact:true}).fill('Synthetic private note <script>text only</script>');}
test('public note is no-login, exact identity and independent of Hours window',async({page})=>{const f=await setup(page);await page.goto('/submit-documentation');await fill(page);await page.getByRole('button',{name:'Send note',exact:true}).click();await expect(page.getByRole('heading',{name:'Note received'})).toBeVisible();expect(JSON.parse(f.bodies[0]).memberId).toBe('00123');expect(f.saved.size).toBe(1);expect(f.requests.every(p=>!p.includes('/hours/'))).toBe(true);expect(await page.evaluate(()=>(window as any).__calls.filter((c:any)=>c.url.includes('/public/')).every((c:any)=>c.credentials==='omit'))).toBe(true);expect(await page.evaluate(()=>JSON.stringify({...localStorage,...sessionStorage}))).not.toContain('00123');await expect(page.getByRole('link',{name:'Submit hours separately (opens a new tab)'})).toHaveAttribute('target','_blank');});
test('lost acknowledgement preserves frozen exact body/key, no automatic retry',async({page})=>{const f=await setup(page);f.drop();await page.goto('/submit-documentation');await fill(page);await page.getByRole('button',{name:'Send note',exact:true}).click();await expect(page.getByRole('alert')).toContainText('could not be confirmed');await expect(page.getByLabel('Activity note',{exact:true})).toBeDisabled();expect(f.bodies).toHaveLength(1);await page.getByRole('button',{name:'Retry this submission'}).click();await expect(page.getByRole('heading',{name:'Note received'})).toBeVisible();expect(f.bodies).toHaveLength(2);expect(f.bodies[1]).toBe(f.bodies[0]);expect(f.saved.size).toBe(1);});
for(const status of [409,503])test('note '+status+' remains frozen until explicit discard/reload',async({page})=>{const f=await setup(page);await page.goto('/submit-documentation');await fill(page);f.status(status);await page.getByRole('button',{name:'Send note',exact:true}).click();await expect(page.getByRole('alert')).toBeVisible();await expect(page.getByText('private error',{exact:true})).toHaveCount(0);expect(f.bodies).toHaveLength(1);await page.getByRole('button',{name:'Discard unconfirmed submission'}).click();await expect(page.getByRole('button',{name:'Send note',exact:true})).toBeDisabled();f.status(0);await page.getByRole('button',{name:'Reload first activity page'}).click();await expect(page.getByLabel('Activity note',{exact:true})).toHaveValue('Synthetic private note <script>text only</script>');await expect(page.getByLabel('Activity',{exact:true})).toHaveValue('');});
test('malformed acknowledgement cannot confirm or expose private fields',async({page})=>{const f=await setup(page);f.malformed();await page.goto('/submit-documentation');await fill(page);await page.getByRole('button',{name:'Send note',exact:true}).click();await expect(page.getByRole('heading',{name:'Note received'})).toHaveCount(0);await expect(page.getByRole('alert')).toBeVisible();});
test('429 countdown never schedules a submission',async({page})=>{const f=await setup(page);await page.clock.install();await page.goto('/submit-documentation');await fill(page);f.status(429);await page.getByRole('button',{name:'Send note',exact:true}).click();await expect(page.getByRole('button',{name:'Retry this submission'})).toBeDisabled();await page.clock.fastForward(2000);await expect(page.getByRole('button',{name:'Retry this submission'})).toBeEnabled();expect(f.bodies).toHaveLength(1);});
test('activity paging preserves unsent text and current unavailability clears selection',async({page})=>{const f=await setup(page);await page.goto('/submit-documentation');await fill(page);await page.getByRole('button',{name:'Next activity page'}).click();await expect(page.getByRole('option',{name:'Earlier service · 2020-01-01'})).toHaveCount(1);await expect(page.getByLabel('Activity note',{exact:true})).not.toHaveValue('');await expect(page.getByLabel('Activity',{exact:true})).toHaveValue('');f.off();await page.getByRole('button',{name:'Reload first activity page'}).click();await expect(page.getByRole('heading',{name:'Note submission unavailable'})).toBeVisible();expect(f.bodies).toHaveLength(0);});
for(const viewport of design.viewports)for(const theme of design.themes)test('public Documentation visual '+viewport.width+' '+theme,async({page})=>{await setup(page,theme);await page.setViewportSize(viewport);await page.goto('/submit-documentation');await fill(page);const button=page.getByRole('button',{name:'Send note',exact:true});await button.focus();await expect(button).toBeFocused();expect(await button.evaluate(e=>getComputedStyle(e).outlineStyle)).not.toBe('none');expect((await button.boundingBox())!.height).toBeGreaterThanOrEqual(44);await expect(page.locator('main h1')).toHaveCount(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:test.info().outputPath('public-documentation.png'),fullPage:true});});

test('serialized preflight rejection keeps editable text and sends no request',async({page})=>{const f=await setup(page);await page.goto('/submit-documentation');await fill(page);await page.getByLabel('Activity note',{exact:true}).evaluate(el=>{Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value')!.set!.call(el,String.fromCharCode(0xd800).repeat(7000));el.dispatchEvent(new Event('input',{bubbles:true}));});await expect(page.getByText('7000/8000',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Send note',exact:true}).click();await expect(page.getByRole('alert')).toContainText('nothing was submitted');await expect(page.getByLabel('Activity note',{exact:true})).toBeEnabled();await expect(page.getByRole('button',{name:'Retry this submission'})).toHaveCount(0);expect(f.bodies).toHaveLength(0);});
for(const field of ['date','title'])test('malformed activity '+field+' fails closed',async({page})=>{const f=await setup(page);await page.route('**/public/documentation/activities?*',r=>r.fulfill({json:{activities:[{id:'activity',title:field==='title'?17:'Synthetic',serviceDate:field==='date'?'2026-02-30':'2026-02-01',mode:'event',revision:0}],sectionRevision:0,next:null}}));await page.goto('/submit-documentation');await expect(page.getByRole('alert')).toContainText('could not be confirmed');await expect(page.getByRole('button',{name:'Send note',exact:true})).toBeDisabled();expect(f.bodies).toHaveLength(0);});
