import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {createHash,generateKeyPairSync,sign} from 'node:crypto';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {migrationStatements} from './migration-statements.mjs';
import {documentationFileDiscordInteraction,selectedDocumentationFile,downloadDocumentationFile} from '../apps/api/src/documentation-discord-file.ts';
import {encryptIntegration,decryptIntegration} from '../apps/api/src/integration-crypto.ts';
import {createSessionCodec,hashPassword} from '../apps/api/src/runtime-security.ts';
import worker from '../apps/api/src/index.ts';
const secret='AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',user='123456789012345678',config={applicationId:'123456789012345679',guildId:'123456789012345680'};
const sha=b=>createHash('sha256').update(b).digest('hex');
const find=(m,label)=>m.components.flatMap(r=>r.components).find(c=>c.label===label);
const source=(size=1200000)=>{const id='123456789012345681',now=Date.now();return {components:[{type:18,component:{type:19,custom_id:'original',values:[id]}}],resolved:{attachments:{[id]:{id,filename:'Synthetic file.txt',content_type:'text/plain',size,url:'https://cdn.discordapp.com/attachments/123456789012345680/'+id+'/file.txt?ex='+Math.floor((now+600000)/1000).toString(16)+'&is='+Math.floor(now/1000).toString(16)+'&hm='+'a'.repeat(64)}}}};};
test('signed-member file intake freezes identity and bytes, continues privately and excludes transient authority from backup',{timeout:180000},async()=>{
 const mf=new Miniflare(convertV4MiniflareOptions({modules:true,script:'export default {fetch(){return new Response("fixture")}}',compatibilityDate:'2026-08-01',d1Databases:['DB']}));const oldFetch=globalThis.fetch;
 try{
  const db=await mf.getD1Database('DB'),directory=new URL('../apps/api/migrations/',import.meta.url);for(const name of readdirSync(directory).filter(n=>n.endsWith('.sql')).sort())await db.batch(migrationStatements(readFileSync(new URL(name,directory),'utf8')).map(s=>db.prepare(s)));
  await db.batch([
   db.prepare("INSERT INTO installations(id,created_at,auth_mode) VALUES('primary','2026-01-01','local'),('foreign','2026-01-01','local')"),
   db.prepare("INSERT INTO organization_settings(installation_id,organization_name,time_zone) VALUES('primary','Synthetic Team','UTC')"),
   db.prepare("INSERT INTO users(id,installation_id,local_username,role,created_at) VALUES('admin','primary','synthetic-admin','admin','2026-01-01'),('docs','primary','synthetic-docs','staff','2026-01-01'),('hours','primary','synthetic-hours','staff','2026-01-01'),('operator','primary','synthetic-operator','operator','2026-01-01')"),
   db.prepare("INSERT INTO platform_module_configuration VALUES('primary',1,1,1)"),
   db.prepare("INSERT INTO platform_module_grants VALUES('primary','docs',0,1),('primary','hours',1,0)"),
   db.prepare("INSERT INTO hours_categories(installation_id,id,name,mode,created_at,updated_at) VALUES('primary','event','Event','event','2026-01-01','2026-01-01')"),
   db.prepare("INSERT INTO hours_activities(installation_id,id,category_id,mode,service_date,title,description,planning_time_zone,impact_relevant,created_at,updated_at) VALUES('primary','activity','event','event','2026-01-19','Synthetic eligible activity','PRIVATE HOURS DESCRIPTION','UTC',1,'2026-01-01','2026-01-01'),('primary','unrelated','event','event','2026-01-19','Unrelated hours-only','PRIVATE UNRELATED','UTC',0,'2026-01-01','2026-01-01')"),
   db.prepare("INSERT INTO hours_entry_settings(installation_id) VALUES('primary')"),
   db.prepare("INSERT INTO members(id,installation_id,external_id,first_name,last_name,created_at) VALUES('member1','primary','00123','PRIVATE','ONE','2026-01-01'),('member2','primary','00456','PRIVATE','TWO','2026-01-01')")
  ]);

 const original=Buffer.alloc(1200000,65),manifestStore=new Map(),chunks=new Map();let activeReads=0,maxReads=0,loseChunkAck=true;let computeComplete=false,remoteComplete=false,remoteOffset=0,createCount=0,mediaReads=0,partial=true,loseAck=false;
 const connection={clientId:'synthetic-client',clientSecret:'synthetic-secret',loginEnabled:false,calendarEnabled:false,driveEnabled:true,generation:'generation',loginProof:false,organizationProof:true,calendarProof:false,legacyFingerprint:'[null,null,{}]',grant:{proofId:'proof',refreshToken:'synthetic-refresh',subject:'synthetic',scopes:['https://www.googleapis.com/auth/drive.file']}};
 await db.prepare("UPDATE users SET password_hash=? WHERE id='admin'").bind(await hashPassword('synthetic recovery password')).run();
 const crypt=await encryptIntegration({payload:JSON.stringify(connection),installation:'primary',slot:'active'},secret);
 await db.prepare("INSERT INTO google_connections(installation_id,active_ciphertext,active_iv,revision,updated_at) VALUES('primary',?,?,1,'2026-01-01')").bind(crypt.ciphertext,crypt.iv).run();
 await db.prepare("UPDATE google_connections SET shared_mode=1,grant_proof_id='proof'").run();
 await db.prepare("INSERT INTO google_drive_storage VALUES('primary',1,'root','Synthetic private root','generation',?,'2026-01-01')").bind(crypt.iv).run();
 const compute={async fetch(request){const p=new URL(request.url).pathname;if(p==='/jobs'){const m=await request.json();manifestStore.set(m.id,m);return Response.json({id:m.id,manifestDigest:sha(JSON.stringify(m)),state:'staging'});}const id=p.split('/')[2],m=manifestStore.get(id),manifestDigest=sha(JSON.stringify(m));
 if(request.method==='PUT'){const n=Number(p.split('/').at(-1)),b=Buffer.from(await request.arrayBuffer());if(chunks.has(id+':'+n)&&!chunks.get(id+':'+n).equals(b))return new Response(null,{status:409});chunks.set(id+':'+n,b);if(loseChunkAck){loseChunkAck=false;throw Error('Synthetic lost chunk acknowledgement');}return Response.json({id});}
 if(p.endsWith('/seal')){computeComplete=true;return Response.json({id,state:'queued'});}
 if(p.endsWith('/original'))return Response.json({jobId:id,itemIndex:0,id:'original',revision:'1',type:m.items[0].type,byteLength:original.length,sha256:sha(original),chunkSize:262144,chunkCount:Math.ceil(original.length/262144),chunkSha256:Array.from({length:Math.ceil(original.length/262144)},(_,n)=>sha(original.subarray(n*262144,(n+1)*262144))),manifestDigest,snapshotDigest:m.snapshotDigest,policyVersion:'document-input-v1',outcome:'linked-only',expiresAt:Date.now()+100000});
 if(p.includes('/original/chunks/')){activeReads++;maxReads=Math.max(maxReads,activeReads);await new Promise(r=>setTimeout(r,25));activeReads--;const n=Number(p.split('/').at(-1)),b=original.subarray(n*262144,(n+1)*262144);return new Response(b,{headers:{'content-type':'application/octet-stream','content-length':String(b.length),'x-document-item-index':'0','x-document-chunk-index':String(n),'x-document-byte-offset':String(n*262144),'x-document-sha256':sha(original),'x-document-chunk-sha256':sha(b),'x-document-manifest-sha256':manifestDigest,'x-document-snapshot-sha256':m.snapshotDigest}});}
 return Response.json({id,manifestDigest,state:computeComplete?'complete':'staging'});
 }};
 let currentOp;const messages=new Map();let acknowledged=false,cdnReads=0;const keys=generateKeyPairSync('ed25519');const discord=await encryptIntegration({...config,publicKey:keys.publicKey.export({type:'spki',format:'der'}).subarray(-32).toString('hex')},secret);await db.prepare("UPDATE installations SET discord_enabled=1 WHERE id='primary'").run();await db.prepare("UPDATE members SET discord_user_id=? WHERE id='member1'").bind(user).run();await db.prepare("INSERT INTO encrypted_integrations(id,installation_id,provider,ciphertext,iv,updated_at,verified_at) VALUES('discord','primary','discord',?,?,'2026-01-01','2026-01-01')").bind(discord.ciphertext,discord.iv).run();await db.prepare("INSERT INTO documentation_sections(installation_id,notes_enabled,files_enabled) VALUES('primary',0,1)").run();
 globalThis.fetch=async(url,init={})=>{url=String(url);if(url.startsWith('https://cdn.discordapp.com/')){assert.ok(acknowledged);assert.equal(new Headers(init.headers).has('authorization'),false);assert.equal(init.redirect,'manual');cdnReads++;return new Response(original,{headers:{'content-length':String(original.length)}});}if(url.startsWith('https://discord.com/api/v10/webhooks/')){assert.equal(new Headers(init.headers).has('authorization'),false);const body=JSON.parse(init.body);assert.deepEqual(body.allowed_mentions,{parse:[]});messages.set(url.split('/')[7],body);return Response.json({});}assert.ok(url.startsWith('https://www.googleapis.com/')||url==='https://oauth2.googleapis.com/token');if(url==='https://oauth2.googleapis.com/token')return Response.json({access_token:'synthetic-token'});
 if(url.includes('/permissions?'))return Response.json({permissions:[{type:'user',role:'owner'}]});
 if(url.includes('/files/root?'))return Response.json({id:'root',mimeType:'application/vnd.google-apps.folder',trashed:false,ownedByMe:true,capabilities:{canAddChildren:true}});
 if(url.includes('generateIds'))return Response.json({ids:['reserved-file']});
 if(url.includes('uploadType=resumable')){if(init.method==='POST'){createCount++;return new Response(null,{headers:{location:'https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable&upload_id=synthetic'}});}const headers=new Headers(init.headers);if(headers.get('content-range').startsWith('bytes */'))return remoteComplete?Response.json({id:'reserved-file'}):new Response(null,{status:308,headers:remoteOffset?{range:'bytes=0-'+(remoteOffset-1)}:{}});
 const b=Buffer.from(init.body);if(partial){remoteOffset+=7;partial=false;}else remoteOffset+=b.length;remoteComplete=remoteOffset===original.length;if(loseAck){loseAck=false;throw Error('synthetic lost response');}return remoteComplete?Response.json({id:'reserved-file'}):new Response(null,{status:308,headers:{range:'bytes=0-'+(remoteOffset-1)}});}
 if(url.includes('alt=media')){mediaReads++;return new Response(original);}
 if(url.includes('/files/reserved-file?'))return remoteComplete?Response.json({id:'reserved-file',mimeType:'text/plain',size:String(original.length),trashed:false,ownedByMe:true,parents:['root'],appProperties:{lancerloginUpload:currentOp}}):new Response(null,{status:404});
 throw Error('unexpected synthetic provider route');};
 let loseAdmissionAck=true;const uncertainDB={prepare:sql=>db.prepare(sql),batch:async statements=>{const result=await db.batch(statements);if(loseAdmissionAck){loseAdmissionAck=false;throw Error('Synthetic lost admission acknowledgement');}return result;}};
 const env={DB:uncertainDB,APP_MODE:'configured',SESSION_KEY:secret,INTEGRATION_KEY:secret,ALLOWED_ORIGIN:'https://fixture.test',DOCUMENT_COMPUTE:compute};

 let seq=123456789012345700n;
 async function call(type,data,extra={}){const id=String(seq++),token='synthetic-'+id,pending=[];acknowledged=false;const response=await documentationFileDiscordInteraction(env,{id,token,type,data,application_id:config.applicationId,guild_id:config.guildId,member:{user:{id:user}},...extra},config,discord.iv,{waitUntil:p=>pending.push(p)});const b=await response.json();acknowledged=b.type===5;if(b.type===5){assert.equal(b.data.flags,64);await Promise.all(pending);return messages.get(token);}return b;}
 async function start(){const catalog=await call(2,{name:'activity-file'});assert.doesNotMatch(JSON.stringify(catalog),/PRIVATE/);const choice=catalog.components[0].components[0];const detail=await call(3,{custom_id:choice.custom_id,values:['0']});const modal=await call(3,{custom_id:find(detail,'Attach file').custom_id});assert.equal(modal.type,9);assert.equal(modal.data.components[0].type,18);assert.equal(modal.data.components[0].component.type,19);return modal;}
 const modal=await start();let message=await call(5,{custom_id:modal.data.custom_id,...source()});assert.match(message.content,/not confirmed saved/);let op=await db.prepare('SELECT * FROM documentation_upload_operations').first();assert.equal(op.source,'discord');assert.equal(op.author_member_id,'member1');currentOp=op.id;const frozenKey=op.key_hash;
 const stored=await db.prepare('SELECT * FROM discord_documentation_file_drafts').first();assert.doesNotMatch(JSON.stringify(stored),/cdn.discordapp|Synthetic file.txt|synthetic-123/);const decrypted=JSON.parse((await decryptIntegration(stored.ciphertext,stored.iv,secret)).payload);assert.equal(decrypted.admission.sha256,sha(original));
 // Replayed modal cannot replace the selected content or frozen key.
 message=await call(5,{custom_id:modal.data.custom_id,...source(1)});assert.equal((await db.prepare('SELECT COUNT(*) n FROM documentation_upload_operations').first()).n,1);assert.equal((await db.prepare('SELECT key_hash FROM documentation_upload_operations').first()).key_hash,frozenKey);
 const continuation=find(message,'Continue / check upload').custom_id;
 for(const extra of [{guild_id:'123456789012345699'},{application_id:'123456789012345699'},{member:{user:{id:'123456789012345699'}}},{member:undefined}]){const denied=await call(3,{custom_id:continuation},extra);assert.match(denied.content??denied.data.content,/unavailable/);}
 for(const [off,on] of [["UPDATE members SET active=0 WHERE id='member1'","UPDATE members SET active=1 WHERE id='member1'"],["UPDATE installations SET discord_enabled=0 WHERE id='primary'","UPDATE installations SET discord_enabled=1 WHERE id='primary'"],["UPDATE documentation_sections SET files_enabled=0","UPDATE documentation_sections SET files_enabled=1"]]){await db.prepare(off).run();const count=createCount;await call(3,{custom_id:continuation});assert.equal(createCount,count);await db.prepare(on).run();}
 loseAck=true;for(let i=0;i<18;i++){message=await call(3,{custom_id:continuation});op=await db.prepare('SELECT * FROM documentation_upload_operations').first();if(op.state==='saved')break;}
 assert.equal(op.state,'saved',JSON.stringify(op));assert.match(message.content,/saved privately and verified/);assert.equal(createCount,1);assert.equal(op.key_hash,frozenKey);assert.ok(cdnReads>=1);assert.equal((await db.prepare('SELECT COUNT(*) n FROM hours_entries').first()).n,0);assert.equal((await db.prepare('SELECT COUNT(*) n FROM documentation_notes').first()).n,0);
 const artifact=await db.prepare('SELECT * FROM documentation_artifacts').first();assert.equal(artifact.source,'discord');assert.equal(artifact.file_sha256,sha(original));assert.equal(artifact.author_member_id,'member1');
 const finalDraft=await db.prepare('SELECT * FROM discord_documentation_file_drafts').first();assert.equal(JSON.parse((await decryptIntegration(finalDraft.ciphertext,finalDraft.iv,secret)).payload).source,undefined);
 const signed={id:String(seq++),token:'synthetic-signed-file',type:2,application_id:config.applicationId,guild_id:config.guildId,member:{user:{id:user}},data:{name:'activity-file'}},raw=JSON.stringify(signed),timestamp=String(Math.floor(Date.now()/1000)),signature=sign(null,Buffer.from(timestamp+raw),keys.privateKey).toString('hex'),pending=[];
 const request=new Request('https://fixture.test/discord/interactions',{method:'POST',headers:{'x-signature-ed25519':signature,'x-signature-timestamp':timestamp},body:raw});assert.equal((await worker.fetch(request,env,{waitUntil:p=>pending.push(p)})).status,200);await Promise.all(pending);assert.ok(messages.has(signed.token));assert.equal((await worker.fetch(new Request('https://fixture.test/discord/interactions',{method:'POST',body:raw}),env)).status,401);
 const session=await createSessionCodec(secret).issue({userId:'admin',role:'admin'});const backupResponse=await worker.fetch(new Request('https://fixture.test/admin/data/backup?scope=installation',{headers:{cookie:'lancerlogin_session='+session}}),env);assert.equal(backupResponse.status,200);const backup=await backupResponse.json();assert.equal(backup.tables.discord_documentation_file_drafts,undefined);assert.equal(backup.tables.documentation_upload_operations[0].source,'discord');assert.doesNotMatch(JSON.stringify(backup),/cdn.discordapp|synthetic-123/);
 const restore=await worker.fetch(new Request('https://fixture.test/admin/data/restore',{method:'POST',headers:{cookie:'lancerlogin_session='+session,'content-type':'application/json'},body:JSON.stringify({scope:'installation',confirmation:'RESTORE INSTALLATION',backup})}),env);assert.equal(restore.status,200,await restore.clone().text());assert.equal((await db.prepare('SELECT COUNT(*) n FROM discord_documentation_file_drafts').first()).n,0);
 }finally{globalThis.fetch=oldFetch;await mf.dispose();}
});
test('file selection and bounded CDN bytes reject wrong identities, oversize and redirects',async()=>{
 for(const mutate of [d=>d.components[0].component.values.push('123456789012345682'),d=>d.resolved.attachments['123456789012345681'].id='123456789012345682',d=>d.resolved.attachments['123456789012345681'].size=4194305,d=>d.resolved.attachments['123456789012345681'].url='https://evil.invalid/a',d=>d.components[0].type=1]){const d=source();mutate(d);assert.throws(()=>selectedDocumentationFile(d));}
 assert.equal(selectedDocumentationFile(source(4194304)).size,4194304);const old=globalThis.fetch;try{for(const response of [new Response(null,{status:302,headers:{location:'https://evil.invalid'}}),new Response(new Uint8Array(3)),new Response(new Uint8Array(4),{headers:{'content-length':'3'}})]){globalThis.fetch=async()=>response;await assert.rejects(()=>downloadDocumentationFile(selectedDocumentationFile(source(4))));}}finally{globalThis.fetch=old;}
});
