import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {migrationStatements} from './migration-statements.mjs';
import {createSessionCodec} from '../apps/api/src/runtime-security.ts';
import {submitStaffHours,accountingRoute} from '../apps/api/src/hour-accounting.ts';
import {claimRoute,claimColumns} from '../apps/api/src/documentation-claims.ts';
import worker from '../apps/api/src/index.ts';
const secret='AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA';
test('claims preserve exact evidence and definition pins, independent review and portable provenance', {timeout:180000},async()=>{
 const mf=new Miniflare(convertV4MiniflareOptions({modules:true,script:'export default {fetch(){return new Response("fixture")}}',compatibilityDate:'2026-08-01',d1Databases:['DB']}));
 try{
  const db=await mf.getD1Database('DB'),directory=new URL('../apps/api/migrations/',import.meta.url);for(const name of readdirSync(directory).filter(n=>n.endsWith('.sql')).sort())await db.batch(migrationStatements(readFileSync(new URL(name,directory),'utf8')).map(s=>db.prepare(s)));
  await db.batch([
   db.prepare("INSERT INTO installations(id,created_at,auth_mode) VALUES('primary','2026-01-01','local'),('foreign','2026-01-01','local')"),
   db.prepare("INSERT INTO organization_settings(installation_id,organization_name,time_zone) VALUES('primary','Synthetic Team','UTC')"),
   db.prepare("INSERT INTO users(id,installation_id,local_username,role,created_at) VALUES('admin','primary','synthetic-admin','admin','2026-01-01'),('docs','primary','synthetic-docs','staff','2026-01-01'),('hours','primary','synthetic-hours','staff','2026-01-01'),('operator','primary','synthetic-operator','operator','2026-01-01')"),
   db.prepare("INSERT INTO platform_module_configuration VALUES('primary',1,1,1)"),
   db.prepare("INSERT INTO platform_module_grants VALUES('primary','docs',0,1),('primary','hours',1,0)"),
   db.prepare("INSERT INTO hours_categories(installation_id,id,name,mode,created_at,updated_at) VALUES('primary','event','Event','event','2026-01-01','2026-01-01')"),
   db.prepare("INSERT INTO hours_activities(installation_id,id,category_id,mode,service_date,title,description,planning_time_zone,impact_relevant,created_at,updated_at) VALUES('primary','activity','event','event','2026-01-19','Synthetic eligible activity','PRIVATE HOURS DESCRIPTION','UTC',1,'2026-01-01','2026-01-01'),('primary','unrelated','event','event','2026-01-19','Unrelated hours-only','PRIVATE UNRELATED','UTC',0,'2026-01-01','2026-01-01')"),
   db.prepare("INSERT INTO hours_entry_settings(installation_id) VALUES('primary')"),
   db.prepare("INSERT INTO members(id,installation_id,external_id,first_name,last_name,created_at) VALUES('member1','primary','00123','PRIVATE','ONE','2026-01-01'),('member2','primary','00456','PRIVATE','TWO','2026-01-01')")
  ]);
  const env={DB:db,APP_MODE:'configured',SESSION_KEY:secret,ALLOWED_ORIGIN:'https://fixture.test'};
  const call=async(path,input,user='docs',method=input?'POST':'GET')=>worker.fetch(new Request('https://fixture.test'+path,{method,headers:{cookie:'lancerlogin_session='+await createSessionCodec(secret).issue({userId:user,role:'admin'}),...(input?{'content-type':'application/json'}:{})},...(input?{body:JSON.stringify(input)}:{})}),env);
  const good=async(...args)=>{const r=await call(...args);assert.ok(r.ok,await r.clone().text());return r.json();};const base='/admin/documentation/claims',definitions='/admin/documentation/definitions';

  const definitionPayload={title:'Synthetic definition',definition:'Locally authored criterion, not an official rule.',source:'https://example.invalid/text-only'};
  const original=globalThis.fetch;let fetched=0;globalThis.fetch=async()=>{fetched++;throw Error('Metadata must not fetch providers');};
  try{
   assert.equal((await call(definitions,null,'operator')).status,403);assert.equal((await call(base,null,'hours')).status,403);assert.deepEqual((await good(definitions)).definitions,[]);
   let definition=(await good(definitions,definitionPayload)).definition;const firstDefinition=structuredClone(definition);definition=(await good(definitions+'/'+definition.id,{revision:0,definition:'New current criterion'},'docs','PATCH')).definition;
   const payload={title:'Synthetic claim',definitionId:definition.id,definitionRevision:0,periodStart:'2026-01-01',periodEnd:'2026-01-31'};
   for(const value of [{periodStart:'2026-02-30'},{periodEnd:'2025-12-31'},{definitionId:'foreign'},{definitionRevision:99}])assert.ok([400,409].includes((await call(base,{...payload,...value})).status));
   let claim=(await good(base,payload)).claim;let detail=await good(base+'/'+claim.id);assert.equal(detail.definition.definition,firstDefinition.definition);assert.equal(detail.dependencyChanged,true);assert.deepEqual(detail.incompleteness,{rationaleMissing:true,contextsMissing:true,evidenceMissing:true});
   const reviews=await Promise.all([call(base+'/'+claim.id+'/review',{revision:0,decision:'reviewed'}),call(base+'/'+claim.id+'/review',{revision:0,decision:'rejected'},'admin')]);assert.deepEqual(reviews.map(r=>r.status).sort(),[200,409]);detail=await good(base+'/'+claim.id);claim=detail.claim;assert.ok(claim.review);assert.equal(claim.review.reviewedRevision,0);assert.equal(detail.incompleteness.evidenceMissing,true);
   await db.prepare("INSERT INTO hours_teams(installation_id,id,name,number,organization,program,historical_descriptors,created_at,updated_at) VALUES('primary','team','Synthetic supported team','123','Synthetic organization','Synthetic program','PRIVATE HISTORICAL DESCRIPTORS','2026-01-01','2026-01-01')").run();
   await db.prepare("INSERT INTO hours_teams(installation_id,id,name,number,organization,program,historical_descriptors,created_at,updated_at) VALUES('foreign','foreign-team','Foreign synthetic team','','','','','2026-01-01','2026-01-01')").run();assert.equal((await call(base,{...payload,teams:[{teamId:'foreign-team',revision:0}]})).status,409);
   const teams=await good('/admin/documentation/teams');assert.equal(teams.teams[0].id,'team');assert.ok(!JSON.stringify(teams).includes('DESCRIPTORS'));assert.equal((await call('/admin/hours/teams',null,'docs')).status,403);
   const initiative=(await good('/admin/documentation/initiatives',{title:'Synthetic initiative'})).initiative;
   let artifact=(await good('/admin/documentation/artifacts',{title:'Synthetic artifact',caption:'Original caption',url:'https://example.invalid/original',sectionRevision:0})).artifact;
   artifact=(await good('/admin/documentation/artifacts/'+artifact.id,{revision:0,sectionRevision:0,caption:'Current caption'},'docs','PATCH')).artifact;
   let metric=(await good('/admin/documentation/metrics',{title:'Synthetic metric',kind:'participants',value:'1.2500',unit:'recorded interactions',periodStart:'2026-01-01',periodEnd:'2026-01-31',source:'Original source',method:'Original method',basis:'estimated'})).metric;
   metric=(await good('/admin/documentation/metrics/'+metric.id,{revision:0,value:'2.00'},'docs','PATCH')).metric;
   const associations={activities:[{activityId:'activity',revision:0}],teams:[{teamId:'team',revision:0}],initiatives:[{initiativeId:initiative.id,revision:0}],artifacts:[{artifactId:artifact.id,revision:0,currentRevision:1}],metrics:[{metricId:metric.id,revision:0,currentRevision:1}]};
   assert.equal((await call(base,{...payload,artifacts:[{artifactId:artifact.id,revision:0}]})).status,409);assert.equal((await call(base,{...payload,metrics:[{metricId:metric.id,revision:99,currentRevision:1}]})).status,409);assert.equal((await call(base,{...payload,activities:[associations.activities[0],associations.activities[0]]})).status,400);assert.equal((await call(base,{...payload,activities:[{activityId:'unrelated',revision:0}]})).status,409);
   claim=(await good(base+'/'+claim.id,{revision:claim.revision,...associations,rationale:'Private synthetic rationale'},'docs','PATCH')).claim;assert.equal(claim.review,null);detail=await good(base+'/'+claim.id);assert.equal(detail.artifacts[0].caption,'Original caption');assert.equal(detail.artifacts[0].selectedReview,null);assert.equal(detail.metrics[0].value,'1.2500');assert.equal(detail.metrics[0].basis,'estimated');assert.equal(detail.metrics[0].method,'Original method');assert.equal(detail.metrics[0].currentRevision,1);assert.deepEqual(detail.incompleteness,{rationaleMissing:false,contextsMissing:false,evidenceMissing:false});
   claim=(await good(base+'/'+claim.id+'/review',{revision:claim.revision,decision:'reviewed'})).claim;assert.equal(claim.review.decision,'reviewed');assert.equal((await good(base+'/'+claim.id)).artifacts[0].selectedReview,null);
   // Unrelated built-in sections do not gate manual claims or their explicit review.
   await good('/admin/documentation/sections',{version:1,revision:0,notesEnabled:false,summaryEnabled:false,filesEnabled:false},'admin','PUT');
   claim=(await good(base+'/'+claim.id+'/review',{revision:claim.revision,decision:'rejected'})).claim;
   // Every new association and authority change must be checked again in the mutation transaction.
   const attempts=[['grant',()=>db.prepare("UPDATE platform_module_grants SET documentation_manage=0 WHERE user_id='docs'").run(),()=>db.prepare("UPDATE platform_module_grants SET documentation_manage=1 WHERE user_id='docs'").run()],['module',()=>db.prepare('UPDATE platform_module_configuration SET documentation_enabled=0').run(),()=>db.prepare('UPDATE platform_module_configuration SET documentation_enabled=1').run()],['activity',()=>db.prepare("UPDATE hours_activities SET impact_relevant=0 WHERE id='activity'").run(),()=>db.prepare("UPDATE hours_activities SET impact_relevant=1 WHERE id='activity'").run()],['team',()=>db.prepare("UPDATE hours_teams SET archived=1 WHERE id='team'").run(),()=>db.prepare("UPDATE hours_teams SET archived=0 WHERE id='team'").run()],['initiative',()=>db.prepare('UPDATE documentation_initiatives SET archived=1 WHERE id=?').bind(initiative.id).run(),()=>db.prepare('UPDATE documentation_initiatives SET archived=0 WHERE id=?').bind(initiative.id).run()],['artifact',()=>db.prepare('UPDATE documentation_artifacts SET revision=revision+1 WHERE id=?').bind(artifact.id).run(),()=>db.prepare('UPDATE documentation_artifacts SET revision=1 WHERE id=?').bind(artifact.id).run()],['metric',()=>db.prepare('UPDATE documentation_metrics SET archived=1 WHERE id=?').bind(metric.id).run(),()=>db.prepare('UPDATE documentation_metrics SET archived=0 WHERE id=?').bind(metric.id).run()],['definition',()=>db.prepare('UPDATE documentation_definitions SET archived=1 WHERE id=?').bind(definition.id).run(),()=>db.prepare('UPDATE documentation_definitions SET archived=0 WHERE id=?').bind(definition.id).run()]];
   for(const [label,change,reset] of attempts){const before=(await db.prepare('SELECT COUNT(*) n FROM documentation_claims').first()).n;const raced={prepare:sql=>db.prepare(sql),async batch(statements){await change();return db.batch(statements);}};await assert.rejects(()=>claimRoute(raced,'primary','docs',new Request('https://fixture.test'+base,{method:'POST'}),{...payload,...associations}),e=>e.status===409,label);await reset();assert.equal((await db.prepare('SELECT COUNT(*) n FROM documentation_claims').first()).n,before,label);}
   const oldRevision=claim.revision;const edits=await Promise.all([call(base+'/'+claim.id,{revision:oldRevision,rationale:'First concurrent rationale'},'docs','PATCH'),call(base+'/'+claim.id,{revision:oldRevision,rationale:'Second concurrent rationale'},'admin','PATCH')]);assert.deepEqual(edits.map(r=>r.status).sort(),[200,409]);claim=(await good(base+'/'+claim.id)).claim;
   claim=(await good(base+'/'+claim.id+'/review',{revision:claim.revision,decision:'reviewed'})).claim;const retainedReview=structuredClone(claim.review);
   // Real target edits retain histories and make pinned dependencies visibly changed.
   await good('/admin/hours/activities/activity',{revision:0,impactRelevant:false},'admin','PATCH');await good('/admin/hours/teams/team',{revision:0,archived:true},'admin','PATCH');await good('/admin/documentation/initiatives/'+initiative.id,{revision:0,archived:true},'docs','PATCH');
   detail=await good(base+'/'+claim.id);assert.deepEqual(detail.claim.review,retainedReview);assert.equal(detail.activities[0].eligible,false);assert.equal(detail.teams[0].eligible,false);assert.equal(detail.initiatives[0].eligible,false);assert.equal(detail.dependencyChanged,true);claim=(await good(base+'/'+claim.id,{revision:claim.revision,rationale:'Retained evidence'},'docs','PATCH')).claim;
   claim=(await good(base+'/'+claim.id,{revision:claim.revision,archived:true},'docs','PATCH')).claim;assert.equal((await call(base+'/'+claim.id+'/review',{revision:claim.revision,decision:'reviewed'})).status,409);assert.equal((await call(base+'/'+claim.id,{revision:claim.revision,archived:false,rationale:'Not pure'},'docs','PATCH')).status,409);claim=(await good(base+'/'+claim.id,{revision:claim.revision,archived:false},'docs','PATCH')).claim;
   const history=await good(base+'/'+claim.id+'/history?limit=2');assert.equal(history.revisions.length,2);assert.equal(history.next,1);assert.equal(history.revisions[1].claim.review.reviewedRevision,0);assert.equal((await good(base+'?limit=1')).claims.length,1);
   definition=(await good(definitions+'/'+definition.id,{revision:definition.revision,archived:true},'docs','PATCH')).definition;assert.equal((await call(definitions+'/'+definition.id,{revision:definition.revision,title:'Blocked edit'},'docs','PATCH')).status,409);definition=(await good(definitions+'/'+definition.id,{revision:definition.revision,archived:false},'docs','PATCH')).definition;
   const definitionHistory=await good(definitions+'/'+definition.id+'/history');assert.equal(definitionHistory.revisions[0].definition,firstDefinition.definition);
   const audit=await db.prepare("SELECT metadata_json FROM audit_log WHERE action LIKE 'documentation.claim.%'").all();assert.ok(audit.results.every(r=>r.metadata_json===null||r.metadata_json==='{}'));assert.equal(fetched,0);
   const backup=await good('/admin/data/backup?scope=installation',undefined,'admin');assert.equal(backup.schemaVersion,28);
   const bads=[b=>b.tables.documentation_claim_revisions.pop(),b=>b.tables.documentation_claim_reviews.pop(),b=>b.tables.documentation_claim_revision_metrics[0].target_revision=99,b=>b.tables.documentation_claim_revision_artifacts[0].artifact_id='foreign',b=>b.tables.documentation_definition_revisions[0].actor_user_id='foreign',b=>b.tables.documentation_claim_reviews[0].reviewed_revision=9,b=>b.tables.documentation_claim_revision_teams.push({...b.tables.documentation_claim_revision_teams[0]}),b=>b.tables.documentation_claim_revisions[1].rationale='Changed reviewed content',b=>b.tables.documentation_claims[0].definition_revision=99];
   for(const corrupt of bads){const bad=structuredClone(backup);corrupt(bad);const result=await call('/admin/data/restore',{scope:'installation',confirmation:'RESTORE INSTALLATION',backup:bad},'admin');assert.equal(result.status,400,await result.text());assert.equal((await good(base+'/'+claim.id)).claim.revision,claim.revision);}
   const meetings=await good('/admin/data/backup?scope=meetings',undefined,'admin');await good('/admin/data/restore',{scope:'meetings',confirmation:'RESTORE MEETINGS',backup:meetings},'admin');assert.equal((await good(base+'/'+claim.id)).claim.revision,claim.revision);
   await good('/admin/data/restore',{scope:'installation',confirmation:'RESTORE INSTALLATION',backup},'admin');assert.equal((await good(base+'/'+claim.id)).metrics[0].value,'1.2500');assert.equal((await good(base+'/'+claim.id+'/history?limit=2')).revisions[1].claim.review.reviewedRevision,0);
   await db.prepare("UPDATE users SET active=0 WHERE id='docs'").run();assert.equal((await call(base)).status,401);assert.equal((await good(base+'/'+claim.id,undefined,'admin')).claim.authorUserId,'docs');
   const legacy=structuredClone(backup);legacy.schemaVersion=24;for(const table of Object.keys(claimColumns))delete legacy.tables[table];await good('/admin/data/restore',{scope:'installation',confirmation:'RESTORE INSTALLATION',backup:legacy},'admin');assert.deepEqual((await good(base)).claims,[]);assert.deepEqual((await db.prepare('PRAGMA foreign_key_check').all()).results,[]);
  }finally{globalThis.fetch=original;}
 }finally{await mf.dispose();}
});
