import test from 'node:test';
import assert from 'node:assert/strict';
import { controlFixture } from './fixtures/updater-control-fixture.mjs';
import { signedUpdaterRequest } from '../packages/shared/src/updater/service-auth.ts';
async function session(f,body){const grant=await f.call('control-grant',body);const response=await f.controls.fetch(new Request(f.origin+'/control/exchange',{method:'POST',headers:{origin:f.origin,'content-type':'application/json'},body:JSON.stringify({grant:grant.grant})}));assert.equal(response.status,200);const cookie=response.headers.get('set-cookie').split(';')[0];let state;return{grant,cookie,async call(action,payload,nonce=crypto.randomUUID()){const response=await f.controls.fetch(new Request(f.origin+'/control/'+action,{method:payload?'POST':'GET',headers:{cookie,origin:f.origin,...(payload?{'content-type':'application/json','x-control-csrf':state?.csrfToken??'','x-control-nonce':nonce}:{})},body:payload?JSON.stringify(payload):undefined}));const value=await response.json();if(response.ok)state=value;return{response,value};}};}
test('one-use controller follows exact signed admission through actual engine; final start requires original actor',async t=>{const f=await controlFixture(t);await f.call('check');await f.call('check');const body={requestId:crypto.randomUUID(),releaseId:2},s=await session(f,body);const writes=f.db.prepare('SELECT total_changes() n').get().n;assert.equal((await s.call('status')).value.job,null);assert.equal(f.db.prepare('SELECT total_changes() n').get().n,writes);assert.equal((await s.call('start',body)).response.status,409);assert.equal((await s.call('advance',{jobId:crypto.randomUUID()})).response.status,409);
const wrong=await signedUpdaterRequest({secret:f.secret,installationId:f.install,actorId:'other-admin',action:'start',body});assert.equal((await f.service.fetch(wrong)).status,409);assert.equal(f.db.prepare('SELECT count(*) n FROM updater_admissions').get().n,0);
const started=await f.call('start',body);const state=(await s.call('status')).value;assert.equal(state.job.id,started.job.id);assert.equal(state.admission.requestId,body.requestId);
assert.equal((await f.controls.fetch(new Request(f.origin+'/control/exchange',{method:'POST',headers:{origin:f.origin,'content-type':'application/json'},body:JSON.stringify({grant:s.grant.grant})}))).status,409);
await assert.rejects(f.call('control-grant',body));const nonce=crypto.randomUUID();assert.equal((await s.call('advance',{jobId:started.job.id},nonce)).response.status,200);assert.equal((await s.call('advance',{jobId:started.job.id},nonce)).response.status,409);
let result;for(let i=0;i<12;i++){result=await s.call('advance',{jobId:started.job.id});assert.equal(result.response.status,200);if(result.value.job.status==='succeeded')break;}assert.equal(result.value.job.status,'succeeded');const serialized=JSON.stringify(result.value);assert.ok(!serialized.includes(f.secret)&&!serialized.includes('manifestBytes'));
f.expire();assert.equal((await s.call('status')).response.status,401);});
test('atomic preadmission replacement revokes old session; CSRF/origin and unrelated jobs denied',async t=>{const f=await controlFixture(t);await f.call('check');await f.call('check');const body={requestId:crypto.randomUUID(),releaseId:2},old=await session(f,body);await old.call('status');const next=await session(f,body);assert.equal((await old.call('status')).response.status,401);await next.call('status');const bad=new Request(f.origin+'/control/advance',{method:'POST',headers:{cookie:next.cookie,origin:f.dashboardOrigin,'content-type':'application/json'},body:JSON.stringify({jobId:crypto.randomUUID()})});assert.equal((await f.controls.fetch(bad)).status,409);const started=await f.call('start',body);assert.equal((await next.call('advance',{jobId:crypto.randomUUID()})).response.status,409);
const row=await f.store.read();row.state.job.requestId=crypto.randomUUID();await f.store.replace(row.revision,row.state);assert.equal((await next.call('status')).response.status,401);assert.equal((await next.call('advance',{jobId:started.job.id})).response.status,401);assert.notEqual(row.state.job.requestId,body.requestId);});

test('cross-site navigation serves public shell only; authenticated control APIs retain site guard',async t=>{const f=await controlFixture(t);for(const path of ['/control','/control/status']){const response=await f.controls.fetch(new Request(f.origin+path,{headers:{'sec-fetch-site':'cross-site'}}));assert.equal(response.status,path==='/control'?200:409);} });
