import { createRecoveryProgress } from './recovery-progress.mjs';
export function controlPage(nonce,dashboardOrigin){return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Update controls</title><style nonce="${nonce}">:root{color-scheme:light dark;font:16px system-ui}body{margin:24px;line-height:1.5}main{max-width:720px;margin:auto}button{font:inherit;min-height:44px;padding:10px 16px;border-radius:8px}button:focus-visible,a:focus-visible{outline:3px solid #6750bf;outline-offset:3px}.actions{display:flex;align-items:center;flex-wrap:wrap;gap:8px}p{overflow-wrap:anywhere}@media(max-width:440px){body{margin:16px}.actions{display:grid}}</style></head><body><main><h1>Application update controls</h1><p>This controller works independently of the application. Keep it available until the update finishes.</p><p id="state" role="status">Authorize from Settings - Updates.</p><p id="expiry"></p><p id="notice" role="status"></p><div class="actions"><button id="refresh">Refresh status</button><button id="advance" disabled>Continue once</button><button id="auto" disabled>Continue automatically</button><button id="pause">Pause automatic progress</button><button id="retry" disabled>Retry preparation</button><button id="logout">Sign out</button></div><p><a href="/recovery">Open independent recovery</a></p></main><script nonce="${nonce}">
const parentOrigin=${JSON.stringify(dashboardOrigin)},parentWindow=window.opener,el=id=>document.getElementById(id);let state,expiryNotice='';
function text(id,value){if(el(id).textContent!==value)el(id).textContent=value;}
function show(value){state=value;text('state',value.job?value.job.status+': '+value.job.step+' / '+value.job.completedSteps+' of '+value.job.totalSteps+' steps':value.admission?.state==='rejected'?'Update request rejected. Return to Updates to choose again.':'Waiting for the original Admin to start this update.');el('advance').disabled=el('auto').disabled=!value.job||value.ended;el('retry').disabled=!value.job?.retryPreparationOperationId;el('expiry').textContent=value.expiresAt?'Controls expire at '+new Date(value.expiresAt*1000).toLocaleTimeString()+'. This session cannot be renewed.':'';}
async function call(action,body){const headers={};if(body!==undefined){headers['content-type']='application/json';headers['x-control-csrf']=state?.csrfToken??'';headers['x-control-nonce']=crypto.randomUUID()}const response=await fetch('/control/'+action,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers,body:body===undefined?undefined:JSON.stringify(body)});const value=await response.json();if(!response.ok){const error=Error(value.error);error.status=response.status;throw error;}return value;}
const progress=(${createRecoveryProgress.toString()})({read:()=>call('status'),advance:jobId=>call('advance',{jobId}),show,notice:value=>text('notice',value.replaceAll('Recovery sign-in','Control session').replaceAll('Sign in again','Use independent recovery'))});
async function command(action,body){if(action==='exchange'){try{await call('exchange',body)}catch{await progress.refresh()}await progress.refresh();return state;}if(action==='status'){await progress.refresh();return state;}if(!['advance','retry-preparation','logout'].includes(action))throw Error('Unsupported control');return progress.action(()=>call(action,body));}
window.addEventListener('message',async event=>{if(event.origin!==parentOrigin||event.source!==parentWindow||event.data?.type!=='ll-control-command'||typeof event.data.id!=='string')return;const id=event.data.id;try{const value={...await command(event.data.action,event.data.body)};delete value.csrfToken;parentWindow.postMessage({type:'ll-control-result',id,value},parentOrigin)}catch(error){parentWindow.postMessage({type:'ll-control-result',id,error:'Control response unavailable. Refresh before retrying.',ended:error.status===401},parentOrigin)}});
for(const[id,action]of [['refresh','status'],['advance','advance'],['retry','retry-preparation'],['logout','logout']])el(id).onclick=()=>{const body=action==='status'?undefined:action==='logout'?{}:action==='advance'?{jobId:state.job.id}:{jobId:state.job.id,failedOperationId:state.job.retryPreparationOperationId};void command(action,body).catch(error=>el('notice').textContent=error.message)};
el('auto').onclick=()=>progress.arm(state.job.id);el('pause').onclick=()=>progress.pause();document.addEventListener('visibilitychange',()=>progress.visibilityChanged());setInterval(()=>{if(state?.expiresAt&&Date.now()>=state.expiresAt*1000){if(expiryNotice!=='expired'){expiryNotice='expired';progress.pause('Control session expired. Use independent recovery to authenticate and continue.');}el('advance').disabled=el('auto').disabled=el('retry').disabled=true}else if(state?.expiresAt&&state.expiresAt*1000-Date.now()<120000&&expiryNotice!=='warning'){expiryNotice='warning';el('expiry').textContent='Controls expire within two minutes. Independent recovery requires a separate sign-in.'}},1000);if(parentWindow)parentWindow.postMessage({type:'ll-control-ready'},parentOrigin);void progress.refresh().catch(()=>{});
</script></body></html>`;}
