// Self-contained recovery page. No app assets, cookies, endpoints or third parties.
import { createRecoveryProgress } from './recovery-progress.mjs';
export function recoveryPage(nonce) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>LancerLogin recovery</title>
<style nonce="${nonce}">
:root{color-scheme:light dark;font:16px system-ui,sans-serif;background:#f4f6f8;color:#14202b}*{box-sizing:border-box}body{margin:0;padding:24px}main{max-width:780px;margin:auto}h1{font-size:2rem}h2{font-size:1.3rem}section{margin:20px 0;padding:20px;border:1px solid #b8c3cc;border-radius:12px;background:#fff}label{display:grid;gap:8px;margin:16px 0}input,button{font:inherit;min-height:44px;border:1px solid #687b8b;border-radius:8px;padding:10px 14px}input{width:100%;background:inherit;color:inherit}button{cursor:pointer;background:#e7edf2;color:#14202b}button:disabled{opacity:.55;cursor:default}button:focus-visible,input:focus-visible{outline:3px solid #6750bf;outline-offset:3px}.actions{display:flex;gap:12px;flex-wrap:wrap;align-items:center}.danger{border-color:#a32d31;color:#a32d31}.notice{white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.5}small{display:block;line-height:1.5}[hidden]{display:none!important}@media(prefers-color-scheme:dark){:root{background:#10161c;color:#e8eef3}section{background:#1a232b;border-color:#596b7b}button{background:#2b3945;color:#e8eef3}.danger{color:#ffb0b4;border-color:#ffb0b4}}@media(max-width:440px){body{padding:16px}section{padding:16px}.actions{display:grid}.actions button{width:100%}}
</style></head><body><main><h1>LancerLogin recovery</h1><p>This independent updater remains accessible when the application is unavailable.</p><p id="notice" class="notice" role="status" aria-live="polite"></p>
<p id="expiry" class="notice" role="status" aria-live="polite" hidden></p><section id="login"><h2>Recovery sign-in</h2><form id="login-form"><label>Recovery credential<input id="credential" type="password" autocomplete="off" required maxlength="64" aria-describedby="credential-help"></label><small id="credential-help">Use the separately provisioned 64-character recovery credential. It is never saved in browser storage.</small><button type="submit">Sign in to recovery</button></form></section>
<section id="workspace" hidden><div class="actions"><button id="refresh" type="button">Refresh status</button><button id="logout" type="button">Sign out</button></div><h2>Installed application</h2><p id="installed"></p><h2>Current job</h2><p id="job" class="notice"></p><div class="actions"><button id="advance" type="button" hidden>Continue automatically</button><button id="pause" type="button">Pause automatic progress</button><button id="retry" type="button" hidden>Retry failed preparation</button></div><p>Keep this page visible for automatic progress. Hiding it or pausing stops new steps without canceling the current operation. Sign-in expires after 15 minutes; sign in again to continue.</p>
<section id="recovery-options" hidden><h2>Recover the failed update</h2><p>Code recovery uses the captured prior release. Database restoration replaces application data with the verified retained backup. The updater still enforces its backup and write-quiescence requirements.</p><div class="actions"><button id="code" type="button">Recover previous code</button></div><label>Type RESTORE APPLICATION DATABASE to enable restoration<input id="confirmation" autocomplete="off"></label><div class="actions"><button id="restore" class="danger" type="button" disabled>Restore verified backup</button></div></section><p id="pending" class="notice" hidden>A recovery request is awaiting confirmation. Refresh status or retry the same saved request.</p></section></main>
<script nonce="${nonce}">const createRecoveryProgress=${createRecoveryProgress.toString()};const byId=id=>document.getElementById(id);let state=null,busy=false,sessionRejected=false;const pendingKey='lancerlogin-independent-recovery-request-v1';let pending=null;try{pending=JSON.parse(localStorage.getItem(pendingKey)||'null')}catch{};
function message(value){byId('notice').textContent=value}
function expiry(){const expired=progress.checkExpiry()||sessionRejected;const seconds=Number.isFinite(state?.expiresAt)?Math.ceil(state.expiresAt-Date.now()/1000):null;byId('expiry').hidden=!expired&&(seconds===null||seconds>60);const text=expired?'Sign-in has expired or reached its expiry time. The current job is retained. Sign in again, then select Continue automatically.':seconds!==null&&seconds<=60?'Sign-in expires within one minute. Automatic progress will pause; sign in again to continue.':'';if(byId('expiry').textContent!==text)byId('expiry').textContent=text;if(expired)byId('login').hidden=false;for(const id of ['advance','retry','code','restore'])byId(id).disabled=busy||expired||(id==='restore'&&byId('confirmation').value!=='RESTORE APPLICATION DATABASE');return expired}
function render(value){if(!value)return;state=value;sessionRejected=false;byId('login').hidden=true;byId('workspace').hidden=false;byId('installed').textContent=value.installedVersion+' · schema '+value.schema;const job=value.job;byId('job').textContent=job?job.status+': '+job.step+' · '+job.completedSteps+' of '+job.totalSteps+' steps complete'+(job.failure?' · '+job.failure:'')+(value.maintenance?' · Application '+value.maintenance.state:''):'No update job is recorded.';byId('advance').hidden=!job||(!['running','reconciling'].includes(job.status)&&!(['succeeded','recovered'].includes(job.status)&&value.maintenance&&value.maintenance.state!=='open'));byId('retry').hidden=!job?.retryPreparationOperationId;byId('recovery-options').hidden=!value.recoveryAvailable;if(pending&&(job?.requestId===pending.requestId||(value.recoveryRequest?.requestId===pending.requestId&&["accepted","rejected"].includes(value.recoveryRequest.state)))){if(value.recoveryRequest?.state==="rejected")message("The recovery request was rejected. Refresh status before choosing another recovery action.");pending=null;localStorage.removeItem(pendingKey)}byId('pending').hidden=!pending;byId('restore').disabled=busy||byId('confirmation').value!=='RESTORE APPLICATION DATABASE';expiry()}
async function call(action,body){const headers={};if(body!==undefined){headers['content-type']='application/json';if(state){headers['x-recovery-csrf']=state.csrfToken;headers['x-recovery-nonce']=crypto.randomUUID()}}const response=await fetch('/recovery/'+action,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers,body:body===undefined?undefined:JSON.stringify(body)});const value=await response.json();if(!response.ok){if(response.status===401){sessionRejected=true;progress.pause('Recovery sign-in expired. Sign in again, then explicitly continue this job.');expiry()}const error=Error(value.error||'Recovery request unavailable.');error.status=response.status;throw error}return value}
const progress=createRecoveryProgress({read:()=>call('status'),advance:jobId=>call('advance',{jobId}),show:render,notice:message});
async function refresh(){try{await progress.refresh()}catch(error){progress.pause(error.message)}}
async function act(action,body){if(busy)return;busy=true;document.querySelectorAll('button:not(#pause)').forEach(button=>button.disabled=true);message('');try{await progress.action(()=>call(action,body),value=>((action==='recovery'&&value.job?.requestId===body.requestId)||(action==='retry-preparation'&&value.job?.id===body.jobId))?value.job.id:null)}catch(error){progress.pause(error.message+' Refresh status before retrying.')}finally{busy=false;document.querySelectorAll('button').forEach(button=>button.disabled=false);expiry()}}
byId('login-form').addEventListener('submit',async event=>{event.preventDefault();if(busy)return;busy=true;const credential=byId('credential').value;byId('credential').value='';try{await progress.action(async()=>{await call('session',{credential});return call('status')});message('Signed in. Select Continue automatically to resume a job.')}catch(error){message(error.message)}finally{busy=false;expiry()}});
byId('refresh').onclick=()=>refresh();byId('logout').onclick=async()=>{if(busy)return;busy=true;try{await progress.action(async()=>{await call('logout',{});return null});state=null;byId('login').hidden=false;byId('workspace').hidden=true;byId('expiry').hidden=true;message('Signed out.')}catch(error){message(error.message)}finally{busy=false}};
byId('advance').onclick=()=>{if(!busy&&!expiry()&&state?.job)progress.arm(state.job.id)};byId('pause').onclick=()=>progress.pause();byId('retry').onclick=()=>act('retry-preparation',{jobId:state.job.id,failedOperationId:state.job.retryPreparationOperationId});
function recover(mode){if(!state?.job||expiry())return;if(pending&&(pending.failedJobId!==state.job.id||pending.mode!==mode)){message('A different recovery request is still awaiting confirmation. Refresh its status first.');return}if(!pending){pending={requestId:crypto.randomUUID(),failedJobId:state.job.id,mode};localStorage.setItem(pendingKey,JSON.stringify(pending))}byId('pending').hidden=false;act('recovery',{...pending,confirmation:mode==='restore'?byId('confirmation').value:'RECOVER APPLICATION CODE'})}
byId('code').onclick=()=>recover('code-recovery');byId('restore').onclick=()=>recover('restore');byId('confirmation').oninput=()=>expiry();setInterval(expiry,1000);document.addEventListener('visibilitychange',()=>progress.visibilityChanged());refresh();
</script></body></html>`;
}
