export type ArtifactFields={title:string;caption:string;url:string};
export type Review={decision:'reviewed'|'rejected';reviewedRevision:number;reviewerUserId:string;reviewedAt:string};
export type Artifact=ArtifactFields&{id:string;kind:'external-link'|'file'|'preserved-drive';originalUrl:string;revision:number;archived:boolean;authorUserId:string|null;file?:{id:string;rootId:string;generation:string;sha256:string;byteLength:number;mime:string;validationOutcome:'embedded'|'linked-only'};preservedDrive?:{id:string;rootId:string;generation:string;mime:string;sourceId:string;sourceVersion:string;copiedAt:string;byteLength?:number;sha256?:string;validation:{outcome:'native'|'embedded'|'linked-only'}};contributor?:{kind:'member'|'staff';source:'public'|'staff'|'discord'};createdAt:string;updatedAt:string;review:Review|null};
export type ContextKind='activities'|'initiatives';
export type ArtifactContext={activityId?:string;initiativeId?:string;title:string;revision:number;eligible:boolean};
export type ArtifactDetail={artifact:Artifact;activities:ArtifactContext[];initiatives:ArtifactContext[];readOnly:boolean;filesEnabled:boolean;sectionRevision:number};
export type Selection={id:string;type:ContextKind;title:string;revision:number;eligible:boolean};
export type Sections={version:1;revision:number;notesEnabled:boolean;summaryEnabled:boolean;filesEnabled:boolean};
export const emptyArtifact:ArtifactFields={title:'',caption:'',url:''};
export const artifactFields=(value:ArtifactFields):ArtifactFields=>({title:value.title,caption:value.caption,url:value.url});
export function validUrl(value:unknown):value is string{if(typeof value!=='string'||value.length>2048||/[\s\u0000-\u001f\u007f]/.test(value))return false;try{const url=new URL(value);return url.protocol==='https:'&&!url.username&&!url.password;}catch{return false;}}
export function artifactErrors(value:ArtifactFields):Partial<Record<keyof ArtifactFields,string>>{const errors:Partial<Record<keyof ArtifactFields,string>>={};for(const [key,max] of [['title',200],['caption',4000]] as const)if(typeof value[key]!=='string'||value[key].length>max||key==='title'&&!value[key].trim()||/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(value[key]))errors[key]=`Enter plain text, maximum ${max} characters.`;if(!validUrl(value.url))errors.url='Enter an HTTPS URL without spaces or embedded credentials, maximum 2048 characters.';return errors;}
export function checkedSections(value:Sections){if(!value||value.version!==1||!Number.isSafeInteger(value.revision)||['notesEnabled','summaryEnabled','filesEnabled'].some(key=>typeof value[key as keyof Sections]!=='boolean'))throw Error('Invalid sections');return value;}
export function selections(detail:ArtifactDetail):Selection[]{return (['activities','initiatives'] as const).flatMap(type=>detail[type].map(link=>({id:(type==='activities'?link.activityId:link.initiativeId)!,type,title:link.title,revision:link.revision,eligible:link.eligible})));}
export function checkedArtifact(value:Artifact):Artifact{if(!value||typeof value.id!=='string'||!['external-link','file','preserved-drive'].includes(value.kind)||!Number.isSafeInteger(value.revision)||value.revision<0||typeof value.archived!=='boolean'||!validUrl(value.originalUrl)||Object.keys(artifactErrors(value)).length||value.review!==null&&(!value.review||!['reviewed','rejected'].includes(value.review.decision)||!Number.isSafeInteger(value.review.reviewedRevision)||value.review.reviewedRevision!==value.revision-1||typeof value.review.reviewerUserId!=='string'||typeof value.review.reviewedAt!=='string'))throw Error('Invalid artifact');if(value.kind==='file'&&(!value.file||typeof value.file.id!=='string'||!Number.isSafeInteger(value.file.byteLength)||value.file.byteLength<1||value.file.byteLength>4194304||!/^[a-f0-9]{64}$/.test(value.file.sha256)||typeof value.file.mime!=='string'||!['embedded','linked-only'].includes(value.file.validationOutcome)||value.originalUrl!=='https://drive.google.com/file/d/'+value.file.id+'/view'||value.url!==value.originalUrl))throw Error('Invalid original file');if(value.kind==='preserved-drive'){const p=value.preservedDrive;if(!p||['id','rootId','generation','mime','sourceId','sourceVersion','copiedAt'].some(k=>typeof p[k as keyof typeof p]!=='string')||!p.validation||!['native','embedded','linked-only'].includes(p.validation.outcome)||value.url!==value.originalUrl)throw Error('Invalid preserved copy');if(p.validation.outcome==='native'?(p.byteLength!==undefined||p.sha256!==undefined):(!Number.isSafeInteger(p.byteLength)||!p.byteLength||p.byteLength>4194304||! /^[a-f0-9]{64}$/.test(p.sha256??'')))throw Error('Invalid preserved validation');}return value;}
export function checkedDetail(value:ArtifactDetail){checkedArtifact(value?.artifact);for(const type of ['activities','initiatives'] as const){if(!Array.isArray(value[type])||value[type].some(link=>typeof (type==='activities'?link.activityId:link.initiativeId)!=='string'||typeof link.title!=='string'||!Number.isSafeInteger(link.revision)||typeof link.eligible!=='boolean'))throw Error('Invalid associations');}if(value.activities.length+value.initiatives.length>100||typeof value.filesEnabled!=='boolean'||!Number.isSafeInteger(value.sectionRevision))throw Error('Invalid detail');return value;}
