import { FormEvent, useEffect, useState } from "react";

const apiBaseUrl = (import.meta.env.VITE_API_BASE_URL as string | undefined)?.replace(/\/$/, "") ?? "";
type Meeting = { id: string; title: string; startsAt: string; endsAt?: string; required: boolean | number };
type AttendanceRow = { memberId: string; externalId: string; firstName: string; lastName: string; discordUserId?: string; disposition: "present" | "absent" | "excused"; occurredAt?: string; reason?: string };
type Kiosk = { id: string; name: string; active: number; lastSeenAt?: string; pairedAt: string };
type Contest = { meetingId: string; memberId: string; externalId: string; firstName: string; lastName: string; status: "open" | "approved" | "rejected" | "reviewed"; createdAt: string; resolvedAt?: string };
async function api<T>(path: string, init?: RequestInit): Promise<T> { const result = await fetch(`${apiBaseUrl}${path}`, { credentials: "include", ...init, headers: { ...(init?.body ? { "content-type": "application/json" } : {}), ...init?.headers } }); const body = await result.json() as T & { error?: string; details?: string[] }; if (!result.ok) throw new Error(body.details?.join(" ") ?? body.error ?? "Request failed"); return body; }

export function AttendanceWorkspace({ embedded = false, onSignedOut }: { embedded?: boolean; onSignedOut?: () => void }) {
  const [meetings, setMeetings] = useState<Meeting[]>([]); const [selected, setSelected] = useState(""); const [rows, setRows] = useState<AttendanceRow[]>([]); const [kiosks, setKiosks] = useState<Kiosk[]>([]); const [contests, setContests] = useState<Contest[]>([]);
  const [title, setTitle] = useState(""); const [startsAt, setStartsAt] = useState(new Date(Date.now() + 3_600_000).toISOString().slice(0, 16)); const [notice, setNotice] = useState("Loading meetings…");
  async function refreshMeetings() { const result = await api<{ meetings: Meeting[] }>("/meetings"); setMeetings(result.meetings); if (!selected && result.meetings[0]) setSelected(result.meetings[0].id); setNotice(result.meetings.length ? "Meeting data is current." : "Create your first meeting."); }
  async function refreshKiosks() { const result = await api<{ kiosks: Kiosk[] }>("/admin/kiosks"); setKiosks(result.kiosks); }
  async function refreshAttendance(meetingId = selected) { if (!meetingId) { setRows([]); setContests([]); return; } const [attendance, contestResult] = await Promise.all([api<{ attendance: AttendanceRow[] }>(`/attendance?meetingId=${encodeURIComponent(meetingId)}`), api<{ contests: Contest[] }>(`/discord/contests?meetingId=${encodeURIComponent(meetingId)}`)]); setRows(attendance.attendance); setContests(contestResult.contests); }
  useEffect(() => { Promise.all([refreshMeetings(), refreshKiosks()]).catch((error: Error) => setNotice(error.message)); const timer = window.setInterval(() => void refreshKiosks().catch(() => undefined), 30_000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { refreshAttendance().catch((error: Error) => setNotice(error.message)); }, [selected]);
  async function createMeeting(event: FormEvent) { event.preventDefault(); setNotice("Creating meeting…"); try { const result = await api<{ meeting: Meeting }>("/meetings", { method: "POST", body: JSON.stringify({ title, startsAt: new Date(startsAt).toISOString(), required: true }) }); setTitle(""); await refreshMeetings(); setSelected(result.meeting.id); setNotice("Meeting created."); } catch (error) { setNotice((error as Error).message); } }
  async function editMeeting() { const meeting = meetings.find((item) => item.id === selected); if (!meeting) return; const nextTitle = window.prompt("Meeting title", meeting.title); if (!nextTitle) return; const nextStart = window.prompt("Meeting start (ISO date and time)", meeting.startsAt); if (!nextStart) return; try { await api(`/meetings/${encodeURIComponent(meeting.id)}`, { method: "PATCH", body: JSON.stringify({ title: nextTitle, startsAt: new Date(nextStart).toISOString(), endsAt: meeting.endsAt ?? null, required: Boolean(meeting.required) }) }); await refreshMeetings(); setNotice("Meeting details updated and audited."); } catch (error) { setNotice((error as Error).message); } }
  async function correct(row: AttendanceRow, disposition: AttendanceRow["disposition"]) { const reason = window.prompt(`Reason for marking ${row.firstName} ${disposition}:`); if (!reason) return; try { await api("/attendance/corrections", { method: "POST", body: JSON.stringify({ memberId: row.memberId, meetingId: selected, disposition, reason }) }); await refreshAttendance(); setNotice("Attendance correction saved and audited."); } catch (error) { setNotice((error as Error).message); } }
  async function email(row: AttendanceRow, kind: "missed-meeting" | "individual-report") { try { await api("/communications/email", { method: "POST", body: JSON.stringify({ kind, memberId: row.memberId, meetingId: selected }) }); setNotice(kind === "missed-meeting" ? "Missed-meeting email sent." : "Individual attendance report sent."); } catch (error) { setNotice((error as Error).message); } }
  async function linkDiscord(row: AttendanceRow) { const discordUserId = window.prompt(`Discord user ID for ${row.firstName} ${row.lastName}. Leave blank to unlink.`, row.discordUserId ?? ""); if (discordUserId === null) return; try { await api("/discord/link", { method: "POST", body: JSON.stringify({ memberId: row.memberId, discordUserId: discordUserId.trim() || null }) }); await refreshAttendance(); setNotice(discordUserId.trim() ? "Discord member link saved and audited." : "Discord member link removed and audited."); } catch (error) { setNotice((error as Error).message); } }
  async function resolveContest(contest: Contest, resolution: Contest["status"]) { try { await api("/discord/contests/resolve", { method: "POST", body: JSON.stringify({ meetingId: contest.meetingId, memberId: contest.memberId, resolution }) }); await refreshAttendance(); setNotice("Discord attendance contest resolved and audited."); } catch (error) { setNotice((error as Error).message); } }
  async function signOut() { await api("/auth/logout", { method: "POST" }); onSignedOut?.(); }
  async function downloadCsv() { const result = await fetch(`${apiBaseUrl}/exports/attendance.csv`, { credentials: "include" }); if (!result.ok) { setNotice("CSV export failed."); return; } const blob = await result.blob(); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `lancerlogin-attendance-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(link.href); }
  async function discord(path: "missing" | "calendar" | "kiosk-status") { try { await api(`/discord/${path}`, { method: "POST", body: JSON.stringify(path === "kiosk-status" ? {} : { meetingId: selected }) }); setNotice(path === "missing" ? "Discord missing-member notice posted and contests opened." : path === "calendar" ? "Discord calendar event synchronized." : "Persistent Discord kiosk status updated."); } catch (error) { setNotice((error as Error).message); } }
  const activeKiosk = kiosks.find((kiosk) => kiosk.active === 1); const kioskOnline = Boolean(activeKiosk?.lastSeenAt && Date.now() - Date.parse(activeKiosk.lastSeenAt) < 90_000);
  return <section className={embedded ? "attendance-workspace embedded" : "attendance-workspace"}>
    {!embedded && <header className="workspace-header"><div><p className="kicker">Operator workspace</p><h1>Meetings & attendance</h1></div><button className="theme-button" type="button" onClick={signOut}>Sign out</button></header>}
    <div className="setup-status" role="status"><span>{notice}</span><span className="toolbar-actions"><button className="text-button" type="button" onClick={downloadCsv}>Export CSV</button><button className="text-button" type="button" onClick={() => discord("kiosk-status")}>Sync kiosk status</button></span></div>
    <section className="kiosk-monitor" aria-labelledby="kiosk-monitor-title"><div><p className="kicker">Kiosk status</p><h2 id="kiosk-monitor-title">{activeKiosk?.name ?? "No kiosk paired"}</h2></div><span className={kioskOnline ? "online" : "offline"}>{kioskOnline ? "Online" : activeKiosk ? "Offline" : "Not paired"}</span><p>{activeKiosk?.lastSeenAt ? `Last heartbeat ${new Date(activeKiosk.lastSeenAt).toLocaleString()}` : "Pair one kiosk from Admin setup. Status refreshes every 30 seconds."}</p></section>
    <div className="attendance-layout"><form className="task-card" onSubmit={createMeeting}><p className="kicker">Meetings</p><h2>Create meeting</h2><label>Title<input required maxLength={120} value={title} onChange={(event) => setTitle(event.target.value)} /></label><label>Starts<input required type="datetime-local" value={startsAt} onChange={(event) => setStartsAt(event.target.value)} /></label><button className="primary-button" type="submit">Create meeting</button><label>View meeting<select value={selected} onChange={(event) => setSelected(event.target.value)}><option value="">Choose a meeting</option>{meetings.map((meeting) => <option key={meeting.id} value={meeting.id}>{meeting.title} · {new Date(meeting.startsAt).toLocaleString()}</option>)}</select></label>{selected && <p className="meeting-id"><span>Kiosk meeting ID</span><code>{selected}</code><button type="button" onClick={() => void navigator.clipboard.writeText(selected).then(() => setNotice("Meeting ID copied for kiosk setup."), () => setNotice("Copy the displayed meeting ID into the kiosk setup screen."))}>Copy ID</button></p>}<div className="meeting-actions"><button type="button" disabled={!selected} onClick={editMeeting}>Edit selected</button><button type="button" disabled={!selected} onClick={() => discord("calendar")}>Sync Discord calendar</button><button type="button" disabled={!selected} onClick={() => discord("missing")}>Ping linked missing members</button></div></form>
      <section className="attendance-card"><div className="panel-heading"><div><p className="kicker">Attendance</p><h2>{meetings.find((meeting) => meeting.id === selected)?.title ?? "Choose a meeting"}</h2></div><span className="progress-count">{rows.filter((row) => row.disposition === "present").length} present</span></div>{rows.length ? <div className="attendance-table" role="table" aria-label="Meeting attendance"><div className="attendance-row header" role="row"><span>Member</span><span>Status</span><span>Actions</span></div>{rows.map((row) => <div className="attendance-row" role="row" key={row.memberId}><span><strong>{row.firstName} {row.lastName}</strong><small>{row.externalId}{row.discordUserId ? ` · Discord ${row.discordUserId}` : ""}</small></span><span className={`attendance-state ${row.disposition}`}>{row.disposition}</span><span className="correction-actions"><button type="button" onClick={() => correct(row, "present")}>Present</button><button type="button" onClick={() => correct(row, "excused")}>Excuse</button><button type="button" onClick={() => correct(row, "absent")}>Absent</button><button type="button" onClick={() => linkDiscord(row)}>{row.discordUserId ? "Edit Discord" : "Link Discord"}</button>{row.disposition === "absent" && <button type="button" onClick={() => email(row, "missed-meeting")}>Email missed</button>}<button type="button" onClick={() => email(row, "individual-report")}>Email report</button></span></div>)}</div> : <p className="empty-state">{selected ? "No active roster records are available." : "Choose or create a meeting to view attendance."}</p>}</section></div>
    {contests.length > 0 && <section className="contest-card" aria-labelledby="contest-title"><div className="panel-heading"><div><p className="kicker">Discord attendance review</p><h2 id="contest-title">Missing-member contests</h2></div><span className="progress-count">{contests.filter((contest) => contest.status === "open").length} open</span></div><div className="contest-list">{contests.map((contest) => <article key={contest.memberId}><div><strong>{contest.firstName} {contest.lastName}</strong><span>{contest.externalId} · {contest.status}</span></div>{contest.status === "open" && <div><button type="button" onClick={() => resolveContest(contest, "approved")}>Approve</button><button type="button" onClick={() => resolveContest(contest, "rejected")}>Reject</button><button type="button" onClick={() => resolveContest(contest, "reviewed")}>Mark reviewed</button></div>}</article>)}</div></section>}
  </section>;
}
