import { useEffect, useState, type FormEvent } from "react";
import { api } from "./dashboard-api";
import { MeetingWeightSettings } from "./meeting-weight-settings";
import { DiscordLabelRoleSettings } from "./discord-label-role-settings";

type Label = { id: string; name: string; active: boolean | number };
type Rule = { id?: string; labelId: string; startsOn: string | null; endsOn: string | null; ruleType: "weighted_percentage" | "weekly_count"; thresholdPercent: number | null; meetingsPerWeek: number | null };
type PolicyData = { labels: Label[]; rules: Rule[]; recentDays: number };
type Mutation = { rule?: Rule; removeRuleId?: string; recentDays?: number };
type Preview = { impact: { memberId: string; before: { status: string; rate: number | null }; after: { status: string; rate: number | null }; beforeHistoricalRate: number | null; afterHistoricalRate: number | null }[]; previewToken: string };

export function AttendanceSettings({ role }: { role: "admin" | "operator" }) {
  const [data, setData] = useState<PolicyData>();
  const [name, setName] = useState("");
  const [rule, setRule] = useState<Rule>({ labelId: "", startsOn: null, endsOn: null, ruleType: "weighted_percentage", thresholdPercent: 80, meetingsPerWeek: null });
  const [windowDays, setWindowDays] = useState(30);
  const [pending, setPending] = useState<Mutation>();
  const [preview, setPreview] = useState<Preview>();
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState("");
  async function load() { const result = await api<PolicyData>("/attendance/policy"); setData(result); setWindowDays(result.recentDays); }
  useEffect(() => { void load().catch((error: Error) => setNotice(error.message)); }, []);
  async function createLabel(event: FormEvent) { event.preventDefault(); setBusy(true); try { await api("/labels", { method: "POST", body: JSON.stringify({ name }) }); setName(""); await load(); setNotice("Label created."); } catch (error) { setNotice((error as Error).message); } finally { setBusy(false); } }
  async function retire(label: Label) { setBusy(true); try { await api("/labels/" + encodeURIComponent(label.id), { method: "PATCH", body: JSON.stringify({ active: !label.active }) }); await load(); setNotice(label.active ? "Label retired. History is preserved." : "Label restored."); } catch (error) { setNotice((error as Error).message); } finally { setBusy(false); } }
  async function prepare(change: Mutation) { setBusy(true); setNotice(""); try { const result = await api<Preview>("/attendance/policy/preview", { method: "POST", body: JSON.stringify(change) }); setPending(change); setPreview(result); } catch (error) { setNotice((error as Error).message); } finally { setBusy(false); } }
  async function apply() { if (!pending || !preview) return; setBusy(true); try { await api("/attendance/policy/apply", { method: "POST", body: JSON.stringify({ ...pending, previewToken: preview.previewToken }) }); setPreview(undefined); setPending(undefined); await load(); setNotice("Attendance policy saved."); } catch (error) { setPreview(undefined); setNotice((error as Error).message); } finally { setBusy(false); } }
  function saveRule(event: FormEvent) { event.preventDefault(); void prepare({ rule: { ...rule, startsOn: rule.startsOn || null, endsOn: rule.endsOn || null, thresholdPercent: rule.ruleType === "weighted_percentage" ? Number(rule.thresholdPercent) : null, meetingsPerWeek: rule.ruleType === "weekly_count" ? Number(rule.meetingsPerWeek) : null } }); }
  if (role === "operator") return <section className="settings-page settings-attendance" aria-labelledby="attendance-settings-title"><div className="page-intro"><h1 id="attendance-settings-title">Attendance</h1><p>View member labels, attendance rules, and Discord role sync status.</p></div>{notice && <p className="ui-status" role="status">{notice}</p>}<section className="task-card ui-card member-labels-panel" aria-labelledby="settings-labels-title"><h2 id="settings-labels-title">Member labels</h2><ul className="compact-list label-period-list">{data?.labels.map((label) => <li key={label.id}>{label.name}{label.active ? "" : " · retired"}</li>)}</ul></section><section className="task-card ui-card member-labels-panel" aria-labelledby="settings-rules-title"><h2 id="settings-rules-title">Attendance requirements</h2><ul className="compact-list label-period-list">{data?.rules.map((item) => <li key={item.id}>{data.labels.find((label) => label.id === item.labelId)?.name ?? "Label"}: {item.startsOn ? item.startsOn + " to " + (item.endsOn ?? "ongoing") : "Standing"} · {item.ruleType === "weighted_percentage" ? item.thresholdPercent + "% weighted" : item.meetingsPerWeek + " per week"}</li>)}</ul></section><DiscordLabelRoleSettings role={role} /></section>;
  return <section className="settings-page settings-attendance" aria-labelledby="attendance-settings-title"><div className="page-intro"><h1 id="attendance-settings-title">Attendance</h1><p>Define member labels and attendance rules. Assign labels on member profiles in Roster. Admin and Operator access stays separate.</p></div>
    {notice && <p className="ui-status" role="status">{notice}</p>}
    <section className="task-card ui-card member-labels-panel" aria-labelledby="settings-labels-title"><h2 id="settings-labels-title">Member labels</h2><p>Members can hold overlapping labels, with at most one policy label at a time.</p>
      <form className="form-grid" onSubmit={(event) => void createLabel(event)}><label>New label name<input required maxLength={80} value={name} onChange={(event) => setName(event.target.value)} /></label><button className="ui-button ui-button--primary" type="submit" disabled={busy}>Create label</button></form>
      {data?.labels.length ? <ul className="compact-list label-period-list">{data.labels.map((label) => <li key={label.id}><span><strong>{label.name}</strong>{data.rules.some((item) => item.labelId === label.id) ? " · attendance policy" : ""}{label.active ? "" : " · retired"}</span><button className={"ui-button" + (label.active ? " ui-button--danger" : "")} type="button" disabled={busy} onClick={() => void retire(label)}>{label.active ? "Retire" : "Restore"}</button></li>)}</ul> : <p>No labels are configured.</p>}
    </section>
    <DiscordLabelRoleSettings role={role} />
    <section className="task-card ui-card member-labels-panel" aria-labelledby="settings-rules-title"><h2 id="settings-rules-title">Attendance requirements</h2><p>Choose a standing rule or a dated override. Dated overrides on a label cannot overlap. Percentage rules use saved meeting weights; weekly rules count meetings once each.</p>
      <form className="form-grid" onSubmit={saveRule}><label>Policy label<select required value={rule.labelId} onChange={(event) => setRule({ ...rule, id: undefined, labelId: event.target.value })}><option value="">Choose label</option>{data?.labels.filter((label) => label.active).map((label) => <option key={label.id} value={label.id}>{label.name}</option>)}</select></label>
        <label>Rule type<select value={rule.ruleType} onChange={(event) => setRule({ ...rule, ruleType: event.target.value as Rule["ruleType"], thresholdPercent: event.target.value === "weighted_percentage" ? 80 : null, meetingsPerWeek: event.target.value === "weekly_count" ? 1 : null })}><option value="weighted_percentage">Weighted percentage</option><option value="weekly_count">Meetings per week</option></select></label>
        <label>Starts on <span>(blank for standing rule)</span><input type="date" value={rule.startsOn ?? ""} onChange={(event) => setRule({ ...rule, startsOn: event.target.value || null })} /></label><label>Ends on <span>(optional)</span><input type="date" min={rule.startsOn ?? undefined} value={rule.endsOn ?? ""} disabled={!rule.startsOn} onChange={(event) => setRule({ ...rule, endsOn: event.target.value || null })} /></label>
        {rule.ruleType === "weighted_percentage" ? <label>Required attendance (%)<input required type="number" min="0.01" max="100" step="0.01" value={rule.thresholdPercent ?? ""} onChange={(event) => setRule({ ...rule, thresholdPercent: Number(event.target.value) })} /></label> : <label>Meetings per week<input required type="number" min="1" max="100" step="1" value={rule.meetingsPerWeek ?? ""} onChange={(event) => setRule({ ...rule, meetingsPerWeek: Number(event.target.value) })} /></label>}
        <button className="ui-button ui-button--primary" type="submit" disabled={busy}>{rule.id ? "Preview rule update" : "Preview new rule"}</button>{rule.id && <button className="ui-button" type="button" onClick={() => setRule({ labelId: "", startsOn: null, endsOn: null, ruleType: "weighted_percentage", thresholdPercent: 80, meetingsPerWeek: null })}>Cancel edit</button>}</form>
      {data?.rules.length ? <ul className="compact-list label-period-list">{data.rules.map((item) => <li key={item.id}><span>{data.labels.find((label) => label.id === item.labelId)?.name ?? "Label"}: {item.startsOn ? item.startsOn + " to " + (item.endsOn ?? "ongoing") : "Standing"} · {item.ruleType === "weighted_percentage" ? item.thresholdPercent + "% weighted" : item.meetingsPerWeek + " per week"}</span><div className="dialog-actions"><button className="ui-button" type="button" disabled={busy} onClick={() => setRule(item)}>Edit</button><button className="ui-button ui-button--danger" type="button" disabled={busy} onClick={() => void prepare({ removeRuleId: item.id })}>Preview removal</button></div></li>)}</ul> : <p>No attendance requirements are configured.</p>}
    </section>
    <section className="task-card ui-card member-labels-panel" aria-labelledby="recent-window-title"><h2 id="recent-window-title">Current percentage window</h2><p>Official percentage compliance uses completed, required meetings within the latest calendar days. Historical summaries remain available separately.</p><form className="form-grid" onSubmit={(event) => { event.preventDefault(); void prepare({ recentDays: windowDays }); }}><label>Recent days<input required type="number" min="1" max="365" step="1" value={windowDays} onChange={(event) => setWindowDays(Number(event.target.value))} /></label><button className="ui-button ui-button--primary" type="submit" disabled={busy}>Preview window change</button></form></section>
    {preview && <section className="task-card ui-card member-labels-panel" aria-labelledby="policy-preview-title"><h2 id="policy-preview-title">Review historical impact</h2><p>{preview.impact.length} member records change. Confirm to apply this policy change and record its audit entry.</p>{preview.impact.length > 0 && <ul className="compact-list">{preview.impact.map((item) => <li key={item.memberId}>{item.memberId}: {item.before.status} ({item.before.rate ?? "N/A"}) to {item.after.status} ({item.after.rate ?? "N/A"}); history {item.beforeHistoricalRate ?? "N/A"} to {item.afterHistoricalRate ?? "N/A"}</li>)}</ul>}<div className="dialog-actions"><button className="ui-button" type="button" onClick={() => setPreview(undefined)}>Back</button><button className="ui-button ui-button--primary" type="button" disabled={busy} onClick={() => void apply()}>Apply attendance policy</button></div></section>}
    <MeetingWeightSettings />
  </section>;
}
