import { useEffect, useState } from "react";

const apiBaseUrl = (import.meta.env.VITE_API_BASE_URL as string | undefined)?.replace(/\/$/, "") ?? "";
type Meeting = { id: string; title: string; startsAt: string; endsAt?: string | null; required: boolean | number; notes?: string | null };
type AttendanceRow = { memberId: string; externalId: string; firstName: string; lastName: string; discordUserId?: string; disposition: "present" | "active" | "absent" | "excused"; checkedInAt?: string; checkedOutAt?: string; reason?: string };
type Kiosk = { id: string; name: string; active: number; lastSeenAt?: string; readerOnline?: number; releaseVersion?: string; pairedAt: string };
type Contest = { meetingId: string; memberId: string; externalId: string; firstName: string; lastName: string; status: "open" | "approved" | "rejected" | "reviewed"; createdAt: string; resolvedAt?: string };
async function api<T>(path: string, init?: RequestInit): Promise<T> { const result = await fetch(`${apiBaseUrl}${path}`, { credentials: "include", ...init, headers: { ...(init?.body ? { "content-type": "application/json" } : {}), ...init?.headers } }); const body = await result.json() as T & { error?: string; details?: string[] }; if (!result.ok) throw new Error(body.details?.join(" ") ?? body.error ?? "Request failed"); return body; }

export function AttendanceWorkspace({ embedded = false, onSignedOut }: { embedded?: boolean; onSignedOut?: () => void }) {
  const [meetings, setMeetings] = useState<Meeting[]>([]); const [selected, setSelected] = useState(""); const [rows, setRows] = useState<AttendanceRow[]>([]); const [kiosks, setKiosks] = useState<Kiosk[]>([]); const [contests, setContests] = useState<Contest[]>([]);
  const [notice, setNotice] = useState("Loading meetings…"); const [memberNotices, setMemberNotices] = useState<Record<string, string>>({});
  async function refreshMeetings() { const result = await api<{ meetings: Meeting[] }>("/meetings"); setMeetings(result.meetings); if (!selected && result.meetings[0]) setSelected(result.meetings[0].id); setNotice(result.meetings.length ? "" : "No meetings have been created yet."); }
  async function refreshKiosks() { const result = await api<{ kiosks: Kiosk[] }>("/admin/kiosks"); setKiosks(result.kiosks); }
  async function refreshAttendance(meetingId = selected) { if (!meetingId) { setRows([]); setContests([]); return; } const [attendance, contestResult] = await Promise.all([api<{ attendance: AttendanceRow[] }>(`/attendance?meetingId=${encodeURIComponent(meetingId)}`), api<{ contests: Contest[] }>(`/discord/contests?meetingId=${encodeURIComponent(meetingId)}`)]); setRows(attendance.attendance); setContests(contestResult.contests); }
  useEffect(() => { Promise.all([refreshMeetings(), refreshKiosks()]).catch((error: Error) => setNotice(error.message)); const timer = window.setInterval(() => void refreshKiosks().catch(() => undefined), 30_000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { refreshAttendance().catch((error: Error) => setNotice(error.message)); }, [selected]);
  function memberNotice(memberId: string, message: string) { setMemberNotices((current) => ({ ...current, [memberId]: message })); window.setTimeout(() => setMemberNotices((current) => { const next = { ...current }; delete next[memberId]; return next; }), 5000); }
  async function correct(row: AttendanceRow, disposition: AttendanceRow["disposition"]) { const reason = window.prompt(disposition === "present" ? `Optional note for marking ${row.firstName} present:` : `Reason for marking ${row.firstName} ${disposition}:`); if (reason === null) return; if (disposition !== "present" && !reason.trim()) { memberNotice(row.memberId, "A reason is required for this change."); return; } try { await api("/attendance/corrections", { method: "POST", body: JSON.stringify({ memberId: row.memberId, meetingId: selected, disposition, reason }) }); await refreshAttendance(); memberNotice(row.memberId, `Marked ${disposition}.`); } catch (error) { memberNotice(row.memberId, (error as Error).message); } }
  async function resolveContest(contest: Contest, resolution: Contest["status"]) { const reviewNote = window.prompt(`Review note for ${contest.firstName} ${contest.lastName}:`); if (!reviewNote?.trim()) return; try { await api("/discord/contests/resolve", { method: "POST", body: JSON.stringify({ meetingId: contest.meetingId, memberId: contest.memberId, resolution, reviewNote }) }); await refreshAttendance(); memberNotice(contest.memberId, "Contest resolved and audited."); } catch (error) { memberNotice(contest.memberId, (error as Error).message); } }
  async function signOut() { await api("/auth/logout", { method: "POST" }); onSignedOut?.(); }
  async function downloadCsv() { const result = await fetch(`${apiBaseUrl}/exports/attendance.csv`, { credentials: "include" }); if (!result.ok) { setNotice("CSV export failed."); return; } const blob = await result.blob(); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `lancerlogin-attendance-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(link.href); }
  async function discord(path: "missing" | "kiosk-status") { try { await api(`/discord/${path}`, { method: "POST", body: JSON.stringify(path === "kiosk-status" ? {} : { meetingId: selected }) }); setNotice(path === "missing" ? "Discord absence notice posted. A contest opens only when a linked member presses its button." : "Persistent Discord kiosk status updated."); } catch (error) { setNotice((error as Error).message); } }
  const activeKiosk = kiosks.find((kiosk) => kiosk.active === 1); const kioskOnline = Boolean(activeKiosk?.lastSeenAt && Date.now() - Date.parse(activeKiosk.lastSeenAt) < 90_000);
  return <section className={embedded ? "attendance-workspace embedded" : "attendance-workspace"}>
    {!embedded && <header className="workspace-header"><h1>Attendance</h1><button className="theme-button" type="button" onClick={signOut}>Sign out</button></header>}
    {(notice || true) && <div className="attendance-utilities"><span role="status">{notice}</span><span className="toolbar-actions"><button className="text-button" type="button" onClick={downloadCsv}>Export CSV</button><button className="text-button" type="button" onClick={() => discord("kiosk-status")}>Sync kiosk status</button></span></div>}
    <section className="kiosk-monitor" aria-labelledby="kiosk-monitor-title"><h2 id="kiosk-monitor-title">{activeKiosk?.name ?? "No kiosk paired"}</h2><span className={kioskOnline ? "online" : "offline"}>{kioskOnline ? "Online" : activeKiosk ? "Offline" : "Not paired"}</span><p>{activeKiosk?.lastSeenAt ? `Last heartbeat ${new Date(activeKiosk.lastSeenAt).toLocaleString()} · Reader ${activeKiosk.readerOnline ? "online" : "offline"}${activeKiosk.releaseVersion ? ` · Release ${activeKiosk.releaseVersion}` : ""}` : "Pair a kiosk from the Kiosks page. Status refreshes every 30 seconds."}</p></section>
    <div className="attendance-layout"><section className="task-card attendance-meeting-picker" aria-labelledby="attendance-meeting-title"><h2 id="attendance-meeting-title">Meeting</h2><label>View attendance for<select value={selected} onChange={(event) => setSelected(event.target.value)}><option value="">Choose a meeting</option>{meetings.map((meeting) => <option key={meeting.id} value={meeting.id}>{new Date(meeting.startsAt).toLocaleDateString()} · {meeting.title}</option>)}</select></label><button className="primary-button" type="button" disabled={!selected} onClick={() => discord("missing")}>Send Discord absence notice</button></section>
      <section className="attendance-card"><div className="panel-heading"><div><h2>{meetings.find((meeting) => meeting.id === selected)?.title ?? "Choose a meeting"}</h2></div><span className="progress-count">{rows.filter((row) => row.disposition === "present").length} present</span></div>{rows.length ? <div className="attendance-table" role="table" aria-label="Meeting attendance"><div className="attendance-row header" role="row"><span>Member</span><span>Status</span><span>Actions</span></div>{rows.map((row) => <div className="attendance-row" role="row" key={row.memberId}><span><strong>{row.firstName} {row.lastName}</strong><small>{row.externalId}{row.discordUserId ? ` · Discord ${row.discordUserId}` : ""}</small>{memberNotices[row.memberId] && <small className="member-action-notice" role="status">{memberNotices[row.memberId]}</small>}</span><span className={`attendance-state ${row.disposition}`}>{row.disposition}</span><span className="correction-actions"><button type="button" disabled={row.disposition === "present"} onClick={() => correct(row, "present")}>Present</button><button type="button" disabled={row.disposition === "excused"} onClick={() => correct(row, "excused")}>Excuse</button><button type="button" disabled={row.disposition === "absent"} onClick={() => correct(row, "absent")}>Absent</button></span></div>)}</div> : <p className="empty-state">{selected ? "No active roster records are available." : "Choose a meeting to view attendance."}</p>}</section></div>
    {contests.filter((contest) => contest.status === "open").length > 0 && <section className="contest-card" aria-labelledby="contest-title"><div className="panel-heading"><h2 id="contest-title">Missing-member contests</h2><span className="progress-count">{contests.filter((contest) => contest.status === "open").length} open</span></div><div className="contest-list">{contests.filter((contest) => contest.status === "open").map((contest) => <article key={contest.memberId}><div><strong>{contest.firstName} {contest.lastName}</strong><span>{contest.externalId}</span></div><div><button type="button" onClick={() => resolveContest(contest, "approved")}>Approve</button><button type="button" onClick={() => resolveContest(contest, "rejected")}>Reject</button><button type="button" onClick={() => resolveContest(contest, "reviewed")}>Mark reviewed</button></div></article>)}</div></section>}
  </section>;
}
