export const linkTypes=['activities','teams','initiatives','artifacts','metrics'] as const;
export type LinkType=typeof linkTypes[number];
export const linkKeys={activities:'activityId',teams:'teamId',initiatives:'initiativeId',artifacts:'artifactId',metrics:'metricId'} as const;
export type RecordValue={id:string;title:string;revision:number;archived:boolean;createdAt:string;definition?:string;source?:string;rationale?:string;definitionId?:string;definitionRevision?:number;periodStart?:string;periodEnd?:string;review?:{decision:string;reviewedRevision:number;reviewedAt:string}|null};
export type Pin={id:string;type:LinkType;title:string;revision:number;currentRevision:number;eligible:boolean;changed?:boolean;currentArchived?:boolean;selectedArchived?:boolean;selectedReview?:{decision:string;reviewedRevision:number;reviewedAt:string}|null;value?:string;unit?:string;kind?:string;basis?:string;periodStart?:string;periodEnd?:string;source?:string;method?:string;caption?:string;url?:string;originalUrl?:string};
export type DefinitionPin={id:string;title:string;revision:number;currentRevision:number;definition:string;source:string;archived:boolean;changed:boolean};
export type Detail={record:RecordValue;pins:Pin[];definition?:DefinitionPin;dependencyChanged:boolean;incompleteness?:{rationaleMissing:boolean;contextsMissing:boolean;evidenceMissing:boolean}};
export type Draft={title:string;definition:string;source:string;rationale:string;periodStart:string;periodEnd:string};
export const blank:Draft={title:'',definition:'',source:'',rationale:'',periodStart:'',periodEnd:''};
export const fields=(r:RecordValue):Draft=>({title:r.title,definition:r.definition??'',source:r.source??'',rationale:r.rationale??'',periodStart:r.periodStart??'',periodEnd:r.periodEnd??''});
const integer=(v:unknown)=>Number.isSafeInteger(v)&&Number(v)>=0;
const object=(v:any)=>v&&typeof v==='object'&&!Array.isArray(v);
export function checkedRecord(v:any,claim:boolean,history=false):RecordValue{if(!object(v)||typeof v.title!=='string'||!integer(v.revision)||typeof v.archived!=='boolean'||typeof v.createdAt!=='string'||!history&&typeof v.id!=='string')throw Error('Invalid record');for(const key of claim?['definitionId','periodStart','periodEnd','rationale']:['definition','source'])if(typeof v[key]!=='string')throw Error('Invalid fields');if(claim&&(!integer(v.definitionRevision)||v.review!==null&&(!object(v.review)||!['reviewed','rejected'].includes(v.review.decision)||!integer(v.review.reviewedRevision)||typeof v.review.reviewedAt!=='string')))throw Error('Invalid review');return v;}
export function checkedDetail(v:any,claim:boolean,history=false):Detail{const record=checkedRecord(claim?v.claim:history?v:v.definition,claim,history);if(!claim)return {record,pins:[],dependencyChanged:false};if(!object(v.definition)||typeof v.definition.id!=='string'||!integer(v.definition.revision)||!integer(v.definition.currentRevision)||['title','definition','source'].some(k=>typeof v.definition[k]!=='string')||typeof v.definition.archived!=='boolean'||typeof v.definition.changed!=='boolean'||typeof v.dependencyChanged!=='boolean'||!object(v.incompleteness)||['rationaleMissing','contextsMissing','evidenceMissing'].some(k=>typeof v.incompleteness[k]!=='boolean'))throw Error('Invalid claim detail');const pins=linkTypes.flatMap(type=>{if(!Array.isArray(v[type]))throw Error('Invalid associations');return v[type].map((p:any)=>{if(!object(p)||typeof p[linkKeys[type]]!=='string'||typeof p.title!=='string'||!integer(p.revision)||!integer(p.currentRevision)||typeof p.eligible!=='boolean'||typeof p.changed!=='boolean'||typeof p.currentArchived!=='boolean')throw Error('Invalid pin');if(type==='metrics'&&['value','unit','kind','basis','periodStart','periodEnd'].some(k=>typeof p[k]!=='string'))throw Error('Invalid metric snapshot');return {...p,type,id:p[linkKeys[type]]} as Pin;});});return {record,pins,definition:v.definition,dependencyChanged:v.dependencyChanged,incompleteness:v.incompleteness};}
export function errors(d:Draft,claim:boolean){const result:Partial<Record<keyof Draft,string>>={};const limits=claim?{title:200,rationale:8000,periodStart:10,periodEnd:10}:{title:200,definition:8000,source:2000};for(const [k,max] of Object.entries(limits)){const key=k as keyof Draft,value=d[key];if(value.length>max||/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(value))result[key]='Remove unsupported characters or shorten this field.';if(['title','definition','periodStart','periodEnd'].includes(key)&&!value.trim())result[key]='Required.';}if(claim){for(const key of ['periodStart','periodEnd'] as const){const value=d[key],date=new Date(value+'T00:00:00Z');if(!/^\d{4}-\d{2}-\d{2}$/.test(value)||value<'1900-01-01'||value>'9999-12-31'||!Number.isFinite(date.getTime())||date.toISOString().slice(0,10)!==value)result[key]='Enter a real date from 1900 through 9999.';}if(d.periodEnd<d.periodStart)result.periodEnd='End must be on or after start.';}return result;}
export const pinIdentity=(p:Pin)=>p.type+':'+p.id+':'+p.revision;
