import { FormEvent, useState } from "react";
import { api } from "./dashboard-api";
import type { Branding } from "./setup-workspace";
import { InfoTip } from "./info-tip";

export function ConfigurationSettings({ initialBranding, onChanged }: { initialBranding: Branding; onChanged: (branding: Branding) => void }) {
  const [lateScanMinutes, setLateScanMinutes] = useState(String(initialBranding.lateScanMinutes));
  const [attendanceReportingStartsOn, setAttendanceReportingStartsOn] = useState(initialBranding.attendanceReportingStartsOn ?? "");
  const [anomalyLateThresholdMinutes, setAnomalyLateThresholdMinutes] = useState(String(initialBranding.anomalyLateThresholdMinutes ?? 10));
  const [anomalyEarlyThresholdMinutes, setAnomalyEarlyThresholdMinutes] = useState(String(initialBranding.anomalyEarlyThresholdMinutes ?? 10));
  const [notice, setNotice] = useState<{ tone: "success" | "error"; text: string }>(); const [saving, setSaving] = useState(false);
  async function save(event: FormEvent) {
    event.preventDefault(); const next = { ...initialBranding, lateScanMinutes: lateScanMinutes.trim() === "" ? 0 : Number(lateScanMinutes), attendanceReportingStartsOn: attendanceReportingStartsOn || null, anomalyLateThresholdMinutes: Number(anomalyLateThresholdMinutes), anomalyEarlyThresholdMinutes: Number(anomalyEarlyThresholdMinutes) };
    setSaving(true); try { await api("/admin/branding", { method: "PATCH", body: JSON.stringify(next) }); onChanged(next); setLateScanMinutes(String(next.lateScanMinutes)); setNotice({ tone: "success", text: "Attendance configuration saved." }); } catch (error) { setNotice({ tone: "error", text: (error as Error).message }); } finally { setSaving(false); }
  }
  return <section className="settings-page settings-configuration" aria-labelledby="configuration-title"><div className="page-intro"><h1 id="configuration-title">Configuration</h1><p>Set the organization-wide timing rules used by attendance and reporting.</p></div>{notice && <p className="ui-status settings-notice" data-tone={notice.tone} role={notice.tone === "error" ? "alert" : "status"}>{notice.text}</p>}<form className="settings-form configuration-form" onSubmit={save}><div className="configuration-grid"><label><span className="field-label-with-info">Late scan allowance (minutes)<InfoTip>Scans close this many minutes after every meeting’s required end time.</InfoTip></span><input aria-label="Late scan allowance (minutes)" type="number" min={0} max={180} step={1} value={lateScanMinutes} placeholder="0" onChange={(event) => setLateScanMinutes(event.target.value)} /></label><label><span className="field-label-with-info">Late-arrival limit (minutes)<InfoTip>A check-in later than this limit counts toward mean anomalous time.</InfoTip></span><input aria-label="Late-arrival limit (minutes)" required type="number" min={0} max={1440} step={1} value={anomalyLateThresholdMinutes} onChange={(event) => setAnomalyLateThresholdMinutes(event.target.value)} /></label><label><span className="field-label-with-info">Early-departure limit (minutes)<InfoTip>A check-out earlier than this limit counts toward mean anomalous time.</InfoTip></span><input aria-label="Early-departure limit (minutes)" required type="number" min={0} max={1440} step={1} value={anomalyEarlyThresholdMinutes} onChange={(event) => setAnomalyEarlyThresholdMinutes(event.target.value)} /></label><label><span className="field-label-with-info">Attendance reporting baseline <span>(optional)</span><InfoTip>Reports use completed meetings on or after this date. Leave blank to include all preserved history.</InfoTip></span><input aria-label="Attendance reporting baseline" type="date" value={attendanceReportingStartsOn} onChange={(event) => setAttendanceReportingStartsOn(event.target.value)} /></label></div><button className="primary-button" disabled={saving} type="submit">{saving ? "Saving…" : "Save configuration"}</button></form></section>;
}
