import { FormEvent, useState } from "react";
import { api } from "./dashboard-api";
import type { Branding } from "./setup-workspace";

export function ConfigurationSettings({ initialBranding, onChanged }: { initialBranding: Branding; onChanged: (branding: Branding) => void }) {
  const [lateScanMinutes, setLateScanMinutes] = useState(String(initialBranding.lateScanMinutes));
  const [discordContestWindowHours, setDiscordContestWindowHours] = useState(String(initialBranding.discordContestWindowHours));
  const [attendanceReportingStartsOn, setAttendanceReportingStartsOn] = useState(initialBranding.attendanceReportingStartsOn ?? "");
  const [notice, setNotice] = useState<{ tone: "success" | "error"; text: string }>(); const [saving, setSaving] = useState(false);
  async function save(event: FormEvent) {
    event.preventDefault(); const next = { ...initialBranding, lateScanMinutes: lateScanMinutes.trim() === "" ? 0 : Number(lateScanMinutes), discordContestWindowHours: discordContestWindowHours.trim() === "" ? 24 : Number(discordContestWindowHours), attendanceReportingStartsOn: attendanceReportingStartsOn || null };
    setSaving(true); try { await api("/admin/branding", { method: "PATCH", body: JSON.stringify(next) }); onChanged(next); setLateScanMinutes(String(next.lateScanMinutes)); setDiscordContestWindowHours(String(next.discordContestWindowHours)); setNotice({ tone: "success", text: "Attendance configuration saved." }); } catch (error) { setNotice({ tone: "error", text: (error as Error).message }); } finally { setSaving(false); }
  }
  return <section className="settings-page settings-configuration" aria-labelledby="configuration-title"><div className="page-intro"><h1 id="configuration-title">Configuration</h1><p>Set the organization-wide timing rules used by attendance and reporting.</p></div>{notice && <p className="ui-status settings-notice" data-tone={notice.tone} role={notice.tone === "error" ? "alert" : "status"}>{notice.text}</p>}<form className="settings-form configuration-form" onSubmit={save}><div className="configuration-grid"><label>Late scan allowance (minutes)<input type="number" min={0} max={180} step={1} value={lateScanMinutes} placeholder="0" aria-describedby="late-scan-help" onChange={(event) => setLateScanMinutes(event.target.value)} /><span id="late-scan-help" className="field-help">Scans close this many minutes after every meeting’s required end time.</span></label><label>Discord contest window (hours)<input type="number" min={1} max={168} step={1} value={discordContestWindowHours} placeholder="24" aria-describedby="contest-window-help" onChange={(event) => setDiscordContestWindowHours(event.target.value)} /><span id="contest-window-help" className="field-help">An absence notice accepts contests for this many hours after delivery.</span></label><label>Attendance reporting baseline <span>(optional)</span><input type="date" value={attendanceReportingStartsOn} aria-describedby="reporting-baseline-help" onChange={(event) => setAttendanceReportingStartsOn(event.target.value)} /><span id="reporting-baseline-help" className="field-help">Reports use completed meetings on or after this date. Leave blank to include all preserved history.</span></label></div><button className="primary-button" disabled={saving} type="submit">{saving ? "Saving…" : "Save configuration"}</button></form></section>;
}
