import type { WalkthroughStep } from "./page-walkthrough";

const anchor = (name: string) => `[data-walkthrough="${name}"]`;
export const dashboardWalkthrough: WalkthroughStep[] = [
  { id: "navigation", title: "Find your way around", description: "Dashboard is your meeting hub. Roster manages people, Reports shows attendance results, Kiosks shows device status, and Settings contains your available preferences and configuration.", targets: anchor("navigation") },
  { id: "calendar", title: "See what is coming up", description: "The calendar shows five weeks at a time. Use the arrows to browse earlier or later dates, and Today to return to the current range. Meeting entries show their start time and title. Try the arrows, then Today.", targets: anchor("calendar-navigation"), practice: anchor("calendar-navigation") },
  { id: "find-meeting", title: "Find the meeting you need", description: "After the walkthrough, open a calendar entry or use Choose a meeting when you know which one you want. Both lead to that meeting's details and attendance. If no meetings exist yet, scheduled meetings will appear here when you add them.", targets: `${anchor("meeting-picker")}, ${anchor("calendar-entry")}:first-of-type` },
  { id: "table", title: "Compare meetings in a list", description: "Select Table to compare dates, times, audiences, attendance requirements, recurrence, and notes. Opening a row leads to the same meeting workspace. Next will switch views if you prefer to follow along.", targets: anchor("meeting-view"), practice: anchor("meeting-view") },
  { id: "search", title: "Narrow the list", description: "Use Search Meetings to find a title or details such as notes or required/optional status. Try typing a search, then clear it to see everything again. No matches simply means nothing fits that search.", targets: anchor("meeting-search"), practice: anchor("meeting-search") },
  { id: "selection", title: "Understand selection and deletion", description: "A row opens a meeting. Its checkbox selects it for bulk actions. Delete selected removes the selected meetings after confirmation. You may practice selecting; deletion is unavailable here. Bulk deletion does not offer the meeting-detail Undo action.", targets: `${anchor("meeting-selection")}, ${anchor("meeting-delete")}`, practice: anchor("meeting-selection") },
  { id: "add-meeting", title: "Plan another meeting", description: "Use Add meeting when the meeting you need is not scheduled. This is a practice preview. Duplicate an existing meeting provides a starting point for similar meetings. With no existing meetings, start with blank fields.", targets: anchor("meeting-duplicate"), practice: anchor("practice-form") },
  { id: "essentials", title: "Set the essentials", description: "Give the meeting a clear title, check its date and start/end times, and add optional notes. Review the end time before saving. Attendance windows cannot overlap. Try editing these fields; nothing will be saved.", targets: anchor("meeting-essentials"), practice: anchor("practice-form") },
  { id: "audience", title: "Choose who it is for", description: "Choose All members or Selected labels for the audience. Attendance required determines whether the meeting counts toward regular attendance percentages. Attendance weight controls its contribution to weighted calculations; Automatic uses configured rules. You can leave All members selected if no labels exist.", targets: anchor("meeting-attendance"), practice: anchor("practice-form") },
  { id: "recurrence", title: "Schedule once or repeat", description: "Choose One time for a single meeting, or a recurring frequency and series end date. Normally, Create meeting or Create recurring series saves the schedule; Cancel closes without saving. Saving is unavailable in practice. Choose Next to finish.", targets: anchor("meeting-recurrence"), practice: anchor("practice-form") },
];
