import { useState } from "react";
import { apiBaseUrl } from "./dashboard-api";

type Scope = "meetings" | "roster" | "installation";
const details: Record<Scope, { title: string; backup: string; restore: string; deletion: string; confirmation: string }> = {
  meetings: { title: "Meetings and attendance", backup: "Meetings, check-ins, corrections, excuses, and attendance contests.", restore: "Replaces only meetings and attendance. Existing roster member IDs must match the backup.", deletion: "Deletes meetings and attendance while keeping roster, accounts, settings, integrations, and audit history.", confirmation: "DELETE ATTENDANCE" },
  roster: { title: "Roster", backup: "Roster identities, contact fields, Discord links, and active status. Dashboard credentials remain separate.", restore: "Restores the active roster state. Current historical members missing from the backup are retained as inactive when referenced.", deletion: "Deletes roster only. If attendance still references members, delete meetings and attendance first. Linked dashboard accounts become non-rostered.", confirmation: "DELETE ROSTER" },
  installation: { title: "Entire installation", backup: "All D1 state, including password hashes, encrypted integrations, kiosk credential hashes, settings, and audit history.", restore: "Replaces the entire D1 installation. It works only while the installation encryption secrets remain unchanged.", deletion: "Deletes the entire installation and returns to first-Admin setup.", confirmation: "DELETE INSTALLATION" },
};
async function errorMessage(result: Response) { const body = await result.json() as { error?: string; details?: string[] }; return body.details?.join(" ") ?? body.error ?? "Request failed"; }

export function DataSettings({ onReset }: { onReset: () => void }) {
  const [files, setFiles] = useState<Partial<Record<Scope, File>>>({}); const [notice, setNotice] = useState("Choose a category. Backup, restore, and deletion stay independent."); const [busy, setBusy] = useState<string>(); const [errors, setErrors] = useState<Partial<Record<Scope | "reset", string>>>({});
  function showError(scope: Scope | "reset", message: string) { setErrors((current) => ({ ...current, [scope]: message })); window.requestAnimationFrame(() => document.getElementById(`data-error-${scope}`)?.focus()); }
  function clearError(scope: Scope | "reset") { setErrors((current) => ({ ...current, [scope]: undefined })); }
  async function backup(scope: Scope) { clearError(scope); setBusy(`backup-${scope}`); try { const result = await fetch(`${apiBaseUrl}/admin/data/backup?scope=${scope}`, { credentials: "include" }); if (!result.ok) throw new Error(await errorMessage(result)); const blob = await result.blob(); const name = result.headers.get("content-disposition")?.match(/filename="([^"]+)"/)?.[1] ?? `lancerlogin-${scope}-backup.json`; const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); setNotice(`${details[scope].title} backup downloaded. Store it securely.`); } catch (error) { showError(scope, (error as Error).message); } finally { setBusy(undefined); } }
  async function restore(scope: Scope) { clearError(scope); const file = files[scope]; if (!file) { showError(scope, `Choose a ${details[scope].title.toLowerCase()} backup first.`); return; } if (file.size > 10_485_760) { showError(scope, "Dashboard restore supports files up to 10 MiB; use the documented D1 workflow for larger backups."); return; } if (!window.confirm(`${details[scope].restore} Continue?`)) return; const confirmation = window.prompt(`Type RESTORE ${scope.toUpperCase()} exactly to continue.`); if (confirmation === null) return; setBusy(`restore-${scope}`); try { const backupDocument = JSON.parse(await file.text()) as unknown; const result = await fetch(`${apiBaseUrl}/admin/data/restore`, { method: "POST", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify({ scope, confirmation, backup: backupDocument }) }); if (!result.ok) throw new Error(await errorMessage(result)); setNotice(`${details[scope].title} restored successfully.`); if (scope === "installation") window.location.reload(); } catch (error) { showError(scope, error instanceof SyntaxError ? "The selected backup is not valid JSON." : (error as Error).message); } finally { setBusy(undefined); } }
  async function remove(scope: Scope) { clearError(scope); if (!window.confirm(`${details[scope].deletion} This cannot be undone without a backup. Continue?`)) return; const confirmation = window.prompt(`Type ${details[scope].confirmation} exactly to continue.`); if (confirmation === null) return; setBusy(`delete-${scope}`); try { const result = await fetch(`${apiBaseUrl}/admin/data`, { method: "DELETE", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify({ scope: scope === "meetings" ? "attendance" : scope, confirmation }) }); if (!result.ok) throw new Error(await errorMessage(result)); if (scope === "installation") window.location.reload(); else setNotice(`${details[scope].title} deleted.`); } catch (error) { showError(scope, (error as Error).message); } finally { setBusy(undefined); } }
  async function resetOnboarding() { clearError("reset"); if (!window.confirm("This reopens all six onboarding tasks without deleting data or configuration. Continue?")) return; const confirmation = window.prompt("Type RESET ONBOARDING exactly to continue."); if (confirmation === null) return; setBusy("reset"); try { const result = await fetch(`${apiBaseUrl}/admin/setup/reset`, { method: "POST", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify({ confirmation }) }); if (!result.ok) throw new Error(await errorMessage(result)); setNotice("Onboarding reset without deleting organization data."); onReset(); } catch (error) { showError("reset", (error as Error).message); } finally { setBusy(undefined); } }
  return <section className="settings-page" aria-labelledby="data-title"><div className="page-intro"><p className="kicker">Settings</p><h2 id="data-title">Data management</h2><p>Each category has its own backup, restore, and delete controls. A backup from one category can restore only that same category.</p></div><p className="setup-status" role="status">{notice}</p><div className="data-category-list">{(["meetings", "roster", "installation"] as const).map((scope) => <article className={scope === "installation" ? "data-category sensitive" : "data-category"} key={scope}><div><h3>{details[scope].title}</h3><p>{details[scope].backup}</p>{scope === "installation" && <strong className="sensitive-note">Sensitive backup: protect it like an administrator credential.</strong>}</div><div className="data-control"><button type="button" disabled={Boolean(busy)} onClick={() => backup(scope)}>{busy === `backup-${scope}` ? "Preparing…" : "Download backup"}</button></div><div className="data-control"><label>Restore file<input type="file" accept="application/json,.json" onChange={(event) => { clearError(scope); setFiles({ ...files, [scope]: event.target.files?.[0] }); }} /></label><button type="button" disabled={Boolean(busy) || !files[scope]} onClick={() => restore(scope)}>{busy === `restore-${scope}` ? "Restoring…" : "Validate and restore"}</button></div><div className="data-control danger"><p>{details[scope].deletion}</p><button type="button" disabled={Boolean(busy)} onClick={() => remove(scope)}>{busy === `delete-${scope}` ? "Deleting…" : `Delete ${details[scope].title.toLowerCase()}`}</button></div>{errors[scope] && <p id={`data-error-${scope}`} className="inline-messages error" role="alert" tabIndex={-1}>{errors[scope]}</p>}</article>)}</div><article className="reset-card"><div><h3>Restart onboarding</h3><p>Reopens every guided task without deleting roster, meetings, attendance, credentials, branding, integrations, or kiosk state.</p>{errors.reset && <p id="data-error-reset" className="inline-messages error" role="alert" tabIndex={-1}>{errors.reset}</p>}</div><button type="button" disabled={Boolean(busy)} onClick={resetOnboarding}>{busy === "reset" ? "Resetting…" : "Reset onboarding"}</button></article><p className="field-help">For backups larger than 10 MiB or infrastructure disaster recovery, use the documented adopter-owned Cloudflare D1 backup and restore workflow.</p></section>;
}
