import { useEffect, useState } from "react";
import { api } from "./dashboard-api";
import { InfoHeading } from "./info-tip";

type Mapping = { labelId: string; labelName: string; roleId: string; roleName: string; health: string; healthDetail?: string; latestJob?: { id: string; status: string; updatedAt: string } };
type Person = { discordUserId: string; displayName: string; memberId?: string };
type Preview = { previewId: string; expiresAt: string; labelId: string; roleName: string; memberCount: number; additions: Person[]; removals: Person[]; unpaired: { memberId: string; name: string }[]; absent: { memberId: string; name: string; discordUserId: string }[]; inactive: { memberId: string; name: string; discordUserId?: string }[] };
type Job = { id: string; status: string; updatedAt: string; items: { discordUserId: string; action: "add" | "remove"; status: string; attempts: number; lastError?: string }[] };

export function DiscordLabelRoleSettings({ role }: { role: "admin" | "operator" }) {
  const [mappings, setMappings] = useState<Mapping[]>([]);
  const [available, setAvailable] = useState(false);
  const [preview, setPreview] = useState<Preview>();
  const [job, setJob] = useState<Job>();
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState("");
  async function load() { const data = await api<{ mappings: Mapping[]; integrationAvailable: boolean }>("/admin/integrations/discord/label-roles"); setMappings(data.mappings); setAvailable(data.integrationAvailable); }
  useEffect(() => { void load().catch((error: Error) => setNotice(error.message)); }, []);
  useEffect(() => {
    if (!job || !["pending", "running"].includes(job.status)) return;
    const timer = window.setInterval(() => { void api<Job>(`/admin/integrations/discord/label-role-jobs/${encodeURIComponent(job.id)}${role === "admin" ? "/advance" : ""}`, role === "admin" ? { method: "POST", body: "{}" } : undefined).then((next) => { setJob(next); if (!["pending", "running"].includes(next.status)) void load(); }).catch((error: Error) => setNotice(error.message)); }, 4000);
    return () => window.clearInterval(timer);
  }, [job?.id, job?.status, role]);
  async function prepare(labelId: string) { setBusy(true); setNotice(""); setPreview(undefined); try { setPreview(await api<Preview>("/admin/integrations/discord/label-roles/preview", { method: "POST", body: JSON.stringify({ labelId }) })); } catch (error) { setNotice((error as Error).message); } finally { setBusy(false); } }
  async function apply() { if (!preview) return; setBusy(true); try { const result = await api<{ jobId: string }>("/admin/integrations/discord/label-roles/apply", { method: "POST", body: JSON.stringify({ previewId: preview.previewId }) }); setPreview(undefined); setJob(await api<Job>(`/admin/integrations/discord/label-role-jobs/${encodeURIComponent(result.jobId)}`)); await load(); setNotice("Discord role sync started. Progress appears below."); } catch (error) { setPreview(undefined); setNotice((error as Error).message); } finally { setBusy(false); } }
  async function unlink(mapping: Mapping) { if (!window.confirm(`Unlink ${mapping.labelName} from ${mapping.roleName}? Existing Discord role assignments will stay in place.`)) return; setBusy(true); try { await api(`/admin/integrations/discord/label-roles/${encodeURIComponent(mapping.labelId)}`, { method: "DELETE" }); setPreview(undefined); await load(); setNotice("Role unlinked. Existing Discord assignments were not changed."); } catch (error) { setNotice((error as Error).message); } finally { setBusy(false); } }
  async function retry(id: string) { if (!window.confirm("Retry only failed role changes that are still needed?")) return; setBusy(true); try { const result = await api<{ jobId?: string; retried: number }>(`/admin/integrations/discord/label-role-jobs/${encodeURIComponent(id)}/retry`, { method: "POST", body: "{}" }); if (result.jobId) setJob(await api<Job>(`/admin/integrations/discord/label-role-jobs/${encodeURIComponent(result.jobId)}`)); else setJob(undefined); await load(); setNotice(result.retried ? `Retrying ${result.retried} role changes.` : "No failed changes are still needed."); } catch (error) { setNotice((error as Error).message); } finally { setBusy(false); } }
  function showJob(id: string) { setBusy(true); void api<Job>(`/admin/integrations/discord/label-role-jobs/${encodeURIComponent(id)}`).then(setJob).catch((error: Error) => setNotice(error.message)).finally(() => setBusy(false)); }
  return <section className="task-card ui-card member-labels-panel" aria-labelledby="discord-label-role-title"><InfoHeading id="discord-label-role-title" info={<>Pair a LancerLogin Admin account, then use <code>/label @ROLE</code> in your configured Discord server to associate a role with an exactly named label. Association alone does not change anyone's role.</>}>Discord roles</InfoHeading>
    {!available && <p className="ui-status" data-tone="warning">Enable and verify Discord in Settings → Integrations to preview or sync roles.</p>}
    {notice && <p className="ui-status" role="status">{notice}</p>}
    {mappings.length ? <ul className="compact-list label-period-list">{mappings.map((mapping) => <li key={mapping.labelId}><span><strong>{mapping.labelName}</strong> → {mapping.roleName} · {mapping.health.replaceAll("_", " ")}{mapping.healthDetail && <small> · {mapping.healthDetail}</small>}{mapping.latestJob && <small> · Last sync: {mapping.latestJob.status} ({new Date(mapping.latestJob.updatedAt).toLocaleString()})</small>}</span><div className="dialog-actions">{mapping.latestJob && <button className="ui-button" type="button" disabled={busy} onClick={() => showJob(mapping.latestJob!.id)}>View status</button>}{role === "admin" && <><button className="ui-button ui-button--primary" type="button" disabled={busy || !available || mapping.health !== "ready"} onClick={() => void prepare(mapping.labelId)}>Sync to Discord</button><button className="ui-button ui-button--danger" type="button" disabled={busy} onClick={() => void unlink(mapping)}>Unlink</button></>}</div></li>)}</ul> : <p>No labels are associated with Discord roles. Labels without an association remain local to LancerLogin.</p>}
    {preview && <section className="discord-role-preview" aria-labelledby="discord-role-preview-title"><h3 id="discord-role-preview-title">Review role changes for {preview.roleName}</h3><p>Discord returned {preview.memberCount} server members. This preview expires at {new Date(preview.expiresAt).toLocaleTimeString()}.</p><p><strong>{preview.additions.length} additions</strong> and <strong>{preview.removals.length} removals</strong>. Unpaired Discord accounts holding this role appear in removals.</p>
      <h4>Add role</h4>{preview.additions.length ? <ul className="compact-list">{preview.additions.map((person) => <li key={person.discordUserId}>{person.displayName} · {person.memberId ?? person.discordUserId}</li>)}</ul> : <p>None</p>}
      <h4>Remove role</h4>{preview.removals.length ? <ul className="compact-list">{preview.removals.map((person) => <li key={person.discordUserId}>{person.displayName} · {person.discordUserId}</li>)}</ul> : <p>None</p>}
      <h4>Roster exceptions</h4><p>{preview.unpaired.length} labeled members are unpaired, {preview.absent.length} are absent from the server, and {preview.inactive.length} are inactive.</p>{preview.unpaired.length + preview.absent.length + preview.inactive.length > 0 && <ul className="compact-list">{preview.unpaired.map((person) => <li key={`unpaired-${person.memberId}`}>{person.name} ({person.memberId}) · unpaired</li>)}{preview.absent.map((person) => <li key={`absent-${person.memberId}`}>{person.name} ({person.memberId}) · not in server</li>)}{preview.inactive.map((person) => <li key={`inactive-${person.memberId}`}>{person.name} ({person.memberId}) · inactive</li>)}</ul>}
      <div className="dialog-actions"><button className="ui-button" type="button" onClick={() => setPreview(undefined)}>Cancel</button><button className="ui-button ui-button--primary" type="button" disabled={busy} onClick={() => void apply()}>Confirm full-server sync</button></div></section>}
    {job && <section className="discord-role-job" aria-labelledby="discord-role-job-title"><h3 id="discord-role-job-title">Role sync status</h3><p>Status: <strong>{job.status}</strong>. {job.items.filter((item) => item.status === "completed").length} completed, {job.items.filter((item) => item.status === "pending").length} pending, {job.items.filter((item) => item.status === "failed").length} failed.</p>{job.items.some((item) => item.status === "failed") && <ul className="compact-list">{job.items.filter((item) => item.status === "failed").map((item) => <li key={item.discordUserId}>{item.action} {item.discordUserId}: {item.lastError}</li>)}</ul>}{role === "admin" && job.status === "partial" && <button className="ui-button" type="button" disabled={busy} onClick={() => void retry(job.id)}>Retry failed changes</button>}{job.status === "stale" && <p>Roster labels or pairing changed during sync. Review a fresh preview before continuing.</p>}</section>}
  </section>;
}
