import {useEffect,useRef,useState} from 'react';
import {DocumentationError,documentationRequest as api} from './documentation-request';
import {noteValue,historyValue,type Note,type History,type Contributor,type Review} from './documentation-notes-contract';
function Provenance({value}:{value:Contributor}){return <p>{value.kind==='staff'?'Staff contribution':value.source==='public'?'Self-asserted member contribution':'Linked Discord member contribution'}{value.kind==='member'&&<><br/>Current member name: {value.currentMemberLabel||'Name unavailable'}. {value.source==='public'?'The roster match does not verify the submitter.':'The linked account does not verify the content.'}</>}</p>;}
function ReviewStatus({value}:{value:Review}){return <p>{value?<>Staff review: {value.decision==='reviewed'?'Reviewed':'Rejected'} · content revision {value.reviewedRevision} · {value.reviewedAt}</>:'Not currently reviewed'}</p>;}
type Activity = { id:string; title:string; serviceDate:string; revision:number; archived:boolean; impactRelevant:boolean; readOnly?:boolean; sectionRevision?:number; summary?:{countedMinutes:number;distinctParticipants:number} };
type Sections = {version:1;revision:number;notesEnabled:boolean;summaryEnabled:boolean;filesEnabled:boolean};
type Notes = {notes:Note[];next:string|null;readOnly:boolean;sectionRevision:number;activityRevision:number};
const root='/admin/documentation';
const id=(value:string)=>encodeURIComponent(value);
export function DocumentationActivities({admin=false,accessChecking=false,reloadAccess,onOccupied}:{admin?:boolean;accessChecking?:boolean;reloadAccess:()=>void;onOccupied:(value:boolean)=>void}) {
 const [activities,setActivities]=useState<{activities:Activity[];next:string|null}>(); const [archival,setArchival]=useState(false);
 const [activity,setActivity]=useState<Activity>(); const [notes,setNotes]=useState<Notes>(); const [sections,setSections]=useState<Sections>();
 const [editing,setEditing]=useState<Note>(); const [draft,setDraft]=useState(''); const [history,setHistory]=useState<{note:Note;page:History}>();
 const [working,setBusy]=useState(false); const [writing,setWriting]=useState(false); const busy=working||writing; const [locked,setLocked]=useState(false); const [notice,setNotice]=useState('');
 const mutationPending=useRef(false); const generation=useRef(0); const pending=useRef(false); const noticeRef=useRef<HTMLParagraphElement>(null);
 const disabled=busy||accessChecking||locked; const readOnly=!!notes?.readOnly||!sections?.notesEnabled||!!activity?.readOnly;
 const dirty=editing?draft!==editing.text:!!draft;
 const invalid=!draft.trim()||draft.length>8000||/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(draft);
 useEffect(()=>{onOccupied(busy||!!draft||locked);},[busy,draft,locked,onOccupied]);
 useEffect(()=>{if(notice)noticeRef.current?.focus();},[notice]);
 async function current(target=activity,after='') {
  const config=await api<Sections>(root+'/sections');
  if(config.version!==1||!Number.isInteger(config.revision)||typeof config.notesEnabled!=='boolean'||typeof config.summaryEnabled!=='boolean'||typeof config.filesEnabled!=='boolean')throw Error('Invalid sections');
  if(!target)return {config};
  const [detail,list]=await Promise.all([api<Activity>(root+'/activities/'+id(target.id)),api<Notes>(root+'/activities/'+id(target.id)+'/notes?limit=25'+(after?'&after='+id(after):''))]);
  if(detail.id!==target.id||!Array.isArray(list.notes)||!Number.isInteger(list.activityRevision)||!Number.isInteger(list.sectionRevision)||list.sectionRevision!==config.revision||detail.sectionRevision!==config.revision||list.activityRevision!==detail.revision)throw Error('Invalid records');
  list.notes=list.notes.map(noteValue);if(list.notes.some(n=>n.activityId!==target.id)||new Set(list.notes.map(n=>n.id)).size!==list.notes.length)throw Error('Invalid note scope');return {config,detail,list};
 }
 function denied(error:unknown) { if(error instanceof DocumentationError && [401,403].includes(error.status)){generation.current++;setActivities(undefined);setActivity(undefined);setNotes(undefined);setSections(undefined);setDraft('');setEditing(undefined);setHistory(undefined);reloadAccess();} }
 async function read(action:(valid:()=>boolean)=>Promise<void>) {if(pending.current||mutationPending.current)return;const token=generation.current;const valid=()=>token===generation.current;pending.current=true;setBusy(true);try{await action(valid);}catch(error){if(valid()){denied(error);setLocked(true);setNotice('Records could not be confirmed. Reload current records before making a change.');}}finally{if(valid()){pending.current=false;setBusy(false);}}}
 async function list(after='',include=archival) {await read(async valid=>{const page=await api<{activities:Activity[];next:string|null}>(root+'/activities?limit=25&archival='+include+(after?'&after='+id(after):''));if(!Array.isArray(page.activities))throw Error('Invalid activities');const value=await current();if(!valid())return;setActivities(page);setSections(value.config);});}
 async function select(target:Activity) {await read(async valid=>{const value=await current(target);if(!valid())return;setActivity(value.detail);setNotes(value.list);setSections(value.config);setEditing(undefined);setDraft('');setHistory(undefined);setNotice('');});}
 async function reload(explicit=true) {await read(async valid=>{const [value,page,result]=await Promise.all([current(),api<{activities:Activity[];next:string|null}>(root+'/activities?limit=25&archival='+archival),editing?api<{note:Note}>(root+'/notes/'+id(editing.id)):Promise.resolve(undefined)]);if(!Array.isArray(page.activities))throw Error('Invalid activities');if(!valid())return;setActivities(page);setSections(value.config);setActivity(value.detail);setNotes(value.list);setHistory(undefined);if(result)setEditing(noteValue(result.note));if(explicit){setLocked(false);setNotice('Current records reloaded. Review the server notes and preserved draft before a new explicit save.');}});}

 useEffect(()=>{pending.current=false;void list();return()=>{generation.current++;};},[]);
 useEffect(()=>{if(accessChecking){generation.current++;pending.current=false;setBusy(false);setLocked(true);}else if(activities){void reload(false);}},[accessChecking]);
 async function write(path:string,method:string,body:unknown) {
  if(disabled||pending.current||mutationPending.current)return;mutationPending.current=true;setWriting(true);const token=generation.current;
  try{const result=await api<{note?:Note}>(root+path,{method,body:JSON.stringify(body)});if(token!==generation.current)return;
   if(method!=='PUT'){const saved=noteValue(result.note);if(path.startsWith('/notes/')&&path.split('/')[2]!==saved.id)throw Error('Mismatched note');const confirmed=await api<{note:Note}>(root+'/notes/'+id(result.note!.id));if(noteValue(confirmed.note).id!==result.note!.id||confirmed.note.revision!==result.note!.revision)throw Error('Unconfirmed revision');}
   const value=await current();if(token!==generation.current)return;if(method!=='PUT'&&(value.config.revision!==(body as {sectionRevision:number}).sectionRevision||value.list?.activityRevision!==(body as {activityRevision:number}).activityRevision||!value.config.notesEnabled||value.detail?.readOnly))throw Error('Current eligibility changed');setSections(value.config);setActivity(value.detail);setNotes(value.list);setHistory(undefined);if(method!=='PUT'){setEditing(undefined);setDraft('');}setNotice('Saved and confirmed from current server records.');
  }catch(error){if(token===generation.current){denied(error);setLocked(true);setNotice('The change could not be confirmed. Reload current records and check whether it was saved before another explicit change. No write is retried automatically.');}}
  finally{mutationPending.current=false;setWriting(false);}
 }
 async function showHistory(note:Note,after?:number){await read(async valid=>{const page=historyValue(await api<History>(root+'/notes/'+id(note.id)+'/history?limit=25'+(after===undefined?'':'&after='+after)),note,after);if(!valid())return;setHistory({note,page});});}
 const revisions={activityRevision:notes?.activityRevision,sectionRevision:notes?.sectionRevision};
 return <section className="hours-workspace documentation-workspace" aria-busy={busy||accessChecking}>
 {notice&&<p ref={noticeRef} tabIndex={-1} role={locked?'alert':'status'} className="ui-status">{notice}</p>}
 <div className="hours-actions"><button disabled={busy||accessChecking} onClick={()=>void reload()}>Reload current records</button><a href="/submit-documentation" target="_blank" rel="noopener noreferrer">Open member note form (opens a new tab)</a></div>
 {accessChecking?<p role="status">Checking current workspace access…</p>:<>
 <section className="ui-card hours-stack"><h2>Choose an activity</h2><label className="hours-check"><input type="checkbox" checked={archival} disabled={busy} onChange={e=>{setArchival(e.target.checked);void list('',e.target.checked);}}/>Include archival activities with preserved notes</label><p>Active impact-relevant activities are shown by default.</p>
 <div className="hours-records">{activities?.activities.map(item=><div className="hours-row" key={item.id}><span>{item.title} · {item.serviceDate}{item.archived?' · Archived':!item.impactRelevant?' · No longer impact-relevant':''}</span><button disabled={busy||dirty} aria-pressed={activity?.id===item.id} onClick={()=>void select(item)}>Open {item.title}</button></div>)}</div>{activities?.activities.length===0&&<p>No eligible activities on this page.</p>}<div className="hours-actions"><button disabled={busy} onClick={()=>void list()}>First activities page</button>{activities?.next&&<button disabled={busy} onClick={()=>void list(activities.next!)}>Next activities page</button>}</div></section>
 {admin&&sections&&<section className="ui-card hours-stack"><h2>Built-in sections</h2><p>Disabling a section preserves existing records.</p><label className="hours-check"><input type="checkbox" checked={sections.notesEnabled} disabled={disabled} onChange={e=>void write('/sections','PUT',{...{version:1,revision:sections.revision,summaryEnabled:sections.summaryEnabled},notesEnabled:e.target.checked})}/>Enable notes</label><label className="hours-check"><input type="checkbox" checked={sections.summaryEnabled} disabled={disabled} onChange={e=>void write('/sections','PUT',{version:1,revision:sections.revision,notesEnabled:sections.notesEnabled,summaryEnabled:e.target.checked})}/>Enable participant/hour summaries</label><label className="hours-check"><input type="checkbox" checked={sections.filesEnabled} disabled={disabled} onChange={e=>void write('/sections','PUT',{version:1,revision:sections.revision,notesEnabled:sections.notesEnabled,summaryEnabled:sections.summaryEnabled,filesEnabled:e.target.checked})}/>Enable files and external-link artifacts</label></section>}
 {activity&&<section className="hours-stack"><h2>{activity.title}</h2>{(activity.archived||!activity.impactRelevant)&&<p className="ui-status">Read-only activity: {activity.archived?'archived':'no longer impact-relevant'}. Existing notes and history are preserved.</p>}
 {activity.summary&&<section className="ui-card hours-stack"><h3>Current participant/hour summary</h3><p>{activity.summary.countedMinutes} counted minutes · {activity.summary.distinctParticipants} distinct participants</p></section>}
 {!sections?.summaryEnabled&&<p>Participant/hour summary is disabled.</p>}
 <section className="ui-card hours-stack"><h3>Notes</h3><p>Review applies to the saved content revision. Editing or archiving clears its current review; history is retained. Review never publishes a note.</p>{dirty&&<p>Save or cancel your draft before reviewing or changing another note.</p>}{!sections?.notesEnabled&&<p>Notes section is disabled. Preserved notes and immutable history remain readable.</p>}
 {notes?.notes.map(note=><article className="ui-card hours-stack" key={note.id}><h4>{note.archived?'Archived note (preserved)':'Note'} · revision {note.revision}</h4><p className="documentation-text">{note.text}</p><Provenance value={note.contributor}/><ReviewStatus value={note.review}/><p>Created {note.createdAt} · Updated {note.updatedAt}</p><div className="hours-actions"><button disabled={disabled||readOnly||note.archived||dirty} onClick={()=>{setEditing(note);setDraft(note.text);setHistory(undefined);}}>Edit note {note.revision}</button><button className="danger-button" disabled={disabled||readOnly||note.archived||dirty} onClick={()=>void write('/notes/'+id(note.id),'PATCH',{...revisions,revision:note.revision,archived:true})}>Archive note {note.revision}</button>{note.archived&&<button disabled={disabled||readOnly||dirty} onClick={()=>void write('/notes/'+id(note.id),'PATCH',{...revisions,revision:note.revision,archived:false})}>Unarchive note {note.revision}</button>}<button disabled={disabled||readOnly||note.archived||dirty} onClick={()=>void write('/notes/'+id(note.id)+'/review','POST',{...revisions,revision:note.revision,decision:'reviewed'})}>Review saved note {note.revision}</button><button disabled={disabled||readOnly||note.archived||dirty} onClick={()=>void write('/notes/'+id(note.id)+'/review','POST',{...revisions,revision:note.revision,decision:'rejected'})}>Reject saved note {note.revision}</button><button disabled={busy} onClick={()=>void showHistory(note)}>History for note {note.revision}</button></div></article>)}{notes?.notes.length===0&&<p>No notes yet.</p>}
 <div className="hours-actions"><button disabled={busy} onClick={()=>void read(async valid=>{const v=await current();if(!valid())return;setNotes(v.list);setActivity(v.detail);setSections(v.config);})}>First notes page</button>{notes?.next&&<button disabled={busy} onClick={()=>void read(async valid=>{const v=await current(activity,notes.next!);if(!valid())return;setNotes(v.list);setActivity(v.detail);setSections(v.config);})}>Next notes page</button>}</div>
 {!readOnly&&<form className="hours-stack" onSubmit={e=>{e.preventDefault();if(!invalid)void write(editing?'/notes/'+id(editing.id):'/activities/'+id(activity.id)+'/notes',editing?'PATCH':'POST',{...revisions,...(editing?{revision:editing.revision}:{}),text:draft});}}><label htmlFor="documentation-note">{editing?'Edit note text':'New note text'}</label><p id="documentation-help">Plain text only. Maximum 8000 characters; some symbols may count as two. {draft.length}/8000.</p><textarea id="documentation-note" value={draft} maxLength={8000} disabled={busy||accessChecking} aria-describedby="documentation-help" aria-invalid={!!draft&&invalid} onChange={e=>setDraft(e.target.value)}/><div className="hours-actions"><button className="primary-button" disabled={disabled||invalid}>{editing?'Save note':'Add note'}</button>{editing&&<button type="button" disabled={busy} onClick={()=>{setEditing(undefined);setDraft('');}}>Cancel edit</button>}</div></form>}
 </section>{history&&<section className="ui-card hours-stack"><h3>Immutable note history</h3>{history.page.revisions.map(item=><article key={item.revision}><h4>Revision {item.revision}{item.archived?' · Archived':''}</h4><p>{item.createdAt}</p><Provenance value={item.contributor}/><ReviewStatus value={item.review}/><p className="documentation-text">{item.text}</p></article>)}<div className="hours-actions"><button disabled={busy} onClick={()=>void showHistory(history.note)}>First history page</button>{history.page.next!==null&&<button disabled={busy} onClick={()=>void showHistory(history.note,history.page.next!)}>Next history page</button>}<button onClick={()=>setHistory(undefined)}>Close history</button></div></section>}</section>}
 </> }</section>;
}
