export type Contributor={kind:'staff'|'member';userId:string|null;memberId:string|null;source:'staff'|'public'|'discord';attribution:'staff'|'self_asserted'|'linked_discord';currentMemberLabel:string|null};
export type Review={decision:'reviewed'|'rejected';reviewedRevision:number;reviewerUserId:string;reviewedAt:string}|null;
export type Note={id:string;activityId:string;authorUserId:string|null;text:string;archived:boolean;revision:number;createdAt:string;updatedAt:string;contributor:Contributor;review:Review};
export type History={noteId:string;authorUserId:string|null;contributor:Contributor;createdAt:string;revisions:{revision:number;actorUserId:string|null;contributor:Contributor;review:Review;text:string;archived:boolean;createdAt:string}[];next:number|null};
const obj=(v:any)=>v&&typeof v==='object'&&!Array.isArray(v),str=(v:any,max=128)=>typeof v==='string'&&v.length>0&&v.length<=max,num=(v:any)=>Number.isSafeInteger(v)&&v>=0,stamp=(v:any)=>typeof v==='string'&&Number.isFinite(Date.parse(v));
function contributor(v:any):Contributor{if(!obj(v)||v.currentMemberLabel!==null&&typeof v.currentMemberLabel!=='string')throw Error('Invalid contributor');if(v.kind==='staff'){if(!str(v.userId)||v.memberId!==null||v.source!=='staff'||v.attribution!=='staff')throw Error('Invalid staff contributor');}else if(v.kind!=='member'||v.userId!==null||!str(v.memberId)||!['public','discord'].includes(v.source)||v.attribution!==(v.source==='public'?'self_asserted':'linked_discord'))throw Error('Invalid member contributor');return v;}
function review(v:any,revision:number):Review{if(v===null)return null;if(!obj(v)||!['reviewed','rejected'].includes(v.decision)||v.reviewedRevision!==revision-1||revision<1||!str(v.reviewerUserId)||!stamp(v.reviewedAt))throw Error('Invalid review');return v;}
export function noteValue(v:any):Note{if(!obj(v)||!str(v.id)||!str(v.activityId)||!str(v.text,8000)||typeof v.archived!=='boolean'||!num(v.revision)||!stamp(v.createdAt)||!stamp(v.updatedAt))throw Error('Invalid note');const c=contributor(v.contributor);if(v.authorUserId!==c.userId)throw Error('Mismatched author');review(v.review,v.revision);return v;}
export function historyValue(v:any,note:Note,after=-1):History{if(!obj(v)||v.noteId!==note.id||v.authorUserId!==note.authorUserId||!stamp(v.createdAt)||!Array.isArray(v.revisions)||v.revisions.length>25||v.next!==null&&!num(v.next))throw Error('Invalid history');const c=contributor(v.contributor);if(c.userId!==note.contributor.userId||c.memberId!==note.contributor.memberId||c.source!==note.contributor.source)throw Error('Mismatched author');let previous=after;for(const r of v.revisions){if(!obj(r)||!num(r.revision)||r.revision<=previous||!str(r.text,8000)||typeof r.archived!=='boolean'||!stamp(r.createdAt)||r.actorUserId!==contributor(r.contributor).userId)throw Error('Invalid revision');review(r.review,r.revision);previous=r.revision;}if(v.next!==null&&v.next!==previous)throw Error('Invalid cursor');return v;}
