import {useEffect,useRef,useState} from 'react';
import {GoogleDrivePickerSettings} from './google-drive-picker-settings';
import {DocumentationError,documentationRequest as api} from './documentation-request';
import {checkedSections,type Sections,type Selection} from './artifacts-contract';
type Operation={reference:string;title:string;state:'ready'|'validating'|'reconciling'|'saved'|'failed';saved:boolean;artifactId:string|null;requiresReconciliation:boolean;error?:string};
const base='/admin/documentation/drive-copies';
const names={ready:'Ready to preserve',validating:'Validating private copy',reconciling:'Copy needs reconciliation',saved:'Private copy saved',failed:'Copy not accepted'};
function checked(o:Operation,reference?:string){if(!o||typeof o.reference!=='string'||reference&&o.reference!==reference||typeof o.title!=='string'||!Object.hasOwn(names,o.state)||typeof o.saved!=='boolean'||o.saved!==(o.state==='saved')||typeof o.requiresReconciliation!=='boolean'||o.artifactId!==null&&typeof o.artifactId!=='string')throw Error('Invalid copy response');return o;}
export function DriveCopiesWorkspace({accessChecking=false,reloadAccess,onOccupied}:{accessChecking?:boolean;reloadAccess:()=>void;onOccupied:(value:boolean)=>void}){
 const [sections,setSections]=useState<Sections>(),[source,setSource]=useState<string|null>(null),[title,setTitle]=useState(''),[caption,setCaption]=useState(''),[choices,setChoices]=useState<Selection[]>([]),[links,setLinks]=useState<Selection[]>([]),[cursors,setCursors]=useState<Partial<Record<Selection['type'],string|null>>>({}),[rows,setRows]=useState<Operation[]>([]),[next,setNext]=useState<string|null>(null),[operation,setOperation]=useState<Operation>(),[busy,setBusy]=useState(false),[frozen,setFrozen]=useState(false),[notice,setNotice]=useState(''),[uncertain,setUncertain]=useState(false);
 const pending=useRef<string|undefined>(undefined),gate=useRef(false),generation=useRef(0),noticeRef=useRef<HTMLParagraphElement>(null);
 const disabled=busy||accessChecking,validTitle=!!title.trim()&&title.length<=200&&caption.length<=4000;
 useEffect(()=>onOccupied(busy||frozen&&!operation),[busy,frozen,operation,onOccupied]);useEffect(()=>{if(notice)noticeRef.current?.focus();},[notice]);
 async function run(action:(valid:()=>boolean)=>Promise<void>){if(gate.current||accessChecking)return;gate.current=true;setBusy(true);const token=generation.current;try{await action(()=>token===generation.current);}catch(e){if(token===generation.current){setUncertain(true);setNotice('The result is unconfirmed. Keep this page open. Check the existing copy or explicitly retry its unchanged request; do not create a replacement.');if(e instanceof DocumentationError&&[401,403].includes(e.status)){setRows([]);setChoices([]);setSource(null);reloadAccess();}}}finally{if(token===generation.current){gate.current=false;setBusy(false);}}}
 async function inventory(after=''){const p=await api<{operations:Operation[];next:string|null}>(base+'?limit=25'+(after?'&after='+encodeURIComponent(after):''));if(!Array.isArray(p.operations)||p.next!==null&&typeof p.next!=='string')throw Error();p.operations.forEach(o=>checked(o));return p;}
 async function choicePage(type:Selection['type'],after=''){const p=await api<Record<string,any>>('/admin/documentation/'+type+'?limit=25'+(after?'&after='+encodeURIComponent(after):''));if(!Array.isArray(p[type]))throw Error();const items:Selection[]=p[type].map((x:any)=>{if(typeof x.id!=='string'||typeof x.title!=='string'||!Number.isSafeInteger(x.revision))throw Error();return {id:x.id,title:x.title,revision:x.revision,type,eligible:!x.archived&&(type==='initiatives'||x.impactRelevant===true)};});return {items,next:p.next as string|null};}
 async function load(){await run(async valid=>{const [s,p,a,i]=await Promise.all([api<Sections>('/admin/documentation/sections').then(checkedSections),inventory(),choicePage('activities'),choicePage('initiatives')]);if(!valid())return;setSections(s);setRows(p.operations);setNext(p.next);setChoices([...a.items,...i.items]);setCursors({activities:a.next,initiatives:i.next});if(!pending.current)setLinks([]);setUncertain(false);});}
 useEffect(()=>{gate.current=false;void load();return()=>{generation.current++;};},[]);
 useEffect(()=>{if(accessChecking){generation.current++;gate.current=false;setBusy(false);setSource(null);if(pending.current)setNotice('Access is being checked. This copy request is retained; check the same operation when access returns.');}else if(!sections)void load();},[accessChecking]);
 async function admit(){await run(async valid=>{if(!pending.current){if(!source||!sections?.filesEnabled||!validTitle)return;pending.current=JSON.stringify({sourceIntentId:source,title,caption,sectionRevision:sections.revision,activities:links.filter(l=>l.type==='activities').map(l=>({activityId:l.id,revision:l.revision})),initiatives:links.filter(l=>l.type==='initiatives').map(l=>({initiativeId:l.id,revision:l.revision})),idempotencyKey:crypto.randomUUID()});setFrozen(true);}const o=checked(await api<Operation>(base,{method:'POST',body:pending.current}));if(!valid())return;setOperation(o);setUncertain(false);setNotice('Copy request recorded. Continue this same operation to preserve the selected original.');});}
 async function act(o:Operation,action:'check'|'advance'|'reconcile'){await run(async valid=>{const result=checked(await api<Operation>(base+'/'+encodeURIComponent(o.reference)+(action==='check'?'':'/'+action),action==='check'?undefined:{method:'POST',body:'{}'}),o.reference);if(!valid())return;if(operation?.reference===o.reference)setOperation(result);setRows(items=>items.map(item=>item.reference===o.reference?result:item));setUncertain(false);setNotice(result.saved?'Private copy saved. Review it in Artifacts; staff review and publication are separate.':result.requiresReconciliation?'Copy ownership or source state remains unresolved. Reconcile this operation; a second copy is not created.':'Current copy state confirmed. Continue explicitly when ready.');});}
 function actions(o:Operation){return <div className="hours-actions"><button disabled={disabled} onClick={()=>void act(o,'check')}>Check {o.title}</button>{!o.saved&&o.state!=='failed'&&(o.requiresReconciliation||o.state==='reconciling'?<button disabled={disabled} onClick={()=>void act(o,'reconcile')}>Reconcile {o.title}</button>:<button disabled={disabled} onClick={()=>void act(o,'advance')}>Continue {o.title}</button>)}</div>;}
 return <section className="hours-stack" aria-busy={disabled}><h2>Preserved Drive copies</h2><p>Keep private evidence from Drive without changing hours or publishing files. Native Google files retain their native format; binary files are limited to 4 MiB. Folders and shortcuts cannot be copied as evidence.</p>{notice&&<p ref={noticeRef} tabIndex={-1} role={uncertain?'alert':'status'} className="ui-status">{notice}</p>}
 {!frozen&&<GoogleDrivePickerSettings documentationMode disabled={disabled||!sections?.filesEnabled} onSourceSelection={setSource}/>}
 <fieldset className="hours-stack" disabled={disabled||frozen||!sections?.filesEnabled}><legend>Copy details</legend><label>Copy title<input required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Copy caption<textarea maxLength={4000} value={caption} onChange={e=>setCaption(e.target.value)}/></label><p>Optional associations; up to 100 activities and initiatives combined.</p>{(['activities','initiatives'] as const).map(type=><section className="hours-stack" key={type}><h3>{type==='activities'?'Eligible activities':'Active initiatives'}</h3>{choices.filter(x=>x.type===type).map(x=><label className="hours-check" key={x.id}><input type="checkbox" checked={links.some(l=>l.id===x.id&&l.type===type)} disabled={!x.eligible||links.length>=100&&!links.some(l=>l.id===x.id&&l.type===type)} onChange={e=>setLinks(e.target.checked?[...links,x]:links.filter(l=>l.id!==x.id||l.type!==type))}/>Associate {x.title}</label>)}{cursors[type]&&<button type="button" onClick={()=>void run(async valid=>{const p=await choicePage(type,cursors[type]!);if(valid()){setChoices(items=>[...items.filter(x=>x.type!==type),...p.items]);setCursors(c=>({...c,[type]:p.next}));}})}>Next {type} choices</button>}</section>)}{links.length>0&&<ul>{links.map(l=><li key={l.type+l.id}>{l.title} <button type="button" onClick={()=>setLinks(items=>items.filter(x=>x!==l))}>Remove {l.title}</button></li>)}</ul>}</fieldset>
 {!frozen&&<div className="hours-actions"><button disabled={disabled} onClick={()=>void load()}>Reload copy context</button><button className="primary-button" disabled={disabled||!sections?.filesEnabled||!source||!validTitle} onClick={()=>void admit()}>Preserve selected original</button></div>}{!sections?.filesEnabled&&<p>Files are unavailable. Existing copy records remain readable.</p>}
 {frozen&&<p className="ui-status">Keep this page open until confirmed. The original request is frozen to prevent a duplicate copy.</p>}{frozen&&!operation&&<button disabled={disabled} onClick={()=>void admit()}>Retry this same copy request</button>}
 {operation&&<section className="ui-card hours-stack"><h3>{names[operation.state]}</h3><p>{operation.title}</p><p className="documentation-text">Copy reference: {operation.reference}</p>{actions(operation)}{(operation.saved||operation.state==='failed')&&<button disabled={disabled} onClick={()=>{pending.current=undefined;setFrozen(false);setOperation(undefined);setTitle('');setCaption('');setSource(null);void load();}}>{operation.saved?'Start a separate copy':'Choose a different original'}</button>}</section>}
 <section className="ui-card hours-stack"><h3>Copy inventory</h3><p>Reconciliation checks the original private destination and connection. An unresolved copy must not be replaced by another admission.</p><div className="hours-actions"><button disabled={disabled} onClick={()=>void run(async valid=>{const p=await inventory();if(valid()){setRows(p.operations);setNext(p.next);}})}>Reload copy inventory</button>{next&&<button disabled={disabled} onClick={()=>void run(async valid=>{const p=await inventory(next);if(valid()){setRows(p.operations);setNext(p.next);}})}>Next copies page</button>}</div>{rows.filter(o=>o.reference!==operation?.reference).map(o=><article className="ui-card hours-stack" key={o.reference}><h4>{o.title}</h4><p>{names[o.state]}</p><p className="documentation-text">Copy reference: {o.reference}</p>{actions(o)}</article>)}</section></section>;
}
