import {useEffect,useRef,useState} from 'react';
import {apiBaseUrl} from './dashboard-api';
import {documentationActivities,type PublicActivity} from './public-documentation-contract';
type Progress={reference:string;state:'uploading'|'validating'|'ready'|'preserving'|'reconciling'|'saved'|'failed'|'expired';nextChunk:number;chunkSize:number;maxBytes:number;expiresAt:number;saved:boolean;error?:string;ticket?:string};
type Pending={body:string;bytes:Uint8Array;ticket?:string;progress?:Progress;label:string};
class UploadError extends Error{constructor(public status:number){super('File request not confirmed');}}
async function request(path:string,publicMode:boolean,method='GET',body?:BodyInit,ticket?:string){const headers:Record<string,string>={};if(body!==undefined)headers['content-type']=method==='PUT'?'application/octet-stream':'application/json';if(ticket)headers['x-lancerlogin-upload-ticket']=ticket;const response=await fetch(apiBaseUrl+path,{method,body,headers,credentials:publicMode?'omit':'include',signal:AbortSignal.timeout(45000)});if(!response.ok)throw new UploadError(response.status);return response.json();}
function progress(v:any,reference?:string):Progress{if(!v||typeof v.reference!=='string'||reference&&v.reference!==reference||!['uploading','validating','ready','preserving','reconciling','saved','failed','expired'].includes(v.state)||!Number.isSafeInteger(v.nextChunk)||v.nextChunk<0||v.nextChunk>16||v.chunkSize!==262144||v.maxBytes!==4194304||!Number.isSafeInteger(v.expiresAt)||typeof v.saved!=='boolean'||v.saved!==(v.state==='saved')||v.ticket!==undefined&&!/^[a-f0-9]{64}$/.test(v.ticket))throw Error('Invalid file status');return v;}
const names:Record<Progress['state'],string>={uploading:'Sending file',validating:'Checking original file',ready:'Preparing private storage',preserving:'Preserving original',reconciling:'Staff reconciliation needed',saved:'File saved privately',failed:'File was not accepted',expired:'Upload expired'};
export function FileUpload({publicMode=false,accessChecking=false,reloadAccess=()=>{},onOccupied=()=>{}}:{publicMode?:boolean;accessChecking?:boolean;reloadAccess?:()=>void;onOccupied?:(v:boolean)=>void}){
 const [member,setMember]=useState(''),[file,setFile]=useState<File>(),[title,setTitle]=useState(''),[caption,setCaption]=useState(''),[activity,setActivity]=useState<PublicActivity>(),[activities,setActivities]=useState<PublicActivity[]>([]),[next,setNext]=useState<string|null>(null),[section,setSection]=useState<number>(),[available,setAvailable]=useState(false),[busy,setBusy]=useState(false),[frozen,setFrozen]=useState(false),[state,setState]=useState<Progress>(),[notice,setNotice]=useState(''),[uncertain,setUncertain]=useState(false);
 const generation=useRef(0),gate=useRef(false),pending=useRef<Pending|undefined>(undefined),noticeRef=useRef<HTMLParagraphElement>(null),fileRef=useRef<HTMLInputElement>(null);const base=(publicMode?'/public':'/admin')+'/documentation/uploads';
 useEffect(()=>{onOccupied(busy||frozen);},[busy,frozen,onOccupied]);useEffect(()=>{if(notice)noticeRef.current?.focus();},[notice]);
 useEffect(()=>{gate.current=false;void load();return()=>{generation.current++;pending.current=undefined;};},[]);
 useEffect(()=>{if(accessChecking){generation.current++;gate.current=false;setBusy(false);if(pending.current&&!pending.current.progress?.saved){setFrozen(true);setUncertain(true);setNotice('Access is being checked. This submission is retained. When access returns, explicitly check or retry this same upload; its previous request may already have succeeded.');}}},[accessChecking]);
 function failure(e:unknown){setUncertain(true);if(!publicMode&&e instanceof UploadError&&[401,403].includes(e.status)){pending.current=undefined;setFrozen(false);setState(undefined);setFile(undefined);setTitle('');setCaption('');reloadAccess();}setNotice(e instanceof UploadError&&e.status===429?'Too many requests. Wait before explicitly checking or continuing this upload.':e instanceof UploadError&&e.status===403?'Upload access or its time limit ended. Ask staff to find this existing submission; do not send it again.':'The file result is unconfirmed. Keep this page open and check this upload before continuing. It may already be stored; no new submission was created automatically.');}
 async function load(after=''){if(gate.current||pending.current||accessChecking)return;gate.current=true;setBusy(true);const token=generation.current;try{let sr:number,rows:PublicActivity[],cursor:string|null;
 if(publicMode){const c=await request(base+'/context',true);if(c.available!==true){if(token===generation.current){setAvailable(false);setActivities([]);}return;}if(!Number.isSafeInteger(c.sectionRevision))throw Error();sr=c.sectionRevision;const page=documentationActivities(await request(base+'/activities?limit=25'+(after?'&after='+encodeURIComponent(after):''),true),sr);rows=page.activities;cursor=page.next;}
 else{const c=await request('/admin/documentation/sections',false);if(!Number.isSafeInteger(c.revision)||typeof c.filesEnabled!=='boolean')throw Error();sr=c.revision;const p=await request('/admin/documentation/activities?limit=25'+(after?'&after='+encodeURIComponent(after):''),false);if(!Array.isArray(p.activities))throw Error();rows=p.activities.filter((a:any)=>!a.archived&&a.impactRelevant).map((a:any)=>({id:a.id,title:a.title,serviceDate:a.serviceDate,revision:a.revision,mode:a.mode}));cursor=p.next;if(!c.filesEnabled){if(token===generation.current)setAvailable(false);return;}}
 if(token!==generation.current)return;setSection(sr);setActivities(rows);setNext(cursor);setActivity(undefined);setAvailable(true);setUncertain(false);
 }catch(e){if(token===generation.current){setAvailable(false);failure(e);}}finally{if(token===generation.current){gate.current=false;setBusy(false);}}}
 async function run(checkOnly=false){if(gate.current||accessChecking)return;gate.current=true;setBusy(true);setUncertain(false);const token=generation.current,valid=()=>token===generation.current;
 try{if(!pending.current){if(checkOnly||!file||!available||section===undefined||!title.trim()||title.length>200||caption.length>4000||publicMode&&(!member.trim()||member.length>128||!activity))return;if(file.size<1||file.size>4194304){setNotice('Choose one nonempty file up to 4 MiB. Nothing was submitted.');return;}const bytes=new Uint8Array(await file.arrayBuffer());if(!valid())return;const sha=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');if(!valid())return;const body=JSON.stringify({...(publicMode?{memberId:member}:{}),title,caption,mime:file.type||'application/octet-stream',byteLength:bytes.length,sha256:sha,sectionRevision:section,activities:activity?[{activityId:activity.id,revision:activity.revision}]:[],idempotencyKey:crypto.randomUUID()});pending.current={body,bytes,label:file.name};setFrozen(true);}
 const p=pending.current!;if(!p.progress){const value=progress(await request(base,publicMode,'POST',p.body));if(!valid())return;if(!value.ticket)throw Error();p.progress=value;p.ticket=value.ticket;setState(value);}
 else if(checkOnly){const value=progress(await request(base+'/'+encodeURIComponent(p.progress.reference),publicMode,'GET',undefined,p.ticket),p.progress.reference);if(!valid())return;p.progress=value;setState(value);setNotice(value.saved?'File saved privately. Notes and hours have separate outcomes.':'Current upload checked. Continue this same upload when ready.');return;}
 for(let step=0;step<40&&valid();step++){const current=p.progress!;if(current.saved){setNotice('File saved privately. Staff review is separate; notes and hours are unchanged.');setFrozen(false);return;}if(['reconciling','failed','expired'].includes(current.state)){setNotice(current.state==='reconciling'?'Ask staff to reconcile this existing upload. Do not create a replacement.':'This file was not accepted. Ask staff before starting a separate submission.');return;}const target=base+'/'+encodeURIComponent(current.reference);let value:any;
 if(current.state==='uploading'){const offset=current.nextChunk*262144;value=offset<p.bytes.length?await request(target+'/chunks/'+current.nextChunk,publicMode,'PUT',p.bytes.slice(offset,offset+262144) as BodyInit,p.ticket):await request(target+'/seal',publicMode,'POST','{}',p.ticket);}
 else value=await request(target+'/advance',publicMode,'POST','{}',p.ticket);
 if(!valid())return;p.progress=progress(value,current.reference);setState(p.progress);if(current.state==='validating'&&p.progress.state==='validating'){setNotice('Validation is still running. Check the upload, then continue when ready.');return;}}
 }catch(e){if(valid())failure(e);}finally{if(valid()){gate.current=false;setBusy(false);}}}
 const disabled=busy||accessChecking,invalid=!file||!title.trim()||title.length>200||caption.length>4000||publicMode&&(!member.trim()||!activity);
 return <section className="ui-card hours-stack" aria-busy={disabled}><h2>{publicMode?'Submit a file':'Upload original evidence'}</h2><p id="file-upload-help">One file, up to 4 MiB. Originals remain private. Uploading does not submit a note, change hours, or mark evidence reviewed.</p><p>Keep this page open until confirmed. Closing it loses this upload's recovery information.</p>{notice&&<p ref={noticeRef} tabIndex={-1} role={uncertain?'alert':'status'} className="ui-status">{notice}</p>}
 {state&&<section className="hours-stack"><h3>{names[state.state]}</h3><p>{pending.current?.label}</p><p>{state.state==='uploading'?`${Math.min(state.nextChunk*262144,pending.current?.bytes.length??0)} of ${pending.current?.bytes.length??0} bytes sent`:state.saved?'Private persistence confirmed.':'The file has not yet been confirmed saved.'}</p><p>Submission reference: <span className="documentation-text">{state.reference}</span></p>{state.error==='OWNERSHIP_VERIFIED_ELIGIBILITY_REQUIRED'&&<p>Storage was verified, but contribution eligibility needs staff attention.</p>}</section>}
 {frozen&&<p className="ui-status">This submission may already exist. Do not select a replacement or resend it as a new upload. Ask staff if access expires.</p>}
 <fieldset className="hours-stack" disabled={disabled||frozen||!!state?.saved}>{publicMode&&<label>File contributor member ID<input autoComplete="off" maxLength={128} value={member} onChange={e=>setMember(e.target.value)}/></label>}<label className="file-picker">Evidence file<input ref={fileRef} type="file" aria-describedby="file-upload-help" onChange={e=>{const f=e.target.files?.[0];setFile(f);if(!title&&f)setTitle(f.name.slice(0,200));}}/></label><label>File title<input maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>File caption<textarea maxLength={4000} value={caption} onChange={e=>setCaption(e.target.value)}/></label><label htmlFor="file-activity">File activity</label><select id="file-activity" className="ui-native-select" value={activity?.id??''} onChange={e=>setActivity(activities.find(a=>a.id===e.target.value))}><option value="">{publicMode?'Choose an activity':'No activity association'}</option>{activities.map(a=><option key={a.id} value={a.id}>{a.title} · {a.serviceDate}</option>)}</select></fieldset>
 {!frozen&&!state?.saved&&<div className="hours-actions"><button disabled={disabled} onClick={()=>void load()}>Reload file activities</button>{next&&<button disabled={disabled} onClick={()=>void load(next)}>Next file activities page</button>}<button className="primary-button" disabled={disabled||!available||invalid} onClick={()=>void run()}>Upload file</button></div>}
 {!available&&!frozen&&<p>File submission is unavailable. Ask staff about Files settings and private storage.</p>}
 {pending.current&&!state?.saved&&<div className="hours-actions">{state&&<button disabled={disabled} onClick={()=>void run(true)}>Check this upload</button>}<button disabled={disabled||state?.state==='reconciling'||state?.state==='failed'||state?.state==='expired'} onClick={()=>void run() }>{state?'Continue this upload':'Retry this submission'}</button></div>}
 {state?.saved&&<button disabled={disabled} onClick={()=>{pending.current=undefined;setState(undefined);setFile(undefined);if(fileRef.current)fileRef.current.value='';setTitle('');setCaption('');setNotice('');setFrozen(false);void load();}}>Start a separate file</button>}
 </section>;
}
export function UploadInventory({accessChecking=false,reloadAccess}:{accessChecking?:boolean;reloadAccess:()=>void}){
 const [rows,setRows]=useState<(Progress&{title:string;source:string})[]>([]),[next,setNext]=useState<string|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');const generation=useRef(0),gate=useRef(false);
 async function load(after=''){if(gate.current||accessChecking)return;gate.current=true;setBusy(true);const token=generation.current;try{const p=await request('/admin/documentation/uploads?limit=25'+(after?'&after='+encodeURIComponent(after):''),false);if(!Array.isArray(p.operations)||p.operations.some((o:any)=>typeof o.title!=='string'))throw Error();p.operations.forEach((o:any)=>progress(o));if(token===generation.current){setRows(p.operations);setNext(p.next);}}catch(e){if(token===generation.current){setRows([]);setNotice('Current upload inventory is unavailable. Reload access and try again.');if(e instanceof UploadError&&[401,403].includes(e.status))reloadAccess();}}finally{if(token===generation.current){gate.current=false;setBusy(false);}}}
 useEffect(()=>{gate.current=false;void load();return()=>{generation.current++;};},[]);useEffect(()=>{if(accessChecking){generation.current++;gate.current=false;setBusy(false);setRows([]);setNext(null);}},[accessChecking]);
 async function reconcile(o:Progress){if(gate.current||accessChecking)return;gate.current=true;setBusy(true);const token=generation.current;try{const value=progress(await request('/admin/documentation/uploads/'+encodeURIComponent(o.reference)+'/reconcile',false,'POST','{}'),o.reference);if(token!==generation.current)return;setRows(items=>items.map(x=>x.reference===o.reference?{...x,...value}:x));setNotice(value.saved?'Original file confirmed and artifact saved.':value.error==='OWNERSHIP_VERIFIED_ELIGIBILITY_REQUIRED'?'Private ownership verified. Original contribution eligibility still requires attention.':'Reconciliation is incomplete. Keep the same original root and connection; do not create a replacement.');}catch(e){if(token===generation.current){if(e instanceof UploadError&&[401,403].includes(e.status)){setRows([]);reloadAccess();}setNotice('Reconciliation was not confirmed. Reload this inventory. Verify the original private root and organizational connection before trying again.');}}finally{if(token===generation.current){gate.current=false;setBusy(false);}}}
 return <section className="ui-card hours-stack"><h2>Upload reconciliation</h2><p>Reconciliation uses the original private root and organizational connection. It does not move files, replace an upload or bypass contribution eligibility.</p>{notice&&<p role="status" className="ui-status">{notice}</p>}<div className="hours-actions"><button disabled={busy||accessChecking} onClick={()=>void load()}>Reload upload inventory</button>{next&&<button disabled={busy||accessChecking} onClick={()=>void load(next)}>Next upload inventory page</button>}</div>{rows.map(o=><article className="ui-card hours-stack" key={o.reference}><h3>{o.title}</h3><p>Submission reference: <span className="documentation-text">{o.reference}</span></p><p>{names[o.state]} · {o.source==='staff'?'Staff submission':o.source==='discord'?'Member submission through Discord':'Member submission through public form'}</p>{!o.saved&&<button disabled={busy||accessChecking} onClick={()=>void reconcile(o)}>Reconcile {o.title}</button>}</article>)}</section>;
}
