import {useCallback,useEffect,useRef,useState} from 'react';
import {documentationRequest as api,DocumentationError} from './documentation-request';
import {GoogleDrivePickerSettings} from './google-drive-picker-settings';
type Storage={configured:boolean;revision:number;rootId:string|null;rootName:string|null;verifiedAt:string|null;verifiedForConnection:boolean};
type Selection={intentId:string;connectionRevision:number};
const path='/admin/connections/google/storage';
function checked(value:Storage){if(!value||typeof value.configured!=='boolean'||!Number.isSafeInteger(value.revision)||typeof value.verifiedForConnection!=='boolean'||value.rootName!==null&&typeof value.rootName!=='string'||value.verifiedAt!==null&&typeof value.verifiedAt!=='string')throw Error('Invalid storage');return value;}
export function GoogleDriveStorageSettings({available}:{available:boolean}){
 const [snapshot,setSnapshot]=useState<Storage>(),[selection,setSelection]=useState<Selection|null>(null),[busy,setBusy]=useState(false),[locked,setLocked]=useState(true),[notice,setNotice]=useState(''),[picker,setPicker]=useState(false),[feasibility,setFeasibility]=useState(false),[epoch,setEpoch]=useState(0);
 const generation=useRef(0),pending=useRef(false),message=useRef<HTMLParagraphElement>(null),focusNotice=useRef(false);
 const selected=useCallback((value:Selection|null)=>setSelection(value),[]);
 function failure(error:unknown){setLocked(true);setSelection(null);setPicker(false);if(error instanceof DocumentationError&&[401,403].includes(error.status))setSnapshot(undefined);setNotice('Shared storage could not be confirmed. Reload shared storage and check current Admin access and Google connection before a new selection. No write is retried automatically.');}
 async function reload(initial=false){if(pending.current)return;focusNotice.current=!initial;pending.current=true;setBusy(true);const token=generation.current;try{const value=checked(await api<Storage>(path));if(token!==generation.current)return;setSnapshot(value);setLocked(false);setSelection(null);setPicker(false);setNotice('Saved storage inventory reloaded. Select a folder again before a new explicit save.');}catch(error){if(token===generation.current)failure(error);}finally{if(token===generation.current){pending.current=false;setBusy(false);}}}
 useEffect(()=>{pending.current=false;void reload(true);return()=>{generation.current++;};},[]);
 useEffect(()=>{setSelection(null);setPicker(false);setFeasibility(false);setEpoch(value=>value+1);},[available]);
 useEffect(()=>{if(notice&&focusNotice.current)message.current?.focus();},[notice]);
 async function save(){if(pending.current||locked||!available||!snapshot||!selection)return;focusNotice.current=true;pending.current=true;setBusy(true);const token=generation.current,submitted=selection,revision=snapshot.revision;setSelection(null);setPicker(false);try{const result=await api<{saved:boolean;revision:number}>(path,{method:'PUT',body:JSON.stringify({revision,pickerIntentId:submitted.intentId,connectionRevision:submitted.connectionRevision})});if(token!==generation.current)return;const value=checked(await api<Storage>(path));if(token!==generation.current)return;if(!result.saved||result.revision!==revision+1||value.revision!==result.revision||!value.verifiedForConnection)throw Error('Unconfirmed storage');setSnapshot(value);setNotice('Shared storage saved. Folder ownership and permissions were checked during this save; later use must check them again.');}catch(error){if(token===generation.current)failure(error);}finally{if(token===generation.current){pending.current=false;setBusy(false);}}}
 return <section className="integration-card google-connection" aria-busy={busy}><h2>Shared Drive storage</h2><p>One private folder configuration for this installation. External-link artifacts do not require Drive storage.</p>{notice&&<p ref={message} tabIndex={-1} role={locked?'alert':'status'} className="ui-status">{notice}</p>}<div className="google-actions"><button disabled={busy} onClick={()=>void reload()}>Reload shared storage</button></div>{snapshot&&<><p>Saved folder: {snapshot.configured?snapshot.rootName:'Not configured'}</p><p>{snapshot.verifiedForConnection&&available?'Previously verified for the current Google connection. This is not a fresh folder privacy check.':snapshot.configured?'Saved inventory only. Select and verify the private folder again after restore or a connection change.':'Choose and save a private folder when storage is needed.'}</p>{snapshot.verifiedAt&&<p>Last verification: {snapshot.verifiedAt}</p>}</>}{!available&&<p>Drive capability is unavailable. Restore the shared Google connection and reload it before selecting storage. Saved inventory remains visible.</p>}<div className="google-actions"><button disabled={busy||locked||!available} onClick={()=>{setFeasibility(false);setPicker(true);setEpoch(value=>value+1);setSelection(null);}}>Select shared storage folder</button><button disabled={busy||locked||!available} onClick={()=>{setPicker(false);setSelection(null);setFeasibility(value=>!value);}}>Development feasibility controls</button></div>{available&&!busy&&picker&&<GoogleDrivePickerSettings key={epoch} storageMode onRootSelection={selected}/>} {selection&&<p>A selected folder is ready for a fresh ownership and permissions check. Saving replaces the current shared folder configuration.</p>}<div className="google-actions"><button className="primary-button" disabled={busy||locked||!available||!selection} onClick={()=>void save()}>Verify and save shared folder</button></div>{available&&!busy&&feasibility&&<GoogleDrivePickerSettings/>}</section>;
}
