import {GoogleDriveProofControls} from './google-drive-proof-controls';
import {useEffect,useId,useRef,useState,type FormEvent} from 'react';
import {api} from './dashboard-api';
const base='/admin/connections/google/drive';
type Status={revision:number;configRevision:number;configured:boolean;rootName:string|null;intent:null|{id:string;purpose:'root'|'source'|'documentation-source';status:string;diagnostic?:unknown}};
declare global {interface Window {gapi?:any;google?:any;}}
function status(value:Status){if(!value||!Number.isSafeInteger(value.revision)||!Number.isSafeInteger(value.configRevision)||typeof value.configured!=='boolean'||value.rootName!==null&&(typeof value.rootName!=='string'||value.rootName.length>255)||value.intent&&(!['root','source','documentation-source'].includes(value.intent.purpose)||!['pending','exchanging','ready','claimed','selected'].includes(value.intent.status)||typeof value.intent.id!=='string'||value.intent.id.length>128))throw Error();return value;}
const failureGuidance:Record<string,Record<string,string>>={
 admission:{consent_declined:'Google authorization was declined. Start a new selection authorization when ready.',code_missing:'Google returned without an authorization code. Start a new selection authorization when ready.'},
 code_exchange:{state_unavailable:'The saved selection authorization could not be opened. Start a new selection authorization when ready.',provider_unconfirmed:'Google did not confirm the authorization-code exchange. Ask the maintainer to review the connection before trying again.'},
 token_validation:{access_token_shape:'Google did not return a usable selection token. The maintainer needs to review the provider response contract.',scope_mismatch:'Google did not return access limited to selected Drive files. Picker access was blocked; the maintainer needs to verify scope isolation.',token_type_mismatch:'Google returned an unsupported selection token type. The maintainer needs to review the provider response contract.',expiry_shape:'Google did not return a valid selection-token lifetime. The maintainer needs to review the provider response contract.'},
 token_information:{provider_unconfirmed:'Google did not confirm the selection-token information. Ask the maintainer to review provider availability before trying again.'},
 identity_validation:{client_mismatch:'Google could not confirm that selection access belongs to this application. Ask the maintainer to review the shared client configuration.',subject_mismatch:'Google token information could not confirm the organizational account. The maintainer needs to review account verification before another attempt.',scope_mismatch:'Google token information did not confirm access limited to selected Drive files. Picker access was blocked; the maintainer needs to verify scope isolation.',expiry_shape:'Google token information did not confirm a valid access lifetime. The maintainer needs to review the provider response contract.'},
 drive_identity:{provider_unconfirmed:'Google did not confirm Drive account ownership. Ask the maintainer to review provider availability before trying again.',identity_invalid:'Google did not return a usable Drive account identity. The maintainer needs to review the provider response contract.',account_mismatch:'The selected Drive account did not match the organizational connection. Start a new selection authorization with the organizational account.',connection_changed:'The shared Google connection changed while Drive ownership was checked. Reload its settings before starting a new selection authorization.'},
 persistence:{connection_changed:'The shared Google connection changed during authorization. Reload its settings before starting a new selection authorization.',write_unconfirmed:'Selection authorization could not be saved under the current access and connection settings. Reload settings before starting a new authorization.'},
};
function diagnosticGuidance(intent:Status['intent']){
 const value=intent?.diagnostic;if(intent?.status!=='exchanging'||!value||typeof value!=='object'||Array.isArray(value))return '';
 const record=value as Record<string,unknown>;
 if(Object.keys(record).length!==2||typeof record.stage!=='string'||typeof record.reason!=='string'||!Object.hasOwn(failureGuidance,record.stage)||!Object.hasOwn(failureGuidance[record.stage],record.reason))return '';
 return failureGuidance[record.stage][record.reason];
}
async function loadPicker(){
 if(!window.gapi)await new Promise<void>((resolve,reject)=>{const script=document.createElement('script');script.src='https://apis.google.com/js/api.js';script.async=true;script.onload=()=>resolve();script.onerror=()=>reject(Error());document.head.append(script);});
 await new Promise<void>((resolve,reject)=>window.gapi.load('picker',{callback:resolve,onerror:()=>reject(Error()),timeout:10000,ontimeout:()=>reject(Error())}));
}
export function GoogleDrivePickerSettings({storageMode=false,documentationMode=false,disabled=false,onSourceSelection,onRootSelection}:{storageMode?:boolean;documentationMode?:boolean;disabled?:boolean;onSourceSelection?:(intentId:string|null)=>void;onRootSelection?:(value:{intentId:string;connectionRevision:number}|null)=>void}){
 const Heading=storageMode?'h3':'h2';
 const id=useId(),noticeRef=useRef<HTMLParagraphElement>(null),pickerRef=useRef<any>(undefined),alive=useRef(true),lock=useRef(false),focusNotice=useRef(false);
 const closePicker=useRef<(()=>void)|undefined>(undefined);
 const disabledRef=useRef(disabled);disabledRef.current=disabled;
 useEffect(()=>{if(disabled&&closePicker.current){closePicker.current();setBlocked(true);}},[disabled]);
 const [snapshot,setSnapshot]=useState<Status>(),[busy,setBusy]=useState(false),[blocked,setBlocked]=useState(true),[notice,setNotice]=useState(''),[project,setProject]=useState(''),[browserKey,setBrowserKey]=useState('');
 async function read(){const current=status(await api<Status>(base+'/status'+(documentationMode?'?purpose=documentation-source':'')));if(!alive.current)return current;setSnapshot(current);setBlocked(false);onSourceSelection?.(current.intent?.purpose==='documentation-source'&&current.intent.status==='selected'?current.intent.id:null);onRootSelection?.(current.intent?.purpose==='root'&&current.intent.status==='selected'?{intentId:current.intent.id,connectionRevision:current.revision}:null);return current;}
 function error(focus=true){if(!alive.current)return;onRootSelection?.(null);onSourceSelection?.(null);focusNotice.current=focus;setBlocked(true);setNotice('Drive selection could not be confirmed. Reload status before another action. Check shared Drive consent and your current staff access. No action will be retried automatically.');}
 async function reload(callback?:string,initial=false){if(lock.current)return;focusNotice.current=!initial||callback==="failed";lock.current=true;setBusy(true);try{const current=await read(),guidance=diagnosticGuidance(current.intent);setNotice(guidance?guidance+' Current Drive selection status loaded. No authorization will be retried automatically.':(callback==='failed'?'Google did not complete isolated Drive authorization. Select the organizational account and authorize again. ':'')+'Current Drive selection status loaded. A claimed Picker session cannot be recovered after reload; authorize another selection if needed.');}catch{error(!initial);}finally{lock.current=false;setBusy(false);}}
 useEffect(()=>{alive.current=true;const url=new URL(window.location.href),marker=url.searchParams.get('drivePicker')??undefined;url.searchParams.delete('drivePicker');window.history.replaceState({},'',url);void reload(marker,true);return()=>{alive.current=false;closePicker.current?.();pickerRef.current?.setVisible(false);pickerRef.current?.dispose?.();pickerRef.current=undefined;};},[]);
 useEffect(()=>{if(notice&&focusNotice.current)noticeRef.current?.focus();},[notice]);
 async function configure(event:FormEvent){event.preventDefault();focusNotice.current=true;if(!snapshot||lock.current||blocked||disabled)return;onRootSelection?.(null);onSourceSelection?.(null);lock.current=true;setBusy(true);const submitted=browserKey;setBrowserKey('');try{await api(base+'/configuration',{method:'PUT',body:JSON.stringify({revision:snapshot.revision,configRevision:snapshot.configRevision,projectNumber:project,browserKey:submitted})});await read();setNotice('Picker configuration saved and reloaded. Select the private development test folder next.');}catch{error();}finally{lock.current=false;setBusy(false);}}
 async function authorize(purpose:'root'|'source'|'documentation-source'){
  if(!snapshot||lock.current||blocked||disabled)return;onRootSelection?.(null);onSourceSelection?.(null);lock.current=true;setBusy(true);
  try{const result=await api<{authorizationUrl:string}>(base+'/picker/authorize',{method:'POST',body:JSON.stringify({revision:snapshot.revision,purpose})}),url=new URL(result.authorizationUrl);if(url.origin!=='https://accounts.google.com'||url.pathname!=='/o/oauth2/v2/auth'||url.searchParams.get('scope')!=='https://www.googleapis.com/auth/drive.file'||url.searchParams.get('include_granted_scopes')!=='false'||url.searchParams.get('redirect_uri')!==window.location.origin+'/api/admin/connections/google/callback')throw Error();window.location.assign(url.href);}catch{error();lock.current=false;setBusy(false);}
 }
 async function choose(){focusNotice.current=true;
  if(!snapshot?.intent||lock.current||blocked||disabled)return;onRootSelection?.(null);onSourceSelection?.(null);lock.current=true;setBusy(true);let token='';let timer:ReturnType<typeof setTimeout>|undefined;
  const close=()=>{closePicker.current=undefined;token='';clearTimeout(timer);pickerRef.current?.setVisible(false);pickerRef.current?.dispose?.();pickerRef.current=undefined;lock.current=false;if(alive.current)setBusy(false);};
  try{
   closePicker.current=close;await loadPicker();if(!alive.current||disabledRef.current)throw Error();
   const claim=await api<{intentId:string;purpose:string;accessToken:string;scope:string;expiresAt:number;projectNumber:string;browserKey:string}>(base+'/picker/claim',{method:'POST',body:JSON.stringify({revision:snapshot.revision,intentId:snapshot.intent.id})});
   if(!alive.current||disabledRef.current)throw Error();
   if(claim.intentId!==snapshot.intent.id||claim.purpose!==snapshot.intent.purpose||claim.scope!=='https://www.googleapis.com/auth/drive.file'||typeof claim.accessToken!=='string'||claim.accessToken.length>16000||!Number.isSafeInteger(claim.expiresAt)||claim.expiresAt<=Date.now()||claim.expiresAt>Date.now()+600000||!/^\d{1,30}$/.test(claim.projectNumber)||!/^[A-Za-z0-9_-]{20,200}$/.test(claim.browserKey))throw Error();token=claim.accessToken;
   const picker=window.google.picker,view=new picker.DocsView().setMode(picker.DocsViewMode.LIST);
   if(claim.purpose==='root')view.setIncludeFolders(true).setSelectFolderEnabled(true).setMimeTypes('application/vnd.google-apps.folder');else if(!documentationMode)view.setMimeTypes('application/pdf,image/png,application/vnd.google-apps.document');
   pickerRef.current=new picker.PickerBuilder().addView(view).setOAuthToken(token).setDeveloperKey(claim.browserKey).setAppId(claim.projectNumber).setOrigin(window.location.origin).setCallback(async(data:any)=>{
    if(data.action===picker.Action.CANCEL){close();if(alive.current){setBlocked(true);setNotice('Selection cancelled. Reload and authorize again when ready.');}return;}
    if(data.action!==picker.Action.PICKED)return;close();if(!alive.current||disabledRef.current)return;
    if(!Array.isArray(data.docs)||data.docs.length!==1||typeof data.docs[0].id!=='string'){error();return;}
    lock.current=true;setBusy(true);try{const item=data.docs[0];await api(base+'/selection',{method:'POST',body:JSON.stringify({revision:snapshot.revision,intentId:claim.intentId,fileId:item.id,...(item.resourceKey?{resourceKey:item.resourceKey}:{})})});await read();setNotice(documentationMode?'Source selection verified. Review the copy details below.':storageMode?'Folder selection is ready. Review and save it as shared storage below.':'Selection verified through the organizational connection. Synthetic proof operations are available to the maintainer separately.');}catch{error();}finally{lock.current=false;setBusy(false);}
   }).build();pickerRef.current.setVisible(true);token='';claim.accessToken='';timer=setTimeout(()=>{close();if(alive.current){setBlocked(true);setNotice('Picker authorization expired. Reload and authorize again.');}},claim.expiresAt-Date.now());
  }catch{close();if(alive.current)error();}
 }
 if(documentationMode)return <section className="ui-card hours-stack" aria-labelledby={id+'-title'}><h3 id={id+'-title'}>Choose a Drive original</h3><p>Use the organizational account to choose one file. A private copy preserves its selected version; selection alone does not copy or publish it.</p>{notice&&<p tabIndex={-1} ref={noticeRef} className="ui-status" role="status">{notice}</p>}<div className="hours-actions"><button disabled={busy||disabled} onClick={()=>void reload()}>Reload Drive selection</button><button disabled={busy||disabled||blocked||!snapshot?.configured} onClick={()=>void authorize('documentation-source')}>Authorize evidence selection</button>{snapshot?.intent?.purpose==='documentation-source'&&snapshot.intent.status==='ready'&&<button disabled={busy||disabled||blocked} onClick={()=>void choose()}>Open Google Picker</button>}</div>{!snapshot?.configured&&<p>Ask an Admin to configure shared Drive selection and private storage.</p>}{snapshot?.intent?.status==='selected'&&<p>Drive source selected.</p>}</section>;
 return <section className="integration-card google-connection" aria-labelledby={id+'-title'}><Heading id={id+'-title'}>{storageMode?'Choose shared storage folder':'Drive selection feasibility'}</Heading><p>{storageMode?'Use the organizational Google account to select a private My Drive folder. Selection alone does not save shared storage.':'Development-only provider checks. Use the organizational Google account and synthetic test files. This does not enable Activity Documentation.'}</p><div className="google-actions"><button disabled={busy} onClick={()=>void reload()}>Reload Drive selection</button></div>{notice&&<p tabIndex={-1} ref={noticeRef} className="ui-status" role="status">{notice}</p>}{!storageMode&&<p>Private test folder: {snapshot?.rootName??'Not selected'}</p>}<form onSubmit={configure}><fieldset disabled={busy||blocked}><legend>Shared Picker configuration</legend><p>Use the existing browser key restricted to this dashboard and the Picker API, plus its Google Cloud project number. Portable restore clears these Picker settings; configure them again before selecting a folder.</p><label>Google Cloud project number<input required inputMode="numeric" pattern="[0-9]{1,30}" maxLength={30} value={project} onChange={e=>setProject(e.target.value)}/></label><label>Restricted Picker browser key<input required autoComplete="off" maxLength={200} value={browserKey} onChange={e=>setBrowserKey(e.target.value)}/></label><button type="submit">Save Picker configuration</button></fieldset></form><div className="google-actions"><button disabled={busy||blocked||!snapshot?.configured} onClick={()=>void authorize('root')}>Authorize private folder selection</button>{!storageMode&&<button disabled={busy||blocked||!snapshot?.rootName} onClick={()=>void authorize('source')}>Authorize synthetic source selection</button>}{snapshot?.intent?.status==='ready'&&(!storageMode||snapshot.intent.purpose==='root')&&<button className="primary-button" disabled={busy||blocked} onClick={()=>void choose()}>Open Google Picker</button>}</div>{!storageMode&&<><p>Source checks accept owned PDFs, PNG images and native Google Docs named “LancerLogin synthetic …”. Native Docs remain linked evidence; inline conversion is not included.</p>{snapshot&&<GoogleDriveProofControls revision={snapshot.revision} sourceIntentId={snapshot.intent?.purpose==='source'&&snapshot.intent.status==='selected'?snapshot.intent.id:undefined} available={snapshot.configured&&Boolean(snapshot.rootName)} disabled={busy||blocked} onBusyChange={setBusy}/>}</>}</section>;
}
