import { useEffect, useMemo, useState } from "react";
import { api } from "./dashboard-api";
import { ContestReviewList, type Contest } from "./contest-review-list";
import { useDashboardLoadingOverlay } from "./loading-overlay";
import { MeetingsPage } from "./meetings-page";

type Meeting = { id: string; title: string; startsAt: string; endsAt: string; attendanceClosesAt: string; required: boolean | number };
type Attendance = { memberId: string; externalId: string; firstName: string; lastName: string; disposition: "present" | "active" | "absent" | "excused"; checkedInAt?: string; checkedOutAt?: string };
type ActiveMeeting = Meeting & { attendance: Attendance[]; finalized: boolean };
const dayKey = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
export const dashboardMeetingViewKey = "lancerlogin-dashboard-meeting-view";
type MeetingView = "calendar" | "table";

export function HomePage({ navigate, discordEnabled }: { role: "admin" | "operator"; navigate: (path: string) => void; discordEnabled: boolean }) {
  const [meetings, setMeetings] = useState<Meeting[]>([]); const [active, setActive] = useState<ActiveMeeting[]>([]); const [contests, setContests] = useState<Contest[]>([]); const [notice, setNotice] = useState("Loading dashboard…");
  const [meetingView, setMeetingView] = useState<MeetingView>(() => window.localStorage.getItem(dashboardMeetingViewKey) === "table" ? "table" : "calendar");
  const [calendarOffset, setCalendarOffset] = useState(0);
  useDashboardLoadingOverlay(notice === "Loading dashboard…", "Loading dashboard…");
  async function load() { const [meetingResult, contestResult] = await Promise.all([api<{ meetings: Meeting[] }>("/meetings"), discordEnabled ? api<{ contests: Contest[] }>("/discord/contests") : Promise.resolve({ contests: [] as Contest[] })]); const now = Date.now(); const current = meetingResult.meetings.filter((meeting) => Date.parse(meeting.startsAt) <= now && Date.parse(meeting.endsAt) >= now); const activeResults = await Promise.all(current.map(async (meeting) => ({ ...meeting, ...await api<{ attendance: Attendance[]; finalized: boolean }>(`/attendance?meetingId=${encodeURIComponent(meeting.id)}`) }))); setMeetings(meetingResult.meetings); setActive(activeResults); setContests(contestResult.contests); setNotice("Dashboard data is current."); }
  useEffect(() => { void load().catch((error: Error) => setNotice(error.message)); const timer = window.setInterval(() => void load().catch(() => undefined), 60_000); return () => window.clearInterval(timer); }, [discordEnabled]);
  const days = useMemo(() => { const currentWeek = new Date(); currentWeek.setHours(0, 0, 0, 0); currentWeek.setDate(currentWeek.getDate() - currentWeek.getDay()); const start = new Date(currentWeek); start.setDate(start.getDate() - 7 + calendarOffset * 35); return Array.from({ length: 35 }, (_, index) => { const date = new Date(start); date.setDate(start.getDate() + index); return date; }); }, [calendarOffset]);
  const events = useMemo(() => new Map(days.map((day) => [dayKey(day), meetings.filter((meeting) => dayKey(new Date(meeting.startsAt)) === dayKey(day)).sort((a, b) => Date.parse(a.startsAt) - Date.parse(b.startsAt))])), [days, meetings]);
  const open = contests.filter((contest) => contest.status === "open");
  function chooseView(view: MeetingView) { window.localStorage.setItem(dashboardMeetingViewKey, view); setMeetingView(view); }
  function addMeeting() { chooseView("table"); window.requestAnimationFrame(() => document.querySelector<HTMLInputElement>("#meeting-create-form input")?.focus()); }
  const rangeLabel = `${days[0].toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })} – ${days.at(-1)!.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })}`;
  return <section className="page-stack dashboard-home" aria-labelledby="home-title">
    <div className="page-intro"><h1 id="home-title">Dashboard</h1></div>
    <p className="setup-status" role="status">{notice}</p>
    <section className="meeting-browser-controls" aria-label="Meeting browser controls">
      <fieldset className="meeting-view-toggle"><legend>Meeting view</legend><div><label className={meetingView === "calendar" ? "selected" : ""}><input type="radio" name="meeting-view" value="calendar" checked={meetingView === "calendar"} onChange={() => chooseView("calendar")} />Calendar</label><label className={meetingView === "table" ? "selected" : ""}><input type="radio" name="meeting-view" value="table" checked={meetingView === "table"} onChange={() => chooseView("table")} />Table</label></div></fieldset>
      <label className="meeting-browser-select">Meeting<select value="" onChange={(event) => { if (event.target.value) navigate(`/meetings/${encodeURIComponent(event.target.value)}`); }}><option value="">Choose a meeting</option>{meetings.map((meeting) => <option key={meeting.id} value={meeting.id}>{new Date(meeting.startsAt).toLocaleDateString()} · {meeting.title}</option>)}</select></label>
      <button className="primary-button" type="button" onClick={addMeeting}>Add meeting</button>
    </section>
    {meetingView === "calendar" ? <section className="rolling-calendar dashboard-meeting-calendar" aria-labelledby="calendar-title"><div className="section-heading calendar-heading"><div><h2 id="calendar-title">Meeting calendar</h2><p aria-live="polite">{rangeLabel}</p></div><div className="calendar-navigation"><button type="button" aria-label="Show previous five weeks" onClick={() => setCalendarOffset((value) => value - 1)}>←</button><button type="button" disabled={calendarOffset === 0} onClick={() => setCalendarOffset(0)}>Today</button><button type="button" aria-label="Show next five weeks" onClick={() => setCalendarOffset((value) => value + 1)}>→</button></div></div><div className="calendar-weekdays" aria-hidden="true">{["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-grid">{days.map((day) => { const now = new Date(); const today = dayKey(day) === dayKey(now); const previousMonth = day.getFullYear() * 12 + day.getMonth() < now.getFullYear() * 12 + now.getMonth(); const items = events.get(dayKey(day)) ?? []; return <article key={dayKey(day)} className={`calendar-day${today ? " today" : ""}${previousMonth ? " previous-month" : ""}`}><header><span>{day.toLocaleDateString(undefined, { month: "short" })}</span><strong>{day.getDate()}</strong></header>{items.map((meeting) => <button key={meeting.id} type="button" onClick={() => navigate(`/meetings/${encodeURIComponent(meeting.id)}`)} title={`${meeting.title}, ${new Date(meeting.startsAt).toLocaleString()} to ${new Date(meeting.endsAt).toLocaleTimeString()}`}><span>{new Date(meeting.startsAt).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</span>{meeting.title}</button>)}</article>; })}</div></section> : <MeetingsPage discordEnabled={discordEnabled} navigate={navigate} embedded />}
    <section className="home-section" aria-labelledby="live-title"><div className="section-heading"><h2 id="live-title">Meetings in progress {active.length > 0 && <span className="live-pill">Live</span>}</h2></div>{active.length ? active.map((meeting) => <article className="live-meeting" key={meeting.id}><header><div><strong>{meeting.title}</strong><span>Scans accepted until {new Date(meeting.attendanceClosesAt).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</span></div><span>{meeting.attendance.filter((row) => row.disposition === "active").length} active · {meeting.attendance.filter((row) => row.disposition === "present").length} checked out</span><button type="button" onClick={() => navigate(`/meetings/${encodeURIComponent(meeting.id)}`)}>Open meeting</button></header><div className="live-roster">{meeting.attendance.map((row) => <div key={row.memberId}><span><strong>{row.firstName} {row.lastName}</strong><small>{row.externalId}</small></span><span className={`attendance-state ${row.disposition}`}>{row.disposition === "active" ? "Active · not checked out" : row.disposition}</span></div>)}</div></article>) : <p className="empty-state">No meeting is currently in progress.</p>}</section>
    {open.length > 0 && <section className="home-section" aria-labelledby="open-contests-title"><div className="section-heading"><h2 id="open-contests-title">Attendance contests</h2><span className="progress-count">{open.length} open</span></div><ContestReviewList contests={open} onResolved={() => { void load().then(() => setNotice("Attendance contest reviewed and audited.")).catch((error: Error) => setNotice(error.message)); }} /></section>}
  </section>;
}
