import { useEffect, useState } from "react";
import { api } from "./dashboard-api";

type Summary = { meetings: number; members: number; kiosk: string; setup: number };
export function HomePage({ role, navigate }: { role: "admin" | "operator"; navigate: (path: string) => void }) {
  const [summary, setSummary] = useState<Summary>(); const [notice, setNotice] = useState("Loading dashboard…");
  useEffect(() => { Promise.all([api<{ meetings: unknown[] }>("/meetings"), api<{ members: unknown[] }>("/admin/members"), api<{ kiosks: { active: number; lastSeenAt?: string }[] }>("/admin/kiosks"), role === "admin" ? api<{ completedSteps: unknown[] }>("/admin/setup/progress") : Promise.resolve({ completedSteps: [] })]).then(([meetings, members, kiosks, setup]) => { const kiosk = kiosks.kiosks.find((item) => item.active === 1); const online = Boolean(kiosk?.lastSeenAt && Date.now() - Date.parse(kiosk.lastSeenAt) < 90_000); setSummary({ meetings: meetings.meetings.length, members: members.members.length, kiosk: kiosk ? online ? "Online" : "Offline" : "Not paired", setup: setup.completedSteps.length }); setNotice("Dashboard data is current."); }).catch((error: Error) => setNotice(error.message)); }, [role]);
  return <section className="page-stack" aria-labelledby="home-title"><div className="page-intro"><p className="kicker">Home</p><h2 id="home-title">Attendance at a glance</h2><p>Start common tasks without reopening onboarding or loading every administration tool.</p></div><p className="setup-status" role="status">{notice}</p><div className="summary-grid"><article><span>Roster</span><strong>{summary?.members ?? "—"}</strong><button type="button" onClick={() => navigate("/roster")}>Open roster</button></article><article><span>Meetings</span><strong>{summary?.meetings ?? "—"}</strong><button type="button" onClick={() => navigate("/meetings")}>Manage meetings</button></article><article><span>Kiosk</span><strong>{summary?.kiosk ?? "—"}</strong><button type="button" onClick={() => navigate("/attendance")}>Open attendance</button></article>{role === "admin" && <article><span>Setup</span><strong>{summary ? `${Math.round(summary.setup / 6 * 100)}%` : "—"}</strong><button type="button" onClick={() => navigate("/setup")}>Open setup</button></article>}</div></section>;
}
