import { useEffect, useRef, useState } from 'react';
import { hourApi as api, durationLabel } from './hour-entry-contract';
import { CurrentName, NamedChoice } from './hour-named-choice';
import { reportPeriod, reportResult, type Report, type ReportFilters } from './hour-review-contract';
const blank:ReportFilters={from:'',to:'',groupBy:'member',memberId:'',activityId:'',categoryId:'',teamId:''};
const groups={member:'Member',activity:'Activity',category:'Category',team:'Primary supported team'};
const kinds={member:'member-choices',activity:'activities',category:'categories',team:'teams'};
export function HourReports({accessChecking,onOccupied}:{accessChecking:boolean;onOccupied:(v:boolean)=>void}){
 const [filter,setFilter]=useState(blank),[applied,setApplied]=useState<ReportFilters>(),[report,setReport]=useState<Report>(),[cursor,setCursor]=useState(''),[working,setWorking]=useState(false),[notice,setNotice]=useState('');
 const gate=useRef(false),alive=useRef(true),heading=useRef<HTMLHeadingElement>(null),alert=useRef<HTMLParagraphElement>(null);const busy=working||accessChecking;let invalid=false;try{reportPeriod(filter.from,filter.to);}catch{invalid=true;}
 useEffect(()=>{onOccupied(working);},[working,onOccupied]);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);useEffect(()=>{if(notice)alert.current?.focus();},[notice]);
 async function load(filters=applied,after=''){if(!filters||gate.current||accessChecking)return;gate.current=true;setWorking(true);setNotice('');setReport(undefined);try{reportPeriod(filters.from,filters.to);const q=new URLSearchParams({limit:'50'});for(const[k,v]of Object.entries(filters))if(v)q.set(k,v);if(after)q.set('after',after);const result=reportResult(await api<Report>('/admin/hours/reports?'+q),filters);if(alive.current){setReport(result);setApplied({...filters});setCursor(after);requestAnimationFrame(()=>heading.current?.focus());}}catch{if(alive.current)setNotice('The report could not be verified. Check the period and current access, then reload. Previous totals are hidden.');}finally{gate.current=false;if(alive.current)setWorking(false);}}
 return <section className="hours-stack" aria-label="Hour reports"><h2>Reports</h2><p>Choose an inclusive period of up to 3660 service dates. Overnight hours belong to their start service date. Only current counted entries contribute; voided entries and older history remain retained.</p>
 <form className="ui-card hours-stack" onSubmit={e=>{e.preventDefault();void load(filter);}}><div className="hours-grid"><label>Report from service date<input required type="date" value={filter.from} disabled={busy} onChange={e=>setFilter({...filter,from:e.target.value})}/></label><label>Report through service date<input required type="date" min={filter.from} value={filter.to} disabled={busy} onChange={e=>setFilter({...filter,to:e.target.value})}/></label><label>Group report by<select className="ui-native-select" value={filter.groupBy} disabled={busy} onChange={e=>setFilter({...filter,groupBy:e.target.value as ReportFilters['groupBy']})}>{Object.entries(groups).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div><details><summary>Filter report records</summary>{(['member','activity','category','team'] as const).map(kind=><NamedChoice key={kind} label={`Report ${groups[kind].toLowerCase()} filter`} kind={kinds[kind]} query={kind==='member'?'':'archived=all'} value={filter[`${kind}Id`]} disabled={busy} onChange={v=>setFilter({...filter,[`${kind}Id`]:v?.id??''})}/>)}</details><p>Team attribution uses the activity’s primary supported team. Partner teams do not duplicate hours. Names are current catalog and roster labels.</p>{invalid&&filter.from&&filter.to&&<p>Use an ordered period of at most 3660 service dates.</p>}<div className="hours-actions"><button className="primary-button" disabled={busy||invalid}>Run report</button>{applied&&<button type="button" disabled={busy} onClick={()=>void load()}>Reload applied report</button>}</div></form>
 {working&&<p role="status">Loading report…</p>}{notice&&<p ref={alert} tabIndex={-1} role="alert" className="ui-status settings-notice" data-tone="error">{notice}</p>}
 {report&&<><section className="ui-card hours-stack" aria-label="Whole period totals"><h3 ref={heading} tabIndex={-1}>Whole period totals</h3><p>{report.from} through {report.to} · grouped by {groups[report.groupBy].toLowerCase()}</p>{applied&&<p>Applied record filters: {(['member','activity','category','team'] as const).filter(kind=>applied[`${kind}Id`]).length===0?'all records':(['member','activity','category','team'] as const).filter(kind=>applied[`${kind}Id`]).map(kind=><span key={kind}>{groups[kind]}: <CurrentName kind={kinds[kind]} id={applied[`${kind}Id`]}/>; </span>)}</p>}<p><strong>{durationLabel(report.totals.minutes)}</strong></p><p>{report.totals.entryCount} counted entries · {report.totals.distinctParticipants} distinct participants</p><p>These totals cover all matching records, independently of the group page. Group participant counts must not be added together.</p></section><div className="hours-records">{report.items.map(row=><article className="ui-card hours-stack" key={row.id??'no-team'}><h3>{row.id===null?'No primary supported team':<CurrentName kind={kinds[report.groupBy]} id={row.id}/>}</h3><p>{durationLabel(row.minutes)}</p><p>{row.entryCount} counted entries · {row.distinctParticipants} distinct participants in this group</p></article>)}</div>{!report.items.length&&<p>No counted entries match this period and filters.</p>}<p>Pages show current records and may change as entries are reviewed. Choose another explicit period to include older service dates.</p><div className="hours-actions">{cursor&&<button disabled={busy} onClick={()=>void load()}>First report page</button>}{report.nextCursor&&<button disabled={busy} onClick={()=>void load(applied,report.nextCursor!)}>Next report page</button>}</div></>}
 </section>;
}
