import { useEffect, useRef, useState } from 'react';
import { hourApi as api, entry, settings, type Entry, type EntrySettings } from './hour-entry-contract';
import { pageResult, recordItem, type RecordItem, type PageResult } from './hours-contract';
import { correctionRequest, requestPage, type CorrectionRequest } from './hour-review-contract';
import { CurrentName, NamedChoice } from './hour-named-choice';
import { EntrySummary } from './hour-entries';
import { EntryEditor } from './hour-entry-editor';
const root='/admin/hours/correction-requests';
const failure='The review result could not be confirmed. No action is retried automatically. Reload this request before another change; check current access, the entry revision, activity date and clock validity.';
type Filters={status:string;memberId:string};
const initial:Filters={status:'open',memberId:''};
function Claims({value}:{value:CorrectionRequest}){return <section className="ui-card hours-stack"><h3>Original request</h3><p><strong>{value.attribution==='self_asserted'?'Self-asserted, unverified identity':'Linked Discord identity'}</strong></p><p>{value.attribution==='self_asserted'?'A matching roster record does not verify the person who submitted this claim.':'The linked account identifies the requester; it does not verify the requested hours or approve a change.'}</p>{value.requesterMemberId&&<p>{value.attribution==='self_asserted'?'Roster match (unverified)':'Linked member'}: <CurrentName kind="member-choices" id={value.requesterMemberId}/></p>}<p>Received {value.createdAt}</p><p className="entry-notes">{value.message}</p><dl className="entry-notes">{([['Claimed member ID',value.claimedMemberId],['Claimed receipt reference',value.claimedReceiptId],['Claimed activity reference',value.claimedActivityId],['Claimed service date',value.claimedServiceDate]] as const).filter(([,v])=>v!==null).map(([label,v])=><div key={label}><dt>{label} (unverified)</dt><dd>{v}</dd></div>)}</dl><p>Original claims are retained unchanged. Names shown here are current roster labels.</p></section>;}
function MatchEntry({disabled,onSelect}:{disabled:boolean;onSelect:(value:Entry)=>void}){
 const blank={memberId:'',activityId:'',from:'',to:''};const [filter,setFilter]=useState(blank),[applied,setApplied]=useState(blank),[page,setPage]=useState<PageResult<Entry>>(),[busy,setBusy]=useState(false),[error,setError]=useState(false);const gate=useRef(false),alive=useRef(true);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 async function load(filters=applied,after=''){if(gate.current||disabled)return;gate.current=true;setBusy(true);setError(false);setPage(undefined);try{const q=new URLSearchParams({limit:'20'});for(const[k,v]of Object.entries(filters))if(v)q.set(k,v);if(after)q.set('after',after);const p=pageResult(await api<PageResult<Entry>>('/admin/hours/entries?'+q),v=>!!entry(v));if(alive.current){setPage(p);setApplied({...filters});}}catch{if(alive.current)setError(true);}finally{gate.current=false;if(alive.current)setBusy(false);}}
 return <section className="ui-card hours-stack" aria-label="Find matching entry"><h3>Find an entry to review</h3><p>Select a record explicitly after comparing its member, activity and clocks. Request claims do not automatically select or authorize an entry.</p><form className="hours-stack" onSubmit={e=>{e.preventDefault();void load(filter);}}><NamedChoice label="Match member" kind="member-choices" value={filter.memberId} disabled={disabled||busy} onChange={v=>setFilter({...filter,memberId:v?.id??''})}/><NamedChoice label="Match activity" kind="activities" query="archived=all" value={filter.activityId} disabled={disabled||busy} onChange={v=>setFilter({...filter,activityId:v?.id??''})}/><div className="hours-grid"><label>Match from service date<input type="date" value={filter.from} disabled={disabled||busy} onChange={e=>setFilter({...filter,from:e.target.value})}/></label><label>Match through service date<input type="date" min={filter.from} value={filter.to} disabled={disabled||busy} onChange={e=>setFilter({...filter,to:e.target.value})}/></label></div><button disabled={disabled||busy}>Find entries</button></form>{error&&<p role="alert">Entries could not be loaded. Check filters and current access, then find entries again.</p>}{busy&&<p role="status">Loading matching entries…</p>}{page&&<p>Matching entries{applied.memberId?<> for <CurrentName kind="member-choices" id={applied.memberId}/></>:' for all members'}{applied.activityId?<> · <CurrentName kind="activities" id={applied.activityId}/></>:null}{applied.from?' · from '+applied.from:''}{applied.to?' · through '+applied.to:''}.</p>}{page?.items.map((v,i)=><article className="ui-card hours-stack" key={v.id}><EntrySummary value={v}/><button disabled={disabled||busy} onClick={()=>onSelect(v)}>Review matching entry {i+1}</button></article>)}{page&&!page.items.length&&<p>No entries match these filters.</p>}{page&&<div className="hours-actions"><button disabled={disabled||busy} onClick={()=>void load()}>Reload first matching page</button>{page.nextCursor&&<button disabled={disabled||busy} onClick={()=>void load(applied,page.nextCursor!)}>Next matching entries page</button>}</div>}</section>;
}
export function HourCorrections({accessChecking,onOccupied}:{accessChecking:boolean;onOccupied:(v:boolean)=>void}){
 const [filter,setFilter]=useState(initial),[applied,setApplied]=useState(initial),[page,setPage]=useState<PageResult<CorrectionRequest>>(),[cursor,setCursor]=useState(''),[record,setRecord]=useState<CorrectionRequest>(),[matched,setMatched]=useState<Entry>(),[context,setContext]=useState<EntrySettings>(),[editing,setEditing]=useState(false),[action,setAction]=useState('acknowledged'),[note,setNote]=useState(''),[working,setWorking]=useState(false),[locked,setLocked]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(false);
 const gate=useRef(false),alive=useRef(true),heading=useRef<HTMLHeadingElement>(null),noticeRef=useRef<HTMLParagraphElement>(null);const busy=working||accessChecking;
 useEffect(()=>{onOccupied(working||!!record||locked);},[working,record,locked,onOccupied]);useEffect(()=>{if(notice)noticeRef.current?.focus();},[notice]);
 function fail(){if(alive.current){setLocked(true);setError(true);setNotice(failure);}}
 async function load(after='',filters=applied,focus=false){if(gate.current||accessChecking)return;gate.current=true;setWorking(true);setNotice('');setPage(undefined);try{const q=new URLSearchParams({limit:'50',status:filters.status});if(filters.memberId)q.set('memberId',filters.memberId);if(after)q.set('after',after);const result=requestPage(await api<PageResult<CorrectionRequest>>(root+'?'+q));if(alive.current){setPage(result);setApplied({...filters});setCursor(after);setLocked(false);if(focus)requestAnimationFrame(()=>heading.current?.focus());}}catch{fail();}finally{gate.current=false;if(alive.current)setWorking(false);}}
 useEffect(()=>{alive.current=true;void load();return()=>{alive.current=false;};},[]);
 async function read(id:string){const current=correctionRequest(await api<CorrectionRequest>(root+'/'+encodeURIComponent(id)),true);if(current.id!==id)throw Error('Request mismatch');const target=current.resolution?.entryId;const linked=target?entry(await api<Entry>('/admin/hours/entries/'+encodeURIComponent(target))):undefined;if(linked&&(linked.id!==target||linked.revision<current.resolution!.entryRevision!))throw Error('Invalid linked entry');return {current,linked};}
 async function open(id:string,recovery=false){if(gate.current||accessChecking)return;gate.current=true;setWorking(true);setNotice('');try{const {current,linked}=await read(id);const clock=current.status==='open'?settings(await api<EntrySettings>('/admin/hours/entry-settings')):undefined;if(!alive.current)return;setRecord(current);setMatched(linked);setContext(clock);setEditing(false);setNote('');setAction('acknowledged');setLocked(false);setError(false);if(recovery)setNotice(current.status==='resolved'?'Current saved resolution loaded. Review the recorded outcome below; no action was retried.':'The request is still open. Review it and select a current entry before making another change.');else requestAnimationFrame(()=>heading.current?.focus());}catch{fail();}finally{gate.current=false;if(alive.current)setWorking(false);}}
 async function choose(value:Entry){if(gate.current||busy||locked)return;gate.current=true;setWorking(true);try{const fresh=entry(await api<Entry>('/admin/hours/entries/'+encodeURIComponent(value.id)));if(fresh.id!==value.id)throw Error('Mismatched entry');setMatched(fresh);setNote('');setNotice('Current entry loaded. Compare it with the original request before resolving.');setError(false);}catch{fail();}finally{gate.current=false;setWorking(false);}}
 async function resolve(selectedAction:string,reviewNote:string,correction?:Record<string,unknown>){if(gate.current||busy||locked||!record||record.status!=='open'||!reviewNote.trim()||(['corrected','voided'].includes(selectedAction)&&(!matched||matched.status!=='counted')))return;gate.current=true;setWorking(true);setNotice('');const payload={revision:record.revision,action:selectedAction,note:reviewNote.trim(),...(matched?{entryId:matched.id,entryRevision:matched.revision}:{}),...(correction?{correction}:{})};
  try{const receipt=await api<any>(root+'/'+encodeURIComponent(record.id)+'/resolve',{method:'POST',body:JSON.stringify(payload)});if(!receipt||receipt.id!==record.id||receipt.status!=='resolved'||receipt.revision!==1)throw Error('Invalid receipt');const changed=['corrected','voided'].includes(selectedAction);if(changed&&(!receipt.entry||receipt.entry.id!==matched!.id||receipt.entry.revision!==matched!.revision+1||receipt.entry.status!==(selectedAction==='voided'?'void':'counted')))throw Error('Invalid entry receipt');
   const {current,linked}=await read(record.id),r=current.resolution;if(!r||r.action!==selectedAction||r.note!==payload.note||r.entryId!==(matched?.id??null)||r.entryRevision!==(matched?matched.revision+Number(changed):null))throw Error('Resolution mismatch');
   if(changed){if(!linked||linked.revision!==matched!.revision+1||linked.status!==receipt.entry.status)throw Error('Entry advanced');if(linked.timeZone!==matched!.timeZone)throw Error('Saved zone changed');if(selectedAction==='voided')for(const key of ['memberId','activityId','serviceDate','startLocal','endLocal','endNextDay','startOccurrence','endOccurrence','startMs','endMs','startOffsetSeconds','endOffsetSeconds','durationMinutes','taskNotes'])if((linked as any)[key]!==(matched as any)[key])throw Error('Void changed accounting fields');if(correction){for(const key of ['memberId','serviceDate','startLocal','endLocal','endNextDay','startOccurrence','endOccurrence','taskNotes'])if((linked as any)[key]!==correction[key])throw Error('Correction mismatch');if(correction.activityId&&linked.activityId!==correction.activityId)throw Error('Activity mismatch');if(!correction.activityId){const activity=recordItem(await api<RecordItem>('/admin/hours/activities/'+encodeURIComponent(linked.activityId)),'activities');if(activity.id!==linked.activityId||activity.categoryId!==correction.categoryId||activity.teamId!==correction.teamId||activity.serviceDate!==correction.serviceDate)throw Error('Canonical activity mismatch');}}}
   setRecord(current);setMatched(linked);setEditing(false);setNote('');setLocked(false);setError(false);setNotice('Resolution saved and confirmed from the server. This request is terminal.');
  }catch{fail();}finally{gate.current=false;setWorking(false);}
 }
 return <section className="hours-stack" aria-label="Hour corrections"><h2 ref={heading} tabIndex={-1}>{record?'Review correction request':'Corrections'}</h2>{notice&&<p ref={noticeRef} tabIndex={-1} role={error?'alert':'status'} className="ui-status settings-notice" data-tone={error?'error':'success'}>{notice}</p>}{working&&<p role="status">Loading or saving review…</p>}
 {record?<><div className="hours-actions"><button disabled={busy} onClick={()=>void open(record.id,true)}>Reload current request</button><button disabled={busy} onClick={()=>{setRecord(undefined);setMatched(undefined);setEditing(false);setLocked(false);void load(cursor,applied,true);}}>Back to correction inbox</button></div><Claims value={record}/>{record.resolution?<section className="ui-card hours-stack"><h3>Saved resolution</h3><p>{record.resolution.action} · {record.resolution.createdAt}</p><p className="entry-notes">{record.resolution.note}</p><p>This request cannot be resolved again. The resolution preserves the reviewed entry revision.</p>{matched&&<><h3>Current linked entry</h3>{matched.revision!==record.resolution.entryRevision&&<p>The entry has changed since this resolution. This is its current state, not the historical reviewed snapshot.</p>}<EntrySummary value={matched}/></>}</section>:<>{matched&&<section className="ui-card hours-stack"><h3>Selected current entry</h3><EntrySummary value={matched}/><button disabled={busy||locked||editing} onClick={()=>{setMatched(undefined);setNote('');setError(false);setNotice('Entry selection cleared. Review another entry or resolve without changing hours.');}}>Clear selected entry</button>{matched.status==='void'&&<p>This entry is already voided. Acknowledge or dismiss the request; it cannot be corrected or voided again.</p>}</section>}
 {editing&&matched&&context?<><p>The correction reason will become this request’s resolution note. Saving corrects the entry and resolves the request together.</p><EntryEditor record={matched} context={context} disabled={busy||locked} onClose={()=>{setEditing(false);requestAnimationFrame(()=>heading.current?.focus());}} onSave={body=>{const {revision:ignored,reason,...correction}=body;void resolve('corrected',String(reason??''),correction);}}/></>:<><MatchEntry disabled={busy||locked} onSelect={v=>void choose(v)}/><form className="ui-card hours-stack" onSubmit={e=>{e.preventDefault();void resolve(action,note);}}><h3>Resolve request</h3><p>Acknowledge records that the request was reviewed; dismiss closes it without an entry change. Correct or void changes the selected entry atomically with this resolution.</p><label>Resolution action<select className="ui-native-select" value={action} disabled={busy||locked} onChange={e=>setAction(e.target.value)}><option value="acknowledged">Acknowledge without changing hours</option><option value="dismissed">Dismiss without changing hours</option><option value="voided" disabled={!matched||matched.status!=='counted'}>Void selected entry</option></select></label><label>Review note<textarea required maxLength={4000} value={note} disabled={busy||locked} onChange={e=>setNote(e.target.value)}/></label>{action==='voided'&&<p>Voiding is terminal. The entry will stop contributing hours; its history remains retained.</p>}<div className="hours-actions"><button className={action==='voided'?'danger-button':'primary-button'} disabled={busy||locked||!note.trim()||(action==='voided'&&(!matched||matched.status!=='counted'))}>Confirm resolution</button><button type="button" disabled={busy||locked||!matched||matched.status!=='counted'||!context} onClick={()=>setEditing(true)}>Correct selected entry and resolve</button></div></form></>}
 </>}</>:<><p>Review original claims and explicitly select any entry to change. Receiving a request never approves hours.</p><form className="ui-card hours-stack" onSubmit={e=>{e.preventDefault();void load('',filter);}}><label>Correction status<select className="ui-native-select" value={filter.status} disabled={busy} onChange={e=>setFilter({...filter,status:e.target.value})}><option value="open">Open</option><option value="resolved">Resolved</option><option value="all">Open and resolved</option></select></label><NamedChoice label="Requester roster match filter" kind="member-choices" value={filter.memberId} disabled={busy} onChange={v=>setFilter({...filter,memberId:v?.id??''})}/><div className="hours-actions"><button disabled={busy}>Apply correction filters</button><button type="button" disabled={busy} onClick={()=>void load()}>Reload correction inbox</button></div></form>{page&&<p>Showing {applied.status==='all'?'open and resolved':applied.status} requests{applied.memberId?<> for roster match <CurrentName kind="member-choices" id={applied.memberId}/></>:' for all requesters'}.</p>}{page?.items.map((v,i)=><article className="ui-card hours-stack" key={v.id}><h3>{v.attribution==='self_asserted'?'Self-asserted, unverified request':'Linked Discord request'}</h3><p>{v.status} · {v.createdAt}</p><p className="entry-notes">{v.message}</p><button disabled={busy||locked} onClick={()=>void open(v.id)}>Review request {i+1}</button></article>)}{page&&!page.items.length&&<p>No correction requests match these filters.</p>}<div className="hours-actions">{cursor&&<button disabled={busy} onClick={()=>void load()}>First correction page</button>}{page?.nextCursor&&<button disabled={busy||locked} onClick={()=>void load(page.nextCursor!)}>Next correction page</button>}</div></>}
 </section>;
}
