import { useEffect, useRef, useState } from 'react';
import { addCalendarDays, elapsedIntegerMinutes, selectCivilTime, type CivilTimeOccurrence } from '@lancerlogin/shared/civil-time';
import { Clock } from './hours-clock';
import { NamedChoice } from './hour-named-choice';
import { durationLabel, type Entry, type EntrySettings } from './hour-entry-contract';
export function EntryEditor({record,context,disabled,onSave,onClose}:{record?:Entry;context:EntrySettings;disabled:boolean;onSave:(body:Record<string,unknown>)=>void;onClose:()=>void}) {
  const heading=useRef<HTMLHeadingElement>(null);useEffect(()=>{heading.current?.focus();},[]);
  const [member,setMember]=useState(record?.memberId??''),[activity,setActivity]=useState(record?.activityId??''),[target,setTarget]=useState('existing'),[category,setCategory]=useState(''),[mode,setMode]=useState(''),[team,setTeam]=useState(''),[date,setDate]=useState(record?.serviceDate??context.today);
  const [start,setStart]=useState(record?.startLocal??''),[end,setEnd]=useState(record?.endLocal??''),[nextDay,setNextDay]=useState(record?.endNextDay??false),[startOccurrence,setStartOccurrence]=useState<CivilTimeOccurrence|undefined>(record?.startOccurrence??undefined),[endOccurrence,setEndOccurrence]=useState<CivilTimeOccurrence|undefined>(record?.endOccurrence??undefined),[notes,setNotes]=useState(record?.taskNotes??''),[reason,setReason]=useState('');
  let rulesChanged=false;if(record)try{rulesChanged=selectCivilTime({date:record.serviceDate,time:record.startLocal,timeZone:record.timeZone},record.startOccurrence??undefined).epochMilliseconds!==record.startMs||selectCivilTime({date:addCalendarDays(record.serviceDate,Number(record.endNextDay)),time:record.endLocal,timeZone:record.timeZone},record.endOccurrence??undefined).epochMilliseconds!==record.endMs;}catch{rulesChanged=true;}const [acceptRules,setAcceptRules]=useState(false);
  const zone=record?.timeZone??context.timeZone;let endDate=date,minutes:number|undefined,problem='';
  try{endDate=addCalendarDays(date,Number(nextDay));const first=selectCivilTime({date,time:start,timeZone:zone},startOccurrence),last=selectCivilTime({date:endDate,time:end,timeZone:zone},endOccurrence);minutes=elapsedIntegerMinutes(first.epochMilliseconds,last.epochMilliseconds);if(last.epochMilliseconds>Date.now())throw Error('Future');}catch{problem='Choose valid completed start and end times. End must follow start by a whole number of minutes. Select each repeated-clock occurrence explicitly.';}
  const invalid=(rulesChanged&&!acceptRules)||!!problem||!member||(target==='existing'?!activity:!category||mode==='event'||(mode==='team'&&!team))||!!record&&!reason.trim();
  return <section className="ui-card hours-stack"><h2 ref={heading} tabIndex={-1}>{record?'Correct entry':'Record hours'}</h2><p>Staff may record historical service and inactive members. Future completion and overlapping counted hours remain prohibited.</p><form className="hours-stack" onSubmit={event=>{event.preventDefault();if(disabled||invalid)return;onSave({memberId:member,...(target==='existing'?{activityId:activity,serviceDate:date}:{activityId:null,categoryId:category,serviceDate:date,teamId:mode==='team'?team:null}),startLocal:start,endLocal:end,endNextDay:nextDay,...(startOccurrence?{startOccurrence}:record?{startOccurrence:null}:{}),...(endOccurrence?{endOccurrence}:record?{endOccurrence:null}:{}),taskNotes:notes,...(record?{revision:record.revision,reason:reason.trim()}:{expectedTimeZone:zone})});}}>
    <NamedChoice label="Member" kind="member-choices" value={member} onChange={item=>setMember(item?.id??'')} disabled={disabled}/>
    <label>Activity selection<select aria-label="Activity selection" className="ui-native-select" disabled={disabled} value={target} onChange={e=>{setTarget(e.target.value);setActivity('');setCategory('');setTeam('');setMode('');setStartOccurrence(undefined);setEndOccurrence(undefined);}}><option value="existing">Existing dated activity</option><option value="canonical">Team support or task/service date</option></select></label>
    {target==='existing'?<NamedChoice label="Dated activity" kind="activities" query="archived=all" value={activity} disabled={disabled} onChange={item=>{setActivity(item?.id??'');setDate(item?.serviceDate??'');setStartOccurrence(undefined);setEndOccurrence(undefined);}}/>:<><NamedChoice label="Entry category" kind="categories" value={category} disabled={disabled} onChange={item=>{setCategory(item?.id??'');setMode(item?.mode??'');setTeam('');}}/>{mode==='event'&&<p role="alert">Event categories require an existing dated activity. Change Activity selection.</p>}{mode==='team'&&<NamedChoice label="Supported team" kind="teams" value={team} disabled={disabled} onChange={item=>setTeam(item?.id??'')}/>}<p>The server finds or creates the single activity for this category, date and supported team.</p></>}
    <label>Service date<input type={date.startsWith('0000-')?'text':'date'} required value={date} disabled={disabled||target==='existing'} onChange={e=>{setDate(e.target.value);setStartOccurrence(undefined);setEndOccurrence(undefined);}}/></label>
    <p>Clock zone: <strong>{zone}</strong>{record?'. Saved entry zone; corrections retain it.':'. Reload the draft if organization settings change.'} Activity planning times do not constrain contributed hours.</p>
    {rulesChanged&&<div className="ui-status settings-notice" data-tone="warning"><p>Current browser time-zone rules differ from the saved entry. Read-only history and voiding preserve its recorded instants. A correction recalculates timing using current rules; review the calculated duration before proceeding.</p><label className="hours-check"><input type="checkbox" checked={acceptRules} disabled={disabled} onChange={e=>setAcceptRules(e.target.checked)}/>Use currently resolved timing for this correction</label></div>}
    <div className="hours-grid"><Clock label="Start time" date={date} time={start} zone={zone} occurrence={startOccurrence} onTime={setStart} onOccurrence={setStartOccurrence} disabled={disabled}/><Clock label="End time" date={endDate} time={end} zone={zone} occurrence={endOccurrence} onTime={setEnd} onOccurrence={setEndOccurrence} disabled={disabled}/></div>
    <label className="hours-check"><input type="checkbox" checked={nextDay} disabled={disabled} onChange={e=>{setNextDay(e.target.checked);setEndOccurrence(undefined);}}/>End on the next calendar day</label>
    <p id="entry-timing-help" role="status">{problem||`Calculated duration: ${durationLabel(minutes!)}. No break deduction or total override.`}</p>
    <label>Task notes<textarea maxLength={4000} value={notes} disabled={disabled} onChange={e=>setNotes(e.target.value)}/></label>{record&&<label>Correction reason<textarea required maxLength={4000} value={reason} disabled={disabled} onChange={e=>setReason(e.target.value)}/></label>}
    <div className="hours-actions"><button className="primary-button" disabled={disabled||invalid} aria-describedby="entry-timing-help">{record?'Save correction':'Record completed hours'}</button><button type="button" disabled={disabled} onClick={onClose}>Close entry form</button></div>
  </form></section>;
}
