import { addCalendarDays } from '@lancerlogin/shared/civil-time';
import { useEffect, useRef, useState } from 'react';
import { hourApi as api } from './hour-entry-contract';
import { identity, pageResult, type PageResult } from './hours-contract';
import { entryFailure, settings, windowRecord, type EntrySettings, type WindowRecord } from './hour-entry-contract';
import { CurrentName, NamedChoice } from './hour-named-choice';
export function HourWindows({accessChecking,onOccupied}:{accessChecking:boolean;onOccupied:(value:boolean)=>void}) {
 const [config,setConfig]=useState<EntrySettings>(),[days,setDays]=useState(''),[hours,setHours]=useState(''),[duration,setDuration]=useState(''),[scope,setScope]=useState('single'),[activity,setActivity]=useState(''),[page,setPage]=useState<PageResult<WindowRecord>>(),[cursor,setCursor]=useState(''),[working,setWorking]=useState(false),[locked,setLocked]=useState(false),[notice,setNotice]=useState(''),[confirmed,setConfirmed]=useState<WindowRecord>();const gate=useRef(false),ref=useRef<HTMLParagraphElement>(null);const busy=working||accessChecking;
 useEffect(()=>{onOccupied(working||locked);},[working,locked,onOccupied]);useEffect(()=>{if(notice)ref.current?.focus();},[notice]);
 function fail(){setLocked(true);setNotice(entryFailure+' A window creation may already have succeeded; inspect the reloaded list before creating another.');}
 const readPage=async(after='')=>pageResult(await api<PageResult<WindowRecord>>('/admin/hours/reopen-windows?limit=50'+(after?'&after='+encodeURIComponent(after):'')),value=>!!windowRecord(value));
 async function reload(after=''){if(gate.current)return;gate.current=true;setWorking(true);setNotice('');try{const [current,list]=await Promise.all([api<EntrySettings>('/admin/hours/entry-settings').then(settings),readPage(after)]);setConfig(current);setDays(String(current.reportingDays));setHours(String(current.reopenHours));setDuration(String(current.reopenHours));setPage(list);setCursor(after);setLocked(false);setNotice('Current settings and windows loaded. Review existing windows before creating another.');}catch{fail();}finally{gate.current=false;setWorking(false);}}
 useEffect(()=>{void reload();},[]);
 async function saveSettings(){if(gate.current||busy||locked||!config)return;gate.current=true;setWorking(true);setNotice('');try{const written=await api<any>('/admin/hours/entry-settings',{method:'PUT',body:JSON.stringify({revision:config.revision,reportingDays:Number(days),reopenHours:Number(hours)})});if(written?.revision!==config.revision+1||written.reportingDays!==Number(days)||written.reopenHours!==Number(hours))throw Error('Unconfirmed settings');const current=settings(await api<EntrySettings>('/admin/hours/entry-settings'));if(current.revision!==written.revision||current.reportingDays!==written.reportingDays||current.reopenHours!==written.reopenHours)throw Error('Concurrent settings');setConfig(current);setNotice('Reporting settings confirmed from the server. Existing window expiry times are unchanged.');}catch{fail();}finally{gate.current=false;setWorking(false);}}
 async function changeWindow(record?:WindowRecord){if(gate.current||busy||locked||!config)return;gate.current=true;setWorking(true);setNotice('');try{const written=await api<any>('/admin/hours/reopen-windows'+(record?'/'+encodeURIComponent(record.id):''),{method:record?'PATCH':'POST',body:JSON.stringify(record?{revision:record.revision,revoked:true}:{activityId:scope==='all'?null:activity,durationHours:Number(duration)})});if(!identity(written?.id)||written.revision!==(record?record.revision+1:0)||(record&&written.id!==record.id))throw Error('Invalid window');const current=windowRecord(await api<WindowRecord>('/admin/hours/reopen-windows/'+encodeURIComponent(written.id)));if(current.id!==written.id||current.revision!==written.revision||(record&&!current.revoked)||(!record&&(current.activityId!==(scope==='all'?null:activity)||current.revoked||current.expiresMs-current.startsMs!==Number(duration)*3600000)))throw Error('Unconfirmed window');setConfirmed(current);setPage(await readPage());setCursor('');setNotice(record?'Window revocation confirmed from the server.':'Reopening window confirmed from the server.');}catch{fail();}finally{gate.current=false;setWorking(false);}}
 let pastThrough='';try{if(config)pastThrough=addCalendarDays(config.today,-1);}catch{/* No representable prior day. */}
 const integer=(value:string,min:number,max:number)=>value.trim()!==''&&Number.isInteger(Number(value))&&Number(value)>=min&&Number(value)<=max;
 function show(value:WindowRecord){return <div className="hours-stack"><p>{value.activityId?<><span>Current event name: </span><CurrentName kind="activities" id={value.activityId}/></>:'All past events'}</p><p><strong>{value.revoked?'Revoked':value.active&&value.expiresMs>Date.now()?'Open':'Expired or not yet open'}</strong> · ends {new Date(value.expiresMs).toISOString()} (UTC)</p></div>;}
 return <section className="hours-stack"><div className="hours-actions"><h2>Reporting windows</h2><button disabled={busy} onClick={()=>void reload()}>Reload reporting windows</button></div>{notice&&<p ref={ref} tabIndex={-1} className="ui-status settings-notice" data-tone={locked?'error':'success'} role={locked?'alert':'status'}>{notice}</p>}{busy&&<p role="status">Loading or saving reporting windows…</p>}{config&&<>
 <form className="ui-card hours-stack" onSubmit={e=>{e.preventDefault();if(integer(days,1,365)&&integer(hours,1,168))void saveSettings();}}><h3>Normal member reporting window</h3><p>Includes today and the preceding dates in {config.timeZone}. Today from the server: {config.today}. Staff can record historical entries without reopening member submissions.</p><div className="hours-grid"><label>Reporting days<input type="number" min={1} max={365} required value={days} disabled={busy||locked} onChange={e=>setDays(e.target.value)}/></label><label>Default reopening hours<input type="number" min={1} max={168} required value={hours} disabled={busy||locked} onChange={e=>setHours(e.target.value)}/></label></div><div className="hours-actions"><button className="primary-button" disabled={busy||locked||!integer(days,1,365)||!integer(hours,1,168)}>Save reporting settings</button></div></form>
 <form className="ui-card hours-stack" onSubmit={e=>{e.preventDefault();if(integer(duration,1,168)&&(scope==='all'||activity))void changeWindow();}}><h3>Reopen past event reporting</h3><p>Global reopening applies only to past events. It never opens historical team support or task/service dates. Up to 64 windows may be open at once; expiry is enforced by the server.</p><label>Reopening scope<select className="ui-native-select" disabled={busy||locked} value={scope} onChange={e=>setScope(e.target.value)}><option value="single">One past event</option><option value="all">All past events</option></select></label>{scope==='single'&&<NamedChoice label="Past event" kind="activities" query={'mode=event'+(pastThrough?'&to='+pastThrough:'')} value={activity} disabled={busy||locked||!pastThrough} onChange={item=>setActivity(item?.id??'')}/>}<label>Window duration in hours<input type="number" min={1} max={168} required value={duration} disabled={busy||locked} onChange={e=>setDuration(e.target.value)}/></label><div className="hours-actions"><button className="primary-button" disabled={busy||locked||!integer(duration,1,168)||(scope==='single'&&(!activity||!pastThrough))}>Open reporting window</button></div></form>
 </>}{confirmed&&<section className="ui-card hours-stack"><h3>Last confirmed window</h3>{show(confirmed)}</section>}{page&&<section className="hours-stack"><h3>Existing windows</h3><p>{page.items.length} windows on this page. Stable record order, including expired and revoked windows.</p>{page.items.map(value=><article className="ui-card hours-row" key={value.id}>{show(value)}{!value.revoked&&<button disabled={busy||locked} onClick={()=>void changeWindow(value)}>Revoke window ending {new Date(value.expiresMs).toISOString()}</button>}</article>)}{!page.items.length&&<p>No reporting windows found.</p>}<div className="hours-actions">{cursor&&<button disabled={busy} onClick={()=>void reload()}>First windows page</button>}{page.nextCursor&&<button disabled={busy||locked} onClick={()=>void reload(page.nextCursor!)}>Next windows page</button>}</div></section>}</section>;
}
