import { useEffect, useRef, useState } from 'react';
import { hourApi as api } from './hour-entry-contract';
import { identity, pageResult, type PageResult } from './hours-contract';
import { entry, entryFailure, settings, submissionReceipt, durationLabel, type Entry, type EntrySettings } from './hour-entry-contract';
import { CurrentName, NamedChoice } from './hour-named-choice';
import { EntryEditor } from './hour-entry-editor';
const blankFilters={memberId:'',activityId:'',status:'',from:'',to:''};
export function EntrySummary({value}:{value:Entry}) {return <div className="hours-stack"><p><strong>{value.status==='counted'?'Counted':'Voided'} · {durationLabel(value.durationMinutes)}</strong></p><p>Current member name: <CurrentName kind="member-choices" id={value.memberId}/></p><p>Current activity name: <CurrentName kind="activities" id={value.activityId}/></p><p>{value.serviceDate} · {value.startLocal}–{value.endLocal}{value.endNextDay?' (next day)':''} · {value.timeZone}</p><p>{value.channel==='staff'?'Staff recorded':value.channel==='public'?'Self-asserted submission':'Linked Discord submission'}</p>{value.taskNotes&&<p className="entry-notes">{value.taskNotes}</p>}</div>;}
export function HourEntries({accessChecking,onOccupied}:{accessChecking:boolean;onOccupied:(value:boolean)=>void}) {
 const [context,setContext]=useState<EntrySettings>(),[page,setPage]=useState<PageResult<Entry>>(),[cursor,setCursor]=useState(''),[filter,setFilter]=useState(blankFilters),[applied,setApplied]=useState(blankFilters),[record,setRecord]=useState<Entry>(),[form,setForm]=useState(false),[formKey,setFormKey]=useState(0),[working,setWorking]=useState(false),[locked,setLocked]=useState(false),[notice,setNotice]=useState(''),[voiding,setVoiding]=useState(false),[reason,setReason]=useState(''),[history,setHistory]=useState<PageResult<any>>(),[historyCursor,setHistoryCursor]=useState('');
 const busy=working||accessChecking,gate=useRef(false),active=useRef(true),noticeRef=useRef<HTMLParagraphElement>(null),heading=useRef<HTMLHeadingElement>(null),pending=useRef<{json:string;id?:string}|undefined>(undefined);
 useEffect(()=>{onOccupied(working||form||!!record||locked);},[working,form,record,locked,onOccupied]);
 useEffect(()=>{if(notice)noticeRef.current?.focus();},[notice]);
 function fail(){if(active.current){setLocked(true);setNotice(entryFailure);}}
 async function list(after='',filters=applied){const q=new URLSearchParams({limit:'50'});if(after)q.set('after',after);for(const [key,value]of Object.entries(filters))if(value)q.set(key,value);return pageResult(await api<PageResult<Entry>>('/admin/hours/entries?'+q),v=>!!entry(v));}
 async function reload(after='',filters=applied){if(gate.current)return;gate.current=true;setWorking(true);setNotice('');try{const [result,clock]=await Promise.all([list(after,filters),api<EntrySettings>('/admin/hours/entry-settings').then(settings)]);if(!active.current)return;setPage(result);setContext(clock);setCursor(after);setApplied({...filters});if(!pending.current){setLocked(false);setNotice('Current entries loaded. Review them before making a new change.');}else setNotice('Submission outcome remains uncertain. Review current entries; an exact retry uses the original frozen submission.');}catch{fail();}finally{gate.current=false;if(active.current)setWorking(false);}}
 useEffect(()=>{active.current=true;void reload();return()=>{active.current=false;};},[]);
 async function open(id?:string,edit=false){if(gate.current||busy||locked)return;gate.current=true;setWorking(true);setNotice('');try{const current=id?entry(await api<Entry>('/admin/hours/entries/'+encodeURIComponent(id))):undefined;const clock=current?context!:settings(await api<EntrySettings>('/admin/hours/entry-settings'));setContext(clock);setRecord(current);setForm(edit||!id);setFormKey(v=>v+1);setHistory(undefined);setNotice('');setVoiding(false);setReason('');requestAnimationFrame(()=>heading.current?.focus());}catch{fail();}finally{gate.current=false;setWorking(false);}}
 function close(){setRecord(undefined);setForm(false);setHistory(undefined);setVoiding(false);setReason('');requestAnimationFrame(()=>heading.current?.focus());}
 async function readCurrent(id:string){const value=entry(await api<Entry>('/admin/hours/entries/'+encodeURIComponent(id)));if(value.id!==id)throw Error('Wrong entry');return value;}
 async function create(body?:Record<string,unknown>){if(gate.current||busy)return;if(body){if(locked)return;pending.current={json:JSON.stringify({...body,idempotencyKey:crypto.randomUUID()})};}const submission=pending.current;if(!submission)return;gate.current=true;setWorking(true);setNotice('');try{if(!submission.id){const receipt=await api<any>('/admin/hours/entries',{method:'POST',body:submission.json});submission.id=submissionReceipt(receipt,JSON.parse(submission.json)).id;}const current=await readCurrent(submission.id!);const result=await list();setPage(result);setCursor('');setRecord(current);setForm(false);setHistory(undefined);pending.current=undefined;setLocked(false);setNotice('Original submission accepted. Current entry state was read from the server and is shown below.');}catch{fail();}finally{gate.current=false;setWorking(false);}}
 async function mutate(body:Record<string,unknown>,voidEntry=false){if(gate.current||busy||locked||!record)return;gate.current=true;setWorking(true);setNotice('');try{const result=await api<any>('/admin/hours/entries/'+encodeURIComponent(record.id)+(voidEntry?'/void':''),{method:voidEntry?'POST':'PATCH',body:JSON.stringify(body)});if(result?.id!==record.id||result.revision!==record.revision+1||result.status!==(voidEntry?'void':'counted'))throw Error('Invalid mutation');const current=await readCurrent(record.id);if(current.revision!==result.revision||current.status!==result.status)throw Error('Concurrent mutation');setRecord(current);setPage(await list());setCursor('');setForm(false);setVoiding(false);setHistory(undefined);setReason('');setNotice('Change confirmed from the current server record.');}catch{fail();}finally{gate.current=false;setWorking(false);}}
 async function recover(){if(gate.current||busy)return;if(pending.current?.id){await create();return;}if(!record){await reload();return;}gate.current=true;setWorking(true);setNotice('');try{setRecord(await readCurrent(record.id));setForm(false);setVoiding(false);setHistory(undefined);setLocked(false);setNotice('Current entry reloaded. The previous change was not retried.');}catch{fail();}finally{gate.current=false;setWorking(false);}}
 async function readHistory(after=''){if(gate.current||busy||!record)return;gate.current=true;setWorking(true);setNotice('');try{const result=pageResult(await api<PageResult<any>>(`/admin/hours/entries/${encodeURIComponent(record.id)}/history?limit=50${after?'&after='+encodeURIComponent(after):''}`),v=>v&&Number.isSafeInteger(v.revision)&&v.entryId===record.id&&['created','corrected','voided'].includes(v.action)&&typeof v.createdAt==='string'&&v.createdAt.length<=40&&Number.isFinite(Date.parse(v.createdAt))&&typeof v.reason==='string'&&v.reason.length<=4000&&!!entry(v.snapshot)&&v.snapshot.id===record.id&&v.snapshot.revision===v.revision);setHistory(result);setHistoryCursor(after);}catch{fail();}finally{gate.current=false;setWorking(false);}}
 return <section className="hours-stack"><div className="hours-actions"><h2 ref={heading} tabIndex={-1}>Entries</h2>{!record&&!form&&<button className="primary-button" disabled={busy||locked||!context} onClick={()=>void open()}>Record hours</button>}</div>{notice&&<p ref={noticeRef} tabIndex={-1} role={locked?'alert':'status'} className="ui-status settings-notice" data-tone={locked?'error':'success'}>{notice}</p>}{busy&&<p role="status">Loading or saving hours…</p>}
 {locked&&<div className="hours-actions"><button disabled={busy} onClick={()=>void recover()}>Reload current entries</button>{pending.current&&!pending.current.id&&<><button disabled={busy} onClick={()=>void create()}>Retry exact submission</button><button disabled={busy} onClick={()=>{pending.current=undefined;setForm(false);setRecord(undefined);setLocked(true);setNotice('Draft discarded. Its submission may already exist. Reload and review entries before recording again.');}}>Discard draft and review entries</button></>}</div>}
 {form&&context?<EntryEditor key={formKey} record={record} context={context} disabled={busy||locked} onSave={body=>record?void mutate(body):void create(body)} onClose={close}/>:record?<section className="ui-card hours-stack"><h3>Current entry</h3><EntrySummary value={record}/><div className="hours-actions">{record.status==='counted'&&<><button disabled={busy||locked} onClick={()=>{setForm(true);setFormKey(v=>v+1);}}>Correct entry</button><button className="danger-button" disabled={busy||locked} onClick={()=>{setVoiding(true);setReason('');}}>Void entry</button></>}<button disabled={busy} onClick={()=>void readHistory()}>View history</button><button disabled={busy||locked} onClick={close}>Close entry</button></div>{record.status==='void'&&<p>Void is terminal. Record a separate replacement if needed; this entry remains in history.</p>}{voiding&&<form className="hours-stack" onSubmit={e=>{e.preventDefault();if(reason.trim())void mutate({revision:record.revision,reason:reason.trim()},true);}}><p>Voiding removes these minutes from counted hours and preserves the record.</p><label>Void reason<textarea required maxLength={4000} value={reason} disabled={busy||locked} onChange={e=>setReason(e.target.value)}/></label><div className="hours-actions"><button className="danger-button" disabled={busy||locked||!reason.trim()}>Confirm void</button><button type="button" disabled={busy} onClick={()=>setVoiding(false)}>Cancel void</button></div></form>}{history&&<section className="hours-stack"><h3>Immutable history</h3><p>Names below are current roster/catalog names. Clocks, minutes, notes and reasons are saved revision values.</p>{history.items.map(v=><article className="ui-card hours-stack" key={v.revision}><h4>{v.action==='created'?'Created':v.action==='voided'?'Voided':'Corrected'} · revision {v.revision}</h4><p>{v.createdAt}</p>{v.reason&&<p className="entry-notes">Reason: {v.reason}</p>}<EntrySummary value={v.snapshot}/></article>)}<div className="hours-actions">{historyCursor&&<button disabled={busy} onClick={()=>void readHistory()}>First history page</button>}{history.nextCursor&&<button disabled={busy} onClick={()=>void readHistory(history.nextCursor!)}>Next history page</button>}</div></section>}</section>:<>
 <form className="ui-card hours-stack" onSubmit={e=>{e.preventDefault();void reload('',filter);}}><div className="hours-grid"><label>Entry status<select className="ui-native-select" disabled={busy} value={filter.status} onChange={e=>setFilter({...filter,status:e.target.value})}><option value="">Counted and voided</option><option value="counted">Counted</option><option value="void">Voided</option></select></label><label>From entry date<input type="date" disabled={busy} value={filter.from} onChange={e=>setFilter({...filter,from:e.target.value})}/></label><label>Through entry date<input type="date" disabled={busy} value={filter.to} min={filter.from} onChange={e=>setFilter({...filter,to:e.target.value})}/></label></div><details><summary>Member and activity filters</summary><NamedChoice label="Filter member" kind="member-choices" value={filter.memberId} disabled={busy} onChange={item=>setFilter({...filter,memberId:item?.id??''})}/><NamedChoice label="Filter activity" kind="activities" query="archived=all" value={filter.activityId} disabled={busy} onChange={item=>setFilter({...filter,activityId:item?.id??''})}/></details><div className="hours-actions"><button disabled={busy}>Apply entry filters</button><button type="button" disabled={busy} onClick={()=>void reload()}>Reload entries</button></div></form>
 {page&&<><p>{page.items.length} entries on this page. Stable record order; this is not an aggregate report.</p>{page.items.map((value,index)=><article className="ui-card hours-row" key={value.id}><EntrySummary value={value}/><button disabled={busy||locked} onClick={()=>void open(value.id)}>Review entry {index+1}</button></article>)}{!page.items.length&&<p>No entries match the applied filters.</p>}<div className="hours-actions">{cursor&&<button disabled={busy} onClick={()=>void reload()}>First entries page</button>}{page.nextCursor&&<button disabled={busy||locked} onClick={()=>void reload(page.nextCursor!)}>Next entries page</button>}</div></>}
 </>}
 </section>;
}
