import { useEffect, useId, useRef, useState } from 'react';
import { hourApi as api } from './hour-entry-contract';
import { boundedText, identity, pageResult, recordItem, type RecordItem } from './hours-contract';
export type NamedItem = {id:string;label:string;active?:boolean;archived?:boolean;mode?:string;serviceDate?:string};
export function namedItem(raw:any,kind:string):NamedItem {
  if(kind==='member-choices') { if(!raw||!identity(raw.id)||!boundedText(raw.label,256)||!boundedText(raw.externalId,128)||typeof raw.active!=='boolean') throw Error('Invalid member'); return {id:raw.id,label:`${raw.label} · ${raw.externalId}${raw.active?'':' (inactive)'}`,active:raw.active}; }
  const value=recordItem(raw,kind as 'activities'|'categories'|'teams'); return {id:value.id,label:value.title?`${value.serviceDate} · ${value.title}`:`${value.number?value.number+' · ':''}${value.name}`,archived:value.archived,mode:value.mode,serviceDate:value.serviceDate};
}
let namesInFlight=0;const nameQueue:(()=>void)[]=[];
async function readName(path:string){if(nameQueue.length>=100)throw Error('Name lookup queue full');if(namesInFlight<4)namesInFlight++;else await new Promise<void>(resolve=>nameQueue.push(resolve));try{return await api(path);}finally{const next=nameQueue.shift();if(next)next();else namesInFlight--;}}
export function CurrentName({id,kind}:{id:string;kind:string}) { const [name,setName]=useState('Loading current name…'),[error,setError]=useState(false),[version,setVersion]=useState(0); useEffect(()=>{let active=true;setName('Loading current name…');setError(false);void readName(`/admin/hours/${kind}/${encodeURIComponent(id)}`).then(raw=>{const value=namedItem(raw,kind);if(active)setName(value.label);}).catch(()=>{if(active){setName('Current name unavailable.');setError(true);}});return()=>{active=false;};},[id,kind,version]);return <span>{name}{error&&<button type="button" onClick={()=>setVersion(v=>v+1)}>Reload current name</button>}</span>; }
export function NamedChoice({label,kind,value,onChange,disabled=false,query=''}:{label:string;kind:string;value:string;onChange:(item?:NamedItem)=>void;disabled?:boolean;query?:string}) {
  const id=useId(),seq=useRef(0);const [items,setItems]=useState<NamedItem[]>([]),[next,setNext]=useState<string|null>(null),[current,setCurrent]=useState<NamedItem>(),[busy,setBusy]=useState(true),[error,setError]=useState(false),[search,setSearch]=useState(''),[applied,setApplied]=useState(''),[inactive,setInactive]=useState(false);
  async function load(after='',term=applied) { const token=++seq.current;setBusy(true);setError(false);try {const params=new URLSearchParams(query);params.set('limit','50');if(after)params.set('after',after);if(kind==='member-choices'){params.set('active',inactive?'all':'true');if(term)params.set('q',term);}const raw=await api<any>(`/admin/hours/${kind}?${params}`);pageResult(raw,item=>!!namedItem(item,kind));const rows=raw.items.map((item:RecordItem)=>namedItem(item,kind));const retained=value&&!rows.some((item:NamedItem)=>item.id===value)?namedItem(await api(`/admin/hours/${kind}/${encodeURIComponent(value)}`),kind):rows.find((item:NamedItem)=>item.id===value);if(token!==seq.current)return;setItems(rows);setNext(raw.nextCursor);setCurrent(retained);setApplied(term);}catch{if(token===seq.current)setError(true);}finally{if(token===seq.current)setBusy(false);} }
  useEffect(()=>{void load();return()=>{seq.current++;};},[kind,query,inactive]);
  return <fieldset disabled={disabled} className="hours-stack"><legend>{label}</legend>{kind==='member-choices'&&<><label>Find roster name or ID<input maxLength={100} value={search} onChange={e=>setSearch(e.target.value)} /></label><div className="hours-actions"><button type="button" disabled={busy} onClick={()=>void load('',search)}>Search members</button></div><label className="hours-check"><input type="checkbox" checked={inactive} disabled={busy} onChange={e=>setInactive(e.target.checked)} />Include inactive members for staff records</label></>}{error&&<p role="alert">Choices unavailable. Reload before selecting a reference.</p>}<label htmlFor={id}>{label}</label><select className="ui-native-select" id={id} value={value} disabled={busy||error} onChange={e=>{const selected=items.find(item=>item.id===e.target.value);setCurrent(selected);onChange(selected);}}><option value="">Choose {label.toLowerCase()}</option>{value&&!items.some(item=>item.id===value)&&<option value={value}>{current?.label??'Retained reference — current name unavailable'}</option>}{items.map(item=><option key={item.id} value={item.id} disabled={item.archived&&item.id!==value&&!query.includes('archived=all')}>{item.label}{item.archived?' (archived)':''}</option>)}</select>{value&&<p>Selected: {items.find(item=>item.id===value)?.label??current?.label??'Retained reference — current name unavailable'}</p>}<div className="hours-actions"><button type="button" disabled={busy} onClick={()=>void load()}>Reload {label.toLowerCase()}</button>{next&&<button type="button" disabled={busy||error} onClick={()=>void load(next)}>Next {label.toLowerCase()} page</button>}</div></fieldset>;
}
