import { FormEvent, useEffect, useState } from "react";
import { api, apiBaseUrl } from "./dashboard-api";

type Provider = "google" | "resend" | "discord";
type Status = { provider: Provider; configured: boolean; updatedAt?: string };
type Field = { key: string; label: string; type?: string; help?: string };
const metadata: Record<Provider, { title: string; detail: string; fields: Field[] }> = {
  google: { title: "Google OAuth", detail: "Allow designated Admins and Operators to sign in with their Google accounts.", fields: [{ key: "clientId", label: "OAuth client ID" }, { key: "clientSecret", label: "OAuth client secret", type: "password", help: "Google displays this secret only when the client is created. Store a recovery copy in your organization’s password manager." }] },
  resend: { title: "Resend email", detail: "Send missed-meeting notices and individual attendance reports.", fields: [{ key: "apiKey", label: "Sending API key", type: "password" }, { key: "fromEmail", label: "From address", type: "email", help: "Use an address at the exact domain or subdomain verified in Resend, such as attendance@updates.example.org." }] },
  discord: { title: "Discord bot", detail: "Enable optional member linking, absence contests, calendar events, and persistent kiosk status.", fields: [{ key: "botToken", label: "Bot token", type: "password", help: "Treat this like a password. Discord shows it only when created or reset." }, { key: "publicKey", label: "Application public key" }, { key: "guildId", label: "Server ID" }, { key: "channelId", label: "Attendance channel ID" }] },
};
const publicApiBase = apiBaseUrl.startsWith("http") ? apiBaseUrl : `${window.location.origin}${apiBaseUrl || "/api"}`;
const googleCallback = `${publicApiBase}/auth/google/callback`;
const discordCallback = `${window.location.origin}/api/discord/interactions`;

function CopyValue({ label, value }: { label: string; value: string }) {
  const [copied, setCopied] = useState(false);
  return <div className="copy-value"><span>{label}</span><code>{value}</code><button type="button" onClick={() => void navigator.clipboard.writeText(value).then(() => { setCopied(true); window.setTimeout(() => setCopied(false), 2000); })}>{copied ? "Copied" : "Copy"}</button></div>;
}

function ProviderGuide({ provider }: { provider: Provider }) {
  if (provider === "google") return <details className="integration-guide"><summary>Set up Google OAuth</summary><ol><li>Open the <a href="https://console.cloud.google.com/auth/overview" target="_blank" rel="noreferrer">Google Auth Platform</a>, select or create a project, and choose <strong>Get started</strong>.</li><li>Complete Branding with your organization’s app name and support email. Under Audience, use <strong>Internal</strong> for one Google Workspace organization or <strong>External</strong> and add your initial users as test users.</li><li>Open Clients, choose <strong>Create client</strong>, and select <strong>Web application</strong>.</li><li>Add the exact value below under <strong>Authorized redirect URIs</strong>. An Authorized JavaScript origin is not needed.</li><li>Create the client, then copy its client ID and client secret into LancerLogin.</li></ol><CopyValue label="Authorized redirect URI" value={googleCallback} /><p className="guide-note">LancerLogin requests only OpenID identity, email, and basic profile scopes. Each Google account must also be granted dashboard access on the Roster page.</p></details>;
  if (provider === "resend") return <details className="integration-guide"><summary>Set up Resend email</summary><ol><li>Create or sign in to <a href="https://resend.com" target="_blank" rel="noreferrer">Resend</a>.</li><li>Open <a href="https://resend.com/domains" target="_blank" rel="noreferrer">Domains</a>, add a domain or subdomain your organization controls, and add the DNS records Resend provides.</li><li>Wait until Resend marks the domain <strong>Verified</strong>.</li><li>Open <a href="https://resend.com/api-keys" target="_blank" rel="noreferrer">API Keys</a> and create a <strong>Sending access</strong> key restricted to that domain. Copy it when shown.</li><li>Enter the key and a From address using the verified domain, then save and test.</li></ol><p className="guide-note">Resend does not require a separate sender record after the domain is verified. Use an address that can receive replies when possible.</p></details>;
  return <details className="integration-guide"><summary>Set up a Discord bot</summary><ol><li>Open the <a href="https://discord.com/developers/applications" target="_blank" rel="noreferrer">Discord Developer Portal</a>, choose <strong>New Application</strong>, and name the app.</li><li>On General Information, copy the <strong>Public Key</strong>. Paste the exact Interactions Endpoint URL below and save; Discord should verify it.</li><li>Open Bot and choose <strong>Reset Token</strong> to create the bot token. Copy it immediately.</li><li>Open Installation. Enable <strong>Guild Install</strong>, use the <strong>bot</strong> scope, and grant View Channels, Send Messages, Read Message History, and Manage Events. Copy the install link and add the app to your server.</li><li>In Discord, enable Developer Mode under User Settings → Advanced. Right-click the server and attendance channel to copy their IDs.</li><li>Paste all four values below, save, and test.</li></ol><CopyValue label="Interactions Endpoint URL" value={discordCallback} /><p className="guide-note">Grant the bot access only to the attendance channel it needs. Server or channel permission overrides can prevent message and calendar workflows.</p></details>;
}

export function IntegrationSettings() {
  const [statuses, setStatuses] = useState<Status[]>([]); const [values, setValues] = useState<Record<string, string>>({}); const [notice, setNotice] = useState("Loading integration status…"); const [messages, setMessages] = useState<Partial<Record<Provider, { kind: "success" | "error"; text: string }>>>({}); const [busy, setBusy] = useState<Provider>();
  async function load() { const result = await api<{ integrations: Status[] }>("/admin/integrations"); setStatuses(result.integrations); setNotice("Saved secret values are encrypted and never displayed."); }
  useEffect(() => { void load().catch((error: Error) => setNotice(error.message)); }, []);
  function show(provider: Provider, kind: "success" | "error", text: string) { setMessages((current) => ({ ...current, [provider]: { kind, text } })); if (kind === "error") window.requestAnimationFrame(() => document.getElementById(`${provider}-integration-message`)?.focus()); }
  async function save(event: FormEvent, provider: Provider) { event.preventDefault(); const config = Object.fromEntries(metadata[provider].fields.map(({ key }) => [key, values[`${provider}.${key}`] ?? ""])); setBusy(provider); try { await api(`/admin/integrations/${provider}`, { method: "PUT", body: JSON.stringify(config) }); setValues((current) => Object.fromEntries(Object.entries(current).filter(([key]) => !key.startsWith(`${provider}.`)))); await load(); show(provider, "success", `${metadata[provider].title} saved. Previous credentials were replaced.`); } catch (error) { show(provider, "error", (error as Error).message); } finally { setBusy(undefined); } }
  async function test(provider: Provider) { setBusy(provider); try { await api(`/admin/integrations/${provider}/test`, { method: "POST" }); show(provider, "success", `${metadata[provider].title} connection test passed.`); } catch (error) { show(provider, "error", (error as Error).message); } finally { setBusy(undefined); } }
  async function remove(provider: Provider) { if (!window.confirm(`Remove ${metadata[provider].title}? Workflows using it will stop.`)) return; setBusy(provider); try { await api(`/admin/integrations/${provider}`, { method: "DELETE" }); await load(); show(provider, "success", `${metadata[provider].title} removed.`); } catch (error) { show(provider, "error", (error as Error).message); } finally { setBusy(undefined); } }
  return <section className="integration-section" aria-labelledby="integrations-title"><div className="page-intro"><h1 id="integrations-title">Integrations</h1></div><p className="setup-status" role="status">{notice}</p><div className="integration-grid">{(["google", "resend", "discord"] as const).map((provider) => { const status = statuses.find((item) => item.provider === provider); const message = messages[provider]; return <form className="integration-card" key={provider} onSubmit={(event) => void save(event, provider)}><div className="integration-title"><div><h2>{metadata[provider].title}</h2><p>{metadata[provider].detail}</p></div><span className={status?.configured ? "configured" : "not-configured"}>{status?.configured ? "Configured" : "Not configured"}</span></div><ProviderGuide provider={provider} />{metadata[provider].fields.map((field) => <label key={field.key}>{field.label}<input required type={field.type ?? "text"} autoComplete="off" value={values[`${provider}.${field.key}`] ?? ""} onChange={(event) => setValues({ ...values, [`${provider}.${field.key}`]: event.target.value })} />{field.help && <span className="field-help">{field.help}</span>}</label>)}{message && <p id={`${provider}-integration-message`} className={`inline-field-${message.kind}`} role={message.kind === "error" ? "alert" : "status"} tabIndex={-1}>{message.text}</p>}<button className="primary-button" type="submit" disabled={busy === provider}>{busy === provider ? "Working…" : status?.configured ? "Rotate configuration" : "Save configuration"}</button>{status?.configured && <div className="integration-actions"><button type="button" disabled={busy === provider} onClick={() => void test(provider)}>Test connection</button><button type="button" disabled={busy === provider} onClick={() => void remove(provider)}>Remove</button></div>}</form>; })}</div></section>;
}
