import { FormEvent, useEffect, useState } from "react";

const apiBaseUrl = (import.meta.env.VITE_API_BASE_URL as string | undefined)?.replace(/\/$/, "") ?? "";
type Provider = "google" | "resend" | "discord";
type Status = { provider: Provider; configured: boolean; updatedAt?: string };
const metadata: Record<Provider, { title: string; detail: string; fields: { key: string; label: string; type?: string }[] }> = {
  google: { title: "Google OAuth", detail: "Dashboard sign-in for organization Google accounts.", fields: [{ key: "clientId", label: "OAuth client ID" }, { key: "clientSecret", label: "OAuth client secret", type: "password" }] },
  resend: { title: "Resend email", detail: "Missed-meeting notices and individual attendance reports.", fields: [{ key: "apiKey", label: "API key", type: "password" }, { key: "fromEmail", label: "Verified from address", type: "email" }] },
  discord: { title: "Discord bot", detail: "Optional linking, absence notices and contests, calendar sync, and kiosk status.", fields: [{ key: "botToken", label: "Bot token", type: "password" }, { key: "publicKey", label: "Application public key" }, { key: "guildId", label: "Server ID" }, { key: "channelId", label: "Attendance channel ID" }] },
};
async function api<T>(path: string, init?: RequestInit): Promise<T> { const result = await fetch(`${apiBaseUrl}${path}`, { credentials: "include", ...init, headers: { ...(init?.body ? { "content-type": "application/json" } : {}), ...init?.headers } }); const body = await result.json() as T & { error?: string }; if (!result.ok) throw new Error(body.error ?? "Request failed"); return body; }

export function IntegrationSettings() {
  const [statuses, setStatuses] = useState<Status[]>([]); const [values, setValues] = useState<Record<string, string>>({}); const [notice, setNotice] = useState("Loading integration status…");
  async function load() { const result = await api<{ integrations: Status[] }>("/admin/integrations"); setStatuses(result.integrations); setNotice("Saved values are encrypted and never displayed."); }
  useEffect(() => { load().catch((error: Error) => setNotice(error.message)); }, []);
  async function save(event: FormEvent, provider: Provider) { event.preventDefault(); const config = Object.fromEntries(metadata[provider].fields.map(({ key }) => [key, values[`${provider}.${key}`] ?? ""])); try { await api(`/admin/integrations/${provider}`, { method: "PUT", body: JSON.stringify(config) }); setValues((current) => Object.fromEntries(Object.entries(current).filter(([key]) => !key.startsWith(`${provider}.`)))); await load(); setNotice(`${metadata[provider].title} saved. Previous credentials were replaced.`); } catch (error) { setNotice((error as Error).message); } }
  async function test(provider: Provider) { try { await api(`/admin/integrations/${provider}/test`, { method: "POST" }); setNotice(`${metadata[provider].title} connection test passed.`); } catch (error) { setNotice((error as Error).message); } }
  async function remove(provider: Provider) { if (!window.confirm(`Remove ${metadata[provider].title}? Workflows using it will stop.`)) return; try { await api(`/admin/integrations/${provider}`, { method: "DELETE" }); await load(); setNotice(`${metadata[provider].title} removed.`); } catch (error) { setNotice((error as Error).message); } }
  return <section className="integration-section" aria-labelledby="integrations-title"><div className="section-intro"><p className="kicker">Optional integrations</p><h2 id="integrations-title">Connect services when you’re ready</h2><p>These are separate from required setup. Saving again rotates a credential; LancerLogin never returns a saved value to this page.</p><span role="status">{notice}</span></div><div className="integration-grid">{(["google", "resend", "discord"] as const).map((provider) => { const status = statuses.find((item) => item.provider === provider); return <form className="integration-card" key={provider} onSubmit={(event) => save(event, provider)}><div className="integration-title"><div><h3>{metadata[provider].title}</h3><p>{metadata[provider].detail}</p></div><span className={status?.configured ? "configured" : "not-configured"}>{status?.configured ? "Configured" : "Not configured"}</span></div>{provider === "google" && <p className="callback-note">Authorized redirect URI: <code>{apiBaseUrl}/auth/google/callback</code></p>}{provider === "discord" && <p className="callback-note">Discord Interactions Endpoint URL: <code>{window.location.origin}/api/discord/interactions</code></p>}{metadata[provider].fields.map((field) => <label key={field.key}>{field.label}<input required type={field.type ?? "text"} autoComplete="off" value={values[`${provider}.${field.key}`] ?? ""} onChange={(event) => setValues({ ...values, [`${provider}.${field.key}`]: event.target.value })} /></label>)}<button className="primary-button" type="submit">{status?.configured ? "Rotate configuration" : "Save configuration"}</button>{status?.configured && <div className="integration-actions"><button type="button" onClick={() => test(provider)}>Test</button><button type="button" onClick={() => remove(provider)}>Remove</button></div>}</form>; })}</div></section>;
}
