import { FormEvent, useEffect, useState } from "react";
import { api } from "./dashboard-api";

type Meeting = { id: string; title: string; startsAt: string; endsAt?: string | null; required: boolean | number; notes?: string | null; isTest?: boolean | number };
export function MeetingsPage() {
  const [meetings, setMeetings] = useState<Meeting[]>([]); const [selected, setSelected] = useState(""); const [title, setTitle] = useState(""); const [startsAt, setStartsAt] = useState(new Date(Date.now() + 3_600_000).toISOString().slice(0, 16)); const [notice, setNotice] = useState("Loading meetings…");
  async function load() { const result = await api<{ meetings: Meeting[] }>("/meetings"); setMeetings(result.meetings); setSelected((current) => current || result.meetings[0]?.id || ""); setNotice(result.meetings.length ? "Meeting data is current." : "Create your first meeting."); }
  useEffect(() => { void load().catch((error: Error) => setNotice(error.message)); }, []);
  async function create(event: FormEvent) { event.preventDefault(); try { const result = await api<{ meeting: Meeting }>("/meetings", { method: "POST", body: JSON.stringify({ title, startsAt: new Date(startsAt).toISOString(), required: true, isTest: false }) }); setTitle(""); await load(); setSelected(result.meeting.id); setNotice("Meeting created."); } catch (error) { setNotice((error as Error).message); } }
  async function edit() { const meeting = meetings.find((item) => item.id === selected); if (!meeting) return; const nextTitle = window.prompt("Meeting title", meeting.title); if (!nextTitle) return; const nextStart = window.prompt("Meeting start (ISO date and time)", meeting.startsAt); if (!nextStart) return; const nextEnd = window.prompt("Meeting end (ISO date and time, or leave blank)", meeting.endsAt ?? ""); if (nextEnd === null) return; const nextRequired = window.prompt("Require attendance? Enter yes or no.", meeting.required ? "yes" : "no"); if (!nextRequired || !["yes", "no"].includes(nextRequired.trim().toLowerCase())) { setNotice("Meeting required status must be yes or no."); return; } const notes = window.prompt("Meeting notes (optional, up to 2,000 characters)", meeting.notes ?? ""); if (notes === null) return; try { await api(`/meetings/${encodeURIComponent(meeting.id)}`, { method: "PATCH", body: JSON.stringify({ title: nextTitle, startsAt: new Date(nextStart).toISOString(), endsAt: nextEnd.trim() ? new Date(nextEnd).toISOString() : null, required: nextRequired.toLowerCase() === "yes", notes }) }); await load(); setNotice("Meeting updated and audited."); } catch (error) { setNotice((error as Error).message); } }
  async function calendar() { try { await api("/discord/calendar", { method: "POST", body: JSON.stringify({ meetingId: selected }) }); setNotice("Optional Discord calendar event synchronized."); } catch (error) { setNotice((error as Error).message); } }
  return <section className="page-stack" aria-labelledby="meetings-title"><div className="page-intro"><p className="kicker">Operations</p><h2 id="meetings-title">Meetings</h2><p>Create and edit meetings without loading attendance, reports, or settings.</p></div><p className="setup-status" role="status">{notice}</p><div className="two-column-page"><form className="task-card" onSubmit={create}><h3>Create meeting</h3><label>Title<input required maxLength={120} value={title} onChange={(event) => setTitle(event.target.value)} /></label><label>Starts<input required type="datetime-local" value={startsAt} onChange={(event) => setStartsAt(event.target.value)} /></label><button className="primary-button" type="submit">Create meeting</button></form><section className="task-card"><h3>Existing meetings</h3><label>Meeting<select value={selected} onChange={(event) => setSelected(event.target.value)}><option value="">Choose a meeting</option>{meetings.map((meeting) => <option key={meeting.id} value={meeting.id}>{meeting.isTest ? "[TEST] " : ""}{meeting.title} · {new Date(meeting.startsAt).toLocaleString()}</option>)}</select></label><div className="button-row"><button type="button" disabled={!selected} onClick={edit}>Edit selected</button><button type="button" disabled={!selected} onClick={calendar}>Sync Discord calendar</button></div></section></div></section>;
}
