import { useEffect, useState } from "react";
import { api } from "./dashboard-api";
import { EditMemberDialog } from "./roster-page";
import { RouteLink, usePath } from "./router";
import type { RosterMember } from "./user-settings";

type HistoryRow = { meetingId: string; title: string; startsAt: string; endsAt: string; checkedInAt?: string; checkedOutAt?: string; reason?: string; disposition: "present" | "absent" | "excused" | "not_required" };
type Detail = { member: RosterMember; history: HistoryRow[] };

const formatTime = (value?: string) => value ? new Date(value).toLocaleString() : "—";

export function MemberDetailPage({ role, memberId }: { role: "admin" | "operator"; memberId: string }) {
  const { path, navigate } = usePath(); const [detail, setDetail] = useState<Detail>(); const [notice, setNotice] = useState("Loading member history…"); const [editing, setEditing] = useState(false);
  async function load(message = "") { const result = await api<Detail>(`/admin/members/${encodeURIComponent(memberId)}/history`); setDetail(result); setNotice(message); }
  useEffect(() => { void load().catch((error: Error) => setNotice(error.message)); }, [memberId]);
  async function toggleActive() { if (!detail) return; try { await api(`/admin/members/${encodeURIComponent(detail.member.id)}`, { method: "PATCH", body: JSON.stringify({ active: !detail.member.active }) }); await load(`${detail.member.firstName} is now ${detail.member.active ? "inactive" : "active"}.`); } catch (error) { setNotice((error as Error).message); } }
  async function remove() { if (!detail || !window.confirm(`Permanently delete ${detail.member.firstName} ${detail.member.lastName}? This is available only when they have no attendance history.`)) return; try { await api(`/admin/members/${encodeURIComponent(detail.member.id)}`, { method: "DELETE", body: JSON.stringify({ confirmation: `DELETE MEMBER ${detail.member.memberId}` }) }); navigate("/roster"); } catch (error) { setNotice((error as Error).message); } }
  return <section className="page-stack member-detail-page" aria-labelledby="member-detail-title"><RouteLink href="/roster" currentPath={path} navigate={navigate} className="back-link">← Back to roster</RouteLink>{notice && <p className="setup-status" role="status">{notice}</p>}{detail && <><article className="task-card"><div className="panel-heading"><div><h1 id="member-detail-title">{detail.member.firstName} {detail.member.lastName}</h1><p>{detail.member.memberId} · {detail.member.active ? "Active roster member" : "Inactive roster member"}</p></div>{role === "admin" && <div className="roster-row-actions"><button type="button" onClick={() => setEditing(true)}>Edit</button><button type="button" onClick={() => void toggleActive()}>{detail.member.active ? "Deactivate" : "Activate"}</button><button type="button" onClick={() => void remove()}>Delete</button></div>}</div><p>{detail.member.email || "No email on file"}{detail.member.attendanceRequiredFrom ? ` · Attendance required from ${detail.member.attendanceRequiredFrom}` : ""}</p></article><section className="task-card" aria-labelledby="member-attendance-history-title"><div className="panel-heading"><div><h2 id="member-attendance-history-title">Complete attendance history</h2><p>Every completed meeting, including check-in/check-out timestamps and absence or excuse outcomes.</p></div><span className="progress-count">{detail.history.length} meetings</span></div>{detail.history.length ? <div className="member-history"><div className="member-history-row header"><span>Meeting</span><span>Check-in</span><span>Check-out</span><span>Outcome</span></div>{detail.history.map((row) => <div className="member-history-row" key={row.meetingId}><span><strong>{row.title}</strong><small>{new Date(row.startsAt).toLocaleString()}</small></span><span>{formatTime(row.checkedInAt)}</span><span>{formatTime(row.checkedOutAt)}</span><span><strong className={`attendance-state ${row.disposition}`}>{row.disposition.replace("_", " ")}</strong>{row.reason && <small>{row.reason}</small>}</span></div>)}</div> : <p className="empty-state">No completed meetings are available for this member yet.</p>}</section><EditMemberDialog member={editing ? detail.member : undefined} onClose={() => setEditing(false)} onSaved={async () => { await load("Member updated."); }} /></>}</section>;
}
