import {useEffect,useRef,useState} from 'react';
import {DocumentationError,documentationRequest as api} from './documentation-request';
import {checkedDetail,checkedMetric,emptyMetric,metricErrors,metricFields,metricKinds,selections,type ContextKind,type Metric,type MetricContext,type MetricDetail,type MetricFields,type Selection} from './metrics-contract';
type MetricPage={metrics:Metric[];next:string|null};
type ChoicePage={items:Selection[];next:string|null};
type History={revisions:(MetricFields&{revision:number;archived:boolean;createdAt:string;activities:MetricContext[];initiatives:MetricContext[]})[];next:number|null};
const root='/admin/documentation/metrics';const encode=encodeURIComponent;
const fieldInfo={title:['Metric title','Required; maximum 200 characters.'],value:['Metric value','Exact decimal text, up to 15 integer and 6 fractional digits. A minus sign is allowed. Trailing zeros are preserved.'],unit:['Unit','Required; maximum 80 characters. State the unit explicitly.'],periodStart:['Period start','Inclusive calendar date; 1900-01-01 through 9999-12-31.'],periodEnd:['Period end','Inclusive calendar date; must be on or after the start.'],source:['Source','Required plain text; maximum 2000 characters. Links are stored as text.'],method:['Method','Required plain text; maximum 4000 characters. Explain how the value was obtained.']} as const;
function Contexts({activities,initiatives}:{activities:MetricContext[];initiatives:MetricContext[]}){return <div className="hours-stack">{(['activities','initiatives'] as const).map(type=><div key={type}><p>{type==='activities'?'Activities':'Initiatives'}: {(type==='activities'?activities:initiatives).length}</p><ul>{(type==='activities'?activities:initiatives).map(link=><li key={link.activityId??link.initiativeId}>{link.title}{!link.eligible?' · Retained, currently ineligible':''}</li>)}</ul></div>)}</div>;}
function MetricContent({value}:{value:MetricFields}){return <div className="hours-stack"><p className="documentation-text">{value.title}</p><p>{value.value} {value.unit} · {value.kind} · {value.basis}</p><p>{value.periodStart} through {value.periodEnd}, inclusive</p><p className="documentation-text">Source: {value.source}</p><p className="documentation-text">Method: {value.method}</p></div>;}
export function MetricsWorkspace({accessChecking=false,reloadAccess,onOccupied}:{accessChecking?:boolean;reloadAccess:()=>void;onOccupied:(value:boolean)=>void}){
 const [page,setPage]=useState<MetricPage>();const [archival,setArchival]=useState(false);const [selected,setSelected]=useState<MetricDetail>();const [editor,setEditor]=useState(false);const [draft,setDraft]=useState<MetricFields>({...emptyMetric});const [links,setLinks]=useState<Selection[]>([]);const [choices,setChoices]=useState<Partial<Record<ContextKind,ChoicePage>>>({});const [history,setHistory]=useState<History>();
 const [reading,setReading]=useState(false);const [writing,setWriting]=useState(false);const [locked,setLocked]=useState(false);const [notice,setNotice]=useState('');const generation=useRef(0),readPending=useRef(false),mutationPending=useRef(false);const noticeRef=useRef<HTMLParagraphElement>(null),editorRef=useRef<HTMLHeadingElement>(null);
 const busy=reading||writing,disabled=busy||accessChecking||locked;const errors=metricErrors(draft);const savedLinks=selected?selections(selected):[];const linkKeys=(value:Selection[])=>value.map(link=>link.type+':'+link.id).sort();const dirty=!!selected&&(JSON.stringify(draft)!==JSON.stringify(metricFields(selected.metric))||JSON.stringify(linkKeys(links))!==JSON.stringify(linkKeys(savedLinks)));const invalidLinks=links.length>100||links.some(link=>!link.eligible&&!savedLinks.some(saved=>saved.type===link.type&&saved.id===link.id));
 useEffect(()=>onOccupied(busy||editor||locked),[busy,editor,locked,onOccupied]);useEffect(()=>{if(notice)noticeRef.current?.focus();},[notice]);useEffect(()=>{if(editor)editorRef.current?.focus();},[editor]);
 function clear(){setPage(undefined);setSelected(undefined);setEditor(false);setDraft({...emptyMetric});setLinks([]);setChoices({});setHistory(undefined);}
 function failure(error:unknown){setLocked(true);if(error instanceof DocumentationError&&[401,403].includes(error.status)){clear();reloadAccess();}setNotice('Current metric records could not be confirmed. Reload metrics and review the saved record and preserved draft before a new change. Remove unavailable new associations. No write is retried automatically.');}
 async function read(action:(valid:()=>boolean)=>Promise<void>){if(readPending.current||mutationPending.current)return;const token=generation.current;const valid=()=>generation.current===token;readPending.current=true;setReading(true);try{await action(valid);}catch(error){if(valid())failure(error);}finally{if(valid()){readPending.current=false;setReading(false);}}}
 async function getPage(after='',include=archival){const value=await api<MetricPage>(root+'?limit=25&archival='+include+(after?'&after='+encode(after):''));if(!Array.isArray(value.metrics))throw Error('Invalid metrics');value.metrics.forEach(checkedMetric);return value;}
 async function getChoices(type:ContextKind,after=''):Promise<ChoicePage>{const value=await api<Record<string,unknown>>('/admin/documentation/'+type+'?limit=25'+(after?'&after='+encode(after):''));const items=value[type] as {id:string;title:string;revision:number;archived:boolean;impactRelevant?:boolean}[];if(!Array.isArray(items)||items.some(item=>typeof item.id!=='string'||typeof item.title!=='string'||!Number.isSafeInteger(item.revision)||typeof item.archived!=='boolean'))throw Error('Invalid choices');return {items:items.map(item=>({id:item.id,title:item.title,revision:item.revision,type,eligible:!item.archived&&(type==='initiatives'||item.impactRelevant===true)})),next:value.next as string|null};}
 async function list(after='',include=archival){await read(async valid=>{const value=await getPage(after,include);if(valid())setPage(value);});}
 async function open(item?:Metric){await read(async valid=>{const [current,activities,initiatives]=await Promise.all([item?api<MetricDetail>(root+'/'+encode(item.id)).then(checkedDetail):Promise.resolve(undefined),getChoices('activities'),getChoices('initiatives')]);if(!valid())return;setSelected(current);setDraft(current?metricFields(current.metric):{...emptyMetric});setLinks(current?selections(current):[]);setChoices({activities,initiatives});setEditor(true);setHistory(undefined);setNotice('');});}
 async function refreshLink(link:Selection,current?:MetricDetail){const saved=current&&selections(current).find(item=>item.id===link.id&&item.type===link.type);if(saved)return saved;try{const value=await api<Record<string,any>>('/admin/documentation/'+link.type+'/'+encode(link.id));const item=link.type==='initiatives'?value.initiative:value;if(!item||item.id!==link.id||!Number.isSafeInteger(item.revision))throw Error('Invalid association');return {...link,title:item.title,revision:item.revision,eligible:!item.archived&&(link.type==='initiatives'||item.impactRelevant===true)};}catch(error){if(error instanceof DocumentationError&&error.status===404)return {...link,eligible:false};throw error;}}
 async function reload(explicit=true){await read(async valid=>{const [value,current,activities,initiatives]=await Promise.all([getPage(),selected?api<MetricDetail>(root+'/'+encode(selected.metric.id)).then(checkedDetail):Promise.resolve(undefined),editor?getChoices('activities'):Promise.resolve(undefined),editor?getChoices('initiatives'):Promise.resolve(undefined)]);const refreshed=await Promise.all(links.map(link=>refreshLink(link,current)));if(!valid())return;setPage(value);setSelected(current);setLinks(refreshed);setChoices({activities,initiatives});setHistory(undefined);if(explicit){setLocked(false);setNotice('Current metrics reloaded. Your draft is preserved; review the saved fields and associations before saving.');}});}
 useEffect(()=>{readPending.current=false;void list();return()=>{generation.current++;};},[]);useEffect(()=>{if(accessChecking){generation.current++;readPending.current=false;setReading(false);setLocked(true);}else if(page){void reload(false);}},[accessChecking]);
 async function write(body:object){if(disabled||readPending.current||mutationPending.current)return;mutationPending.current=true;setWriting(true);const token=generation.current;try{const response=await api<{metric:Metric}>(root+(selected?'/'+encode(selected.metric.id):''),{method:selected?'PATCH':'POST',body:JSON.stringify(body)});if(token!==generation.current)return;checkedMetric(response.metric);if(response.metric.revision!==(selected?selected.metric.revision+1:0)||selected&&response.metric.id!==selected.metric.id)throw Error('Invalid write response');const [current,value]=await Promise.all([api<MetricDetail>(root+'/'+encode(response.metric.id)).then(checkedDetail),getPage()]);if(token!==generation.current)return;if(current.metric.id!==response.metric.id||current.metric.revision!==response.metric.revision)throw Error('Uncertain readback');setSelected(current);setDraft(metricFields(current.metric));setLinks(selections(current));setPage(value);setHistory(undefined);setNotice('Saved and confirmed from current server records.');}catch(error){if(token===generation.current)failure(error);}finally{mutationPending.current=false;setWriting(false);}}
 async function showHistory(after?:number){if(!selected)return;await read(async valid=>{const value=await api<History>(root+'/'+encode(selected.metric.id)+'/history?limit=25'+(after===undefined?'':'&after='+after));if(!Array.isArray(value.revisions))throw Error('Invalid history');value.revisions.forEach(row=>checkedDetail({metric:{...row,id:selected.metric.id,updatedAt:row.createdAt},activities:row.activities,initiatives:row.initiatives,readOnly:row.archived}));if(valid())setHistory(value);});}
 function discard(){if(selected){setDraft(metricFields(selected.metric));setLinks(selections(selected));}}
 function close(){setEditor(false);setSelected(undefined);setDraft({...emptyMetric});setLinks([]);setChoices({});setHistory(undefined);}
 return <section className="hours-workspace" aria-busy={busy||accessChecking}><h2>Metrics</h2><p>Record a value with its unit, period and method. Metrics remain separate from Hours accounting and do not establish a reviewed claim.</p>{notice&&<p ref={noticeRef} tabIndex={-1} role={locked?'alert':'status'} className="ui-status">{notice}</p>}<div className="hours-actions"><button disabled={busy||accessChecking} onClick={()=>void reload()}>Reload metrics</button>{editor&&<button disabled={busy} onClick={close}>{dirty||!selected?'Close and discard metric draft':'Close metric'}</button>}</div>{accessChecking?<p role="status">Checking current workspace access…</p>:<>
 {!editor?<><div className="hours-actions"><button className="primary-button" disabled={disabled} onClick={()=>void open()}>Create metric</button></div><label className="hours-check"><input type="checkbox" checked={archival} disabled={busy} onChange={e=>{setArchival(e.target.checked);void list('',e.target.checked);}}/>Include archived metrics</label><div className="hours-records">{page?.metrics.map(item=><article key={item.id} className="ui-card hours-row"><div><h3>{item.title}</h3><p>{item.value} {item.unit} · {item.basis} · {item.archived?'Archived':'Active'}</p><p>{item.periodStart} through {item.periodEnd}</p></div><button disabled={busy} onClick={()=>void open(item)}>Open {item.title}</button></article>)}</div>{page?.metrics.length===0&&<p>No metrics on this page.</p>}<div className="hours-actions"><button disabled={busy} onClick={()=>void list()}>First metrics page</button>{page?.next&&<button disabled={busy} onClick={()=>void list(page.next!)}>Next metrics page</button>}</div></>:<section className="ui-card hours-stack"><h3 ref={editorRef} tabIndex={-1}>{selected?'Edit metric':'New metric'}</h3>{selected&&<><p>Current saved revision {selected.metric.revision}{selected.metric.archived?' · Archived, read-only':''}</p><details><summary>Current saved metric and associations</summary><MetricContent value={selected.metric}/><Contexts activities={selected.activities} initiatives={selected.initiatives}/></details><div className="hours-actions"><button disabled={busy} onClick={()=>void showHistory()}>View metric history</button><button className={selected.metric.archived?'':'danger-button'} disabled={disabled||dirty} onClick={()=>void write({revision:selected.metric.revision,archived:!selected.metric.archived})}>{selected.metric.archived?'Unarchive metric':'Archive metric'}</button></div>{dirty&&<div className="hours-stack"><p>Save or discard your draft before archiving this metric.</p><div className="hours-actions"><button disabled={busy} onClick={discard}>Discard metric draft</button></div></div>}</>}
 {!selected?.metric.archived&&<form className="hours-stack" onSubmit={e=>{e.preventDefault();if(Object.keys(errors).length||invalidLinks)return;void write({...draft,...(selected?{revision:selected.metric.revision}:{}),activities:links.filter(link=>link.type==='activities').map(link=>({activityId:link.id,revision:link.revision})),initiatives:links.filter(link=>link.type==='initiatives').map(link=>({initiativeId:link.id,revision:link.revision}))});}}><div className="hours-grid metrics-fields">{(Object.keys(fieldInfo) as (keyof typeof fieldInfo)[]).map(key=><div key={key} className="hours-stack"><label htmlFor={'metric-'+key}>{fieldInfo[key][0]}</label><p id={'metric-'+key+'-help'}>{fieldInfo[key][1]}{['title','unit','source','method'].includes(key)?' Emoji may count as two characters.':''}</p>{key==='source'||key==='method'?<textarea id={'metric-'+key} value={draft[key]} maxLength={key==='source'?2000:4000} disabled={busy} aria-describedby={'metric-'+key+'-help metric-'+key+'-error'} aria-invalid={!!draft[key]&&!!errors[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/>:<input id={'metric-'+key} type={key==='periodStart'||key==='periodEnd'?'date':'text'} inputMode={key==='value'?'decimal':undefined} min={key==='periodStart'||key==='periodEnd'?'1900-01-01':undefined} max={key==='periodStart'||key==='periodEnd'?'9999-12-31':undefined} maxLength={key==='title'?200:key==='unit'?80:key==='value'?23:undefined} value={draft[key]} disabled={busy} aria-describedby={'metric-'+key+'-help metric-'+key+'-error'} aria-invalid={!!draft[key]&&!!errors[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/>}<p hidden={!draft[key]||!errors[key]} id={'metric-'+key+'-error'} className="ui-status" data-tone="error">{draft[key]&&errors[key]}</p></div>)}<label>Metric kind<select className="ui-native-select" value={draft.kind} disabled={busy} onChange={e=>setDraft({...draft,kind:e.target.value})}>{metricKinds.map(kind=><option key={kind} value={kind}>{kind}</option>)}</select></label><label>Measurement basis<select className="ui-native-select" value={draft.basis} disabled={busy} onChange={e=>setDraft({...draft,basis:e.target.value})}><option value="measured">Measured</option><option value="estimated">Estimated</option></select></label></div><p>Kind describes the metric; participant values do not imply unique people. Values are never added across metrics or converted between units.</p>
 <fieldset className="hours-stack"><legend>Associations</legend><p>{links.length}/100 selected across activities and initiatives. Associations are optional. Saving replaces both selections; selecting an initiative does not automatically select its activities.</p>{links.map(link=><div key={link.type+link.id} className="hours-row"><span>{link.title} · {link.type==='activities'?'Activity':'Initiative'}{!link.eligible?' · Currently ineligible':''}{!link.eligible&&!savedLinks.some(saved=>saved.type===link.type&&saved.id===link.id)?' · Unavailable new association; remove before saving':''}</span><button type="button" disabled={busy} onClick={()=>setLinks(links.filter(item=>item.type!==link.type||item.id!==link.id))}>Remove {link.title}</button></div>)}{(['activities','initiatives'] as const).map(type=><section className="hours-stack" key={type}><h4>{type==='activities'?'Eligible activities':'Active initiatives'}</h4>{choices[type]?.items.map(item=><label className="hours-check" key={item.id}><input type="checkbox" disabled={busy||!item.eligible||(!links.some(link=>link.type===type&&link.id===item.id)&&links.length>=100)} checked={links.some(link=>link.type===type&&link.id===item.id)} onChange={e=>setLinks(e.target.checked?[...links,item]:links.filter(link=>link.type!==type||link.id!==item.id))}/>Associate {item.title}</label>)}{choices[type]?.items.length===0&&<p>No eligible choices on this page.</p>}<div className="hours-actions"><button type="button" disabled={busy} onClick={()=>void read(async valid=>{const value=await getChoices(type);if(valid())setChoices(previous=>({...previous,[type]:value}));})}>First {type} choices page</button>{choices[type]?.next&&<button type="button" disabled={busy} onClick={()=>void read(async valid=>{const value=await getChoices(type,choices[type]!.next!);if(valid())setChoices(previous=>({...previous,[type]:value}));})}>Next {type} choices page</button>}</div></section>)}</fieldset><div className="hours-actions"><button className="primary-button" disabled={disabled||Object.keys(errors).length>0||invalidLinks}>Save metric</button></div></form>}
 {history&&<section className="hours-stack"><h4>Immutable metric history</h4><p>Membership is historical. Associated titles and eligibility are current, not snapshots of those names at the time.</p>{history.revisions.map(row=><article key={row.revision} className="ui-card hours-stack"><h5>Revision {row.revision}{row.archived?' · Archived':''}</h5><p>{row.createdAt}</p><MetricContent value={row}/><Contexts activities={row.activities} initiatives={row.initiatives}/></article>)}<div className="hours-actions"><button disabled={busy} onClick={()=>void showHistory()}>First metric history page</button>{history.next!==null&&<button disabled={busy} onClick={()=>void showHistory(history.next!)}>Next metric history page</button>}</div></section>}
 </section>}</>}</section>;
}
