import { FormEvent, useState } from "react";
import { api } from "./dashboard-api";
import type { Branding } from "./setup-workspace";
import { AdaptiveBrandLogo, type LogoBackdrop } from "./adaptive-brand-logo";
import { ColorEditor } from "./color-editor";

export function OrganizationSettings({ initialBranding, onChanged }: { initialBranding: Branding; onChanged: (branding: Branding) => void }) {
  const [branding, setBranding] = useState(initialBranding); const [notice, setNotice] = useState(""); const [saving, setSaving] = useState(false);
  async function logo(file?: File) { if (!file) return; if (!["image/png", "image/jpeg", "image/webp"].includes(file.type) || file.size > 131_072) { setNotice("Choose a PNG, JPEG, or WebP logo no larger than 128 KiB."); return; } const data = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); }); setBranding({ ...branding, logoData: data }); setNotice("Logo selected. Save to store it in D1."); }
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); try { await api("/admin/branding", { method: "PATCH", body: JSON.stringify(branding) }); onChanged(branding); setNotice("Organization and appearance saved."); } catch (error) { setNotice((error as Error).message); } finally { setSaving(false); } }
  return <section className="settings-page" aria-labelledby="organization-title"><div className="page-intro"><h1 id="organization-title">Organization</h1></div>{notice && <p className="setup-status" role="status">{notice}</p>}<form className="settings-form" onSubmit={save}><label>Organization name<input required maxLength={100} value={branding.organizationName} onChange={(event) => setBranding({ ...branding, organizationName: event.target.value })} /></label><label>Subtitle <span>(optional)</span><input maxLength={140} value={branding.subtitle ?? ""} onChange={(event) => setBranding({ ...branding, subtitle: event.target.value })} /></label><label>Logo image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => void logo(event.target.files?.[0])} /></label>{branding.logoData && <><div className="logo-preview-grid"><div data-preview-theme="light"><span>Light preview</span><AdaptiveBrandLogo src={branding.logoData} alt="Organization logo on light background" backdrop={branding.logoBackdrop} /></div><div data-preview-theme="dark"><span>Dark preview</span><AdaptiveBrandLogo src={branding.logoData} alt="Organization logo on dark background" backdrop={branding.logoBackdrop} /></div></div><fieldset className="logo-backdrop-options"><legend>Logo contrast background</legend><div>{([{ value: "auto", label: "Automatic" }, { value: "light", label: "Light" }, { value: "dark", label: "Dark" }, { value: "none", label: "None" }] as { value: LogoBackdrop; label: string }[]).map((option) => <label className={branding.logoBackdrop === option.value ? "selected" : ""} key={option.value}><input type="radio" name="logo-backdrop" checked={branding.logoBackdrop === option.value} onChange={() => setBranding({ ...branding, logoBackdrop: option.value })} />{option.label}</label>)}</div></fieldset><button className="quiet-button" type="button" onClick={() => setBranding({ ...branding, logoData: "" })}>Remove logo</button></>}<div className="color-grid"><ColorEditor label="Primary color" value={branding.primaryColor} onChange={(primaryColor) => setBranding({ ...branding, primaryColor })} /><ColorEditor label="Secondary color" value={branding.secondaryColor} onChange={(secondaryColor) => setBranding({ ...branding, secondaryColor })} /></div><p className="field-help">Theme choice is saved separately in each browser from the light/dark mode button.</p><button className="primary-button" disabled={saving} type="submit">{saving ? "Saving…" : "Save organization settings"}</button></form></section>;
}
