import { FormEvent, useState } from "react";
import { api } from "./dashboard-api";
import type { Branding } from "./setup-workspace";

export function OrganizationSettings({ initialBranding, onChanged }: { initialBranding: Branding; onChanged: (branding: Branding) => void }) {
  const [branding, setBranding] = useState(initialBranding); const [notice, setNotice] = useState("Changes apply after you save them."); const [saving, setSaving] = useState(false);
  async function logo(file?: File) { if (!file) return; if (!["image/png", "image/jpeg", "image/webp"].includes(file.type) || file.size > 131_072) { setNotice("Choose a PNG, JPEG, or WebP logo no larger than 128 KiB."); return; } const data = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); }); setBranding({ ...branding, logoData: data }); setNotice("Logo selected. Save to store it in D1."); }
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); try { await api("/admin/branding", { method: "PATCH", body: JSON.stringify(branding) }); onChanged(branding); setNotice("Organization and appearance saved."); } catch (error) { setNotice((error as Error).message); } finally { setSaving(false); } }
  return <section className="settings-page" aria-labelledby="organization-title"><div className="page-intro"><p className="kicker">Settings</p><h2 id="organization-title">Organization and appearance</h2><p>Branding stays available here after onboarding and in every display mode.</p></div><p className="setup-status" role="status">{notice}</p><form className="settings-form" onSubmit={save}><label>Organization name<input required maxLength={100} value={branding.organizationName} onChange={(event) => setBranding({ ...branding, organizationName: event.target.value })} /></label><label>Subtitle <span>(optional)</span><input maxLength={140} value={branding.subtitle ?? ""} onChange={(event) => setBranding({ ...branding, subtitle: event.target.value })} /></label><label>Logo image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => void logo(event.target.files?.[0])} /></label>{branding.logoData && <div className="logo-preview"><img src={branding.logoData} alt="Current organization logo preview" /><button type="button" onClick={() => setBranding({ ...branding, logoData: "" })}>Remove logo</button></div>}<div className="color-grid"><label>Primary<input type="color" value={branding.primaryColor} onChange={(event) => setBranding({ ...branding, primaryColor: event.target.value })} /></label><label>Secondary<input type="color" value={branding.secondaryColor} onChange={(event) => setBranding({ ...branding, secondaryColor: event.target.value })} /></label></div><label>Appearance<select value={branding.appearance} onChange={(event) => setBranding({ ...branding, appearance: event.target.value as Branding["appearance"] })}><option value="themed">Organization colors</option><option value="light">Light</option><option value="dark">Dark</option><option value="system">Follow device</option></select></label><button className="primary-button" disabled={saving} type="submit">{saving ? "Saving…" : "Save organization settings"}</button></form></section>;
}
