import { useEffect, useState } from "react";
import { useDashboardLoadingOverlay } from "./loading-overlay";

const apiBaseUrl = (import.meta.env.VITE_API_BASE_URL as string | undefined)?.replace(/\/$/, "") ?? "";
async function api<T>(path: string, init?: RequestInit): Promise<T> { const result = await fetch(`${apiBaseUrl}${path}`, { credentials: "include", ...init, headers: { ...(init?.body ? { "content-type": "application/json" } : {}), ...init?.headers } }); const body = await result.json() as T & { error?: string }; if (!result.ok) throw new Error(body.error ?? "Request failed"); return body; }

export function PrivacySettings() {
  const [accepted, setAccepted] = useState(false); const [acceptedAt, setAcceptedAt] = useState<string>(); const [installationReference, setInstallationReference] = useState<string>(); const [notice, setNotice] = useState("Loading anonymous usage reporting choice…"); const [error, setError] = useState(false); const [busy, setBusy] = useState(false);
  useDashboardLoadingOverlay(notice === "Loading anonymous usage reporting choice…", "Loading privacy settings…");
  useEffect(() => { api<{ telemetryAccepted: boolean; acceptedAt?: string; installationReference?: string; notice: string }>("/admin/privacy").then((result) => { setAccepted(result.telemetryAccepted); setAcceptedAt(result.acceptedAt); setInstallationReference(result.installationReference); setNotice(result.notice); setError(false); }).catch((caught: Error) => { setNotice(caught.message); setError(true); }); }, []);
  async function update(value: boolean) { setBusy(true); try { const result = await api<{ telemetryAccepted: boolean; acceptedAt?: string }>("/admin/privacy", { method: "PATCH", body: JSON.stringify({ telemetryAccepted: value }) }); setAccepted(result.telemetryAccepted); setAcceptedAt(result.acceptedAt); setInstallationReference(undefined); setNotice(value ? "Anonymous usage reporting is on. Delivery is best-effort and never blocks attendance." : "Anonymous usage reporting is off. No report will be sent."); setError(false); } catch (caught) { setNotice((caught as Error).message); setError(true); } finally { setBusy(false); } }
  return <section className="settings-page settings-privacy" aria-labelledby="privacy-settings-title"><div className="page-intro"><h1 id="privacy-settings-title">Privacy</h1><p>Choose whether this installation contributes anonymous operational totals to the community collector.</p></div><article className="privacy-section"><div><h2>Anonymous usage reporting</h2><p><strong>This choice is optional.</strong></p><p className="ui-status settings-notice" data-tone={error ? "error" : accepted ? "success" : "neutral"} role={error ? "alert" : "status"}>{notice}</p>{acceptedAt && <small>Enabled {new Date(acceptedAt).toLocaleString()}</small>}{installationReference && <p><small>Deletion-request reference: <code>{installationReference}</code>. Email it to robolancers@gmail.com to request removal from the community collector.</small></p>}</div><label className="telemetry-choice"><input type="checkbox" checked={accepted} disabled={busy} onChange={(event) => void update(event.target.checked)} /><span><strong>{busy ? "Saving choice…" : "Allow anonymous usage reporting"}</strong><small>Never includes roster, attendance, member identity, fingerprints, dashboard accounts, credentials, content, or raw IP addresses.</small></span></label></article></section>;
}
