import { useEffect, useState } from "react";

const apiBaseUrl = (import.meta.env.VITE_API_BASE_URL as string | undefined)?.replace(/\/$/, "") ?? "";
async function api<T>(path: string, init?: RequestInit): Promise<T> { const result = await fetch(`${apiBaseUrl}${path}`, { credentials: "include", ...init, headers: { ...(init?.body ? { "content-type": "application/json" } : {}), ...init?.headers } }); const body = await result.json() as T & { error?: string }; if (!result.ok) throw new Error(body.error ?? "Request failed"); return body; }

export function PrivacySettings() {
  const [accepted, setAccepted] = useState(false); const [acceptedAt, setAcceptedAt] = useState<string>(); const [installationReference, setInstallationReference] = useState<string>(); const [notice, setNotice] = useState("Loading anonymous usage reporting choice…");
  useEffect(() => { api<{ telemetryAccepted: boolean; acceptedAt?: string; installationReference?: string; notice: string }>("/admin/privacy").then((result) => { setAccepted(result.telemetryAccepted); setAcceptedAt(result.acceptedAt); setInstallationReference(result.installationReference); setNotice(result.notice); }).catch((error: Error) => setNotice(error.message)); }, []);
  async function update(value: boolean) { try { const result = await api<{ telemetryAccepted: boolean; acceptedAt?: string }>("/admin/privacy", { method: "PATCH", body: JSON.stringify({ telemetryAccepted: value }) }); setAccepted(result.telemetryAccepted); setAcceptedAt(result.acceptedAt); setInstallationReference(undefined); setNotice(value ? "Anonymous usage reporting is on. Delivery is best-effort and never blocks attendance." : "Anonymous usage reporting is off. No report will be sent."); } catch (error) { setNotice((error as Error).message); } }
  return <section className="privacy-section" aria-labelledby="privacy-settings-title"><div><h1 id="privacy-settings-title">Privacy</h1><p><strong>Anonymous usage reporting is optional.</strong></p><p>{notice}</p>{acceptedAt && <small>Enabled {new Date(acceptedAt).toLocaleString()}</small>}{installationReference && <p><small>Deletion-request reference: <code>{installationReference}</code>. Email it to robolancers@gmail.com to request removal from the community collector.</small></p>}</div><label className="telemetry-choice"><input type="checkbox" checked={accepted} onChange={(event) => update(event.target.checked)} /><span><strong>Allow anonymous usage reporting</strong><small>Never includes roster, attendance, member identity, fingerprints, dashboard accounts, credentials, content, or raw IP addresses.</small></span></label></section>;
}
