import { useEffect, useState } from "react";

const apiBaseUrl = (import.meta.env.VITE_API_BASE_URL as string).replace(/\/$/, "");
async function api<T>(path: string, init?: RequestInit): Promise<T> { const result = await fetch(`${apiBaseUrl}${path}`, { credentials: "include", ...init, headers: { ...(init?.body ? { "content-type": "application/json" } : {}), ...init?.headers } }); const body = await result.json() as T & { error?: string }; if (!result.ok) throw new Error(body.error ?? "Request failed"); return body; }

export function PrivacySettings() {
  const [accepted, setAccepted] = useState(false); const [acceptedAt, setAcceptedAt] = useState<string>(); const [notice, setNotice] = useState("Loading privacy choice…");
  useEffect(() => { api<{ telemetryAccepted: boolean; acceptedAt?: string; notice: string }>("/admin/privacy").then((result) => { setAccepted(result.telemetryAccepted); setAcceptedAt(result.acceptedAt); setNotice(result.notice); }).catch((error: Error) => setNotice(error.message)); }, []);
  async function update(value: boolean) { try { const result = await api<{ telemetryAccepted: boolean; acceptedAt?: string }>("/admin/privacy", { method: "PATCH", body: JSON.stringify({ telemetryAccepted: value }) }); setAccepted(result.telemetryAccepted); setAcceptedAt(result.acceptedAt); setNotice(value ? "Privacy-preserving telemetry accepted. Delivery is best-effort and never blocks attendance." : "Telemetry declined. No telemetry payload will be sent."); } catch (error) { setNotice((error as Error).message); } }
  return <section className="privacy-section" aria-labelledby="privacy-settings-title"><div><p className="kicker">Privacy</p><h2 id="privacy-settings-title">Community telemetry</h2><p>{notice}</p>{acceptedAt && <small>Accepted {new Date(acceptedAt).toLocaleString()}</small>}</div><label className="telemetry-choice"><input type="checkbox" checked={accepted} onChange={(event) => update(event.target.checked)} /><span><strong>Share privacy-preserving telemetry</strong><small>Random install ID, release version, active kiosk count, scrubbed error category, and best-effort city/metro only. Never organization, roster, attendance, fingerprint, or raw IP.</small></span></label></section>;
}
