import {FileUpload} from './file-upload';
import {useEffect,useRef,useState} from 'react';
import {AdaptiveBrandLogo} from './adaptive-brand-logo';
import {brandTheme} from './theme';
import {publicApi,PublicFailure,documentationContext,documentationActivities,documentationAck,type PublicActivity} from './public-documentation-contract';
export function PublicDocumentationForm(){
 const [config,setConfig]=useState<number|null>(),[rows,setRows]=useState<PublicActivity[]>([]),[next,setNext]=useState<string|null>(null),[selected,setSelected]=useState<PublicActivity>(),[member,setMember]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[locked,setLocked]=useState(false),[frozen,setFrozen]=useState(false),[ack,setAck]=useState(''),[ackLabel,setAckLabel]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState(false),[waitUntil,setWaitUntil]=useState(0),[tick,setTick]=useState(Date.now());
 const [branding,setBranding]=useState({name:'LancerLogin',primary:'#7c3aed',secondary:'#0f766e',logo:''}),[theme,setTheme]=useState<'light'|'dark'>('light');
 const generation=useRef(0),gate=useRef(false),pending=useRef<{json:string;label:string}|undefined>(undefined),noticeRef=useRef<HTMLParagraphElement>(null);
 const waiting=Math.max(0,Math.ceil((waitUntil-tick)/1000)),disabled=busy||waiting>0,invalid=!member.trim()||member.length>128||!selected||!note.trim()||note.length>8000||/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(note);
 useEffect(()=>{if(notice)noticeRef.current?.focus();},[notice]);
 useEffect(()=>{if(!waitUntil)return;const timer=setInterval(()=>setTick(Date.now()),1000);return()=>clearInterval(timer);},[waitUntil]);
 function failure(e:unknown){setError(true);if(e instanceof PublicFailure&&e.status===429){setTick(Date.now());setWaitUntil(Date.now()+e.retryAfter*1000);setNotice('Too many requests. Wait before an explicit reload or retry; nothing is sent automatically.');}else setNotice('The result could not be confirmed. Check current availability and your details. An uncertain submission may already exist. No request is retried automatically.');}
 async function load(after='',initial=false){if(gate.current||pending.current||waiting)return;gate.current=true;setBusy(true);const token=generation.current;try{const current=documentationContext(await publicApi('/public/documentation/context'));if(token!==generation.current)return;if(current===null){setConfig(null);setRows([]);setSelected(undefined);setLocked(true);return;}const page=documentationActivities(await publicApi('/public/documentation/activities?limit=25'+(after?'&after='+encodeURIComponent(after):'')),current);if(token!==generation.current)return;setConfig(current);setRows(page.activities);setNext(page.next);setSelected(undefined);setLocked(false);if(!initial){setNotice('Current activities reloaded. Choose an activity; your unsent note is preserved.');setError(false);}}catch(e){if(token===generation.current){setLocked(true);failure(e);}}finally{if(token===generation.current){gate.current=false;setBusy(false);}}}
 useEffect(()=>{gate.current=false;void load('',true);const token=generation.current;void publicApi('/setup/status').then(v=>{if(token!==generation.current)return;const b=v?.settings;if(typeof b?.organizationName==='string'&&/^#[0-9a-f]{6}$/i.test(b.primaryColor)&&/^#[0-9a-f]{6}$/i.test(b.secondaryColor)){setBranding({name:b.organizationName,primary:b.primaryColor,secondary:b.secondaryColor,logo:typeof b.logoData==='string'&&/^data:image\/(png|jpeg|webp);base64,/.test(b.logoData)&&b.logoData.length<400000?b.logoData:''});if(b.appearance==='light'||b.appearance==='dark')setTheme(b.appearance);}}).catch(()=>undefined);return()=>{generation.current++;};},[]);
 async function submit(retry=false){if(gate.current||disabled||!retry&&(invalid||locked||config===null||config===undefined||pending.current))return;if(!retry){const json=JSON.stringify({memberId:member,activityId:selected!.id,activityRevision:selected!.revision,sectionRevision:config,text:note,idempotencyKey:crypto.randomUUID()});if(new TextEncoder().encode(json).byteLength>40000){setError(true);setNotice('This note exceeds the submission size limit. Edit the text before sending; nothing was submitted.');return;}pending.current={json,label:selected!.title+' · '+selected!.serviceDate};setFrozen(true);}const input=pending.current;if(!input)return;gate.current=true;setBusy(true);const token=generation.current;try{if(new TextEncoder().encode(input.json).byteLength>40000)throw Error('Body limit');const reference=documentationAck(await publicApi('/public/documentation/notes',input.json));if(token!==generation.current)return;setAck(reference);setAckLabel(input.label);pending.current=undefined;setFrozen(false);setNote('');setMember('');setNotice('Note received. Staff review is separate; no hours were changed.');setError(false);}catch(e){if(token===generation.current)failure(e);}finally{if(token===generation.current){gate.current=false;setBusy(false);}}}
 return <div className="app public-hour-app" data-theme={theme} style={brandTheme(branding.primary,branding.secondary)}><a className="skip-link" href="#public-documentation-main">Skip to documentation forms</a><div className="public-hour-shell"><header className="setup-header"><div className="brand-home-link">{branding.logo?<AdaptiveBrandLogo src={branding.logo} alt="" className="header-logo"/>:<div className="brand-mark" aria-hidden="true">L</div>}<span className="brand-heading"><strong>{branding.name}</strong><span>Member documentation</span></span></div><button className="theme-toggle" type="button" role="switch" aria-checked={theme==='dark'} onClick={()=>setTheme(theme==='dark'?'light':'dark')}>Dark mode</button></header><main id="public-documentation-main" className="hours-workspace"><h1>Submit activity documentation</h1><p>No sign-in is needed. Enter your member ID and choose an eligible activity. A matching ID does not verify who submitted the note. This form cannot browse notes or member history.</p><p>Notes are independent of hours and are not restricted to the hours reporting window. Use the separate file form below for original evidence.</p><a href="/submit-hours" target="_blank" rel="noopener noreferrer">Submit hours separately (opens a new tab)</a><p className="ui-status settings-notice" data-tone="warning">Keep this page open until the result is confirmed. Closing or reloading this page loses the ability to check the original result of an unconfirmed submission.</p>
 {notice&&<p ref={noticeRef} tabIndex={-1} role={error?'alert':'status'} className="ui-status settings-notice" data-tone={error?'warning':'success'}>{notice}</p>}{busy&&<p role="status">Loading or submitting…</p>}{waiting>0&&<p role="status">Wait {waiting} seconds. Retry remains manual.</p>}
 {ack?<section className="ui-card hours-stack"><h2>Note received</h2><p>{ackLabel}</p><p>Acknowledgement: <span className="documentation-text">{ack}</span></p><p>This confirms receipt, not staff review or publication. It does not change the outcome of any hour submission.</p><button disabled={disabled} onClick={()=>{setAck('');setNotice('');void load();}}>Start a separate note</button></section>:<>
 {frozen&&<section className="ui-card hours-stack"><h2>Unconfirmed submission</h2><p>Retrying checks the result of this same submission, even if activity availability has changed. The note may already be saved. Discarding loses the ability to recover its original acknowledgement; ask staff before sending it again.</p><div className="hours-actions"><button disabled={disabled} onClick={()=>void submit(true)}>Retry this submission</button><button disabled={disabled} onClick={()=>{pending.current=undefined;setFrozen(false);setLocked(true);setNotice('Unconfirmed submission discarded. It may already exist; ask staff before submitting the same note again. Reload current activities before a new submission.');setError(true);}}>Discard unconfirmed submission</button></div></section>}
 {config===null?<section className="ui-card"><h2>Note submission unavailable</h2><p>Ask staff about current availability. Existing hours are unaffected.</p></section>:<form className="ui-card hours-stack" onSubmit={e=>{e.preventDefault();void submit();}}><label>Member ID<input required maxLength={128} autoComplete="off" spellCheck={false} disabled={disabled||frozen} value={member} onChange={e=>setMember(e.target.value)}/></label><label htmlFor="public-note-activity">Activity</label><select id="public-note-activity" className="ui-native-select" required value={selected?.id??''} disabled={disabled||locked||frozen} onChange={e=>setSelected(rows.find(a=>a.id===e.target.value))}><option value="">Choose an activity</option>{rows.map(a=><option key={a.id} value={a.id}>{a.title} · {a.serviceDate}</option>)}</select>{!busy&&!rows.length&&<p>No eligible activities on this page. Ask staff if your activity is missing.</p>}<div className="hours-actions"><button type="button" disabled={disabled||frozen} onClick={()=>void load()}>Reload first activity page</button>{next&&<button type="button" disabled={disabled||locked||frozen} onClick={()=>void load(next)}>Next activity page</button>}</div><label htmlFor="public-note-text">Activity note</label><textarea id="public-note-text" required maxLength={8000} value={note} disabled={disabled||frozen} aria-describedby="public-note-help" aria-invalid={!!note&&(!note.trim()||/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(note))} onChange={e=>setNote(e.target.value)}/><p id="public-note-help">Plain text. {note.length}/8000 characters; some symbols count as two. Do not include passwords or another member's private details.</p><button className="primary-button" disabled={disabled||frozen||locked||invalid||config===undefined}>Send note</button></form>}
 {config===null&&<button disabled={disabled||frozen} onClick={()=>void load()}>Reload current availability</button>}</>}
 <FileUpload publicMode/>
 </main></div></div>;
}
