import { useEffect, useId, useRef, useState } from 'react';
import { choiceValue, publicApi, text, type Choice } from './public-hour-contract';

export function PublicChoice({kind,label,query='',value,onChange,disabled,onFailure}:{kind:'categories'|'teams'|'events';label:string;query?:string;value?:Choice;onChange:(v?:Choice)=>void;disabled:boolean;onFailure:(e:unknown)=>void}){
 const id=useId(),seq=useRef(0),[rows,setRows]=useState<Choice[]>([]),[next,setNext]=useState<string|null>(null),[cursor,setCursor]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(false);
 async function load(after=''){const token=++seq.current;setBusy(true);setError(false);try{const q=new URLSearchParams(query);q.set('limit','50');if(after)q.set('after',after);const v=await publicApi('/public/hours/'+kind+'?'+q);if(!v||!Array.isArray(v.items)||v.items.length>50||!(v.nextCursor===null||text(v.nextCursor)))throw Error('Invalid page');const items=v.items.map((item:unknown)=>choiceValue(item,kind));if(new Set(items.map((item:Choice)=>item.id)).size!==items.length)throw Error('Duplicate choices');if(kind==='events'&&items.some((item:Choice)=>item.categoryId!==q.get('categoryId')||(q.has('date')&&item.serviceDate!==q.get('date'))))throw Error('Mismatched events');if(token!==seq.current)return;setRows(items);setNext(v.nextCursor);setCursor(after);}catch(e){if(token===seq.current){setError(true);onFailure(e);}}finally{if(token===seq.current)setBusy(false);}}
 useEffect(()=>{setRows([]);void load();return()=>{seq.current++;};},[kind,query]);
 return <fieldset className="hours-stack" disabled={disabled}><legend>{label}</legend>{busy&&<p role="status">Loading {label.toLowerCase()}…</p>}{error&&<p role="alert">Choices could not be loaded. Reload them before selecting.</p>}<label htmlFor={id}>{label}</label><select id={id} className="ui-native-select" value={value?.id??''} disabled={busy||error} onChange={e=>onChange(rows.find(v=>v.id===e.target.value))}><option value="">Choose {label.toLowerCase()}</option>{value&&!rows.some(v=>v.id===value.id)&&<option value={value.id}>{value.label} (selected)</option>}{rows.map(v=><option key={v.id} value={v.id}>{v.label}</option>)}</select>{!busy&&!error&&!rows.length&&<p>No eligible {label.toLowerCase()} on this page. Ask staff if the needed event or team is missing.</p>}<div className="hours-actions"><button type="button" disabled={busy} onClick={()=>void load()}>{cursor?'First':'Reload'} {label.toLowerCase()} page</button>{next&&<button type="button" disabled={busy||error} onClick={()=>void load(next)}>Next {label.toLowerCase()} page</button>}</div></fieldset>;
}
