import { useEffect, useRef, useState } from 'react';
import { addCalendarDays, elapsedIntegerMinutes, selectCivilTime, type CivilTimeOccurrence } from '@lancerlogin/shared/civil-time';
import { Clock } from './hours-clock';
import { PublicChoice } from './public-hour-choice';
import { contextValue, publicApi, PublicFailure, receiptValue, text, type Choice, type Context, type Receipt } from './public-hour-contract';
import { brandTheme } from './theme';
import { AdaptiveBrandLogo } from './adaptive-brand-logo';

type Body=Record<string,unknown>;
type Mode='entries'|'correction-requests';
function EntryFields({context,disabled,onSubmit,onFailure}:{context:Context;disabled:boolean;onSubmit:(v:Body,label:string)=>void;onFailure:(e:unknown)=>void}){
 const [member,setMember]=useState(''),[category,setCategory]=useState<Choice>(),[event,setEvent]=useState<Choice>(),[team,setTeam]=useState<Choice>(),[date,setDate]=useState(context.today),[eventDate,setEventDate]=useState(''),[appliedDate,setAppliedDate]=useState('');
 const [start,setStart]=useState(''),[end,setEnd]=useState(''),[nextDay,setNextDay]=useState(false),[first,setFirst]=useState<CivilTimeOccurrence>(),[last,setLast]=useState<CivilTimeOccurrence>(),[notes,setNotes]=useState('');
 const serviceDate=category?.mode==='event'?event?.serviceDate??'':date;let endDate=serviceDate,minutes:number|undefined,problem='';
 try{endDate=addCalendarDays(serviceDate,Number(nextDay));if(serviceDate>context.today||(category?.mode!=='event'&&serviceDate<context.earliestServiceDate))throw Error();const a=selectCivilTime({date:serviceDate,time:start,timeZone:context.timeZone},first),b=selectCivilTime({date:endDate,time:end,timeZone:context.timeZone},last);minutes=elapsedIntegerMinutes(a.epochMilliseconds,b.epochMilliseconds);if(b.epochMilliseconds>Date.now())throw Error();}catch{problem='Choose completed start and end times on an eligible service date. End must follow start by whole minutes; choose each repeated-clock occurrence.';}
 const invalid=!member.trim()||!category||(category.mode==='event'?!event:category.mode==='team'&&!team)||!!problem;
 return <form className="hours-stack" onSubmit={e=>{e.preventDefault();if(disabled||invalid)return;onSubmit({memberId:member.trim(),serviceDate,expectedTimeZone:context.timeZone,...(category!.mode==='event'?{activityId:event!.id}:{categoryId:category!.id,...(category!.mode==='team'?{teamId:team!.id}:{})}),startLocal:start,endLocal:end,endNextDay:nextDay,...(first?{startOccurrence:first}:{}),...(last?{endOccurrence:last}:{}),taskNotes:notes.trim()},[category!.label,category!.mode==='event'?event!.label:category!.mode==='team'?team!.label:''].filter(Boolean).join(' · '));}}>
  <label>Member ID<input required maxLength={128} autoComplete="off" spellCheck={false} value={member} disabled={disabled} onChange={e=>setMember(e.target.value)} aria-describedby="public-member-help"/></label><p id="public-member-help">Enter your full ID, including leading zeros. An entered ID is self-asserted; it does not sign you in or open member records.</p>
  <PublicChoice kind="categories" label="Service category" value={category} disabled={disabled} onFailure={onFailure} onChange={v=>{setCategory(v);setEvent(undefined);setTeam(undefined);setFirst(undefined);setLast(undefined);}}/>
  {category?.mode==='event'&&<section className="hours-stack"><label>Find events on date (optional)<input type="date" max={context.today} value={eventDate} disabled={disabled} onChange={e=>setEventDate(e.target.value)}/></label><button type="button" disabled={disabled} onClick={()=>{setAppliedDate(eventDate);setEvent(undefined);}}>Apply event date</button><PublicChoice key={category.id} kind="events" label="Dated event" query={new URLSearchParams({categoryId:category.id,...(appliedDate?{date:appliedDate}:{})}).toString()} value={event} disabled={disabled} onFailure={onFailure} onChange={v=>{setEvent(v);setFirst(undefined);setLast(undefined);}}/><p>Only currently eligible events are listed, including events staff have reopened. Each event day is a separate choice.</p>{event&&<p>Selected service date: <strong>{event.serviceDate}</strong></p>}</section>}
  {category?.mode==='team'&&<PublicChoice kind="teams" label="Supported team" value={team} disabled={disabled} onFailure={onFailure} onChange={setTeam}/>}
  {category&&category.mode!=='event'&&<label>Service date<input type="date" required min={context.earliestServiceDate} max={context.today} value={date} disabled={disabled} onChange={e=>{setDate(e.target.value);setFirst(undefined);setLast(undefined);}}/></label>}
  <p>Clock zone: <strong>{context.timeZone}</strong>. Normal reporting dates: {context.earliestServiceDate} through {context.today}. Reopened event exceptions do not extend team or task dates.</p>
  <div className="hours-grid"><Clock label="Start time" date={serviceDate} time={start} zone={context.timeZone} occurrence={first} onTime={setStart} onOccurrence={setFirst} disabled={disabled}/><Clock label="End time" date={endDate} time={end} zone={context.timeZone} occurrence={last} onTime={setEnd} onOccurrence={setLast} disabled={disabled}/></div>
  <label className="hours-check"><input type="checkbox" checked={nextDay} disabled={disabled} onChange={e=>{setNextDay(e.target.checked);setLast(undefined);}}/>End on the next calendar day</label><p id="public-clock-help" role="status">{problem||`Calculated duration: ${minutes} minutes (${(minutes!/60).toFixed(2)} hours). No break deduction or total override.`}</p>
  <label>Task notes (optional)<textarea maxLength={4000} value={notes} disabled={disabled} onChange={e=>setNotes(e.target.value)}/></label><button className="primary-button" disabled={disabled||invalid} aria-describedby="public-clock-help">Submit completed hours</button>
 </form>;
}
function CorrectionFields({disabled,onSubmit,receipt}:{disabled:boolean;onSubmit:(v:Body)=>void;receipt?:Receipt}){
 const [member,setMember]=useState(''),[reference,setReference]=useState(receipt?.id??''),[activity,setActivity]=useState(receipt?.activity_id??''),[date,setDate]=useState(receipt?.service_date??''),[message,setMessage]=useState('');let validDate=true;try{if(date)addCalendarDays(date,0);}catch{validDate=false;}
 return <form className="hours-stack" onSubmit={e=>{e.preventDefault();if(disabled||!member.trim()||!message.trim()||!validDate)return;onSubmit({memberId:member.trim(),message:message.trim(),...(reference.trim()?{receiptId:reference.trim()}:{}),...(activity.trim()?{activityId:activity.trim()}:{}),...(date?{serviceDate:date}:{})});}}><p>A correction request asks staff to review your claim. It does not directly change hours or provide access to records.</p><label>Member ID<input required maxLength={128} autoComplete="off" spellCheck={false} value={member} disabled={disabled} onChange={e=>setMember(e.target.value)}/></label><label>What should staff review?<textarea required maxLength={4000} value={message} disabled={disabled} onChange={e=>setMessage(e.target.value)} aria-describedby="correction-help"/></label><p id="correction-help">Describe the activity, date and intended correction. Do not include passwords or other members’ private information.</p><details><summary>Optional references</summary><div className="hours-stack"><label>Receipt reference<input maxLength={128} autoComplete="off" value={reference} disabled={disabled} onChange={e=>setReference(e.target.value)}/></label><label>Activity reference<input maxLength={128} autoComplete="off" value={activity} disabled={disabled} onChange={e=>setActivity(e.target.value)}/></label><label>Service date<input type="date" value={date} disabled={disabled} onChange={e=>setDate(e.target.value)}/></label></div></details><button className="primary-button" disabled={disabled||!member.trim()||!message.trim()||!validDate}>Send correction request</button></form>;
}
export function PublicHourForm(){
 const [context,setContext]=useState<Context>(),[loaded,setLoaded]=useState(false),[working,setWorking]=useState(false),[mode,setMode]=useState<Mode>('entries'),[version,setVersion]=useState(0),[notice,setNotice]=useState(''),[error,setError]=useState(false),[waitUntil,setWaitUntil]=useState(0),[tick,setTick]=useState(Date.now()),[receipt,setReceipt]=useState<Receipt>(),[receiptLabel,setReceiptLabel]=useState(''),[ack,setAck]=useState(''),[frozen,setFrozen]=useState(false);
 const [branding,setBranding]=useState<{name:string;primary:string;secondary:string;logo?:string}>({name:'LancerLogin',primary:'#7c3aed',secondary:'#0f766e'}),[theme,setTheme]=useState<'light'|'dark'>('light');
 const pending=useRef<{mode:Mode;json:string;label?:string}|undefined>(undefined),gate=useRef(false),alive=useRef(true),noticeRef=useRef<HTMLParagraphElement>(null),heading=useRef<HTMLHeadingElement>(null);const waiting=Math.max(0,Math.ceil((waitUntil-tick)/1000)),disabled=working||waiting>0;
 useEffect(()=>{if(notice)noticeRef.current?.focus();},[notice]);useEffect(()=>{if(waitUntil<=Date.now())return;const timer=setInterval(()=>{const now=Date.now();setTick(now);if(now>=waitUntil)clearInterval(timer);},1000);return()=>clearInterval(timer);},[waitUntil]);
 function fail(e:unknown){if(!alive.current)return;setError(true);if(e instanceof PublicFailure&&e.status===429){setTick(Date.now());setWaitUntil(Date.now()+e.retryAfter*1000);setNotice('Too many requests. Wait before choosing an explicit reload or retry. Nothing will be submitted automatically.');}else setNotice('The result could not be confirmed. Check your details, service date, clocks and current availability. Overlap or identity failures do not reveal another entry. You can request a correction. No submission is retried automatically.');}
 async function reload(){if(gate.current||pending.current||waiting)return;gate.current=true;setWorking(true);setNotice('');try{const current=contextValue(await publicApi('/public/hours/context'));if(!alive.current)return;setContext(current);setLoaded(true);setVersion(v=>v+1);setError(false);}catch(e){setLoaded(false);fail(e);}finally{gate.current=false;if(alive.current)setWorking(false);}}
 useEffect(()=>{alive.current=true;void reload();void publicApi('/setup/status').then(v=>{if(!alive.current)return;const b=v?.settings;if(b&&text(b.organizationName,100)&&/^#[0-9a-f]{6}$/i.test(b.primaryColor)&&/^#[0-9a-f]{6}$/i.test(b.secondaryColor)){setBranding({name:b.organizationName,primary:b.primaryColor,secondary:b.secondaryColor,...(typeof b.logoData==='string'&&/^data:image\/(png|jpeg|webp);base64,/.test(b.logoData)&&b.logoData.length<400000?{logo:b.logoData}:{})});if(b.appearance==='dark'||b.appearance==='light')setTheme(b.appearance);}}).catch(()=>undefined);return()=>{alive.current=false;};},[]);
 async function submit(body?:Body,label?:string){if(gate.current||disabled)return;if(body){if(pending.current)return;pending.current={mode,label,json:JSON.stringify({...body,idempotencyKey:crypto.randomUUID()})};setFrozen(true);}const draft=pending.current;if(!draft)return;gate.current=true;setWorking(true);setNotice('');try{if(new TextEncoder().encode(draft.json).byteLength>16384)throw Error('Body too large');const result=await publicApi('/public/hours/'+draft.mode,draft.json);if(draft.mode==='entries'){const original=receiptValue(result,JSON.parse(draft.json));if(!alive.current)return;setReceipt(original);setReceiptLabel(draft.label??'Submitted service');setAck('');}else{if(result?.accepted!==true||!text(result.reference)||Object.keys(result).sort().join(',')!=='accepted,reference')throw Error('Invalid acknowledgement');if(!alive.current)return;setAck(result.reference);}pending.current=undefined;setFrozen(false);setError(false);setNotice(draft.mode==='entries'?'Hours accepted. Your original submission receipt is shown below.':'Correction request received for staff review. Hours were not changed by this request.');}catch(e){fail(e);}finally{gate.current=false;if(alive.current)setWorking(false);}}
 function changeMode(next:Mode){setMode(next);setAck('');setVersion(v=>v+1);setNotice('');requestAnimationFrame(()=>heading.current?.focus());}
 function newEntry(){setReceipt(undefined);setAck('');setMode('entries');void reload();}
 const complete=mode==='entries'?!!receipt:!!ack;
 return <div className="app public-hour-app" data-theme={theme} style={brandTheme(branding.primary,branding.secondary)}><a className="skip-link" href="#public-hours-main">Skip to hour form</a><div className="public-hour-shell"><header className="setup-header"><div className="brand-home-link">{branding.logo?<AdaptiveBrandLogo src={branding.logo} alt="" className="header-logo"/>:<div className="brand-mark" aria-hidden="true">L</div>}<span className="brand-heading"><strong>{branding.name}</strong><span>Member hours</span></span></div><button className="theme-toggle" type="button" role="switch" aria-checked={theme==='dark'} onClick={()=>setTheme(theme==='dark'?'light':'dark')}>Dark mode</button></header><main id="public-hours-main" className="hours-workspace"><h1 ref={heading} tabIndex={-1}>{mode==='entries'?'Submit hours':'Request a correction'}</h1><p>No sign-in is needed. Normal accepted hours count immediately. This form does not browse member history or edit existing hours, even if you are signed in elsewhere.</p><p className="ui-status settings-notice" data-tone="warning">Keep this page open until the result is confirmed. Drafts, retry keys and receipts stay only in this page’s memory. Reloading or closing it loses recovery of an uncertain submission; request a correction rather than unknowingly submitting twice.</p>
 <nav className="hours-actions" aria-label="Public hour actions"><button aria-pressed={mode==='entries'} disabled={disabled||frozen} onClick={()=>changeMode('entries')}>Submit hours</button><button aria-pressed={mode==='correction-requests'} disabled={disabled||frozen} onClick={()=>changeMode('correction-requests')}>Request a correction</button>{!frozen&&!complete&&<button disabled={disabled} onClick={()=>void reload()}>Reload form context and clear draft</button>}</nav>
 {working&&<p role="status">Loading or submitting…</p>}{notice&&<p ref={noticeRef} tabIndex={-1} role={error?'alert':'status'} className="ui-status settings-notice" data-tone={error?'error':'success'}>{notice}</p>}{waiting>0&&<p role="status">Wait {waiting} seconds. Reload and retry remain manual.</p>}
 {frozen&&<section className="ui-card hours-stack"><h2>Frozen submission</h2><p>The exact submitted details and retry key are retained. A retry can recover the original result; it cannot create a second entry with this same payload and key.</p><div className="hours-actions"><button disabled={disabled} onClick={()=>void submit()}>Retry exact submission</button><button disabled={disabled} onClick={()=>{pending.current=undefined;setFrozen(false);setVersion(v=>v+1);setNotice('Frozen draft discarded. Its submission may already exist. Request a correction if uncertain before recording again.');setError(true);}}>Discard frozen draft</button></div></section>}
 {complete?<section className="ui-card hours-stack"><h2>{mode==='entries'?'Original submission receipt':'Correction acknowledgement'}</h2>{mode==='entries'&&receipt?<><p><strong>{receiptLabel}</strong></p><p>Accepted {receipt.duration_minutes} minutes ({(receipt.duration_minutes/60).toFixed(2)} hours).</p><p>{receipt.service_date} · {receipt.start_local}–{receipt.end_local}{receipt.end_next_day?' (next day)':''} · {receipt.time_zone}</p>{(receipt.start_occurrence||receipt.end_occurrence)&&<p>Recorded occurrence: start {receipt.start_occurrence??'ordinary'}; end {receipt.end_occurrence??'ordinary'}.</p>}{receipt.task_notes&&<p className="entry-notes">Submitted notes: {receipt.task_notes}</p>}<p>Receipt reference: <span className="entry-notes">{receipt.id}</span></p><p>Activity reference: <span className="entry-notes">{receipt.activity_id}</span></p><p>This is the original accepted submission, not a current history view. Staff may later correct or void it.</p></>:<p>Request reference: <span className="entry-notes">{ack}</span>. Receipt of this request does not approve its claims.</p>}<button disabled={disabled} onClick={newEntry}>Start a separate hour entry</button></section>:loaded&&!context?<section className="ui-card"><h2>Hour submission unavailable</h2><p>Ask staff about availability. No submission was sent.</p></section>:context?<section className="ui-card hours-stack">{mode==='entries'?<EntryFields key={version} context={context} disabled={disabled||frozen} onSubmit={(v,label)=>void submit(v,label)} onFailure={fail}/>:<CorrectionFields key={version} disabled={disabled||frozen} onSubmit={v=>void submit(v)} receipt={receipt}/>}</section>:!working&&<p>Reload the form context to check availability.</p>}
 </main></div></div>;
}
