import { useEffect, useMemo, useState } from "react";
import { api, apiBaseUrl } from "./dashboard-api";
import { RouteLink, usePath } from "./router";
import { useDashboardLoadingOverlay } from "./loading-overlay";
import { loadReportAttendance, percent, reportQuery, type AttendanceReport, type ReportFilters } from "./report-attendance";

type Contest = { meetingId: string; memberId: string; firstName: string; lastName: string; meetingTitle: string; status: "open" | "approved" | "rejected" | "reviewed"; createdAt: string };
type SavedView = { range: string; from: string; to: string; meetingType: "all" | "required" | "optional"; roster: "active" | "all"; labelId: string; membership: "current" | "historical"; useBaseline: boolean };
const savedViewKey = "lancerlogin-reports-view";

export function ReportsPage({ discordEnabled }: { discordEnabled: boolean }) {
  const { path, navigate } = usePath();
  const [report, setReport] = useState<AttendanceReport>(); const [contests, setContests] = useState<Contest[]>([]); const [notice, setNotice] = useState("Loading reports…");
  const [sort, setSort] = useState<"rate" | "first" | "last">("rate"); const [range, setRange] = useState("10"); const [from, setFrom] = useState(""); const [to, setTo] = useState("");
  const [meetingType, setMeetingType] = useState<"all" | "required" | "optional">("all"); const [roster, setRoster] = useState<"active" | "all">("active");
  const [labelId, setLabelId] = useState(""); const [membership, setMembership] = useState<"current" | "historical">("current"); const [baseline, setBaseline] = useState(""); const [useBaseline, setUseBaseline] = useState(false);
  const [reviewing, setReviewing] = useState<Contest>(); const [reviewNote, setReviewNote] = useState(""); const [reviewError, setReviewError] = useState(""); const [reviewBusy, setReviewBusy] = useState(false);
  useDashboardLoadingOverlay(notice === "Loading reports…", "Loading reports…");

  const filters: ReportFilters = useMemo(() => ({ from: useBaseline ? baseline : from || undefined, to: to || undefined, meetingType, roster, labelId: labelId || undefined, membership }), [useBaseline, baseline, from, to, meetingType, roster, labelId, membership]);
  useEffect(() => { let active = true; void Promise.all([loadReportAttendance(api, filters), discordEnabled ? api<{ contests: Contest[] }>("/discord/contests") : Promise.resolve({ contests: [] as Contest[] })]).then(([result, review]) => { if (!active) return; setReport(result); setContests(review.contests.filter((item) => item.status === "open")); if (!baseline && result.baseline) { setBaseline(result.baseline); setUseBaseline(true); } setNotice(""); }).catch((error: Error) => { if (active) setNotice(error.message); }); return () => { active = false; }; }, [filters, discordEnabled]);

  const members = useMemo(() => [...(report?.members ?? [])].sort((a, b) => sort === "first" ? a.member.firstName.localeCompare(b.member.firstName) || a.member.lastName.localeCompare(b.member.lastName) : sort === "last" ? a.member.lastName.localeCompare(b.member.lastName) || a.member.firstName.localeCompare(b.member.firstName) : (b.currentCompliance?.rate ?? b.adjustedRate ?? -1) - (a.currentCompliance?.rate ?? a.adjustedRate ?? -1) || a.member.lastName.localeCompare(b.member.lastName)), [report, sort]);
  const meetings = report?.meetings ?? [];
  const points = meetings.slice(-Number(range)).map((meeting) => { const rows = members.flatMap((member) => member.rows.filter((row) => row.meetingId === meeting.id && row.rateEligible)); const present = rows.reduce((sum, row) => sum + (row.attended ? row.weight : 0), 0); const eligible = rows.reduce((sum, row) => sum + row.weight, 0); return { meeting, rate: percent(present, eligible) }; });
  const trendSummary = points.map((point) => `${point.meeting.title} ${point.rate}%`).join("; ");
  const scope = `${meetings.length} completed meeting${meetings.length === 1 ? "" : "s"}${useBaseline && baseline ? ` from ${baseline}` : filters.from || filters.to ? ` from ${filters.from ?? "the beginning"} through ${filters.to ?? "today"}` : " across all preserved history"}`;

  async function downloadCsv() { const query = reportQuery(filters); const result = await fetch(`${apiBaseUrl}/exports/attendance.csv${query ? `?${query}` : ""}`, { credentials: "include" }); if (!result.ok) { setNotice("Attendance CSV export failed."); return; } const blob = await result.blob(); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `lancerlogin-attendance-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(url); setNotice("Attendance CSV downloaded."); }
  function saveView() { const view: SavedView = { range, from, to, meetingType, roster, labelId, membership, useBaseline }; localStorage.setItem(savedViewKey, JSON.stringify(view)); setNotice("Current report filters saved in this browser."); }
  function useSavedView() { try { const view = JSON.parse(localStorage.getItem(savedViewKey) ?? "") as SavedView; setRange(view.range); setFrom(view.from); setTo(view.to); setMeetingType(view.meetingType); setRoster(view.roster); setLabelId(view.labelId); setMembership(view.membership); setUseBaseline(view.useBaseline); setNotice("Saved report filters applied."); } catch { setNotice("No saved report view is available in this browser."); } }
  async function resolveContest(resolution: "approved" | "rejected" | "reviewed") { if (!reviewing) return; const note = reviewNote.trim(); if (!note) { setReviewError("A review reason is required."); return; } setReviewBusy(true); try { await api("/discord/contests/resolve", { method: "POST", body: JSON.stringify({ meetingId: reviewing.meetingId, memberId: reviewing.memberId, resolution, reviewNote: note }) }); setReviewing(undefined); setReviewNote(""); setContests((current) => current.filter((item) => item !== reviewing)); setNotice(`Contest ${resolution}.`); } catch (error) { setReviewError((error as Error).message); } finally { setReviewBusy(false); } }

  return <section className="page-stack reports-page" aria-labelledby="reports-title">
    <div className="page-intro"><h1 id="reports-title">Reports</h1><p>Review attendance under each member's policy, then export the visible records.</p></div>
    {notice && <p className="setup-status" role="status">{notice}</p>}
    <section className="task-card report-filters ui-card" aria-labelledby="report-filters-title"><div className="report-filter-heading"><div><h2 id="report-filters-title">Report filters</h2><p>Choose meetings, roster records, and a label group.</p></div><span className="ui-status" data-tone="neutral">{meetings.length} meetings</span></div>
      <div className="report-filter-controls"><label>Reporting period<select value={useBaseline ? "baseline" : "all"} onChange={(event) => setUseBaseline(event.target.value === "baseline")}><option value="baseline" disabled={!baseline}>Operational baseline{baseline ? ` (${baseline})` : " unavailable"}</option><option value="all">All preserved history</option></select></label><label>From<input type="date" value={from} disabled={useBaseline} onChange={(event) => setFrom(event.target.value)} /></label><label>To<input type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label><label>Meeting type<select value={meetingType} onChange={(event) => setMeetingType(event.target.value as typeof meetingType)}><option value="all">All meetings</option><option value="required">Required meetings</option><option value="optional">Optional meetings</option></select></label><label>Roster<select value={roster} onChange={(event) => setRoster(event.target.value as typeof roster)}><option value="active">Active roster</option><option value="all">All roster history</option></select></label><label>Label group<select value={labelId} onChange={(event) => setLabelId(event.target.value)}><option value="">All labels</option>{report?.labels.map((label) => <option key={label.id} value={label.id}>{label.name}{label.active ? "" : " (retired)"}</option>)}</select></label><label>Group view<select value={membership} disabled={!labelId} onChange={(event) => setMembership(event.target.value as typeof membership)}><option value="current">Current members</option><option value="historical">Historical membership</option></select></label></div>
      <p className="report-scope">Showing {scope}. Historical membership includes a member only for meetings dated while they held the selected label.</p>
    </section>
    <section className="report-grid"><article className="task-card leaderboard-card ui-card"><div className="panel-heading"><div><h2>Attendance leaderboard</h2><p>Current compliance uses the active rule. Historical percentage and weekly summaries stay separate. Optional meetings do not enter weighted rates.</p></div><label>Sort<select value={sort} onChange={(event) => setSort(event.target.value as typeof sort)}><option value="rate">Attendance rate</option><option value="first">First name</option><option value="last">Last name</option></select></label></div><div className="report-table" role="table" aria-label="Attendance leaderboard"><div className="report-row header" role="row"><span role="columnheader">Member</span><span role="columnheader">Current compliance</span><span role="columnheader">Current label history</span></div>{members.map((item) => <RouteLink className="report-row" role="row" key={item.member.id} href={`/roster/${encodeURIComponent(item.member.memberId)}`} currentPath={path} navigate={navigate}><span role="cell"><strong>{item.member.firstName} {item.member.lastName}</strong><small>{item.member.memberId} · {item.policy} policy{item.belowTargetWeeks.length ? ` · ${item.belowTargetWeeks.length} below-target week${item.belowTargetWeeks.length === 1 ? "" : "s"}` : ""}</small></span><span role="cell">{item.currentCompliance && item.currentCompliance.status!=="no_rule" ? `${item.currentCompliance.status.replace("_", " ")}${item.currentCompliance.rate===null?"":` · ${item.currentCompliance.rate}%`}` : item.adjustedRate===null?"No target":`${item.adjustedRate}%`}</span><span role="cell">{item.historySummaries?.length ? item.historySummaries.map((summary) => summary.ruleType === "weekly_count" ? `${summary.weeksMet}/${summary.weeksDue} weeks` : summary.rate === null ? "No eligible meetings" : `${summary.rate}% weighted`).join("; ") : "No policy history"}</span></RouteLink>)}{!members.length && <p className="empty-state">No attendance records match these filters.</p>}</div></article>
      <article className="task-card trend-card ui-card"><div className="panel-heading"><div><h2>Team attendance trend</h2><p>Attendance at each completed meeting among rate eligible members.</p></div><label>Meetings<select value={range} onChange={(event) => setRange(event.target.value)}><option value="5">Last 5</option><option value="10">Last 10</option><option value="20">Last 20</option></select></label></div>{points.length ? <><div className="trend-chart" role="img" aria-label={`Team attendance trend: ${trendSummary}`}>{points.map((point) => <div key={point.meeting.id} title={`${point.meeting.title}: ${point.rate}%`}><span style={{ height: `${point.rate}%` }} /><small>{new Date(point.meeting.startsAt).toLocaleDateString(undefined, { month: "short", day: "numeric" })}</small></div>)}</div><ul className="visually-hidden">{points.map((point) => <li key={point.meeting.id}>{point.meeting.title}: {point.rate}% attendance</li>)}</ul></> : <p className="empty-state">No completed meetings match these filters.</p>}</article>
      <article className="task-card contest-report"><div className="panel-heading"><h2>Contests awaiting review</h2><span className="progress-count">{contests.length} open</span></div>{contests.length ? <div className="contest-list">{contests.map((contest) => <article key={`${contest.meetingId}:${contest.memberId}`}><strong>{contest.firstName} {contest.lastName}</strong><span>{contest.meetingTitle}</span><small>Submitted {new Date(contest.createdAt).toLocaleString()}</small><button type="button" onClick={() => { setReviewing(contest); setReviewNote(""); setReviewError(""); }}>Review contest</button></article>)}</div> : <p className="empty-state">No attendance contests need review.</p>}</article>
    </section>
    {reviewing && <section className="task-card contest-review" aria-labelledby="contest-review-title"><div className="panel-heading"><div><h2 id="contest-review-title">Review contest</h2><p>{reviewing.firstName} {reviewing.lastName} · {reviewing.meetingTitle}</p></div><button type="button" onClick={() => setReviewing(undefined)} disabled={reviewBusy}>Close</button></div><label>Review reason<textarea value={reviewNote} maxLength={500} required aria-invalid={Boolean(reviewError)} aria-describedby={reviewError ? "contest-review-error" : undefined} onChange={(event) => { setReviewNote(event.target.value); setReviewError(""); }} /></label>{reviewError && <p id="contest-review-error" className="inline-messages error" role="alert">{reviewError}</p>}<div className="report-actions"><button type="button" disabled={reviewBusy} onClick={() => void resolveContest("reviewed")}>Keep attendance</button><button type="button" disabled={reviewBusy} onClick={() => void resolveContest("rejected")}>Reject contest</button><button className="primary-button" type="button" disabled={reviewBusy} onClick={() => void resolveContest("approved")}>Approve and mark present</button></div></section>}
    <section className="task-card report-action-card" aria-labelledby="report-actions-title"><div><h2 id="report-actions-title">Saved view and export</h2><p>The CSV uses the same dates, meeting type, roster, and label group shown above.</p></div><div className="report-actions"><button type="button" onClick={saveView}>Save this view</button><button type="button" onClick={useSavedView}>Use saved view</button><button className="primary-button" type="button" onClick={() => void downloadCsv()}>Download attendance CSV</button></div></section>
  </section>;
}
