import { FormEvent, useEffect, useState } from "react";
import { api } from "./dashboard-api";
import { UserSettings, type RosterMember } from "./user-settings";

export function RosterPage({ role }: { role: "admin" | "operator" }) {
  const [members, setMembers] = useState<RosterMember[]>([]); const [csv, setCsv] = useState("memberId,firstName,lastName,email\n"); const [notice, setNotice] = useState("Loading roster…"); const [formErrors, setFormErrors] = useState<string[]>([]);
  async function load() { const result = await api<{ members: RosterMember[] }>("/admin/members"); setMembers(result.members); setNotice(`${result.members.filter((member) => member.active).length} active roster member${result.members.filter((member) => member.active).length === 1 ? "" : "s"}.`); }
  useEffect(() => { void load().catch((error: Error) => setNotice(error.message)); }, []);
  async function importRoster(event: FormEvent) { event.preventDefault(); setFormErrors([]); const lines = csv.trim().split(/\r?\n/); const headers = lines.shift()?.split(",").map((value) => value.trim()) ?? []; const required = ["memberId", "firstName", "lastName"]; const errors: string[] = []; if (required.some((header) => !headers.includes(header))) errors.push("Header row requires memberId, firstName, and lastName."); const incoming = lines.filter(Boolean).map((line, index) => { const values = line.split(",").map((value) => value.trim()); const value = Object.fromEntries(headers.map((header, column) => [header, values[column] ?? ""])); if (!value.memberId || !value.firstName || !value.lastName) errors.push(`Row ${index + 2} is missing a required value.`); return value; }); if (!incoming.length) errors.push("Add at least one roster row."); if (errors.length) { setFormErrors(errors); window.requestAnimationFrame(() => document.getElementById("roster-import-errors")?.focus()); return; } try { const result = await api<{ imported: number; warnings?: string[] }>("/admin/members", { method: "POST", body: JSON.stringify({ members: incoming }) }); await load(); setNotice(`${result.imported} roster member${result.imported === 1 ? "" : "s"} imported.${result.warnings?.length ? ` ${result.warnings.join(" ")}` : ""}`); } catch (error) { setFormErrors([(error as Error).message]); window.requestAnimationFrame(() => document.getElementById("roster-import-errors")?.focus()); } }
  return <div className="page-stack"><section aria-labelledby="roster-title"><div className="page-intro"><p className="kicker">People</p><h2 id="roster-title">Roster</h2><p>Roster members are attendance identities. Dashboard access is optional and must be granted separately by an Admin.</p></div><p className="setup-status" role="status">{notice}</p>{role === "admin" && <form className="task-card roster-import" onSubmit={importRoster}><h3>Import or update roster</h3><label>Roster CSV<textarea rows={7} value={csv} onChange={(event) => setCsv(event.target.value)} aria-describedby={formErrors.length ? "roster-import-errors" : undefined} aria-invalid={formErrors.length > 0} /></label><p className="field-help">Required: memberId, firstName, lastName. Optional: email and discordUserId. Invalid optional Discord IDs are ignored.</p>{formErrors.length > 0 && <div id="roster-import-errors" className="inline-messages error" role="alert" tabIndex={-1}><strong>Please fix this roster import</strong><ul>{formErrors.map((error) => <li key={error}>{error}</li>)}</ul></div>}<button className="primary-button" type="submit">Validate and import</button></form>}<div className="roster-list" role="table" aria-label="Roster members"><div className="roster-row header" role="row"><span>Name</span><span>Member ID</span><span>Status</span></div>{members.map((member) => <div className="roster-row" role="row" key={member.id}><span><strong>{member.firstName} {member.lastName}</strong><small>{member.email || "No email"}</small></span><code>{member.memberId}</code><span>{member.active ? "Active" : "Inactive"}</span></div>)}</div></section>{role === "admin" && <UserSettings members={members} />}</div>;
}
