import { useEffect, useState } from "react";
import { kioskDisplayForAttendance, kioskState, type KioskDisplay } from "../../kiosk/src/kiosk-presentation.mjs";
import { api } from "./dashboard-api";

type Member = { id: string; memberId: string; firstName: string; lastName: string; active: boolean };
type Meeting = { id: string; title: string; startsAt: string };
type Simulator = { name: string; active: number; online: number };

// BrowserMemberInput is the emulator-specific input boundary. It has no kiosk
// credential, reader state, queue, or physical-kiosk status route.
function BrowserMemberInput({ members, meetings, memberId, meetingId, onMemberId, onMeetingId, onRead, disabled }: { members: Member[]; meetings: Meeting[]; memberId: string; meetingId: string; onMemberId: (value: string) => void; onMeetingId: (value: string) => void; onRead: () => void; disabled: boolean }) {
  return <section className="simulator-controls" aria-label="Browser input adapter"><label>Roster member<select value={memberId} onChange={(event) => onMemberId(event.target.value)}><option value="">Choose a member</option>{members.map((member) => <option key={member.id} value={member.id}>{member.firstName} {member.lastName} · {member.memberId}</option>)}</select></label><label>Meeting<select value={meetingId} onChange={(event) => onMeetingId(event.target.value)}><option value="">Choose a meeting</option>{meetings.map((meeting) => <option key={meeting.id} value={meeting.id}>{new Date(meeting.startsAt).toLocaleDateString()} · {meeting.title}</option>)}</select></label><button className="primary-button" type="button" onClick={onRead} disabled={disabled}>Simulate member read</button></section>;
}

export function SimulatorPage() {
  const [simulator, setSimulator] = useState<Simulator>(); const [members, setMembers] = useState<Member[]>([]); const [meetings, setMeetings] = useState<Meeting[]>([]); const [memberId, setMemberId] = useState(""); const [meetingId, setMeetingId] = useState(""); const [display, setDisplay] = useState<KioskDisplay>(() => kioskState("ready", { detail: "Choose a member and meeting to simulate a browser read." })); const [busy, setBusy] = useState(false);
  async function load() { const [sim, roster, schedule] = await Promise.all([api<{ simulator: Simulator | null }>("/admin/simulator"), api<{ members: Member[] }>("/admin/members"), api<{ meetings: Meeting[] }>("/meetings")]); if (!sim.simulator?.active) throw new Error("Pair the browser simulator from guided setup before opening it."); setSimulator(sim.simulator); setMembers(roster.members.filter((member) => member.active)); setMeetings(schedule.meetings); }
  useEffect(() => { void load().catch((error: Error) => setDisplay(kioskState("rejected", { detail: error.message }))); }, []);
  async function scan() { if (!memberId || !meetingId) { setDisplay(kioskState("rejected", { detail: "Choose both a roster member and meeting." })); return; } setBusy(true); setDisplay(kioskState("processing")); try { const result = await api<{ action: "check_in" | "check_out"; duplicate?: boolean }>("/admin/simulator", { method: "POST", body: JSON.stringify({ action: "scan", memberId, meetingId }) }); setDisplay(kioskDisplayForAttendance(result)); } catch (error) { setDisplay(kioskState("rejected", { detail: (error as Error).message })); } finally { setBusy(false); } }
  const selectedMember = members.find((member) => member.id === memberId);
  return <section className="simulator-page" aria-labelledby="simulator-title"><header><span>Browser kiosk emulator</span><strong>{simulator?.name ?? "Not paired"}</strong></header><div className={`simulator-kiosk kiosk-shell kiosk-shell-${display.id}`}><p className="simulator-origin">SIMULATED · BROWSER INPUT</p><main className={`scan-panel scan-panel-${display.id}`} aria-live="polite" aria-labelledby="simulator-title"><div className="reader-mark" aria-hidden="true" /><p className="simulator-kicker">{display.id === "ready" ? "Ready" : display.id === "processing" ? "Reading" : "Attendance"}</p><h1 id="simulator-title">{display.message}</h1>{selectedMember && <p className="simulator-member">{selectedMember.firstName} {selectedMember.lastName}</p>}<p>{display.detail}</p></main><footer className="debug-status"><span>Browser member adapter ready</span><span>Simulated activity is audited</span><span>Not a physical kiosk</span></footer></div><p className="simulator-boundary">This emulator uses the physical kiosk’s shared display-state contract. It cannot pair hardware, submit a kiosk heartbeat, affect the physical active-kiosk record, or access fingerprint templates.</p><BrowserMemberInput members={members} meetings={meetings} memberId={memberId} meetingId={meetingId} onMemberId={setMemberId} onMeetingId={setMeetingId} onRead={() => void scan()} disabled={busy || !simulator?.online} /></section>;
}
