import { useEffect, useState } from "react";
import { api } from "./dashboard-api";

type Member = { id: string; memberId: string; firstName: string; lastName: string; active: boolean };
type Meeting = { id: string; title: string; startsAt: string };
type Simulator = { name: string; active: number; online: number };
export function SimulatorPage() {
  const [simulator, setSimulator] = useState<Simulator>(); const [members, setMembers] = useState<Member[]>([]); const [meetings, setMeetings] = useState<Meeting[]>([]); const [memberId, setMemberId] = useState(""); const [meetingId, setMeetingId] = useState(""); const [message, setMessage] = useState("Choose a member and meeting to simulate a fingerprint read."); const [maintenance, setMaintenance] = useState(false); const [network, setNetwork] = useState(false);
  async function load() { const [sim, roster, schedule] = await Promise.all([api<{ simulator: Simulator | null }>("/admin/simulator"), api<{ members: Member[] }>("/admin/members"), api<{ meetings: Meeting[] }>("/meetings")]); if (!sim.simulator?.active) throw new Error("Pair the browser simulator from guided setup before opening it."); setSimulator(sim.simulator); setMembers(roster.members.filter((member) => member.active)); setMeetings(schedule.meetings); }
  useEffect(() => { void load().catch((error: Error) => setMessage(error.message)); }, []);
  async function scan() { if (!memberId || !meetingId) { setMessage("Choose both a roster member and meeting."); return; } try { const result = await api<{ action: "check_in" | "check_out" }>("/admin/simulator", { method: "POST", body: JSON.stringify({ action: "scan", memberId, meetingId }) }); setMessage(result.action === "check_in" ? "Welcome. Arrival scan recorded." : "Goodbye. Attendance is complete."); } catch (error) { setMessage((error as Error).message); } }
  return <section className="simulator-page" aria-labelledby="simulator-title"><header><span>Browser simulator</span><strong>{simulator?.name ?? "Not paired"}</strong></header><main className={message.startsWith("Welcome") || message.startsWith("Goodbye") ? "simulator-screen success" : "simulator-screen"}><p>SIMULATED KIOSK</p><div className="reader-mark" aria-hidden="true" /><h1 id="simulator-title">{message}</h1><small>Simulated actions are audited and never count as physical kiosk activity.</small></main><section className="simulator-controls"><label>Roster member<select value={memberId} onChange={(event) => setMemberId(event.target.value)}><option value="">Choose a member</option>{members.map((member) => <option key={member.id} value={member.id}>{member.firstName} {member.lastName} · {member.memberId}</option>)}</select></label><label>Meeting<select value={meetingId} onChange={(event) => setMeetingId(event.target.value)}><option value="">Choose a meeting</option>{meetings.map((meeting) => <option key={meeting.id} value={meeting.id}>{new Date(meeting.startsAt).toLocaleDateString()} · {meeting.title}</option>)}</select></label><button className="primary-button" type="button" onClick={() => void scan()}>Simulate fingerprint read</button><button type="button" onClick={() => setNetwork((value) => !value)}>Network settings</button><button type="button" onClick={() => setMaintenance((value) => !value)}>Fingerprint maintenance</button>{network && <p className="simulator-sheet">Browser simulation: online. Hardware Wi-Fi credentials and saved networks are never simulated or stored.</p>}{maintenance && <p className="simulator-sheet">Browser simulation: enrollment and mappings are represented by the selected roster event only. Fingerprint templates remain exclusive to the physical R503.</p>}</section></section>;
}
