import { useEffect, useState } from "react";
import { api, apiBaseUrl } from "./dashboard-api";
import { clearUpdateCheckCache, formatVersion, isNewerRelease } from "./update-indicator";

type Release = { tag_name?: string; name?: string; html_url?: string; body?: string };
type Kiosk = { id: string; name: string; active: number; lastSeenAt?: string; releaseVersion?: string };
export function UpdatesPage() {
  const [current, setCurrent] = useState("Loading…"); const [workflowUrl, setWorkflowUrl] = useState(""); const [latest, setLatest] = useState<Release>(); const [kiosk, setKiosk] = useState<Kiosk>(); const [notice, setNotice] = useState("Checking the community release feed…"); const [busy, setBusy] = useState(false); const [kioskBusy, setKioskBusy] = useState(false);
  useEffect(() => { clearUpdateCheckCache(); Promise.all([api<{ releaseVersion: string; workflowUrl: string }>("/admin/update-info"), api<{ kiosks: Kiosk[] }>("/admin/kiosks"), fetch("https://api.github.com/repos/isriah/LancerLogin/releases/latest", { headers: { accept: "application/vnd.github+json" } }).then((result) => result.ok ? result.json() as Promise<Release> : Promise.reject(new Error("Latest release is temporarily unavailable")))]).then(([installation, kiosks, release]) => { setCurrent(formatVersion(installation.releaseVersion)); setWorkflowUrl(installation.workflowUrl); setKiosk(kiosks.kiosks.find((item) => item.active === 1)); setLatest(release); setNotice(isNewerRelease(release.tag_name ?? "", installation.releaseVersion) ? "A newer community release is available. Review its notes before upgrading." : "This installation is current."); }).catch((error: Error) => setNotice(error.message)); }, []);
  async function begin() { if (!workflowUrl) { setNotice("The private deployment workflow is unavailable."); return; } const github = window.open("about:blank", "_blank", "noopener,noreferrer"); setBusy(true); try { const result = await fetch(`${apiBaseUrl}/admin/data/backup?scope=installation`, { credentials: "include" }); if (!result.ok) throw new Error("The required pre-update backup could not be created."); const blob = await result.blob(); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = result.headers.get("content-disposition")?.match(/filename="([^"]+)"/)?.[1] ?? "lancerlogin-installation-backup.json"; link.click(); URL.revokeObjectURL(url); setNotice("Backup downloaded. Your private GitHub deployment repository is opening so you can authorize Upgrade manually."); if (github) github.location.href = workflowUrl; else window.location.href = workflowUrl; } catch (error) { github?.close(); setNotice((error as Error).message); } finally { setBusy(false); } }
  async function updateKiosk() { if (!kiosk) return; setKioskBusy(true); try { await api(`/admin/kiosks/${encodeURIComponent(kiosk.id)}/commands`, { method: "POST", body: JSON.stringify({ command: "install_latest" }) }); setNotice("Latest stable kiosk update queued. The Pi will download and verify the release, then restart its kiosk service."); } catch (error) { setNotice((error as Error).message); } finally { setKioskBusy(false); } }
  const kioskOnline = Boolean(kiosk?.lastSeenAt && Date.now() - Date.parse(kiosk.lastSeenAt) < 90_000);
  return <section className="settings-page" aria-labelledby="updates-title"><div className="page-intro"><h1 id="updates-title">Updates</h1></div><p className="setup-status" role="status">{notice}</p><section className="release-comparisons"><article><h2>Dashboard</h2><div className="version-grid"><div><span>Installed</span><strong>{current}</strong></div><div><span>Latest release</span><strong>{latest?.tag_name ? formatVersion(latest.tag_name) : "Unavailable"}</strong>{latest?.html_url && <a href={latest.html_url} target="_blank" rel="noreferrer">Read release notes</a>}</div></div></article>{kiosk && <article><div className="panel-heading"><div><h2>Physical kiosk</h2><p>{kiosk.name}</p></div><button className="primary-button" type="button" disabled={kioskBusy || !kioskOnline} onClick={() => void updateKiosk()}>{kioskBusy ? "Queueing…" : "Update to latest stable"}</button></div><div className="version-grid"><div><span>Installed</span><strong>{kiosk.releaseVersion ?? "Unknown"}</strong></div><div><span>Latest compatible</span><strong>{latest?.tag_name ? formatVersion(latest.tag_name) : "Unavailable"}</strong>{!kioskOnline && <small>The kiosk must be online to update.</small>}</div></div></article>}</section><article className="update-card"><h2>Back up and open your private updater</h2><ol><li>Downloads an entire-installation backup.</li><li>Opens the guarded workflow in your private deployment repository.</li><li>You select <strong>upgrade</strong>, keep <strong>Latest stable</strong> selected, and enter your installation slug.</li><li>GitHub validates the exact existing resources before applying migrations or deploying.</li></ol><button className="primary-button" type="button" disabled={busy || !workflowUrl} onClick={begin}>{busy ? "Preparing backup…" : "Back up and begin update"}</button></article></section>;
}
