import { useEffect, useState } from "react";
import { api, apiBaseUrl } from "./dashboard-api";

const workflowUrl = "https://github.com/isriah/LancerLogin/actions/workflows/provision-template.yml";
type Release = { tag_name?: string; name?: string; html_url?: string; body?: string };
export function UpdatesPage() {
  const [current, setCurrent] = useState("Loading…"); const [latest, setLatest] = useState<Release>(); const [notice, setNotice] = useState("Checking the community release feed…"); const [busy, setBusy] = useState(false);
  useEffect(() => { Promise.all([api<{ releaseVersion: string }>("/health"), fetch("https://api.github.com/repos/isriah/LancerLogin/releases/latest", { headers: { accept: "application/vnd.github+json" } }).then((result) => result.ok ? result.json() as Promise<Release> : Promise.reject(new Error("Latest release is temporarily unavailable")))]).then(([health, release]) => { setCurrent(health.releaseVersion); setLatest(release); setNotice(health.releaseVersion === release.tag_name?.replace(/^v/, "") ? "This installation matches the latest release." : "A different community release is available. Review its notes before upgrading."); }).catch((error: Error) => setNotice(error.message)); }, []);
  async function begin() { const github = window.open("about:blank", "_blank", "noopener,noreferrer"); setBusy(true); try { const result = await fetch(`${apiBaseUrl}/admin/data/backup?scope=installation`, { credentials: "include" }); if (!result.ok) throw new Error("The required pre-update backup could not be created."); const blob = await result.blob(); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = result.headers.get("content-disposition")?.match(/filename="([^"]+)"/)?.[1] ?? "lancerlogin-installation-backup.json"; link.click(); URL.revokeObjectURL(url); setNotice("Backup downloaded. GitHub is opening so you can authorize and run Upgrade manually."); if (github) github.location.href = workflowUrl; else window.location.href = workflowUrl; } catch (error) { github?.close(); setNotice((error as Error).message); } finally { setBusy(false); } }
  return <section className="settings-page" aria-labelledby="updates-title"><div className="page-intro"><p className="kicker">Settings</p><h2 id="updates-title">Updates</h2><p>LancerLogin can check and prepare an update, but GitHub remains the authorization boundary and Cloudflare credentials never enter the dashboard.</p></div><p className="setup-status" role="status">{notice}</p><div className="version-grid"><article><span>Installed</span><strong>{current}</strong></article><article><span>Latest release</span><strong>{latest?.tag_name ?? "Unavailable"}</strong>{latest?.html_url && <a href={latest.html_url} target="_blank" rel="noreferrer">Read release notes</a>}</article></div><article className="update-card"><h3>Back up and open GitHub updater</h3><ol><li>Downloads an entire-installation backup.</li><li>Opens the guarded <strong>Install or upgrade LancerLogin</strong> workflow.</li><li>You select <strong>upgrade</strong>, enter your installation slug, and type the required confirmation.</li><li>GitHub validates the exact existing resources before applying migrations or deploying.</li></ol><button className="primary-button" type="button" disabled={busy} onClick={begin}>{busy ? "Preparing backup…" : "Back up and begin update"}</button><p className="field-help">This button never triggers a deployment automatically. Closing GitHub leaves the installation unchanged.</p></article></section>;
}
