import { FormEvent, useEffect, useState } from "react";
import { api } from "./dashboard-api";
import { useDashboardLoadingOverlay } from "./loading-overlay";

export type RosterMember = { id: string; memberId: string; firstName: string; lastName: string; email?: string; discordUserId?: string; active: boolean | number; attendanceRequiredFrom?: string | null; hasDashboardAccess?: boolean | number };
type User = { id: string; email?: string; localUsername?: string; memberId?: string | null; memberExternalId?: string; memberFirstName?: string; memberLastName?: string; role: "admin" | "operator"; active: boolean | number; createdAt: string };

export function UserSettings({ members }: { members: RosterMember[] }) {
  const [users, setUsers] = useState<User[]>([]); const [method, setMethod] = useState<"local" | "google">("local"); const [identifier, setIdentifier] = useState(""); const [password, setPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [role, setRole] = useState<"admin" | "operator">("operator"); const [memberId, setMemberId] = useState(""); const [notice, setNotice] = useState("Loading dashboard access…"); const [error, setError] = useState("");
  useDashboardLoadingOverlay(notice === "Loading dashboard access…", "Loading dashboard access…");
  async function load() { const result = await api<{ users: User[] }>("/admin/users"); setUsers(result.users); setNotice("Only Admins can grant dashboard access or change roles."); }
  useEffect(() => { void load().catch((caught: Error) => setNotice(caught.message)); }, []);
  function showError(message: string) { setError(message); window.requestAnimationFrame(() => document.getElementById("dashboard-access-error")?.focus()); }
  async function create(event: FormEvent) {
    event.preventDefault(); setError(""); if (method === "local" && password !== confirmation) { showError("Temporary password confirmation does not match."); return; }
    try { await api("/admin/users", { method: "POST", body: JSON.stringify(method === "local" ? { localUsername: identifier, localPassword: password, memberId: memberId || null, role } : { email: identifier, memberId: memberId || null, role }) }); setIdentifier(""); setPassword(""); setConfirmation(""); setMemberId(""); await load(); setNotice("Dashboard access created and audited."); }
    catch (caught) { showError((caught as Error).message); }
  }
  async function update(user: User, patch: { active?: boolean; role?: User["role"]; memberId?: string | null }) { setError(""); try { await api(`/admin/users/${encodeURIComponent(user.id)}`, { method: "PATCH", body: JSON.stringify(patch) }); await load(); setNotice("Dashboard access updated and audited."); } catch (caught) { showError((caught as Error).message); } }
  const available = members.filter((member) => member.active && !users.some((user) => user.memberId === member.id));
  return <section className="user-section" aria-labelledby="access-workspace-title">
    <div className="section-intro"><h2 id="access-workspace-title">Accounts and roles</h2><p>Grant Admin or Operator credentials to a roster member or an independent staff account.</p><span className="ui-status settings-notice" data-tone="neutral" role="status">{notice}</span></div>
    {error && <p id="dashboard-access-error" className="inline-messages error" role="alert" tabIndex={-1}>{error}</p>}
    <div className="user-layout"><form className="task-card" onSubmit={create}><h3>Grant dashboard access</h3>
      <label>Roster link <span>(optional)</span><select value={memberId} onChange={(event) => { const next = event.target.value; setMemberId(next); const member = members.find((item) => item.id === next); if (method === "google" && member?.email) setIdentifier(member.email); }}><option value="">Non-rostered Admin or Operator</option>{available.map((member) => <option key={member.id} value={member.id}>{member.firstName} {member.lastName} · {member.memberId}</option>)}</select></label>
      <fieldset className="method-switch"><legend>Sign-in method</legend><div className="method-switch-options"><label className={method === "local" ? "selected" : ""}><input type="radio" name="user-method" checked={method === "local"} onChange={() => setMethod("local")} /> <span>Local login</span></label><label className={method === "google" ? "selected" : ""}><input type="radio" name="user-method" checked={method === "google"} onChange={() => setMethod("google")} /> <span>Google email</span></label></div></fieldset>
      <label>{method === "local" ? "Username" : "Google email"}<input required type={method === "google" ? "email" : "text"} value={identifier} onChange={(event) => setIdentifier(event.target.value)} /></label>
      {method === "local" && <><label>Temporary password<input required type="password" minLength={12} autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} /></label><label>Confirm temporary password<input required type="password" minLength={12} autoComplete="new-password" value={confirmation} aria-invalid={confirmation !== "" && password !== confirmation} aria-describedby={confirmation !== "" && password !== confirmation ? "password-confirmation-error" : undefined} onChange={(event) => setConfirmation(event.target.value)} /></label>{confirmation && password !== confirmation && <p id="password-confirmation-error" className="inline-messages error" role="alert">Passwords do not match.</p>}</>}
      <label>Role<select value={role} onChange={(event) => setRole(event.target.value as User["role"])}><option value="operator">Operator</option><option value="admin">Admin</option></select></label><button className="primary-button" type="submit">Create access</button>
    </form><div className="user-list">{users.map((user) => <article key={user.id}><div><strong>{user.memberId ? `${user.memberFirstName} ${user.memberLastName}` : user.email ?? user.localUsername}</strong><span>{user.memberId ? `${user.memberExternalId} · ` : "Non-rostered · "}{user.email ?? user.localUsername} · {user.active ? "active" : "inactive"}</span></div><select aria-label={`Role for ${user.email ?? user.localUsername}`} value={user.role} onChange={(event) => void update(user, { role: event.target.value as User["role"] })}><option value="operator">Operator</option><option value="admin">Admin</option></select><select aria-label={`Roster link for ${user.email ?? user.localUsername}`} value={user.memberId ?? ""} onChange={(event) => void update(user, { memberId: event.target.value || null })}><option value="">Non-rostered</option>{members.filter((member) => member.id === user.memberId || !users.some((item) => item.memberId === member.id)).map((member) => <option key={member.id} value={member.id}>{member.firstName} {member.lastName}</option>)}</select><button type="button" onClick={() => void update(user, { active: !user.active })}>{user.active ? "Deactivate" : "Activate"}</button></article>)}</div></div>
  </section>;
}
