import { FormEvent, useEffect, useState } from "react";

const apiBaseUrl = (import.meta.env.VITE_API_BASE_URL as string).replace(/\/$/, "");
type User = { id: string; email?: string; localUsername?: string; role: "admin" | "operator"; active: boolean | number; createdAt: string };
async function api<T>(path: string, init?: RequestInit): Promise<T> { const result = await fetch(`${apiBaseUrl}${path}`, { credentials: "include", ...init, headers: { ...(init?.body ? { "content-type": "application/json" } : {}), ...init?.headers } }); const body = await result.json() as T & { error?: string; details?: string[] }; if (!result.ok) throw new Error(body.details?.join(" ") ?? body.error ?? "Request failed"); return body; }

export function UserSettings() {
  const [users, setUsers] = useState<User[]>([]); const [method, setMethod] = useState<"local" | "google">("local"); const [identifier, setIdentifier] = useState(""); const [password, setPassword] = useState(""); const [role, setRole] = useState<"admin" | "operator">("operator"); const [notice, setNotice] = useState("Loading users…");
  async function load() { const result = await api<{ users: User[] }>("/admin/users"); setUsers(result.users); setNotice("Admins control users and security; Operators manage attendance operations only."); }
  useEffect(() => { load().catch((error: Error) => setNotice(error.message)); }, []);
  async function create(event: FormEvent) { event.preventDefault(); try { await api("/admin/users", { method: "POST", body: JSON.stringify(method === "local" ? { localUsername: identifier, localPassword: password, role } : { email: identifier, role }) }); setIdentifier(""); setPassword(""); await load(); setNotice("User created."); } catch (error) { setNotice((error as Error).message); } }
  async function update(user: User, patch: { active?: boolean; role?: User["role"] }) { try { await api(`/admin/users/${encodeURIComponent(user.id)}`, { method: "PATCH", body: JSON.stringify(patch) }); await load(); setNotice("User access updated and audited."); } catch (error) { setNotice((error as Error).message); } }
  return <section className="user-section" aria-labelledby="users-title"><div className="section-intro"><p className="kicker">Users & roles</p><h2 id="users-title">Delegate without sharing Admin access</h2><p>Operators can manage meetings, attendance, corrections, excuses, reports, and kiosk status. They cannot manage this area, security, integrations, branding, or destructive configuration.</p><span role="status">{notice}</span></div><div className="user-layout"><form className="task-card" onSubmit={create}><h3>Add user</h3><div className="method-switch"><label><input type="radio" name="user-method" checked={method === "local"} onChange={() => setMethod("local")} /> Local login</label><label><input type="radio" name="user-method" checked={method === "google"} onChange={() => setMethod("google")} /> Google email</label></div><label>{method === "local" ? "Username" : "Google email"}<input required type={method === "google" ? "email" : "text"} value={identifier} onChange={(event) => setIdentifier(event.target.value)} /></label>{method === "local" && <label>Temporary password<input required type="password" minLength={12} autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} /><span className="field-help">At least 12 characters; share it outside LancerLogin.</span></label>}<label>Role<select value={role} onChange={(event) => setRole(event.target.value as User["role"])}><option value="operator">Operator</option><option value="admin">Admin</option></select></label><button className="primary-button" type="submit">Create user</button></form><div className="user-list">{users.map((user) => <article key={user.id}><div><strong>{user.email ?? user.localUsername}</strong><span>{user.role} · {user.active ? "active" : "inactive"}</span></div><select aria-label={`Role for ${user.email ?? user.localUsername}`} value={user.role} onChange={(event) => update(user, { role: event.target.value as User["role"] })}><option value="operator">Operator</option><option value="admin">Admin</option></select><button type="button" onClick={() => update(user, { active: !user.active })}>{user.active ? "Deactivate" : "Activate"}</button></article>)}</div></div></section>;
}
