import {HttpError} from './http-error.ts';
import {requireModuleCapability,type ModuleDatabase} from './platform-modules.ts';

type Row=Record<string,any>;
export const initiativeColumns={
 documentation_initiatives:['installation_id','id','title','narrative','archived','revision','author_user_id','created_at','updated_at'],
 documentation_initiative_activities:['installation_id','initiative_id','activity_id'],
 documentation_initiative_revisions:['installation_id','initiative_id','revision','actor_user_id','title','narrative','archived','created_at'],
 documentation_initiative_revision_activities:['installation_id','initiative_id','revision','activity_id'],
} as const;
const access=`EXISTS(SELECT 1 FROM users u JOIN platform_module_configuration c ON c.installation_id=u.installation_id LEFT JOIN platform_module_grants g ON g.installation_id=u.installation_id AND g.user_id=u.id WHERE u.installation_id=? AND u.id=? AND u.active=1 AND c.hours_enabled=1 AND c.documentation_enabled=1 AND (u.role='admin' OR g.documentation_manage=1))`;
function fail(status=400,message='Invalid initiative request'):never{throw new HttpError(status,message);}
const record=(v:unknown):v is Row=>!!v&&typeof v==='object'&&!Array.isArray(v);
function fields(v:unknown,keys:string[]){if(!record(v)||Object.keys(v).some(k=>!keys.includes(k)))fail();return v;}
function revision(v:unknown){if(!Number.isSafeInteger(v)||Number(v)<0||Number(v)>=Number.MAX_SAFE_INTEGER)fail();return Number(v);}
function id(v:unknown){if(typeof v!=='string'||!/^[A-Za-z0-9_-]{1,128}$/.test(v))fail();return v;}
function text(v:unknown,max:number,required=false){if(typeof v!=='string'||v.length>max||(required&&!v.trim())||/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(v))fail();return v;}
function links(v:unknown){if(!Array.isArray(v)||v.length>100)fail();const result=v.map(x=>{const r=fields(x,['activityId','revision']);return {activityId:id(r.activityId),revision:revision(r.revision)};});if(new Set(result.map(r=>r.activityId)).size!==result.length)fail();return result;}
function page(url:URL,history=false){const seen=new Set<string>();url.searchParams.forEach((_,key)=>{if(!['after','limit','archival'].includes(key)||seen.has(key))fail();seen.add(key);});const limit=Number(url.searchParams.get('limit')??25),raw=url.searchParams.get('after'),archival=url.searchParams.get('archival')??'false';if(!Number.isInteger(limit)||limit<1||limit>50||!['true','false'].includes(archival))fail();return {limit,after:history?raw===null?-1:revision(Number(raw)):raw===null?'':id(raw),archival:archival==='true'};}
const dto=(r:Row)=>({id:r.id,title:r.title,narrative:r.narrative,archived:Boolean(r.archived),revision:r.revision,authorUserId:r.author_user_id,createdAt:r.created_at,updatedAt:r.updated_at});
const membership=`COALESCE((SELECT json_group_array(json_object('activityId',a.id,'title',a.title,'revision',a.revision,'archived',json(CASE WHEN a.archived=1 THEN 'true' ELSE 'false' END),'impactRelevant',json(CASE WHEN a.impact_relevant=1 THEN 'true' ELSE 'false' END))) FROM documentation_initiative_activities l JOIN hours_activities a ON a.installation_id=l.installation_id AND a.id=l.activity_id WHERE l.installation_id=i.installation_id AND l.initiative_id=i.id),'[]')`;

// The selected initiative set, module authority, section flag and eligible activity/entry
// union are evaluated in one statement. EXISTS avoids multiplying entries across links.
async function summary(db:ModuleDatabase,installation:string,actor:string,ids:string[]){
 const result=await db.prepare(`WITH selected AS (SELECT i.id,i.archived FROM documentation_initiatives i JOIN json_each(?) j ON j.value=i.id WHERE i.installation_id=?), linked AS (SELECT DISTINCT a.id,a.archived,a.impact_relevant FROM hours_activities a JOIN documentation_initiative_activities l ON l.installation_id=a.installation_id AND l.activity_id=a.id JOIN selected s ON s.id=l.initiative_id WHERE a.installation_id=?), eligible AS (SELECT a.id FROM linked a WHERE a.archived=0 AND a.impact_relevant=1 AND EXISTS(SELECT 1 FROM documentation_initiative_activities l JOIN selected s ON s.id=l.initiative_id AND s.archived=0 WHERE l.installation_id=? AND l.activity_id=a.id)) SELECT (SELECT COUNT(*) FROM selected) AS available,COALESCE((SELECT summary_enabled FROM documentation_sections WHERE installation_id=?),1) AS summary_enabled,(SELECT COUNT(*) FROM linked) AS linked_count,(SELECT COUNT(*) FROM eligible) AS eligible_count,CASE WHEN COALESCE((SELECT summary_enabled FROM documentation_sections WHERE installation_id=?),1)=1 THEN (SELECT COALESCE(SUM(e.duration_minutes),0) FROM hours_entries e WHERE e.installation_id=? AND e.status='counted' AND EXISTS(SELECT 1 FROM eligible a WHERE a.id=e.activity_id)) END AS minutes,CASE WHEN COALESCE((SELECT summary_enabled FROM documentation_sections WHERE installation_id=?),1)=1 THEN (SELECT COUNT(DISTINCT e.member_id) FROM hours_entries e WHERE e.installation_id=? AND e.status='counted' AND EXISTS(SELECT 1 FROM eligible a WHERE a.id=e.activity_id)) END AS participants WHERE ${access}`).bind(JSON.stringify(ids),installation,installation,installation,installation,installation,installation,installation,installation,installation,actor).first<Row>();
 if(!result||result.available!==ids.length)fail(404,'Initiative unavailable');
 return {linkedActivityCount:result.linked_count,eligibleActivityCount:result.eligible_count,omittedActivityCount:result.linked_count-result.eligible_count,...(result.summary_enabled?{summary:{countedMinutes:result.minutes,distinctParticipants:result.participants}}:{})};
}
export async function initiativeRoute(db:ModuleDatabase,installation:string,actor:string,request:Request,input?:unknown){
 await requireModuleCapability(db,installation,actor,'documentation.manage');
 const url=new URL(request.url),path=url.pathname.replace('/admin/documentation/initiatives',''),now=new Date().toISOString();
 if(path==='/summary'){
  if(request.method!=='POST')fail(405);const v=fields(input,['initiativeIds']);if(!Array.isArray(v.initiativeIds)||v.initiativeIds.length<1||v.initiativeIds.length>100)fail();const ids=v.initiativeIds.map(id);if(new Set(ids).size!==ids.length)fail();return {status:200,body:await summary(db,installation,actor,ids)};
 }
 const match=/^\/(?:([A-Za-z0-9_-]{1,128}))(\/history)?$/.exec(path);if(path&&!match)fail(404);const initiativeId=match?.[1];
 if(request.method==='GET'){
  const p=page(url,!!match?.[2]);
  if(!initiativeId){const rows=(await db.prepare(`SELECT i.* FROM documentation_initiatives i WHERE i.installation_id=? AND i.id>? AND (?=1 OR i.archived=0) AND ${access} ORDER BY i.id LIMIT ?`).bind(installation,p.after,Number(p.archival),installation,actor,p.limit+1).all<Row>()).results??[];return {status:200,body:{initiatives:rows.slice(0,p.limit).map(dto),next:rows.length>p.limit?rows[p.limit-1].id:null}};}
  if(match?.[2]){
   // Batch provides a coherent header/history snapshot, including immutable author provenance.
   const results=await db.batch([db.prepare(`SELECT i.* FROM documentation_initiatives i WHERE i.installation_id=? AND i.id=? AND ${access}`).bind(installation,initiativeId,installation,actor),db.prepare(`SELECT r.*,COALESCE((SELECT json_group_array(activity_id) FROM documentation_initiative_revision_activities l WHERE l.installation_id=r.installation_id AND l.initiative_id=r.initiative_id AND l.revision=r.revision),'[]') AS activity_ids,COALESCE((SELECT json_group_array(json_object('activityId',a.id,'title',a.title)) FROM documentation_initiative_revision_activities l JOIN hours_activities a ON a.installation_id=l.installation_id AND a.id=l.activity_id WHERE l.installation_id=r.installation_id AND l.initiative_id=r.initiative_id AND l.revision=r.revision),'[]') AS activities FROM documentation_initiative_revisions r WHERE r.installation_id=? AND r.initiative_id=? AND r.revision>? AND ${access} ORDER BY r.revision LIMIT ?`).bind(installation,initiativeId,p.after,installation,actor,p.limit+1)]);
   const header=results[0].results?.[0] as Row|undefined;if(!header)fail(404,'Initiative unavailable');const rows=(results[1].results??[]) as Row[];return {status:200,body:{initiativeId,authorUserId:header.author_user_id,createdAt:header.created_at,revisions:rows.slice(0,p.limit).map(r=>({revision:r.revision,actorUserId:r.actor_user_id,title:r.title,narrative:r.narrative,archived:Boolean(r.archived),createdAt:r.created_at,activityIds:JSON.parse(r.activity_ids),activities:JSON.parse(r.activities)})),next:rows.length>p.limit?rows[p.limit-1].revision:null}};
  }
  // Summary and detail are read together in one transaction; no stale section/grant overlay.
  const rows=await db.batch([db.prepare(`SELECT i.*,${membership} AS activities,COALESCE(s.summary_enabled,1) AS summary_enabled,(SELECT COUNT(*) FROM documentation_initiative_activities l WHERE l.installation_id=i.installation_id AND l.initiative_id=i.id) AS linked_count,(SELECT COUNT(*) FROM documentation_initiative_activities l JOIN hours_activities a ON a.installation_id=l.installation_id AND a.id=l.activity_id WHERE l.installation_id=i.installation_id AND l.initiative_id=i.id AND i.archived=0 AND a.archived=0 AND a.impact_relevant=1) AS eligible_count,CASE WHEN COALESCE(s.summary_enabled,1)=1 THEN (SELECT COALESCE(SUM(e.duration_minutes),0) FROM hours_entries e WHERE e.installation_id=i.installation_id AND e.status='counted' AND i.archived=0 AND EXISTS(SELECT 1 FROM documentation_initiative_activities l JOIN hours_activities a ON a.installation_id=l.installation_id AND a.id=l.activity_id WHERE l.installation_id=i.installation_id AND l.initiative_id=i.id AND a.id=e.activity_id AND a.archived=0 AND a.impact_relevant=1)) END AS minutes,CASE WHEN COALESCE(s.summary_enabled,1)=1 THEN (SELECT COUNT(DISTINCT e.member_id) FROM hours_entries e WHERE e.installation_id=i.installation_id AND e.status='counted' AND i.archived=0 AND EXISTS(SELECT 1 FROM documentation_initiative_activities l JOIN hours_activities a ON a.installation_id=l.installation_id AND a.id=l.activity_id WHERE l.installation_id=i.installation_id AND l.initiative_id=i.id AND a.id=e.activity_id AND a.archived=0 AND a.impact_relevant=1)) END AS participants FROM documentation_initiatives i LEFT JOIN documentation_sections s ON s.installation_id=i.installation_id WHERE i.installation_id=? AND i.id=? AND ${access}`).bind(installation,initiativeId,installation,actor)]);
  const r=rows[0].results?.[0] as Row|undefined;if(!r)fail(404,'Initiative unavailable');return {status:200,body:{initiative:dto(r),activities:JSON.parse(r.activities),readOnly:Boolean(r.archived),linkedActivityCount:r.linked_count,eligibleActivityCount:r.eligible_count,omittedActivityCount:r.linked_count-r.eligible_count,...(r.summary_enabled?{summary:{countedMinutes:r.minutes,distinctParticipants:r.participants}}:{})}};
 }
 if((initiativeId?request.method!=='PATCH':request.method!=='POST')||match?.[2])fail(405);
 const v=fields(input,initiativeId?['revision','title','narrative','activities','archived']:['title','narrative','activities']);
 const current=initiativeId?await db.prepare(`SELECT * FROM documentation_initiatives WHERE installation_id=? AND id=? AND ${access}`).bind(installation,initiativeId,installation,actor).first<Row>():null;if(initiativeId&&!current)fail(404,'Initiative unavailable');
 const rev=initiativeId?revision(v.revision):0;if(initiativeId&&Object.keys(v).length===1)fail();if(v.archived!==undefined&&typeof v.archived!=='boolean')fail();
 if(current?.archived&&(v.archived!==false||Object.keys(v).some(k=>!['revision','archived'].includes(k))))fail(409,'Unarchive the initiative before editing');
 const title=text(Object.hasOwn(v,'title')?v.title:current?.title,200,true),narrative=text(Object.hasOwn(v,'narrative')?v.narrative:current?.narrative??'',8000),archived=v.archived===undefined?current?.archived??0:Number(v.archived);
 const requested=v.activities===undefined?(initiativeId?null:[]):links(v.activities),newId=initiativeId??crypto.randomUUID(),auditId=crypto.randomUUID();
 const additionGate=requested===null?'1':`NOT EXISTS(SELECT 1 FROM json_each(?) j WHERE NOT EXISTS(SELECT 1 FROM documentation_initiative_activities l WHERE l.installation_id=? AND l.initiative_id=? AND l.activity_id=json_extract(j.value,'$.activityId')) AND NOT EXISTS(SELECT 1 FROM hours_activities a WHERE a.installation_id=? AND a.id=json_extract(j.value,'$.activityId') AND a.revision=json_extract(j.value,'$.revision') AND a.archived=0 AND a.impact_relevant=1))`;
 const additionArgs=requested===null?[]:[JSON.stringify(requested),installation,newId,installation];
 const mutation=initiativeId?db.prepare(`UPDATE documentation_initiatives SET title=?,narrative=?,archived=?,revision=revision+1,updated_at=? WHERE installation_id=? AND id=? AND revision=? AND archived=? AND ${access} AND ${additionGate}`).bind(title,narrative,archived,now,installation,newId,rev,current!.archived,installation,actor,...additionArgs):db.prepare(`INSERT INTO documentation_initiatives(installation_id,id,title,narrative,author_user_id,created_at,updated_at) SELECT ?,?,?,?,?,?,? WHERE ${access} AND ${additionGate}`).bind(installation,newId,title,narrative,actor,now,now,installation,actor,...additionArgs);
 const admitted=`EXISTS(SELECT 1 FROM audit_log WHERE installation_id=? AND id=?)`,admittedArgs=[installation,auditId];
 const statements=[mutation,db.prepare("INSERT INTO audit_log(id,installation_id,actor_user_id,action,target_type,target_id,created_at) SELECT ?,?,?,?,'documentation_initiative',?,? WHERE changes()=1").bind(auditId,installation,actor,initiativeId?'documentation.initiative.updated':'documentation.initiative.created',newId,now)];
 if(requested!==null){statements.push(db.prepare(`DELETE FROM documentation_initiative_activities WHERE installation_id=? AND initiative_id=? AND ${admitted}`).bind(installation,newId,...admittedArgs),db.prepare(`INSERT INTO documentation_initiative_activities(installation_id,initiative_id,activity_id) SELECT ?,?,json_extract(value,'$.activityId') FROM json_each(?) WHERE ${admitted}`).bind(installation,newId,JSON.stringify(requested),...admittedArgs));}
 statements.push(db.prepare(`INSERT INTO documentation_initiative_revisions(installation_id,initiative_id,revision,actor_user_id,title,narrative,archived,created_at) SELECT installation_id,id,revision,?,title,narrative,archived,updated_at FROM documentation_initiatives WHERE installation_id=? AND id=? AND ${admitted}`).bind(actor,installation,newId,...admittedArgs),db.prepare(`INSERT INTO documentation_initiative_revision_activities(installation_id,initiative_id,revision,activity_id) SELECT l.installation_id,l.initiative_id,i.revision,l.activity_id FROM documentation_initiative_activities l JOIN documentation_initiatives i ON i.installation_id=l.installation_id AND i.id=l.initiative_id WHERE l.installation_id=? AND l.initiative_id=? AND ${admitted}`).bind(installation,newId,...admittedArgs));
 const results=await db.batch(statements);if(results[1]?.meta?.changes!==1)fail(409,'Initiative, activity or authority changed; reload');return {status:initiativeId?200:201,body:{initiative:dto({id:newId,title,narrative,archived,revision:initiativeId?rev+1:0,author_user_id:current?.author_user_id??actor,created_at:current?.created_at??now,updated_at:now})}};
}

export function validateInitiativeBackup(tables:Record<string,Row[]>){
 const bad=()=>fail(400,'Invalid initiative backup');
 const stamp=(v:unknown)=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}T/.test(v)&&Number.isFinite(Date.parse(v));
 const users=new Set((tables.users??[]).filter(r=>r.installation_id==='primary').map(r=>r.id)),activities=new Set((tables.hours_activities??[]).filter(r=>r.installation_id==='primary').map(r=>r.id));
 const initiatives=new Map<string,Row>();
 for(const r of tables.documentation_initiatives??[]){id(r.id);revision(r.revision);text(r.title,200,true);text(r.narrative,8000);if(r.installation_id!=='primary'||initiatives.has(r.id)||!users.has(r.author_user_id)||![0,1].includes(r.archived)||!stamp(r.created_at)||!stamp(r.updated_at)||Date.parse(r.updated_at)<Date.parse(r.created_at))bad();initiatives.set(r.id,r);}
 const current=new Map<string,Set<string>>(),history=new Map<string,Map<number,Row>>(),historic=new Map<string,Set<string>>();
 for(const r of tables.documentation_initiative_activities??[]){if(r.installation_id!=='primary'||!initiatives.has(r.initiative_id)||!activities.has(r.activity_id))bad();const set=current.get(r.initiative_id)??new Set();if(set.has(r.activity_id)||set.size>=100)bad();set.add(r.activity_id);current.set(r.initiative_id,set);}
 for(const r of tables.documentation_initiative_revisions??[]){revision(r.revision);text(r.title,200,true);text(r.narrative,8000);if(r.installation_id!=='primary'||!initiatives.has(r.initiative_id)||!users.has(r.actor_user_id)||![0,1].includes(r.archived)||!stamp(r.created_at))bad();const rows=history.get(r.initiative_id)??new Map();if(rows.has(r.revision))bad();rows.set(r.revision,r);history.set(r.initiative_id,rows);}
 for(const r of tables.documentation_initiative_revision_activities??[]){revision(r.revision);if(r.installation_id!=='primary'||!history.get(r.initiative_id)?.has(r.revision)||!activities.has(r.activity_id))bad();const key=JSON.stringify([r.initiative_id,r.revision]),set=historic.get(key)??new Set();if(set.has(r.activity_id)||set.size>=100)bad();set.add(r.activity_id);historic.set(key,set);}
 for(const [key,r] of initiatives){const rows=history.get(key);if(!rows||rows.size!==r.revision+1)bad();let previous=0;for(let rev=0;rev<=r.revision;rev++){const h=rows!.get(rev);if(!h||Date.parse(h.created_at)<previous)bad();previous=Date.parse(h!.created_at);if(rev&&rows!.get(rev-1)!.archived){const prior=rows!.get(rev-1)!;if(h!.archived!==0||h!.title!==prior.title||h!.narrative!==prior.narrative||JSON.stringify([...(historic.get(JSON.stringify([key,rev]))??[])].sort())!==JSON.stringify([...(historic.get(JSON.stringify([key,rev-1]))??[])].sort()))bad();}}
  const first=rows!.get(0)!,last=rows!.get(r.revision)!;if(first.actor_user_id!==r.author_user_id||first.created_at!==r.created_at||first.archived!==0||last.title!==r.title||last.narrative!==r.narrative||last.archived!==r.archived||last.created_at!==r.updated_at)bad();
  if(JSON.stringify([...(current.get(key)??[])].sort())!==JSON.stringify([...(historic.get(JSON.stringify([key,r.revision]))??[])].sort()))bad();
 }
}
