import {HttpError} from './http-error.ts';
import {requireModuleCapability,type ModuleDatabase} from './platform-modules.ts';
export const documentationSectionRegistry=Object.freeze([
 {id:'notes',version:1,kind:'plain-text',label:'Private notes'},
 {id:'photos-files',version:1,kind:'artifacts',label:'Photos and files'},
 {id:'participant-hours',version:1,kind:'computed-summary',label:'Participant and hour summary'},
] as const);
export const documentationColumns={
 documentation_sections:['installation_id','version','revision','notes_enabled','summary_enabled','files_enabled'],
 documentation_notes:['installation_id','id','activity_id','author_user_id','text','archived','revision','created_at','updated_at','author_member_id','source','review_decision','reviewed_revision','reviewer_user_id','reviewed_at'],
 documentation_note_revisions:['installation_id','note_id','revision','actor_user_id','text','archived','created_at','actor_member_id','source','review_decision','reviewed_revision','reviewer_user_id','reviewed_at'],
 documentation_note_submission_keys:['installation_id','channel','key_hash','fingerprint','note_id','created_at'],
} as const;
type Row=Record<string,any>;
function fail(status=400,message='Invalid Documentation request'):never{throw new HttpError(status,message);}
const object=(v:unknown):v is Row=>!!v&&typeof v==='object'&&!Array.isArray(v);
const integer=(v:unknown)=>{if(!Number.isSafeInteger(v)||Number(v)<0||Number(v)>=Number.MAX_SAFE_INTEGER)fail();return Number(v);};
const noteText=(v:unknown)=>{if(typeof v!=='string'||!v.trim()||v.length>8000||/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(v))fail();return v;};
const flag=(v:unknown)=>{if(typeof v!=='boolean')fail();return Number(v);};
const identity=(v:unknown)=>{if(typeof v!=='string'||!/^[A-Za-z0-9_-]{1,128}$/.test(v))fail();return v;};
const fields=(v:unknown,allowed:string[])=>{if(!object(v)||Object.keys(v).some(k=>!allowed.includes(k)))fail();return v;};
const access=`EXISTS(SELECT 1 FROM users u JOIN platform_module_configuration c ON c.installation_id=u.installation_id LEFT JOIN platform_module_grants g ON g.installation_id=u.installation_id AND g.user_id=u.id WHERE u.installation_id=? AND u.id=? AND u.active=1 AND c.hours_enabled=1 AND c.documentation_enabled=1 AND (u.role='admin' OR g.documentation_manage=1))`;
const eligible="a.archived=0 AND a.impact_relevant=1";
const visible=`((${eligible}) OR EXISTS(SELECT 1 FROM documentation_notes n WHERE n.installation_id=a.installation_id AND n.activity_id=a.id))`;
const sectionWrite=`COALESCE((SELECT notes_enabled FROM documentation_sections WHERE installation_id=?),1)=1 AND COALESCE((SELECT revision FROM documentation_sections WHERE installation_id=?),0)=?`;
const reviewDto=(r:Row)=>r.review_decision?{decision:r.review_decision,reviewedRevision:r.reviewed_revision,reviewerUserId:r.reviewer_user_id,reviewedAt:r.reviewed_at}:null;
const contributor=(r:Row,history=false)=>({kind:(history?r.actor_member_id:r.author_member_id)?'member':'staff',userId:(history?r.actor_user_id:r.author_user_id)??null,memberId:(history?r.actor_member_id:r.author_member_id)??null,source:r.source??'staff',currentMemberLabel:r.contributor_label??null,attribution:r.source==='public'?'self_asserted':r.source==='discord'?'linked_discord':'staff'});
const noteDto=(r:Row)=>({id:r.id,activityId:r.activity_id,authorUserId:r.author_user_id,contributor:contributor(r),review:reviewDto(r),text:r.text,archived:Boolean(r.archived),revision:r.revision,createdAt:r.created_at,updatedAt:r.updated_at});
async function settings(db:ModuleDatabase,installation:string){const r=await db.prepare('SELECT * FROM documentation_sections WHERE installation_id=?').bind(installation).first<Row>();return {version:1,revision:r?.revision??0,notesEnabled:r?.notes_enabled!==0,summaryEnabled:r?.summary_enabled!==0,filesEnabled:r?.files_enabled!==0,sections:documentationSectionRegistry};}
function page(url:URL,history=false){const keys:string[]=[];url.searchParams.forEach((_,k)=>keys.push(k));if(keys.some(k=>!['after','limit','archival'].includes(k))||new Set(keys).size!==keys.length)fail();const limit=Number(url.searchParams.get('limit')??25);if(!Number.isInteger(limit)||limit<1||limit>50)fail();const raw=url.searchParams.get('after');const after=history?raw===null?-1:integer(Number(raw)):raw===null?'':identity(raw);const archival=url.searchParams.get('archival')??'false';if(!['true','false'].includes(archival))fail();return {limit,after,archival:archival==='true'};}
function audit(db:ModuleDatabase,installation:string,actor:string,action:string,target:string,now:string){return db.prepare("INSERT INTO audit_log(id,installation_id,actor_user_id,action,target_type,target_id,created_at) SELECT ?,?,?,?,'documentation',?,? WHERE changes()=1").bind(crypto.randomUUID(),installation,actor,action,target,now);}
export async function documentationRoute(db:ModuleDatabase,installation:string,actor:string,request:Request,input?:unknown){
 await requireModuleCapability(db,installation,actor,'documentation.manage');const url=new URL(request.url),path=url.pathname.replace('/admin/documentation',''),now=new Date().toISOString();
 if(path==='/sections'){
  if(request.method==='GET')return {status:200,body:await settings(db,installation)};
  if(request.method!=='PUT')fail(405);const v=fields(input,['version','revision','notesEnabled','summaryEnabled','filesEnabled']);if(v.version!==1)fail();const revision=integer(v.revision),notes=flag(v.notesEnabled),summary=flag(v.summaryEnabled),files=Object.hasOwn(v,'filesEnabled')?flag(v.filesEnabled):null;
  const result=await db.batch([db.prepare(`INSERT INTO documentation_sections(installation_id,version,revision,notes_enabled,summary_enabled,files_enabled) SELECT ?,1,1,?,?,COALESCE(?,(SELECT files_enabled FROM documentation_sections WHERE installation_id=?),1) WHERE ${access} AND EXISTS(SELECT 1 FROM users WHERE installation_id=? AND id=? AND role='admin') AND (?=0 OR EXISTS(SELECT 1 FROM documentation_sections WHERE installation_id=?)) ON CONFLICT(installation_id) DO UPDATE SET revision=documentation_sections.revision+1,notes_enabled=excluded.notes_enabled,summary_enabled=excluded.summary_enabled,files_enabled=excluded.files_enabled WHERE documentation_sections.revision=?`).bind(installation,notes,summary,files,installation,installation,actor,installation,actor,revision,installation,revision),audit(db,installation,actor,'documentation.sections.updated',installation,now)]);
  if(result[1]?.meta?.changes!==1)fail(409,'Section configuration or Admin authority changed; reload');return {status:200,body:await settings(db,installation)};
 }
 const activity=/^\/activities(?:\/([A-Za-z0-9_-]{1,128}))?(\/notes)?$/.exec(path);
 if(activity){
  const id=activity[1];if(activity[2]&&!id)fail();
  if(request.method==='GET'){
   const p=page(url),config=await settings(db,installation);
   if(!id){const rows=(await db.prepare(`SELECT a.id,a.title,a.mode,a.service_date,a.team_id,a.revision,a.archived,a.impact_relevant FROM hours_activities a WHERE a.installation_id=? AND a.id>? AND ${p.archival?visible:eligible} AND ${access} ORDER BY a.id LIMIT ?`).bind(installation,p.after,installation,actor,p.limit+1).all<Row>()).results??[];return {status:200,body:{activities:rows.slice(0,p.limit).map(a=>({id:a.id,title:a.title,mode:a.mode,serviceDate:a.service_date,teamId:a.team_id,revision:a.revision,archived:Boolean(a.archived),impactRelevant:Boolean(a.impact_relevant)})),next:rows.length>p.limit?rows[p.limit-1].id:null}};}
   const a=await db.prepare(`SELECT a.id,a.title,a.mode,a.service_date,a.team_id,a.revision,a.archived,a.impact_relevant FROM hours_activities a WHERE a.installation_id=? AND a.id=? AND ${visible} AND ${access}`).bind(installation,id,installation,actor).first<Row>();if(!a)fail(404,'Documentation activity unavailable');
   if(activity[2]){const rows=(await db.prepare(`SELECT n.*,(SELECT trim(first_name||' '||last_name) FROM members m WHERE m.installation_id=n.installation_id AND m.id=n.author_member_id) contributor_label FROM documentation_notes n WHERE n.installation_id=? AND n.activity_id=? AND n.id>? AND ${access} ORDER BY n.id LIMIT ?`).bind(installation,id,p.after,installation,actor,p.limit+1).all<Row>()).results??[];return {status:200,body:{notes:rows.slice(0,p.limit).map(noteDto),next:rows.length>p.limit?rows[p.limit-1].id:null,readOnly:!config.notesEnabled||!!a.archived||!a.impact_relevant,sectionRevision:config.revision,activityRevision:a.revision}};}
   // One statement binds visibility, section settings and private aggregate to the same read snapshot.
   const detail=await db.prepare(`SELECT a.id,a.title,a.mode,a.service_date,a.team_id,a.revision,a.archived,a.impact_relevant,COALESCE(s.revision,0) AS section_revision,COALESCE(s.notes_enabled,1) AS notes_enabled,COALESCE(s.summary_enabled,1) AS summary_enabled,CASE WHEN COALESCE(s.summary_enabled,1)=1 THEN (SELECT COALESCE(SUM(e.duration_minutes),0) FROM hours_entries e WHERE e.installation_id=a.installation_id AND e.activity_id=a.id AND e.status='counted') END AS counted_minutes,CASE WHEN COALESCE(s.summary_enabled,1)=1 THEN (SELECT COUNT(DISTINCT e.member_id) FROM hours_entries e WHERE e.installation_id=a.installation_id AND e.activity_id=a.id AND e.status='counted') END AS distinct_participants FROM hours_activities a LEFT JOIN documentation_sections s ON s.installation_id=a.installation_id WHERE a.installation_id=? AND a.id=? AND ${visible} AND ${access}`).bind(installation,id,installation,actor).first<Row>();if(!detail)fail(404,'Documentation activity unavailable');
   return {status:200,body:{id:detail.id,title:detail.title,mode:detail.mode,serviceDate:detail.service_date,teamId:detail.team_id,revision:detail.revision,archived:Boolean(detail.archived),impactRelevant:Boolean(detail.impact_relevant),readOnly:!detail.notes_enabled||!!detail.archived||!detail.impact_relevant,sectionRevision:detail.section_revision,...(detail.summary_enabled?{summary:{countedMinutes:detail.counted_minutes,distinctParticipants:detail.distinct_participants}}:{})}};
  }
  if(request.method!=='POST'||!id||!activity[2])fail(405);const v=fields(input,['activityRevision','sectionRevision','text']),ar=integer(v.activityRevision),sr=integer(v.sectionRevision),text=noteText(v.text),noteId=crypto.randomUUID();
  const result=await db.batch([db.prepare(`INSERT INTO documentation_notes(installation_id,id,activity_id,author_user_id,text,created_at,updated_at) SELECT ?,?,?,?,?,?,? WHERE ${access} AND ${sectionWrite} AND EXISTS(SELECT 1 FROM hours_activities a WHERE a.installation_id=? AND a.id=? AND a.revision=? AND ${eligible})`).bind(installation,noteId,id,actor,text,now,now,installation,actor,installation,installation,sr,installation,id,ar),db.prepare("INSERT INTO documentation_note_revisions(installation_id,note_id,revision,actor_user_id,text,archived,created_at) SELECT installation_id,id,revision,author_user_id,text,archived,created_at FROM documentation_notes WHERE installation_id=? AND id=? AND changes()=1").bind(installation,noteId),audit(db,installation,actor,'documentation.note.created',noteId,now)]);
  if(result[2]?.meta?.changes!==1)fail(409,'Activity, section or authority changed; reload');return {status:201,body:{note:noteDto({id:noteId,activity_id:id,author_user_id:actor,text,archived:0,revision:0,created_at:now,updated_at:now})}};
 }
 const note=/^\/notes\/([A-Za-z0-9_-]{1,128})(\/history|\/review)?$/.exec(path);if(!note)fail(404);const id=note[1];
 const existing=await db.prepare(`SELECT n.*,(SELECT trim(first_name||' '||last_name) FROM members m WHERE m.installation_id=n.installation_id AND m.id=n.author_member_id) contributor_label FROM documentation_notes n WHERE n.installation_id=? AND n.id=? AND ${access}`).bind(installation,id,installation,actor).first<Row>();if(!existing)fail(404,'Documentation note unavailable');
 if(request.method==='GET'){
  if(note[2]==='/review')fail(405);if(!note[2])return {status:200,body:{note:noteDto(existing)}};const p=page(url,true);const snapshot=await db.prepare(`SELECT n.*,(SELECT trim(first_name||' '||last_name) FROM members m WHERE m.installation_id=n.installation_id AND m.id=n.author_member_id) contributor_label,(SELECT json_group_array(json_object('revision',revision,'actor_user_id',actor_user_id,'actor_member_id',actor_member_id,'source',source,'text',text,'archived',archived,'created_at',created_at,'review_decision',review_decision,'reviewed_revision',reviewed_revision,'reviewer_user_id',reviewer_user_id,'reviewed_at',reviewed_at,'contributor_label',contributor_label)) FROM (SELECT r.*,(SELECT trim(first_name||' '||last_name) FROM members m WHERE m.installation_id=r.installation_id AND m.id=r.actor_member_id) contributor_label FROM documentation_note_revisions r WHERE r.installation_id=n.installation_id AND r.note_id=n.id AND revision>? ORDER BY revision LIMIT ?)) history FROM documentation_notes n WHERE n.installation_id=? AND n.id=? AND ${access}`).bind(p.after,p.limit+1,installation,id,installation,actor).first<Row>();if(!snapshot)fail(404,'Documentation note unavailable');const rows=JSON.parse(snapshot.history) as Row[];return {status:200,body:{noteId:id,authorUserId:snapshot.author_user_id,contributor:contributor(snapshot),createdAt:snapshot.created_at,revisions:rows.slice(0,p.limit).map(r=>({revision:r.revision,actorUserId:r.actor_user_id,contributor:contributor(r,true),review:reviewDto(r),text:r.text,archived:Boolean(r.archived),createdAt:r.created_at})),next:rows.length>p.limit?rows[p.limit-1].revision:null}};
 }
 const reviewing=note[2]==='/review';if(reviewing?request.method!=='POST':request.method!=='PATCH'||!!note[2])fail(405);
 const v=fields(input,reviewing?['revision','activityRevision','sectionRevision','decision']:['revision','activityRevision','sectionRevision','text','archived']);
 if(reviewing?!['reviewed','rejected'].includes(v.decision):!Object.hasOwn(v,'text')&&!Object.hasOwn(v,'archived'))fail();
 const revision=integer(v.revision),ar=integer(v.activityRevision),sr=integer(v.sectionRevision),text=Object.hasOwn(v,'text')?noteText(v.text):existing.text,archived=Object.hasOwn(v,'archived')?flag(v.archived):existing.archived;
 const decision=reviewing?v.decision:null,reviewedRevision=reviewing?revision:null,reviewer=reviewing?actor:null,reviewedAt=reviewing?now:null;
 const result=await db.batch([db.prepare(`UPDATE documentation_notes SET text=?,archived=?,revision=revision+1,updated_at=?,review_decision=?,reviewed_revision=?,reviewer_user_id=?,reviewed_at=? WHERE installation_id=? AND id=? AND revision=? AND ${reviewing?'archived=0 AND ':''}${access} AND ${sectionWrite} AND EXISTS(SELECT 1 FROM hours_activities a WHERE a.installation_id=documentation_notes.installation_id AND a.id=documentation_notes.activity_id AND a.revision=? AND ${eligible})`).bind(text,archived,now,decision,reviewedRevision,reviewer,reviewedAt,installation,id,revision,installation,actor,installation,installation,sr,ar),db.prepare("INSERT INTO documentation_note_revisions(installation_id,note_id,revision,actor_user_id,text,archived,created_at,review_decision,reviewed_revision,reviewer_user_id,reviewed_at) SELECT installation_id,id,revision,?,text,archived,updated_at,review_decision,reviewed_revision,reviewer_user_id,reviewed_at FROM documentation_notes WHERE installation_id=? AND id=? AND changes()=1").bind(actor,installation,id),audit(db,installation,actor,reviewing?'documentation.note.reviewed':'documentation.note.updated',id,now)]);
 if(result[2]?.meta?.changes!==1)fail(409,'Note, activity, section or authority changed; reload');return {status:200,body:{note:noteDto({...existing,text,archived,revision:revision+1,updated_at:now,review_decision:decision,reviewed_revision:reviewedRevision,reviewer_user_id:reviewer,reviewed_at:reviewedAt})}};

}
export function validateDocumentationBackup(tables:Record<string,Row[]>){
 const bad=()=>fail(400,'Invalid Documentation backup');const stamp=(v:unknown)=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}T/.test(v)&&Number.isFinite(Date.parse(v));
 const members=new Set((tables.members??[]).filter(r=>r.installation_id==='primary').map(r=>r.id));
 const users=new Set((tables.users??[]).filter(r=>r.installation_id==='primary').map(r=>r.id)),activities=new Set((tables.hours_activities??[]).filter(r=>r.installation_id==='primary').map(r=>r.id));
 const configs=tables.documentation_sections??[];if(configs.length>1)bad();for(const r of configs){if(r.installation_id!=='primary'||r.version!==1||![0,1].includes(r.notes_enabled)||![0,1].includes(r.summary_enabled)||![0,1].includes(r.files_enabled))bad();integer(r.revision);}
 const provenance=(r:Row,history=false)=>{const user=history?r.actor_user_id:r.author_user_id,member=history?r.actor_member_id:r.author_member_id;if(r.source==='staff'){if(!users.has(user)||member!==null)bad();}else if(!['public','discord'].includes(r.source)||user!==null||!members.has(member)||history&&r.revision!==0)bad();};
 const review=(r:Row,history=false)=>{if(r.review_decision===null){if(r.reviewed_revision!==null||r.reviewer_user_id!==null||r.reviewed_at!==null)bad();}else if(!['reviewed','rejected'].includes(r.review_decision)||r.reviewed_revision!==r.revision-1||r.revision<1||!users.has(r.reviewer_user_id)||r.reviewed_at!==(history?r.created_at:r.updated_at)||!stamp(r.reviewed_at)||r.archived!==0)bad();};
 const notes=new Map<string,Row>();for(const n of tables.documentation_notes??[]){identity(n.id);if(n.installation_id!=='primary'||notes.has(n.id)||!activities.has(n.activity_id)||![0,1].includes(n.archived)||!stamp(n.created_at)||!stamp(n.updated_at)||Date.parse(n.updated_at)<Date.parse(n.created_at))bad();provenance(n);review(n);integer(n.revision);noteText(n.text);notes.set(n.id,n);}
 const histories=new Map<string,Map<number,Row>>();for(const r of tables.documentation_note_revisions??[]){if(r.installation_id!=='primary'||!notes.has(r.note_id)||![0,1].includes(r.archived)||!stamp(r.created_at))bad();provenance(r,true);review(r,true);integer(r.revision);noteText(r.text);const h=histories.get(r.note_id)??new Map();if(h.has(r.revision))bad();h.set(r.revision,r);histories.set(r.note_id,h);}
 for(const [id,n]of notes){const h=histories.get(id);if(!h||h.size!==n.revision+1)bad();let prior=0;for(let i=0;i<=n.revision;i++){const r=h!.get(i);if(!r||Date.parse(r.created_at)<prior)bad();prior=Date.parse(r!.created_at);}const first=h!.get(0)!,last=h!.get(n.revision)!;if(first.actor_member_id!==n.author_member_id||first.source!==n.source||first.review_decision!==null||first.actor_user_id!==n.author_user_id||first.created_at!==n.created_at||first.archived!==0||last.text!==n.text||last.archived!==n.archived||last.created_at!==n.updated_at||['review_decision','reviewed_revision','reviewer_user_id','reviewed_at'].some(k=>last[k]!==n[k]))bad();for(let i=1;i<=n.revision;i++){const r=h!.get(i)!,prior=h!.get(i-1)!;if(r.source!=='staff'||r.review_decision!==null&&(r.actor_user_id!==r.reviewer_user_id||r.text!==prior.text||r.archived!==prior.archived))bad();}}
 const keys=new Set<string>(),receipts=new Set<string>();for(const r of tables.documentation_note_submission_keys??[]){const n=notes.get(r.note_id),key=r.channel+':'+r.key_hash;if(r.installation_id!=='primary'||!n||n.source!==r.channel||!['public','discord'].includes(r.channel)||typeof r.key_hash!=='string'||!/^[a-f0-9]{64}$/.test(r.key_hash)||typeof r.fingerprint!=='string'||!/^[a-f0-9]{64}$/.test(r.fingerprint)||keys.has(key)||receipts.has(r.note_id)||r.created_at!==n.created_at)bad();keys.add(key);receipts.add(r.note_id);}for(const n of notes.values())if(n.source!=='staff'&&!receipts.has(n.id))bad();

}
