import type {Env} from './index.ts';
import {discordReadDeadline} from './discord-platform.ts';
import {encryptIntegration,decryptIntegration} from './integration-crypto.ts';
import {submitMemberDocumentationNote} from './public-documentation.ts';
import {editPrivateInteraction,type PrivateDiscordMessage} from './discord-interaction-reply.ts';
type Interaction={id?:string;application_id?:string;token?:string;type?:number;guild_id?:string;member?:{user?:{id?:string}};data?:{name?:string;custom_id?:string;values?:unknown;options?:unknown;components?:unknown}};
type Row={id:string;guild_id:string;discord_user_id:string;provider_iv:string;revision:number;expires_at:number;confirmation_id:string|null;ciphertext:string;iv:string};
type Choice={id:string;title:string;serviceDate:string;revision:number};
type Draft={step:'activity'|'details'|'review';choices:Choice[];cursor:string;next:string|null;sectionRevision:number;activity?:Choice;first:string;continuation:string;frozen?:{activityId:string;activityRevision:number;sectionRevision:number;text:string;idempotencyKey:string}};
type Context={user:string;guild:string;providerIv:string;interaction:Interaction};
const unavailable='Activity notes are unavailable or this private form expired. Start /activity-note again, or ask Staff to check an uncertain submission before sending another copy.';
const moduleGuard="EXISTS(SELECT 1 FROM platform_module_configuration WHERE installation_id='primary' AND hours_enabled=1 AND documentation_enabled=1) AND COALESCE((SELECT notes_enabled FROM documentation_sections WHERE installation_id='primary'),1)=1";
const providerGuard="EXISTS(SELECT 1 FROM encrypted_integrations i JOIN installations x ON x.id=i.installation_id WHERE i.installation_id='primary' AND i.provider='discord' AND i.iv=? AND i.verified_at IS NOT NULL AND x.discord_enabled=1)";
const selectionGuard="COALESCE((SELECT revision FROM documentation_sections WHERE installation_id='primary'),0)=? AND EXISTS(SELECT 1 FROM hours_activities WHERE installation_id='primary' AND id=? AND revision=? AND archived=0 AND impact_relevant=1)";
const memberGuard="EXISTS(SELECT 1 FROM members WHERE installation_id='primary' AND active=1 AND discord_user_id=?)";
const snow=(value:unknown):value is string=>typeof value==='string'&&/^\d{10,24}$/.test(value);
const safe=(value:string)=>value.replace(/[\x00-\x1f\x7f]/g,' ').replace(/([\\*_`~>|[\]])/g,'\\$1').replaceAll('@','@\u200b').slice(0,100);
function fail():never{throw Error(unavailable);}
const actions=(...components:unknown[])=>({type:1,components});
const custom=(row:Row,action:string)=>`lldn:${row.id}:${row.revision}:${action}`;
const button=(row:Row,label:string,action:string)=>({type:2,style:2,label,custom_id:custom(row,action)});
const privateResponse=(content:string)=>Response.json({type:4,data:{content,flags:64,allowed_mentions:{parse:[]}}});
async function gate(env:Env,context:Context,member=false){if(!await env.DB!.prepare(`SELECT 1 WHERE ${moduleGuard} AND ${providerGuard}${member?' AND '+memberGuard:''}`).bind(context.providerIv,...(member?[context.user]:[])).first())fail();}
async function pack(env:Env,row:Row,draft:Draft){return encryptIntegration({installation:'primary',id:row.id,guild:row.guild_id,user:row.discord_user_id,provider:row.provider_iv,payload:JSON.stringify(draft)},env.INTEGRATION_KEY!);}
async function unpack(env:Env,row:Row):Promise<Draft>{const v=await decryptIntegration(row.ciphertext,row.iv,env.INTEGRATION_KEY!);if(v.installation!=='primary'||v.id!==row.id||v.guild!==row.guild_id||v.user!==row.discord_user_id||v.provider!==row.provider_iv)fail();return JSON.parse(v.payload);}
async function load(env:Env,c:Context,id:string){const row=await env.DB!.prepare("SELECT * FROM discord_documentation_drafts WHERE installation_id='primary' AND id=? AND guild_id=? AND discord_user_id=? AND provider_iv=? AND expires_at>?").bind(id,c.guild,c.user,c.providerIv,Date.now()).first<Row>();if(!row)fail();return row;}
async function choices(env:Env,draft:Draft){const result=await env.DB!.prepare(`SELECT id,title,service_date AS serviceDate,revision,COALESCE((SELECT revision FROM documentation_sections WHERE installation_id='primary'),0) AS sectionRevision FROM hours_activities WHERE installation_id='primary' AND archived=0 AND impact_relevant=1 AND id>? AND ${moduleGuard} ORDER BY id LIMIT 26`).bind(draft.cursor).all<Choice&{sectionRevision:number}>();const rows=result.results??[];draft.choices=rows.slice(0,25).map(({id,title,serviceDate,revision})=>({id,title,serviceDate,revision}));draft.next=rows.length>25?rows[24].id:null;if(rows.length)draft.sectionRevision=rows[0].sectionRevision;}
function render(row:Row,draft:Draft):PrivateDiscordMessage{
 if(row.confirmation_id)return {content:'This submission is unconfirmed. Check its original result; do not submit another copy.',components:[actions(button(row,'Check original result','confirm'))]};
 if(draft.step==='activity'){const components:unknown[]=[];if(draft.choices.length)components.push(actions({type:3,custom_id:custom(row,'pick'),min_values:1,max_values:1,placeholder:'Choose an activity',options:draft.choices.map((choice,index)=>({label:safe(choice.title),description:choice.serviceDate,value:String(index)}))}));components.push(actions(button(row,'First page','first'),...(draft.next?[button(row,'Next page','next')]:[])));return {content:draft.choices.length?'Choose the activity for a private note. This does not record hours.':'No eligible activities. Ask Staff to check the activity catalog.',components};}
 return {content:`${draft.step==='review'?'Review':'Add'} a private note for ${safe(draft.activity!.title)}. ${draft.first.length+draft.continuation.length}/8000 characters. Continuation follows the first field exactly, with no added space or newline. Staff can review the submitted note; this does not publish it or record hours.`,components:[actions(button(row,'Edit note','modal'),...(draft.step==='review'?[button(row,'Submit note','confirm')]:[]))]};
}
function modal(row:Row,draft:Draft){const field=(id:string,label:string,value:string,required:boolean)=>({type:18,label,description:id==='continuation'?'Optional. Appended directly; include any needed space or newline.':'Up to 4000 characters here; use continuation for longer notes.',component:{type:4,custom_id:id,style:2,max_length:4000,required,...(value?{value}:{})}});return Response.json({type:9,data:{custom_id:custom(row,'details'),title:'Private activity note',components:[field('first','Note',draft.first,true),field('continuation','Continuation',draft.continuation,false)]}});}
function values(input:unknown){if(!Array.isArray(input)||input.length!==2)fail();const result:Record<string,string>={};for(const row of input){const field=row?.component;if(row?.type!==18||!field||field.type!==4||!['first','continuation'].includes(field.custom_id)||Object.hasOwn(result,field.custom_id)||typeof field.value!=='string'||field.value.length>4000)fail();result[field.custom_id]=field.value;}const text=result.first+result.continuation;if(!result.first.length||!text.trim()||text.length>8000||/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(text))fail();return {first:result.first,continuation:result.continuation};}
async function update(env:Env,row:Row,draft:Draft){const encrypted=await pack(env,row,draft);const result=await env.DB!.prepare(`UPDATE discord_documentation_drafts SET ciphertext=?,iv=?,revision=revision+1 WHERE installation_id='primary' AND id=? AND revision=? AND confirmation_id IS NULL AND expires_at>? AND ${moduleGuard} AND ${providerGuard} AND ${memberGuard}${draft.activity?' AND '+selectionGuard:''}`).bind(encrypted.ciphertext,encrypted.iv,row.id,row.revision,Date.now(),row.provider_iv,row.discord_user_id,...(draft.activity?[draft.sectionRevision,draft.activity.id,draft.activity.revision]:[])).run();if(result.meta?.changes!==1)fail();row.revision++;}
async function process(env:Env,c:Context):Promise<PrivateDiscordMessage>{await gate(env,c);const db=env.DB!,interaction=c.interaction;await db.prepare("DELETE FROM discord_documentation_drafts WHERE installation_id='primary' AND expires_at<=?").bind(Date.now()).run();
 if(interaction.type===2){if(interaction.data?.options!==undefined&&(!Array.isArray(interaction.data.options)||interaction.data.options.length))fail();await gate(env,c,true);const row:Row={id:crypto.randomUUID(),guild_id:c.guild,discord_user_id:c.user,provider_iv:c.providerIv,revision:0,expires_at:Date.now()+20*60000,confirmation_id:null,ciphertext:'',iv:''};const draft:Draft={step:'activity',choices:[],cursor:'',next:null,sectionRevision:0,first:'',continuation:''};await choices(env,draft);const encrypted=await pack(env,row,draft);const result=await db.prepare(`INSERT INTO discord_documentation_drafts(installation_id,id,guild_id,discord_user_id,provider_iv,expires_at,ciphertext,iv) SELECT 'primary',?,?,?,?,?,?,? WHERE ${moduleGuard} AND ${providerGuard} AND ${memberGuard} AND (SELECT COUNT(*) FROM discord_documentation_drafts WHERE installation_id='primary')<256 AND (SELECT COUNT(*) FROM discord_documentation_drafts WHERE installation_id='primary' AND discord_user_id=?)<4`).bind(row.id,row.guild_id,row.discord_user_id,row.provider_iv,row.expires_at,encrypted.ciphertext,encrypted.iv,c.providerIv,c.user,c.user).run();if(result.meta?.changes!==1)fail();return render(row,draft);}
 const match=/^lldn:([a-f0-9-]{36}):(\d{1,8}):([a-z-]{1,20})$/.exec(interaction.data?.custom_id??'');if(!match)fail();const row=await load(env,c,match[1]),draft=await unpack(env,row),action=match[3];
 if(action==='confirm'&&interaction.type===3&&(draft.step==='review'||row.confirmation_id)){
  if(!row.confirmation_id){if(row.revision!==Number(match[2])||!draft.activity)fail();draft.frozen={activityId:draft.activity.id,activityRevision:draft.activity.revision,sectionRevision:draft.sectionRevision,text:draft.first+draft.continuation,idempotencyKey:interaction.id!};const encrypted=await pack(env,row,draft);await db.prepare(`UPDATE discord_documentation_drafts SET confirmation_id=?,ciphertext=?,iv=?,revision=revision+1 WHERE installation_id='primary' AND id=? AND revision=? AND confirmation_id IS NULL AND expires_at>? AND ${moduleGuard} AND ${providerGuard} AND ${memberGuard} AND ${selectionGuard}`).bind(interaction.id,encrypted.ciphertext,encrypted.iv,row.id,row.revision,Date.now(),c.providerIv,c.user,draft.sectionRevision,draft.activity.id,draft.activity.revision).run();}
  const frozenRow=await load(env,c,row.id),frozen=await unpack(env,frozenRow);if(!frozenRow.confirmation_id||frozen.frozen?.idempotencyKey!==frozenRow.confirmation_id)fail();await gate(env,c);
  // Receipt replay precedes pairing lookup inside the domain service. Never mutate
  // the frozen body or introduce a fresh key when delivery is uncertain.
  try{const result=await submitMemberDocumentationNote(db,'primary',frozen.frozen,{channel:'discord',discordUserId:c.user,expectedDiscordIV:c.providerIv});return {content:`Note received. Reference: ${result.reference}. This acknowledges submission, not staff review or publication.`,components:[]};}catch{return {content:'The note could not be confirmed. Check the original result or ask Staff before sending another copy.',components:[actions(button(frozenRow,'Check original result','confirm'))]};}
 }
 if(row.confirmation_id||row.revision!==Number(match[2]))fail();await gate(env,c,true);
 if((action==='first'||action==='next')&&interaction.type===3){if(draft.step!=='activity'||action==='next'&&!draft.next)fail();draft.cursor=action==='next'?draft.next!:'';await choices(env,draft);}
 else if(action==='pick'&&interaction.type===3){const value=interaction.data?.values;if(draft.step!=='activity'||!Array.isArray(value)||value.length!==1||typeof value[0]!=='string'||!/^\d{1,2}$/.test(value[0])||!draft.choices[Number(value[0])])fail();draft.activity=draft.choices[Number(value[0])];draft.step='details';}
 else if(action==='details'&&interaction.type===5){if(!['details','review'].includes(draft.step))fail();Object.assign(draft,values(interaction.data?.components),{step:'review'});}else fail();await update(env,row,draft);return render(row,draft);
}
export function isDocumentationDiscord(i:Interaction){return i.type===2&&i.data?.name==='activity-note'||[3,5].includes(i.type??0)&&typeof i.data?.custom_id==='string'&&i.data.custom_id.startsWith('lldn:');}
export async function documentationDiscordInteraction(env:Env,interaction:Interaction,config:Record<string,string>,providerIv:string,execution:{waitUntil(p:Promise<unknown>):void}|undefined,receivedAt=Date.now()){
 if(!env.DB||!env.INTEGRATION_KEY||!snow(interaction.id)||interaction.application_id!==config.applicationId||interaction.guild_id!==config.guildId||!snow(interaction.member?.user?.id)||!execution||typeof interaction.token!=='string'||!/^[A-Za-z0-9._-]{1,2048}$/.test(interaction.token)||Date.now()-receivedAt>2500)return privateResponse(unavailable);
 const c:Context={user:interaction.member.user.id,guild:interaction.guild_id!,providerIv,interaction};
 if(interaction.type===3&&interaction.data?.custom_id?.endsWith(':modal')){try{return await discordReadDeadline((async()=>{await gate(env,c,true);const match=/^lldn:([a-f0-9-]{36}):(\d{1,8}):modal$/.exec(interaction.data?.custom_id??'');if(!match)fail();const row=await load(env,c,match[1]),draft=await unpack(env,row);if(row.confirmation_id||row.revision!==Number(match[2])||!['details','review'].includes(draft.step)||Date.now()-receivedAt>2500)fail();if(!draft.activity||!await env.DB!.prepare(`SELECT 1 WHERE ${selectionGuard}`).bind(draft.sectionRevision,draft.activity.id,draft.activity.revision).first())fail();return modal(row,draft);})(),receivedAt+2500);}catch{return privateResponse(unavailable);}}
 const token=interaction.token;execution.waitUntil((async()=>{let message:PrivateDiscordMessage;try{message=await process(env,c);}catch{message={content:unavailable};}try{await editPrivateInteraction(config.applicationId,token,message,receivedAt+14*60000, undefined, env);}catch{/* An explicit old confirmation recovers the frozen receipt. */}})());return Response.json({type:5,data:{flags:64,allowed_mentions:{parse:[]}}});
}
