import { documentationAvailable } from '../../../packages/shared/src/release-capabilities.ts';
import { providerFetch } from './maintenance.ts';
import {sha256} from '@noble/hashes/sha2.js';
import type {Env} from './index.ts';
import {HttpError} from './http-error.ts';
import {googleCapability} from './google-connection.ts';
import {encryptIntegration,decryptIntegration} from './integration-crypto.ts';
import {artifactFileColumns} from './documentation-artifacts.ts';
import {documentationBodyHash as hash} from '@lancerlogin/shared/documentation-proxy';
import {readUploadProxyBody,verifyUploadAssertion,UploadProxyError} from '@lancerlogin/shared/upload-proxy';
import {admitPublicDocumentation} from './public-documentation-admission.ts';
type Row=Record<string,any>;
// Shared bounded original-byte validation transport; copy intake keeps its own durable inventory.
export {bytes as readOriginalBytes,compute as documentCompute,originalMetadata as validatedOriginalMetadata,originalChunk as validatedOriginalChunk};
export type UploadActor={source:'staff';userId:string;expiresAt:number}|{source:'public';memberId:string}|{source:'discord';memberId:string;discordUserId:string;expectedDiscordIV:string};
const enc=new TextEncoder(),chunkSize=262144,maxFile=4194304;
const digest=(s:string)=>hash(enc.encode(s));
const syncDigest=(s:string)=>Array.from(sha256(enc.encode(s)),b=>b.toString(16).padStart(2,'0')).join('');
const id=(v:unknown)=>typeof v==='string'&&/^[A-Za-z0-9_-]{1,128}$/.test(v);
const hex=(v:unknown)=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v);
const integer=(v:unknown)=>Number.isSafeInteger(v)&&Number(v)>=0;
function fail(status=409,message='Upload could not be confirmed; read its current status before continuing'):never{throw new HttpError(status,message);}
const access=`EXISTS(SELECT 1 FROM users u LEFT JOIN platform_module_grants g ON g.installation_id=u.installation_id AND g.user_id=u.id WHERE u.installation_id=o.installation_id AND u.id=o.author_user_id AND u.active=1 AND (u.role='admin' OR g.documentation_manage=1))`;
const staffAccess=`EXISTS(SELECT 1 FROM platform_module_configuration WHERE installation_id='primary' AND hours_enabled=1 AND documentation_enabled=1) AND EXISTS(SELECT 1 FROM users u LEFT JOIN platform_module_grants g ON g.installation_id=u.installation_id AND g.user_id=u.id WHERE u.installation_id='primary' AND u.id=? AND u.active=1 AND (u.role='admin' OR g.documentation_manage=1))`;
const gates=`EXISTS(SELECT 1 FROM platform_module_configuration WHERE installation_id=o.installation_id AND hours_enabled=1 AND documentation_enabled=1)
 AND COALESCE((SELECT files_enabled FROM documentation_sections WHERE installation_id=o.installation_id),1)=1
 AND COALESCE((SELECT revision FROM documentation_sections WHERE installation_id=o.installation_id),0)=o.section_revision
 AND ((o.source='staff' AND ${access}) OR (o.source!='staff' AND EXISTS(SELECT 1 FROM members WHERE installation_id=o.installation_id AND id=o.author_member_id AND active=1)))
 AND (o.source!='discord' OR (EXISTS(SELECT 1 FROM members WHERE installation_id=o.installation_id AND id=o.author_member_id AND discord_user_id=o.discord_user_id) AND EXISTS(SELECT 1 FROM encrypted_integrations WHERE installation_id=o.installation_id AND provider='discord' AND iv=o.discord_iv AND verified_at IS NOT NULL) AND EXISTS(SELECT 1 FROM installations WHERE id=o.installation_id AND discord_enabled=1)))
 AND EXISTS(SELECT 1 FROM google_drive_storage s JOIN google_connections c ON c.installation_id=s.installation_id WHERE s.installation_id=o.installation_id AND s.root_id=o.root_id AND s.revision=o.root_revision AND s.generation=o.connection_generation AND s.verified_iv=o.connection_iv AND c.active_iv=o.connection_iv AND c.grant_error IS NOT 'revoked')
 AND NOT EXISTS(SELECT 1 FROM json_each(o.activities_json) j WHERE NOT EXISTS(SELECT 1 FROM hours_activities WHERE installation_id=o.installation_id AND id=json_extract(j.value,'$.activityId') AND revision=json_extract(j.value,'$.revision') AND archived=0 AND impact_relevant=1))
 AND NOT EXISTS(SELECT 1 FROM json_each(o.initiatives_json) j WHERE NOT EXISTS(SELECT 1 FROM documentation_initiatives WHERE installation_id=o.installation_id AND id=json_extract(j.value,'$.initiativeId') AND revision=json_extract(j.value,'$.revision') AND archived=0))`;
export const uploadColumns={documentation_upload_operations:['installation_id','id','source','author_user_id','author_member_id','request_hash','key_hash','ticket_hash','ticket_expires_ms','title','caption','mime','byte_length','sha256','activities_json','initiatives_json','section_revision','root_id','root_revision','connection_generation','connection_iv','discord_iv','discord_user_id','compute_id','manifest_json','manifest_digest','snapshot_digest','state','next_chunk','validation_outcome','file_id','dispatched','session_ciphertext','session_iv','upload_offset','lease_token','lease_expires_ms','artifact_id','error_code','created_at','updated_at']} as const;
async function bytes(response:Response,max:number,signal?:AbortSignal){const reader=response.body?.getReader();if(!reader)return new Uint8Array();const parts:Uint8Array[]=[];let size=0,timer:ReturnType<typeof setTimeout>|undefined;let rejectAbort:(e:unknown)=>void=()=>{};const abort=()=>{void reader.cancel().catch(()=>{});rejectAbort(new HttpError(503,'Upload response deadline'));};const deadline=new Promise<never>((_,reject)=>{rejectAbort=reject;timer=setTimeout(abort,5000);signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted)abort();});try{for(;;){const value=await Promise.race([reader.read(),deadline]);if(value.done)break;size+=value.value.length;if(size>max)fail(503);parts.push(value.value);}}catch(e){void reader.cancel().catch(()=>{});throw e;}finally{clearTimeout(timer);signal?.removeEventListener('abort',abort);reader.releaseLock();}const result=new Uint8Array(size);let offset=0;for(const part of parts){result.set(part,offset);offset+=part.length;}return result;}
async function json(response:Response,max=16384,signal?:AbortSignal){try{return JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(await bytes(response,max,signal)));}catch{return fail(503);}}
async function compute(env:Env,path:string,method='GET',body?:BodyInit,headers:Record<string,string>={},signal?:AbortSignal){if(!env.DOCUMENT_COMPUTE)fail(503,'File validation is unavailable');const controller=new AbortController(),abort=()=>controller.abort();signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted)controller.abort();const timer=setTimeout(abort,5000);try{const r=await Promise.race([env.DOCUMENT_COMPUTE.fetch(new Request('https://document.internal'+path,{method,body,headers,signal:controller.signal})),new Promise<never>((_,reject)=>{controller.signal.addEventListener('abort',()=>reject(new HttpError(503,'File validation deadline')),{once:true});if(controller.signal.aborted)reject(new HttpError(503,'File validation deadline'));})]);if(!r.ok){void r.body?.cancel().catch(()=>{});fail(r.status===400?400:409,'File validation was not confirmed; inspect this upload');}return r;}finally{clearTimeout(timer);signal?.removeEventListener('abort',abort);}}
async function ticket(env:Env,operation:string){if(!env.SESSION_KEY)fail(503);const key=await crypto.subtle.importKey('raw',enc.encode(env.SESSION_KEY),{name:'HMAC',hash:'SHA-256'},false,['sign']);return Array.from(new Uint8Array(await crypto.subtle.sign('HMAC',key,enc.encode('documentation-upload-ticket-v1:'+operation))),b=>b.toString(16).padStart(2,'0')).join('');}
const ownershipGate=`EXISTS(SELECT 1 FROM platform_module_configuration WHERE installation_id=o.installation_id AND hours_enabled=1 AND documentation_enabled=1) AND EXISTS(SELECT 1 FROM google_drive_storage s JOIN google_connections c ON c.installation_id=s.installation_id WHERE s.installation_id=o.installation_id AND s.root_id=o.root_id AND s.revision=o.root_revision AND s.generation=o.connection_generation AND s.verified_iv=o.connection_iv AND c.active_iv=o.connection_iv AND c.grant_error IS NOT 'revoked')`;
async function current(env:Env,o:Row){const row=await env.DB!.prepare(`SELECT o.id FROM documentation_upload_operations o WHERE o.installation_id='primary' AND o.id=? AND ${o.reconcile_actor?ownershipGate+' AND '+staffAccess:gates} AND (? IS NULL OR (o.lease_token=? AND o.lease_expires_ms>?))`).bind(o.id,...(o.reconcile_actor?[o.reconcile_actor]:[]),o.lease_token??null,o.lease_token??null,Date.now()).first();if(!row)fail(409,'Upload authority or destination changed; staff must reconcile this upload');}
async function provider(env:Env,o:Row,url:string,init:RequestInit={}){await current(env,o);const capability=await googleCapability(env,'drive');if(capability.generation!==o.connection_generation||capability.signature!==o.connection_iv)fail();const token=await capability.accessToken();await current(env,o);const headers=new Headers(init.headers);headers.set('authorization','Bearer '+token);return providerFetch(env)(url,{...init,headers,redirect:'manual',signal:AbortSignal.timeout(10000)});}
async function privateRoot(env:Env,o:Row){const r=await provider(env,o,'https://www.googleapis.com/drive/v3/files/'+o.root_id+'?fields=id,mimeType,trashed,ownedByMe,driveId,capabilities(canAddChildren)');if(!r.ok)fail();const f=await json(r);if(f.id!==o.root_id||f.mimeType!=='application/vnd.google-apps.folder'||f.trashed!==false||f.ownedByMe!==true||f.driveId||f.capabilities?.canAddChildren!==true)fail();await permissions(env,o,o.root_id);}
async function permissions(env:Env,o:Row,file:string){const r=await provider(env,o,'https://www.googleapis.com/drive/v3/files/'+file+'/permissions?fields=permissions(type,role),nextPageToken&pageSize=100');if(!r.ok)fail();const p=await json(r);if(p.nextPageToken||!Array.isArray(p.permissions)||p.permissions.length!==1||p.permissions[0].type!=='user'||p.permissions[0].role!=='owner')fail(409,'Private owner-only storage could not be verified');}
const status=(o:Row)=>({reference:o.id,state:o.state,nextChunk:o.next_chunk,chunkSize,maxBytes:maxFile,expiresAt:o.ticket_expires_ms,saved:o.state==='saved',...(o.error_code?{error:o.error_code}:{})});
function links(v:unknown,key:string){if(!Array.isArray(v)||v.length>100)fail(400);const result=v.map(r=>{if(!r||Object.keys(r).sort().join(',')!==[key,'revision'].sort().join(',')||!id(r[key])||!integer(r.revision))fail(400);return r;});if(new Set(result.map(r=>r[key])).size!==result.length)fail(400);return result;}
export async function admitUpload(env:Env,input:unknown,actor:UploadActor,now=Date.now()){
 if(!documentationAvailable)throw new HttpError(404,'Activity Documentation is unavailable in this release');
 if(!env.DB||!env.DOCUMENT_COMPUTE||!env.INTEGRATION_KEY)fail(503,'Private file storage is unavailable');if(!input||typeof input!=='object'||Array.isArray(input))fail(400);const v=input as Row;
 if(Object.keys(v).some(k=>!['title','caption','mime','byteLength','sha256','activities','initiatives','sectionRevision','idempotencyKey'].includes(k))||typeof v.title!=='string'||!v.title.trim()||v.title.length>200||typeof(v.caption??'')!=='string'||(v.caption??'').length>4000||/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(v.title+(v.caption??''))||typeof v.mime!=='string'||!/^[-a-z0-9.+]+\/[-a-z0-9.+]+$/.test(v.mime)||v.mime.length>100||!integer(v.byteLength)||v.byteLength<1||v.byteLength>maxFile||!hex(v.sha256)||!integer(v.sectionRevision)||!id(v.idempotencyKey)||v.idempotencyKey.length<16)fail(400,'Provide one file up to 4 MiB and valid metadata');
 const activities=links(v.activities??[],'activityId'),initiatives=links(v.initiatives??[],'initiativeId');if(activities.length+initiatives.length>100||actor.source!=='staff'&&(activities.length!==1||initiatives.length))fail(400);
 const keyHash=await digest(v.idempotencyKey),requestHash=await digest(JSON.stringify([actor.source,actor.source==='staff'?actor.userId:actor.memberId,v]));
 const existing=await env.DB.prepare("SELECT * FROM documentation_upload_operations WHERE installation_id='primary' AND source=? AND key_hash=?").bind(actor.source,keyHash).first<Row>();
 if(existing){if(existing.request_hash!==requestHash)fail();await current(env,existing);if(existing.ticket_expires_ms<=now)fail(409,'Upload ticket expired; ask staff to reconcile the existing upload');return {...status(existing),ticket:await ticket(env,existing.id)};}
 const cap=await googleCapability(env,'drive'),root=await env.DB.prepare("SELECT * FROM google_drive_storage WHERE installation_id='primary' AND verified_iv=? AND generation=?").bind(cap.signature,cap.generation).first<Row>();if(!root)fail(409,'Shared private file storage requires verification');
 const operation=crypto.randomUUID(),computeId=now+'-'+crypto.randomUUID(),snapshot=await digest(JSON.stringify([operation,requestHash,root.root_id,cap.generation]));
 const manifest={version:1,id:computeId,operation:'validate-artifact',policyVersion:'document-input-v1',snapshotDigest:snapshot,items:[{id:'original',revision:'1',caption:'',url:'https://drive.google.com/',type:v.mime,byteLength:v.byteLength,sha256:v.sha256,...(v.mime==='application/pdf'?{selectedPages:[1]}:{})}]};
 const row:Row={installation_id:'primary',id:operation,source:actor.source,author_user_id:actor.source==='staff'?actor.userId:null,author_member_id:actor.source==='staff'?null:actor.memberId,request_hash:requestHash,key_hash:keyHash,ticket_hash:await digest(await ticket(env,operation)),ticket_expires_ms:Math.min(now+1800000,actor.source==='staff'?actor.expiresAt:now+1800000),title:v.title,caption:v.caption??'',mime:v.mime,byte_length:v.byteLength,sha256:v.sha256,activities_json:JSON.stringify(activities),initiatives_json:JSON.stringify(initiatives),section_revision:v.sectionRevision,root_id:root.root_id,root_revision:root.revision,connection_generation:cap.generation,connection_iv:cap.signature,discord_iv:actor.source==='discord'?actor.expectedDiscordIV:null,discord_user_id:actor.source==='discord'?actor.discordUserId:null,compute_id:computeId,manifest_json:JSON.stringify(manifest),manifest_digest:null,snapshot_digest:snapshot,state:'uploading',next_chunk:0,validation_outcome:null,file_id:null,dispatched:0,session_ciphertext:null,session_iv:null,upload_offset:0,lease_token:null,lease_expires_ms:0,artifact_id:null,error_code:null,created_at:new Date(now).toISOString(),updated_at:new Date(now).toISOString()};
 const cols=uploadColumns.documentation_upload_operations;
 // Insert is provisional inside this atomic batch; failing the exact current fence removes it before acknowledgement.
 await env.DB.batch([env.DB.prepare(`INSERT INTO documentation_upload_operations(${cols.join(',')}) SELECT ${cols.map(()=>'?').join(',')} WHERE (SELECT COUNT(*) FROM documentation_upload_operations WHERE installation_id='primary' AND created_at>=?)<500 AND (SELECT COUNT(*) FROM documentation_upload_operations WHERE installation_id='primary' AND source=? AND COALESCE(author_user_id,author_member_id)=? AND created_at>=?)<20`).bind(...cols.map(k=>row[k]),new Date(now-86400000).toISOString(),actor.source,actor.source==='staff'?actor.userId:actor.memberId,new Date(now-86400000).toISOString()),env.DB.prepare(`DELETE FROM documentation_upload_operations AS o WHERE id=? AND NOT (${gates})`).bind(operation)]);
 const admitted=await env.DB.prepare("SELECT * FROM documentation_upload_operations WHERE installation_id='primary' AND id=?").bind(operation).first<Row>();if(!admitted)fail(409,'Upload was not admitted; check current activity, file settings and storage');return {...status(admitted),ticket:await ticket(env,operation)};
}

const identity=(o:Row)=>({'x-document-manifest-sha256':o.manifest_digest,'x-document-snapshot-sha256':o.snapshot_digest,'x-document-item-sha256':o.sha256});
async function originalMetadata(env:Env,o:Row,signal?:AbortSignal){const m=await json(await compute(env,'/jobs/'+o.compute_id+'/items/0/original','GET',undefined,identity(o),signal),16384,signal);if(m.jobId!==o.compute_id||m.id!=='original'||m.revision!=='1'||m.itemIndex!==0||m.type!==o.mime||m.byteLength!==o.byte_length||m.sha256!==o.sha256||m.manifestDigest!==o.manifest_digest||m.snapshotDigest!==o.snapshot_digest||m.policyVersion!=='document-input-v1'||m.chunkSize!==chunkSize||m.chunkCount!==Math.ceil(o.byte_length/chunkSize)||!Array.isArray(m.chunkSha256)||m.chunkSha256.length!==m.chunkCount||!m.chunkSha256.every(hex)||!['embedded','linked-only'].includes(m.outcome)||!integer(m.expiresAt)||m.expiresAt<=Date.now())fail(409,'Original validation commitments unavailable');return m;}
async function originalChunk(env:Env,o:Row,m:Row,n:number,signal?:AbortSignal){const r=await compute(env,'/jobs/'+o.compute_id+'/items/0/original/chunks/'+n,'GET',undefined,identity(o),signal),length=Math.min(chunkSize,o.byte_length-n*chunkSize);
 const expected={'content-type':'application/octet-stream','content-length':String(length),'x-document-item-index':'0','x-document-chunk-index':String(n),'x-document-byte-offset':String(n*chunkSize),'x-document-sha256':o.sha256,'x-document-chunk-sha256':m.chunkSha256[n],...identity(o)};
 delete (expected as Row)['x-document-item-sha256'];for(const [k,v] of Object.entries(expected))if(r.headers.get(k)!==v)fail();const b=await bytes(r,chunkSize,signal);if(b.length!==length||await hash(b)!==m.chunkSha256[n])fail();return b;}
export function acknowledgedOffset(r:Response,total:number){const range=r.headers.get('range');if(range===null)return 0;const m=/^bytes=0-([0-9]+)$/.exec(range);if(!m)fail();const n=Number(m[1])+1;if(!integer(n)||n>total)fail();return n;}
function sessionUrl(url:string){let u:URL;try{u=new URL(url);}catch{return fail();}if(u.protocol!=='https:'||u.hostname!=='www.googleapis.com'||u.username||u.password||u.port||u.hash||!/^\/upload\/drive\/v3\/files(?:\/[A-Za-z0-9_-]+)?$/.test(u.pathname)||u.searchParams.get('uploadType')!=='resumable')fail();return u.href;}
async function saveState(env:Env,o:Row,fields:Row){const keys=Object.keys(fields);const r=await env.DB!.batch([env.DB!.prepare(`UPDATE documentation_upload_operations SET ${keys.map(k=>k+'=?').join(',')},updated_at=? WHERE installation_id='primary' AND id=? AND lease_token=? AND lease_expires_ms>?`).bind(...keys.map(k=>fields[k]),new Date().toISOString(),o.id,o.lease_token,Date.now()),env.DB!.prepare('SELECT changes() AS n')]);if((r[1].results?.[0] as Row)?.n!==1)fail();Object.assign(o,fields);}
async function ownedFile(env:Env,o:Row){const r=await provider(env,o,'https://www.googleapis.com/drive/v3/files/'+o.file_id+'?fields=id,mimeType,size,sha256Checksum,trashed,ownedByMe,driveId,parents,appProperties');if(r.status===404){void r.body?.cancel().catch(()=>{});return false;}if(!r.ok)fail();const f=await json(r);if(f.id!==o.file_id||f.mimeType!==o.mime||String(f.size)!==String(o.byte_length)||f.sha256Checksum!==undefined&&f.sha256Checksum!==o.sha256||f.trashed!==false||f.ownedByMe!==true||f.driveId||!Array.isArray(f.parents)||f.parents.length!==1||f.parents[0]!==o.root_id||f.appProperties?.lancerloginUpload!==o.id)fail(409,'Stored original identity could not be verified');await permissions(env,o,o.file_id);if(f.sha256Checksum===undefined){const media=await provider(env,o,'https://www.googleapis.com/drive/v3/files/'+o.file_id+'?alt=media');if(!media.ok)fail();const original=await bytes(media,o.byte_length);if(original.length!==o.byte_length||await hash(original)!==o.sha256)fail(409,'Original file bytes do not match the submission');await permissions(env,o,o.file_id);}return true;}
async function commitArtifact(env:Env,o:Row){await current(env,o);const db=env.DB!,url='https://drive.google.com/file/d/'+o.file_id+'/view',now=new Date().toISOString(),artifact=o.id,audit=crypto.randomUUID();
 const file=["'file'",'o.file_id','o.root_id','o.connection_generation','o.sha256','o.byte_length','o.mime','o.validation_outcome'];
 const admitted="EXISTS(SELECT 1 FROM audit_log WHERE installation_id='primary' AND id=?)";
 const statements=[db.prepare(`INSERT INTO documentation_artifacts(installation_id,id,title,caption,url,original_url,author_user_id,author_member_id,source,created_at,updated_at,${artifactFileColumns.join(',')}) SELECT o.installation_id,o.id,o.title,o.caption,?,?,o.author_user_id,o.author_member_id,o.source,?,?,${file.join(',')} FROM documentation_upload_operations o WHERE o.installation_id='primary' AND o.id=? AND o.lease_token=? AND o.lease_expires_ms>? AND o.state IN ('preserving','reconciling') AND ${gates}`).bind(url,url,now,now,o.id,o.lease_token,Date.now()),db.prepare("INSERT INTO audit_log(id,installation_id,action,target_type,target_id,created_at) SELECT ?,'primary','documentation.file.preserved','documentation_artifact',?,? WHERE changes()=1").bind(audit,artifact,now),db.prepare(`INSERT INTO documentation_artifact_revisions(installation_id,artifact_id,revision,actor_user_id,actor_member_id,title,caption,url,original_url,archived,created_at,${artifactFileColumns.join(',')}) SELECT installation_id,id,0,author_user_id,author_member_id,title,caption,url,original_url,0,created_at,${artifactFileColumns.join(',')} FROM documentation_artifacts WHERE installation_id='primary' AND id=? AND ${admitted}`).bind(artifact,audit)];
 for(const [kind,key] of [['activities','activity'],['initiatives','initiative']]){
 statements.push(db.prepare(`INSERT INTO documentation_artifact_${kind}(installation_id,artifact_id,${key}_id) SELECT 'primary',?,json_extract(value,'$.${key}Id') FROM json_each(?) WHERE ${admitted}`).bind(artifact,o[kind+'_json'],audit),db.prepare(`INSERT INTO documentation_artifact_revision_${kind}(installation_id,artifact_id,revision,${key}_id) SELECT installation_id,artifact_id,0,${key}_id FROM documentation_artifact_${kind} WHERE installation_id='primary' AND artifact_id=? AND ${admitted}`).bind(artifact,audit));}
 statements.push(db.prepare(`UPDATE documentation_upload_operations SET state='saved',artifact_id=?,session_ciphertext=NULL,session_iv=NULL,error_code=NULL,updated_at=? WHERE installation_id='primary' AND id=? AND lease_token=? AND ${admitted}`).bind(artifact,now,o.id,o.lease_token,audit));
 const result=await db.batch(statements);if(result[1].meta?.changes!==1)fail();o.state='saved';o.artifact_id=artifact;
}
/** One serialized bounded phase; caller retries only by re-reading this exact operation. */
export async function advanceUpload(env:Env,o:Row,action:string,body?:Uint8Array){
 if(!documentationAvailable)throw new HttpError(404,'Activity Documentation is unavailable in this release');
 const now=Date.now(),lease=crypto.randomUUID(),reconciler=o.reconcile_actor;await current(env,o);const claimed=await env.DB!.batch([env.DB!.prepare(`UPDATE documentation_upload_operations AS o SET lease_token=?,lease_expires_ms=? WHERE installation_id='primary' AND id=? AND lease_expires_ms<=? AND ${reconciler?ownershipGate+' AND '+staffAccess:gates}`).bind(lease,now+60000,o.id,now,...(reconciler?[reconciler]:[])),env.DB!.prepare('SELECT changes() AS n')]);if((claimed[1].results?.[0] as Row)?.n!==1)fail(409,'Upload is already advancing; read its status');
 o=(await env.DB!.prepare("SELECT * FROM documentation_upload_operations WHERE installation_id='primary' AND id=? AND lease_token=?").bind(o.id,lease).first<Row>())!;o.reconcile_actor=reconciler;
 try{
  if(o.state==='saved')return status(o);
  if(reconciler&&o.dispatched){await privateRoot(env,o);const owned=await ownedFile(env,o);const eligible=await env.DB!.prepare(`SELECT 1 FROM documentation_upload_operations o WHERE id=? AND ${gates}`).bind(o.id).first();if(owned&&eligible){await commitArtifact(env,o);return status(o);}if(!eligible||!o.session_ciphertext){await saveState(env,o,{state:'reconciling',error_code:owned?'OWNERSHIP_VERIFIED_ELIGIBILITY_REQUIRED':'REMOTE_RESULT_UNKNOWN'});return status(o);}}
  if(['failed','expired'].includes(o.state))fail(409,'This upload cannot continue; start a new submission explicitly');
  if(!o.manifest_digest){const r=await json(await compute(env,'/jobs','POST',o.manifest_json,{'content-type':'application/json'}));if(r.id!==o.compute_id||!hex(r.manifestDigest))fail();await saveState(env,o,{manifest_digest:r.manifestDigest});}
  if(action.startsWith('chunks/')){const n=Number(action.slice(7)),expected=Math.min(chunkSize,o.byte_length-n*chunkSize);if(o.state!=='uploading'||!integer(n)||String(n)!==action.slice(7)||n>o.next_chunk||n>=Math.ceil(o.byte_length/chunkSize)||body?.length!==expected)fail(400,'Send the next exact bounded file chunk');await current(env,o);await compute(env,'/jobs/'+o.compute_id+'/items/0/chunks/'+n,'PUT',body as BodyInit,{'content-type':'application/octet-stream'});await saveState(env,o,{next_chunk:Math.max(o.next_chunk,n+1)});return status(o);}
  if(action==='seal'){if(o.state!=='uploading'){if(['validating','ready','preserving','reconciling'].includes(o.state))return status(o);fail();}if(o.next_chunk!==Math.ceil(o.byte_length/chunkSize))fail(409,'Complete all file chunks first');await compute(env,'/jobs/'+o.compute_id+'/seal','POST');await saveState(env,o,{state:'validating'});return status(o);}
  if(action!=='advance'&&action!=='reconcile')fail(405);
  if(o.state==='uploading')return status(o);
  if(o.state==='validating'){const state=await json(await compute(env,'/jobs/'+o.compute_id));if(state.id!==o.compute_id||state.manifestDigest!==o.manifest_digest)fail();if(state.state==='failed'){await saveState(env,o,{state:'failed',error_code:'INPUT_REJECTED'});return status(o);}if(state.state!=='complete')return status(o);
   const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);try{const m=await originalMetadata(env,o,controller.signal),whole=new Uint8Array(o.byte_length);for(let n=0;n<m.chunkCount;n+=4){const group=await Promise.all(Array.from({length:Math.min(4,m.chunkCount-n)},(_,i)=>originalChunk(env,o,m,n+i,controller.signal)));group.forEach((b,i)=>whole.set(b,(n+i)*chunkSize));}if(controller.signal.aborted||await hash(whole)!==o.sha256)fail();await current(env,o);await saveState(env,o,{state:'ready',validation_outcome:m.outcome});}finally{clearTimeout(timer);controller.abort();}return status(o);}
  await privateRoot(env,o);
  if(o.state==='ready'){
   if(!o.file_id){const r=await provider(env,o,'https://www.googleapis.com/drive/v3/files/generateIds?count=1&space=drive&type=files');if(!r.ok)fail();const ids=await json(r);if(!Array.isArray(ids.ids)||ids.ids.length!==1||!id(ids.ids[0]))fail();await saveState(env,o,{file_id:ids.ids[0]});}
   // Durable dispatch is written before the first possible external file effect.
   await current(env,o);await saveState(env,o,{state:'preserving',dispatched:1});
   const r=await provider(env,o,'https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable',{method:'POST',headers:{'content-type':'application/json','x-upload-content-type':o.mime,'x-upload-content-length':String(o.byte_length)},body:JSON.stringify({id:o.file_id,name:'Evidence '+o.id,mimeType:o.mime,parents:[o.root_id],appProperties:{lancerloginUpload:o.id}})});
   if(!r.ok)fail();const location=sessionUrl(r.headers.get('location')??'');void r.body?.cancel().catch(()=>{});const encrypted=await encryptIntegration({url:location},env.INTEGRATION_KEY!);await saveState(env,o,{session_ciphertext:encrypted.ciphertext,session_iv:encrypted.iv});return status(o);
  }
  if(await ownedFile(env,o)){await commitArtifact(env,o);return status(o);}
  if(!o.session_ciphertext){await saveState(env,o,{state:'reconciling',error_code:'REMOTE_RESULT_UNKNOWN'});return status(o);}
  const session=await decryptIntegration(o.session_ciphertext,o.session_iv,env.INTEGRATION_KEY!),url=sessionUrl(session.url);
  const probe=await provider(env,o,url,{method:'PUT',headers:{'content-length':'0','content-range':'bytes */'+o.byte_length}});
  if(probe.status===200||probe.status===201){void probe.body?.cancel().catch(()=>{});if(!await ownedFile(env,o))fail();await commitArtifact(env,o);return status(o);}
  if(probe.status!==308){void probe.body?.cancel().catch(()=>{});await saveState(env,o,{state:'reconciling',error_code:'REMOTE_RESULT_UNKNOWN'});return status(o);}
  const range=probe.headers.get('range'),match=range===null?null:/^bytes=0-([0-9]+)$/.exec(range);void probe.body?.cancel().catch(()=>{});if(range!==null&&!match)fail();const offset=match?Number(match[1])+1:0;if(!integer(offset)||offset<o.upload_offset||offset>=o.byte_length)fail();
  const m=await originalMetadata(env,o),part=(await originalChunk(env,o,m,Math.floor(offset/chunkSize))).slice(offset%chunkSize);
  const r=await provider(env,o,url,{method:'PUT',headers:{'content-type':o.mime,'content-length':String(part.length),'content-range':`bytes ${offset}-${offset+part.length-1}/${o.byte_length}`},body:part as BodyInit});
  if(![200,201,308].includes(r.status)){void r.body?.cancel().catch(()=>{});fail();}const acknowledged=r.status===308?acknowledgedOffset(r,o.byte_length):o.byte_length;void r.body?.cancel().catch(()=>{});if(acknowledged<offset||acknowledged>offset+part.length)fail();await saveState(env,o,{upload_offset:acknowledged,state:'preserving',error_code:null});return status(o);
 }catch(e){if(o.dispatched&&o.state!=='saved')await saveState(env,o,{state:'reconciling',error_code:'REMOTE_RESULT_UNKNOWN'}).catch(()=>{});throw e;}finally{await env.DB!.prepare("UPDATE documentation_upload_operations SET lease_token=NULL,lease_expires_ms=0 WHERE installation_id='primary' AND id=? AND lease_token=?").bind(o.id,lease).run();}
}

export async function uploadRoute(request:Request,env:Env,staff?:{userId:string;expiresAt:number}){try{return await handleUploadRoute(request,env,staff);}catch(e){if(e instanceof UploadProxyError)throw new HttpError(e.status,e.message);throw e;}}
async function handleUploadRoute(request:Request,env:Env,staff?:{userId:string;expiresAt:number}){
 if(!env.DB||!env.SESSION_KEY)fail(503);const url=new URL(request.url),publicRoute=!staff,base=publicRoute?'/public/documentation/uploads':'/admin/documentation/uploads',path=url.pathname.slice(base.length);
 let body:Uint8Array=new Uint8Array();
 if(publicRoute){if(request.method!=='GET'&&request.headers.get('origin')!==env.ALLOWED_ORIGIN)fail(403,'Uploads require the configured form origin');body=await readUploadProxyBody(request);const source=await verifyUploadAssertion(request,env.SESSION_KEY,'primary',env.ALLOWED_ORIGIN,body);await admitPublicDocumentation(env.DB,'primary',env.SESSION_KEY,request.method==='GET'?'read':'mutation',Date.now(),source);}
 else {if(staff.expiresAt<=Date.now()||!await env.DB.prepare('SELECT 1 WHERE '+staffAccess).bind(staff.userId).first())fail(403);if(request.method!=='GET')body=await readUploadProxyBody(request);}
 const reply=(value:unknown,statusCode=200)=>Response.json(value,{status:statusCode,headers:{'cache-control':'no-store'}});
 if(publicRoute&&(path==='/context'||path==='/activities')){
  if(request.method!=='GET')fail(405);const keys:string[]=[];url.searchParams.forEach((_,key)=>keys.push(key));if(new Set(keys).size!==keys.length||keys.some(k=>!(path==='/activities'?['after','limit']:[]).includes(k)))fail(400,'Invalid Files parameters');
  const available="EXISTS(SELECT 1 FROM platform_module_configuration WHERE installation_id='primary' AND hours_enabled=1 AND documentation_enabled=1) AND COALESCE((SELECT files_enabled FROM documentation_sections WHERE installation_id='primary'),1)=1";
  if(path==='/context'){const row=await env.DB.prepare(`SELECT COALESCE((SELECT revision FROM documentation_sections WHERE installation_id='primary'),0) sectionRevision WHERE ${available}`).first<Row>();return reply(row?{available:true,sectionRevision:row.sectionRevision}:{available:false});}
  const limit=Number(url.searchParams.get('limit')??25),after=url.searchParams.get('after')??'';if(!Number.isInteger(limit)||limit<1||limit>50||after&&!id(after))fail(400,'Invalid Files page');
  const row=await env.DB.prepare(`SELECT COALESCE((SELECT revision FROM documentation_sections WHERE installation_id='primary'),0) sectionRevision,(SELECT json_group_array(json_object('id',id,'title',title,'serviceDate',service_date,'mode',mode,'revision',revision)) FROM (SELECT id,title,service_date,mode,revision FROM hours_activities WHERE installation_id='primary' AND archived=0 AND impact_relevant=1 AND id>? ORDER BY id LIMIT ?)) items WHERE ${available}`).bind(after,limit+1).first<Row>();if(!row)fail(403,'Files are unavailable');const items=JSON.parse(row.items);return reply({activities:items.slice(0,limit),next:items.length>limit?items[limit-1].id:null,sectionRevision:row.sectionRevision});
 }
 if(!path&&request.method==='GET'&&staff){const after=url.searchParams.get('after')??'',limit=Number(url.searchParams.get('limit')??25);if(Array.from(url.searchParams.toString().split('&')).filter(Boolean).some(k=>!['after','limit'].includes(k.split('=')[0]))||after&&!id(after)||!Number.isInteger(limit)||limit<1||limit>50)fail(400);const rows=(await env.DB.prepare(`SELECT o.* FROM documentation_upload_operations o WHERE o.installation_id='primary' AND o.id>? AND ${staffAccess} ORDER BY o.id LIMIT ?`).bind(after,staff.userId,limit+1).all<Row>()).results??[];return reply({operations:rows.slice(0,limit).map(o=>({...status(o),title:o.title,source:o.source,artifactId:o.artifact_id,requiresReconciliation:o.dispatched&&o.state!=='saved'})),next:rows.length>limit?rows[limit-1].id:null});}
 if(url.search)fail(400);
 if(!path&&request.method==='POST'){let input:Row;try{input=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(body));}catch{return fail(400);}let actor:UploadActor;
  if(staff)actor={source:'staff',...staff};else{if(!input||typeof input.memberId!=='string'||!input.memberId||input.memberId.length>128)fail(409);const member=await env.DB.prepare("SELECT id FROM members WHERE installation_id='primary' AND external_id=? AND active=1").bind(input.memberId).first<Row>();if(!member)fail(409,'Upload was not admitted; check the current form');actor={source:'public',memberId:member.id};delete input.memberId;}
  return reply(await admitUpload(env,input,actor),202);
 }
 const match=/^\/([A-Za-z0-9_-]{1,128})(?:\/(chunks\/(?:0|[1-9][0-9]*)|seal|advance|reconcile))?$/.exec(path);if(!match)fail(404);const o=await env.DB.prepare("SELECT * FROM documentation_upload_operations WHERE installation_id='primary' AND id=?").bind(match[1]).first<Row>();if(!o)fail(404);
 if(!staff){const presented=request.headers.get('x-lancerlogin-upload-ticket');if(!presented||presented.length!==64||o.ticket_expires_ms<=Date.now()||await digest(presented)!==o.ticket_hash)fail(403,'Upload ticket unavailable or expired');}
 if(staff&&match[2]==='reconcile'&&request.method==='POST'){const cap=await googleCapability(env,'drive');if(cap.generation!==o.connection_generation)fail(409,'Restore the original organizational connection before reconciliation');const root=await env.DB.prepare("SELECT * FROM google_drive_storage WHERE installation_id='primary' AND root_id=? AND generation=? AND verified_iv=?").bind(o.root_id,o.connection_generation,cap.signature).first<Row>();if(!root)fail(409,'Verify the original private root before reconciliation');await env.DB.prepare(`UPDATE documentation_upload_operations SET connection_iv=?,root_revision=? WHERE installation_id='primary' AND id=? AND lease_expires_ms<=? AND ${staffAccess} AND EXISTS(SELECT 1 FROM google_connections WHERE installation_id='primary' AND active_iv=?) AND EXISTS(SELECT 1 FROM google_drive_storage WHERE installation_id='primary' AND root_id=? AND revision=? AND verified_iv=?)`).bind(cap.signature,root.revision,o.id,Date.now(),staff.userId,cap.signature,o.root_id,root.revision,cap.signature).run();o.connection_iv=cap.signature;o.root_revision=root.revision;o.reconcile_actor=staff.userId;}
 await current(env,o);
 if(!match[2]&&request.method==='GET')return reply(status(o));const action=match[2];if(!action||request.method!==(action.startsWith('chunks/')?'PUT':'POST')||action==='reconcile'&&!staff)fail(405);
 if(request.method==='POST'&&body.length&&new TextDecoder().decode(body)!=='{}')fail(400,'This operation takes no new metadata');return reply(await advanceUpload(env,o,action,body),202);
}
export function prepareUploadRestore(tables:Record<string,Row[]>,restoring=true){
 const bad=()=>fail(400,'Invalid upload inventory backup'),artifacts=new Map((tables.documentation_artifacts??[]).map(r=>[r.id,r])),users=new Set((tables.users??[]).map(r=>r.id)),members=new Set((tables.members??[]).map(r=>r.id)),seen=new Set();
 for(const o of tables.documentation_upload_operations??[]){if(o.installation_id!=='primary'||!id(o.id)||seen.has(o.id)||!hex(o.sha256)||!hex(o.request_hash)||!hex(o.key_hash)||!hex(o.snapshot_digest)||!integer(o.byte_length)||o.byte_length<1||o.byte_length>maxFile||!['uploading','validating','ready','preserving','reconciling','saved','failed','expired'].includes(o.state)||!['staff','public','discord'].includes(o.source)||!(o.source==='staff'?users.has(o.author_user_id)&&o.author_member_id===null:members.has(o.author_member_id)&&o.author_user_id===null)||!id(o.root_id)||typeof o.connection_generation!=='string'||typeof o.connection_iv!=='string'||!integer(o.ticket_expires_ms)||!integer(o.next_chunk)||o.next_chunk>Math.ceil(o.byte_length/chunkSize)||!integer(o.upload_offset)||o.upload_offset>o.byte_length||![0,1].includes(o.dispatched)||o.dispatched&&!id(o.file_id)||o.state==='saved'&&!artifacts.has(o.artifact_id))bad();if(Object.keys(o).sort().join(',')!==[...uploadColumns.documentation_upload_operations].sort().join(',')||typeof o.title!=='string'||!o.title.trim()||o.title.length>200||typeof o.caption!=='string'||o.caption.length>4000||typeof o.mime!=='string'||!/^[-a-z0-9.+]+\/[-a-z0-9.+]+$/.test(o.mime)||!integer(o.section_revision)||!integer(o.root_revision)||!integer(o.lease_expires_ms)||typeof o.created_at!=='string'||!Number.isFinite(Date.parse(o.created_at))||typeof o.updated_at!=='string'||!Number.isFinite(Date.parse(o.updated_at))||Date.parse(o.updated_at)<Date.parse(o.created_at)||o.manifest_digest!==null&&!hex(o.manifest_digest)||o.file_id!==null&&!id(o.file_id)||(o.session_ciphertext===null)!==(o.session_iv===null)||o.source!=='discord'&&(o.discord_iv!==null||o.discord_user_id!==null))bad();seen.add(o.id);
  let a,i,m;try{a=links(JSON.parse(o.activities_json),'activityId');i=links(JSON.parse(o.initiatives_json),'initiativeId');m=JSON.parse(o.manifest_json);}catch{return bad();}if(o.source!=='staff'&&(a.length!==1||i.length)||o.snapshot_digest!==syncDigest(JSON.stringify([o.id,o.request_hash,o.root_id,o.connection_generation]))||o.manifest_digest!==null&&o.manifest_digest!==syncDigest(o.manifest_json)||m.version!==1||m.operation!=='validate-artifact'||m.policyVersion!=='document-input-v1'||!/^\d{13}-[a-f0-9-]{36}$/.test(o.compute_id)||m.id!==o.compute_id||m.snapshotDigest!==o.snapshot_digest||m.items?.length!==1||m.items[0].sha256!==o.sha256||m.items[0].byteLength!==o.byte_length||m.items[0].type!==o.mime||m.items[0].id!=='original'||m.items[0].revision!=='1'||m.items[0].caption!==''||m.items[0].url!=='https://drive.google.com/')bad();
  for(const x of a)if(!(tables.hours_activities??[]).some(r=>r.installation_id==='primary'&&r.id===x.activityId))bad();for(const x of i)if(!(tables.documentation_initiatives??[]).some(r=>r.installation_id==='primary'&&r.id===x.initiativeId))bad();
  if(o.state==='saved'){const f=artifacts.get(o.artifact_id)!;if(f.kind!=='file'||f.file_id!==o.file_id||f.file_root_id!==o.root_id||f.file_generation!==o.connection_generation||f.file_sha256!==o.sha256||f.file_size!==o.byte_length||f.file_mime!==o.mime||f.validation_outcome!==o.validation_outcome||f.source!==o.source||f.url!=='https://drive.google.com/file/d/'+o.file_id+'/view'||f.original_url!==f.url||f.author_user_id!==o.author_user_id||f.author_member_id!==o.author_member_id)bad();}
  if(restoring){o.ticket_hash=null;o.session_ciphertext=null;o.session_iv=null;o.lease_token=null;o.lease_expires_ms=0;if(o.state!=='saved'&&!['failed','expired'].includes(o.state)){o.state=o.dispatched?'reconciling':'expired';o.error_code='RESTORE_RECONCILIATION_REQUIRED';}}
 }
 for(const a of artifacts.values())if(a.kind==='file'&&!(tables.documentation_upload_operations??[]).some(o=>o.artifact_id===a.id&&o.state==='saved'))bad();
}
