import {HttpError} from './http-error.ts';
import {requireModuleCapability,type ModuleDatabase} from './platform-modules.ts';
type Row=Record<string,any>;
const definitionData=['title','definition','source','archived'];
const claimData=['title','definition_id','definition_revision','period_start','period_end','rationale','archived','review_decision','reviewed_revision','reviewer_user_id','reviewed_at'];
const links=[{name:'activities',key:'activityId',column:'activity_id',target:'hours_activities',eligible:'a.archived=0 AND a.impact_relevant=1',label:'title',history:''},{name:'teams',key:'teamId',column:'team_id',target:'hours_teams',eligible:'a.archived=0',label:'name',history:''},{name:'initiatives',key:'initiativeId',column:'initiative_id',target:'documentation_initiatives',eligible:'a.archived=0',label:'title',history:''},{name:'artifacts',key:'artifactId',column:'artifact_id',target:'documentation_artifacts',eligible:'a.archived=0',label:'title',history:'documentation_artifact_revisions'},{name:'metrics',key:'metricId',column:'metric_id',target:'documentation_metrics',eligible:'a.archived=0',label:'title',history:'documentation_metric_revisions'}] as const;
export const claimColumns={documentation_definitions:['installation_id','id',...definitionData,'revision','author_user_id','created_at','updated_at'],documentation_definition_revisions:['installation_id','definition_id','revision','actor_user_id',...definitionData,'created_at'],documentation_claims:['installation_id','id',...claimData,'revision','author_user_id','created_at','updated_at'],documentation_claim_revisions:['installation_id','claim_id','revision','actor_user_id',...claimData,'created_at'],documentation_claim_revision_activities:['installation_id','claim_id','revision','activity_id','target_revision'],documentation_claim_revision_teams:['installation_id','claim_id','revision','team_id','target_revision'],documentation_claim_revision_initiatives:['installation_id','claim_id','revision','initiative_id','target_revision'],documentation_claim_revision_artifacts:['installation_id','claim_id','revision','artifact_id','target_revision'],documentation_claim_revision_metrics:['installation_id','claim_id','revision','metric_id','target_revision'],documentation_claim_reviews:['installation_id','claim_id','revision','reviewed_revision','reviewer_user_id','decision','reviewed_at']} as const;
const access=`EXISTS(SELECT 1 FROM users u JOIN platform_module_configuration c ON c.installation_id=u.installation_id LEFT JOIN platform_module_grants g ON g.installation_id=u.installation_id AND g.user_id=u.id WHERE u.installation_id=? AND u.id=? AND u.active=1 AND c.hours_enabled=1 AND c.documentation_enabled=1 AND (u.role='admin' OR g.documentation_manage=1))`;
function fail(status=400,message='Invalid claim or definition request'):never{throw new HttpError(status,message);}
function fields(v:unknown,keys:string[]){if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).some(k=>!keys.includes(k)))fail();return v as Row;}
function id(v:unknown){if(typeof v!=='string'||!/^[A-Za-z0-9_-]{1,128}$/.test(v))fail();return v;}
function rev(v:unknown){if(!Number.isSafeInteger(v)||Number(v)<0||Number(v)>=Number.MAX_SAFE_INTEGER)fail();return Number(v);}
function text(v:unknown,max:number,required=true){if(typeof v!=='string'||required&&!v.trim()||v.length>max||/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(v))fail();return v;}
function date(v:unknown){if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||v<'1900-01-01'||v>'9999-12-31')fail();const d=new Date(v+'T00:00:00Z');if(!Number.isFinite(d.getTime())||d.toISOString().slice(0,10)!==v)fail();return v;}
const stamp=(v:unknown)=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}T/.test(v)&&Number.isFinite(Date.parse(v));
function data(v:Row,claim:boolean){text(v.title,200);if(![0,1].includes(v.archived))fail();if(!claim){text(v.definition,8000);text(v.source,2000,false);return;}
 id(v.definition_id);rev(v.definition_revision);date(v.period_start);date(v.period_end);if(v.period_start>v.period_end)fail();text(v.rationale,8000,false);
 if(v.review_decision===null){if([v.reviewed_revision,v.reviewer_user_id,v.reviewed_at].some(x=>x!==null))fail();}else{if(!['reviewed','rejected'].includes(v.review_decision)||!stamp(v.reviewed_at))fail();rev(v.reviewed_revision);id(v.reviewer_user_id);}}
const review=(r:Row)=>r.review_decision===null?null:{decision:r.review_decision,reviewedRevision:r.reviewed_revision,reviewerUserId:r.reviewer_user_id,reviewedAt:r.reviewed_at};
function dto(r:Row,claim:boolean){return {id:r.id,title:r.title,revision:r.revision,archived:!!r.archived,authorUserId:r.author_user_id,createdAt:r.created_at,updatedAt:r.updated_at,...(claim?{definitionId:r.definition_id,definitionRevision:r.definition_revision,periodStart:r.period_start,periodEnd:r.period_end,rationale:r.rationale,review:review(r)}:{definition:r.definition,source:r.source})};}
function page(url:URL,history=false){const seen=new Set<string>();url.searchParams.forEach((_,k)=>{if(!['after','limit','archival'].includes(k)||seen.has(k))fail();seen.add(k);});const limit=Number(url.searchParams.get('limit')??25),after=url.searchParams.get('after'),archival=url.searchParams.get('archival')??'false';if(!Number.isInteger(limit)||limit<1||limit>50||!['true','false'].includes(archival))fail();return {limit,after:history?after===null?-1:rev(Number(after)):after===null?'':id(after),archival:archival==='true'};}
function parseLinks(v:unknown,c:typeof links[number]){if(!Array.isArray(v)||v.length>100)fail();const result:Row[]=v.map(x=>{const r=fields(x,[c.key,'revision',...(c.history?['currentRevision']:[])]);return {[c.key]:id(r[c.key]),revision:rev(r.revision),...(c.history&&Object.hasOwn(r,'currentRevision')?{currentRevision:rev(r.currentRevision)}:{})};});if(new Set(result.map(r=>r[c.key])).size!==result.length)fail();return result;}
function projection(full=false){return links.map(c=>{const pinned=c.history?'s':'a';let extra='';if(c.name==='artifacts')extra=",'selectedReview',CASE WHEN s.review_decision IS NULL THEN NULL ELSE json_object('decision',s.review_decision,'reviewedRevision',s.reviewed_revision,'reviewerUserId',s.reviewer_user_id,'reviewedAt',s.reviewed_at) END"+(full?",'caption',s.caption,'url',s.url,'originalUrl',s.original_url":'');if(c.name==='metrics')extra=",'kind',s.kind,'value',s.value,'unit',s.unit,'periodStart',s.period_start,'periodEnd',s.period_end,'basis',s.basis"+(full?",'source',s.source,'method',s.method":'');
 return `COALESCE((SELECT json_group_array(json_object('${c.key}',a.id,'revision',l.target_revision,'currentRevision',a.revision,'title',${pinned}.${c.label},'currentTitle',a.${c.label},'eligible',json(CASE WHEN ${c.eligible} THEN 'true' ELSE 'false' END),'changed',json(CASE WHEN a.revision<>l.target_revision OR NOT (${c.eligible}) THEN 'true' ELSE 'false' END),'currentArchived',json(CASE WHEN a.archived=1 THEN 'true' ELSE 'false' END)${c.history?",'selectedArchived',json(CASE WHEN s.archived=1 THEN 'true' ELSE 'false' END)":''}${extra})) FROM documentation_claim_revision_${c.name} l JOIN ${c.target} a ON a.installation_id=l.installation_id AND a.id=l.${c.column} ${c.history?`JOIN ${c.history} s ON s.installation_id=l.installation_id AND s.${c.column}=l.${c.column} AND s.revision=l.target_revision`:''} WHERE l.installation_id=m.installation_id AND l.claim_id=m.id AND l.revision=m.revision),'[]') AS ${c.name}`;}).join(',')+`,(SELECT json_object('id',d.id,'revision',s.revision,'currentRevision',d.revision,'title',s.title,'definition',s.definition,'source',s.source,'archived',json(CASE WHEN d.archived=1 THEN 'true' ELSE 'false' END),'changed',json(CASE WHEN d.revision<>s.revision OR d.archived=1 THEN 'true' ELSE 'false' END)) FROM documentation_definitions d JOIN documentation_definition_revisions s ON s.installation_id=d.installation_id AND s.definition_id=d.id WHERE d.installation_id=m.installation_id AND d.id=m.definition_id AND s.revision=m.definition_revision) AS definition_snapshot`;}
function claimRead(r:Row){const associations=Object.fromEntries(links.map(c=>[c.name,JSON.parse(r[c.name])])),definition=JSON.parse(r.definition_snapshot);return {claim:dto(r,true),...associations,definition,readOnly:!!r.archived,dependencyChanged:definition.changed||links.some(c=>associations[c.name].some((x:Row)=>x.changed)),incompleteness:{rationaleMissing:!r.rationale.trim(),contextsMissing:!['activities','teams','initiatives'].some(k=>associations[k].length),evidenceMissing:!['artifacts','metrics'].some(k=>associations[k].length)}};}
export async function claimRoute(db:ModuleDatabase,installation:string,actor:string,request:Request,input?:unknown){
 await requireModuleCapability(db,installation,actor,'documentation.manage');const url=new URL(request.url),path=url.pathname.replace('/admin/documentation','');
 if(path==='/teams'&&request.method==='GET'){const p=page(url);const rows=(await db.prepare(`SELECT id,name,number,organization,program,revision,archived FROM hours_teams WHERE installation_id=? AND id>? AND archived=0 AND ${access} ORDER BY id LIMIT ?`).bind(installation,p.after,installation,actor,p.limit+1).all<Row>()).results??[];return {status:200,body:{teams:rows.slice(0,p.limit).map(r=>({...r,archived:false})),next:rows.length>p.limit?rows[p.limit-1].id:null}};}
 const match=/^\/(definitions|claims)(?:\/([A-Za-z0-9_-]{1,128})(\/(?:history|review))?)?$/.exec(path);if(!match)fail(404);const claim=match[1]==='claims',table='documentation_'+match[1],singular=claim?'claim':'definition',historyTable='documentation_'+singular+'_revisions',target=match[2],action=match[3],columns=claim?claimData:definitionData;
 if(request.method==='GET'){
  if(action==='/review')fail(405);const p=page(url,action==='/history');
  if(action==='/history'){const results=await db.batch([db.prepare(`SELECT * FROM ${table} WHERE installation_id=? AND id=? AND ${access}`).bind(installation,target,installation,actor),db.prepare(`SELECT h.*,h.${singular}_id AS id ${claim?','+projection(false):''} FROM ${historyTable} h ${claim?`JOIN (SELECT *,claim_id AS id FROM ${historyTable}) m ON m.installation_id=h.installation_id AND m.claim_id=h.claim_id AND m.revision=h.revision`:''} WHERE h.installation_id=? AND h.${singular}_id=? AND h.revision>? AND ${access} ORDER BY h.revision LIMIT ?`).bind(installation,target,p.after,installation,actor,p.limit+1)]);const header=results[0].results?.[0] as Row|undefined;if(!header)fail(404);const rows=results[1].results as Row[];return {status:200,body:{[singular+'Id']:target,authorUserId:header.author_user_id,createdAt:header.created_at,revisions:rows.slice(0,p.limit).map(r=>({...dto(r,claim),actorUserId:r.actor_user_id,...(claim?claimRead(r):{})})),next:rows.length>p.limit?rows[p.limit-1].revision:null}};}
  if(target){const r=await db.prepare(`SELECT m.* ${claim?','+projection(true):''} FROM ${table} m WHERE m.installation_id=? AND m.id=? AND ${access}`).bind(installation,target,installation,actor).first<Row>();if(!r)fail(404);return {status:200,body:claim?claimRead(r):{definition:dto(r,false),readOnly:!!r.archived}};}
  const rows=(await db.prepare(`SELECT m.* ${claim?','+projection(false):''} FROM ${table} m WHERE m.installation_id=? AND m.id>? AND (?=1 OR m.archived=0) AND ${access} ORDER BY m.id LIMIT ?`).bind(installation,p.after,Number(p.archival),installation,actor,p.limit+1).all<Row>()).results??[];return {status:200,body:{[match[1]]:rows.slice(0,p.limit).map(r=>claim?claimRead(r):dto(r,false)),next:rows.length>p.limit?rows[p.limit-1].id:null}};
 }
 const reviewing=claim&&action==='/review';if(reviewing?request.method!=='POST':action||request.method!==(target?'PATCH':'POST'))fail(405);
 const keys=claim?['title','definitionId','definitionRevision','periodStart','periodEnd','rationale',...links.map(c=>c.name)]:['title','definition','source'];const v=fields(input,reviewing?['revision','decision']:target?[...keys,'revision','archived']:keys),current=target?await db.prepare(`SELECT * FROM ${table} WHERE installation_id=? AND id=? AND ${access}`).bind(installation,target,installation,actor).first<Row>():null;if(target&&!current)fail(404);const revision=target?rev(v.revision):0;if(target&&Object.keys(v).length===1)fail();if(Object.hasOwn(v,'archived')&&typeof v.archived!=='boolean')fail();if(current?.archived&&(reviewing||v.archived!==false||Object.keys(v).some(k=>!['revision','archived'].includes(k))))fail(409,'Unarchive before editing');if(reviewing&&!['reviewed','rejected'].includes(v.decision))fail();
 const now=new Date().toISOString(),newId=target??crypto.randomUUID(),auditId=crypto.randomUUID(),nextRev=target?revision+1:0,value:Row={...current,...v,source:v.source??current?.source??'',rationale:v.rationale??current?.rationale??'',archived:Object.hasOwn(v,'archived')?Number(v.archived):current?.archived??0};
 if(claim){for(const [camel,column] of [['definitionId','definition_id'],['definitionRevision','definition_revision'],['periodStart','period_start'],['periodEnd','period_end']])value[column]=Object.hasOwn(v,camel)?v[camel]:current?.[column];Object.assign(value,{review_decision:reviewing?v.decision:null,reviewed_revision:reviewing?revision:null,reviewer_user_id:reviewing?actor:null,reviewed_at:reviewing?now:null});}data(value,claim);
 const requested=claim?links.map(c=>Object.hasOwn(v,c.name)?parseLinks(v[c.name],c):target?null:[]):[],gates:string[]=[],args:unknown[]=[],counts:string[]=[],countArgs:unknown[]=[];
 if(claim){gates.push(`(?=? AND ?=?) OR EXISTS(SELECT 1 FROM documentation_definitions d JOIN documentation_definition_revisions h ON h.installation_id=d.installation_id AND h.definition_id=d.id WHERE d.installation_id=? AND d.id=? AND h.revision=? AND d.archived=0 AND h.archived=0)`);args.push(value.definition_id,current?.definition_id??'',value.definition_revision,current?.definition_revision??-1,installation,value.definition_id,value.definition_revision);
 links.forEach((c,i)=>{const rows=requested[i];if(rows===null){counts.push(`(SELECT COUNT(*) FROM documentation_claim_revision_${c.name} WHERE installation_id=? AND claim_id=? AND revision=?)`);countArgs.push(installation,newId,revision);return;}counts.push('?');countArgs.push(rows.length);gates.push(`NOT EXISTS(SELECT 1 FROM json_each(?) j WHERE NOT EXISTS(SELECT 1 FROM documentation_claim_revision_${c.name} l WHERE l.installation_id=? AND l.claim_id=? AND l.revision=? AND l.${c.column}=json_extract(j.value,'$.${c.key}') AND l.target_revision=json_extract(j.value,'$.revision')) AND NOT EXISTS(SELECT 1 FROM ${c.target} a ${c.history?`JOIN ${c.history} h ON h.installation_id=a.installation_id AND h.${c.column}=a.id AND h.revision=json_extract(j.value,'$.revision')`:''} WHERE a.installation_id=? AND a.id=json_extract(j.value,'$.${c.key}') AND a.revision=json_extract(j.value,'$.${c.history?'currentRevision':'revision'}') AND ${c.eligible}))`);args.push(JSON.stringify(rows),installation,newId,revision,installation);});gates.push(`(${counts.join('+')})<=100`);args.push(...countArgs);}
 const gate=gates.map(g=>'('+g+')').join(' AND ')||'1',values=columns.map(c=>value[c]);
 const mutation=target?db.prepare(`UPDATE ${table} SET ${columns.map(c=>c+'=?').join(',')},revision=revision+1,updated_at=? WHERE installation_id=? AND id=? AND revision=? AND archived=? AND ${access} AND ${gate}`).bind(...values,now,installation,newId,revision,current!.archived,installation,actor,...args):db.prepare(`INSERT INTO ${table}(installation_id,id,${columns.join(',')},author_user_id,created_at,updated_at) SELECT ${Array(columns.length+5).fill('?').join(',')} WHERE ${access} AND ${gate}`).bind(installation,newId,...values,actor,now,now,installation,actor,...args);
 const admitted='EXISTS(SELECT 1 FROM audit_log WHERE installation_id=? AND id=?)',admittedArgs=[installation,auditId],statements=[mutation,db.prepare(`INSERT INTO audit_log(id,installation_id,actor_user_id,action,target_type,target_id,created_at) SELECT ?,?,?,?,'documentation_${singular}',?,? WHERE changes()=1`).bind(auditId,installation,actor,'documentation.'+singular+(reviewing?'.reviewed':target?'.updated':'.created'),newId,now),db.prepare(`INSERT INTO ${historyTable}(installation_id,${singular}_id,revision,actor_user_id,${columns.join(',')},created_at) SELECT installation_id,id,revision,?,${columns.join(',')},updated_at FROM ${table} WHERE installation_id=? AND id=? AND ${admitted}`).bind(actor,installation,newId,...admittedArgs)];
 if(claim){links.forEach((c,i)=>{const rows=requested[i];statements.push(rows===null?db.prepare(`INSERT INTO documentation_claim_revision_${c.name}(installation_id,claim_id,revision,${c.column},target_revision) SELECT installation_id,claim_id,?,${c.column},target_revision FROM documentation_claim_revision_${c.name} WHERE installation_id=? AND claim_id=? AND revision=? AND ${admitted}`).bind(nextRev,installation,newId,revision,...admittedArgs):db.prepare(`INSERT INTO documentation_claim_revision_${c.name}(installation_id,claim_id,revision,${c.column},target_revision) SELECT ?,?,?,json_extract(value,'$.${c.key}'),json_extract(value,'$.revision') FROM json_each(?) WHERE ${admitted}`).bind(installation,newId,nextRev,JSON.stringify(rows),...admittedArgs));});if(reviewing)statements.push(db.prepare(`INSERT INTO documentation_claim_reviews SELECT ?,?,?,?,?,?,? WHERE ${admitted}`).bind(installation,newId,nextRev,revision,actor,v.decision,now,...admittedArgs));}
 const results=await db.batch(statements);if(results[1]?.meta?.changes!==1)fail(409,'Record, association or current authority changed; reload');return {status:target?200:201,body:{[singular]:dto({...value,id:newId,revision:nextRev,author_user_id:current?.author_user_id??actor,created_at:current?.created_at??now,updated_at:now},claim)}};
}

export function validateClaimBackup(tables:Record<string,Row[]>){
 const bad=()=>fail(400,'Invalid claims or definitions backup'),users=new Set((tables.users??[]).filter(r=>r.installation_id==='primary').map(r=>r.id));
 const all=new Map<string,Map<string,Row>>(),histories=new Map<string,Map<string,Map<number,Row>>>();
 for(const claim of [false,true]){const name=claim?'claim':'definition',columns=claim?claimData:definitionData,headers=new Map<string,Row>(),history=new Map<string,Map<number,Row>>();all.set(name,headers);histories.set(name,history);
  for(const r of tables['documentation_'+name+'s']??[]){id(r.id);rev(r.revision);data(r,claim);if(r.installation_id!=='primary'||headers.has(r.id)||!users.has(r.author_user_id)||!stamp(r.created_at)||!stamp(r.updated_at)||Date.parse(r.updated_at)<Date.parse(r.created_at))bad();headers.set(r.id,r);}
  for(const r of tables['documentation_'+name+'_revisions']??[]){rev(r.revision);data(r,claim);if(r.installation_id!=='primary'||!headers.has(r[name+'_id'])||!users.has(r.actor_user_id)||!stamp(r.created_at))bad();const rows=history.get(r[name+'_id'])??new Map();if(rows.has(r.revision))bad();rows.set(r.revision,r);history.set(r[name+'_id'],rows);}
  for(const [key,header] of headers){const rows=history.get(key);if(!rows||rows.size!==header.revision+1)bad();let previous=0;for(let i=0;i<=header.revision;i++){const row=rows!.get(i);if(!row||Date.parse(row.created_at)<previous)bad();previous=Date.parse(row!.created_at);if(claim){if(!histories.get('definition')?.get(row!.definition_id)?.has(row!.definition_revision))bad();if(row!.reviewer_user_id!==null&&!users.has(row!.reviewer_user_id))bad();}if(i&&rows!.get(i-1)!.archived){const prior=rows!.get(i-1)!;if(row!.archived!==0||columns.filter(c=>c!=='archived').some(c=>row![c]!==prior[c]))bad();}}
   const first=rows!.get(0)!,last=rows!.get(header.revision)!;if(first.actor_user_id!==header.author_user_id||first.created_at!==header.created_at||first.archived!==0||last.created_at!==header.updated_at||columns.some(c=>header[c]!==last[c]))bad();
  }
 }
 const memberships=new Map<string,Set<string>>();
 for(const c of links){const targets=new Map((tables[c.target]??[]).filter(r=>r.installation_id==='primary').map(r=>[r.id,r])),pins=new Set((tables[c.history]??[]).filter(r=>r.installation_id==='primary').map(r=>JSON.stringify([r[c.column],r.revision])));
  for(const r of tables['documentation_claim_revision_'+c.name]??[]){rev(r.revision);rev(r.target_revision);const target=targets.get(r[c.column]);if(r.installation_id!=='primary'||!histories.get('claim')?.get(r.claim_id)?.has(r.revision)||!target||r.target_revision>target.revision||c.history&&!pins.has(JSON.stringify([r[c.column],r.target_revision])))bad();const key=JSON.stringify([r.claim_id,r.revision]),member=c.name+':'+r[c.column],set=memberships.get(key)??new Set();if([...set].some(value=>JSON.parse(value)[0]===member)||set.size>=100)bad();set.add(JSON.stringify([member,r.target_revision]));memberships.set(key,set);}
 }
 const members=(key:string,revision:number)=>JSON.stringify([...(memberships.get(JSON.stringify([key,revision]))??[])].sort()),reviews=new Set<string>();
 for(const r of tables.documentation_claim_reviews??[]){rev(r.revision);rev(r.reviewed_revision);const key=JSON.stringify([r.claim_id,r.revision]),rows=histories.get('claim')?.get(r.claim_id),row=rows?.get(r.revision),prior=rows?.get(r.reviewed_revision);if(r.installation_id!=='primary'||reviews.has(key)||r.revision!==r.reviewed_revision+1||!row||!prior||prior.archived||!users.has(r.reviewer_user_id)||!stamp(r.reviewed_at)||row.review_decision!==r.decision||row.reviewed_revision!==r.reviewed_revision||row.reviewer_user_id!==r.reviewer_user_id||row.actor_user_id!==r.reviewer_user_id||row.reviewed_at!==r.reviewed_at||row.created_at!==r.reviewed_at||claimData.filter(c=>!['review_decision','reviewed_revision','reviewer_user_id','reviewed_at'].includes(c)).some(c=>row[c]!==prior[c])||members(r.claim_id,r.revision)!==members(r.claim_id,r.reviewed_revision))bad();reviews.add(key);}
 for(const [key,rows] of histories.get('claim')!){for(const [revision,row] of rows){if(Boolean(row.review_decision)!==reviews.has(JSON.stringify([key,revision]))||revision===0&&row.review_decision!==null)bad();if(revision&&rows.get(revision-1)!.archived&&members(key,revision)!==members(key,revision-1))bad();}}
}
