import {HttpError} from './http-error.ts';
import {requireModuleCapability,type ModuleDatabase} from './platform-modules.ts';
type Row=Record<string,any>;
const dataColumns=['title','kind','value','unit','period_start','period_end','source','method','basis','archived'];
export const metricColumns={
 documentation_metrics:['installation_id','id',...dataColumns,'revision','author_user_id','created_at','updated_at'],
 documentation_metric_revisions:['installation_id','metric_id','revision','actor_user_id',...dataColumns,'created_at'],
 documentation_metric_activities:['installation_id','metric_id','activity_id'],
 documentation_metric_revision_activities:['installation_id','metric_id','revision','activity_id'],
 documentation_metric_initiatives:['installation_id','metric_id','initiative_id'],
 documentation_metric_revision_initiatives:['installation_id','metric_id','revision','initiative_id'],
} as const;
export const metricKinds=['person-hours','participants','interactions','reach','outcomes','other'] as const;
const contexts=[{name:'activities',key:'activityId',column:'activity_id',target:'hours_activities',eligibility:'a.archived=0 AND a.impact_relevant=1'},{name:'initiatives',key:'initiativeId',column:'initiative_id',target:'documentation_initiatives',eligibility:'a.archived=0'}] as const;
const access=`EXISTS(SELECT 1 FROM users u JOIN platform_module_configuration c ON c.installation_id=u.installation_id LEFT JOIN platform_module_grants g ON g.installation_id=u.installation_id AND g.user_id=u.id WHERE u.installation_id=? AND u.id=? AND u.active=1 AND c.hours_enabled=1 AND c.documentation_enabled=1 AND (u.role='admin' OR g.documentation_manage=1))`;
function fail(status=400,message='Invalid metric request'):never{throw new HttpError(status,message);}
function fields(v:unknown,keys:string[]){if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).some(k=>!keys.includes(k)))fail();return v as Row;}
function id(v:unknown){if(typeof v!=='string'||!/^[A-Za-z0-9_-]{1,128}$/.test(v))fail();return v;}
function revision(v:unknown){if(!Number.isSafeInteger(v)||Number(v)<0||Number(v)>=Number.MAX_SAFE_INTEGER)fail();return Number(v);}
function text(v:unknown,max:number){if(typeof v!=='string'||!v.trim()||v.length>max||/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(v))fail();return v;}
export function metricDecimal(v:unknown){if(typeof v!=='string'||! /^-?(?:0|[1-9]\d{0,14})(?:\.\d{1,6})?$/.test(v)||/^-0(?:\.0+)?$/.test(v))fail();return v;}
function date(v:unknown){if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||v<'1900-01-01'||v>'9999-12-31')fail();const parsed=new Date(v+'T00:00:00.000Z');if(!Number.isFinite(parsed.getTime())||parsed.toISOString().slice(0,10)!==v)fail();return v;}
function data(v:Row){const r={title:text(v.title,200),kind:v.kind,value:metricDecimal(v.value),unit:text(v.unit,80),period_start:date(v.period_start),period_end:date(v.period_end),source:text(v.source,2000),method:text(v.method,4000),basis:v.basis,archived:v.archived};if(!metricKinds.includes(r.kind)||!['measured','estimated'].includes(r.basis)||![0,1].includes(r.archived)||r.period_end<r.period_start)fail();return r;}
const dto=(r:Row)=>({id:r.id,title:r.title,kind:r.kind,value:r.value,unit:r.unit,periodStart:r.period_start,periodEnd:r.period_end,source:r.source,method:r.method,basis:r.basis,archived:Boolean(r.archived),revision:r.revision,authorUserId:r.author_user_id,createdAt:r.created_at,updatedAt:r.updated_at});
function page(url:URL,history=false){const seen=new Set<string>();url.searchParams.forEach((_,k)=>{if(!['after','limit','archival'].includes(k)||seen.has(k))fail();seen.add(k);});const limit=Number(url.searchParams.get('limit')??25),after=url.searchParams.get('after'),archival=url.searchParams.get('archival')??'false';if(!Number.isInteger(limit)||limit<1||limit>50||!['true','false'].includes(archival))fail();return {limit,after:history?after===null?-1:revision(Number(after)):after===null?'':id(after),archival:archival==='true'};}
function parseLinks(v:unknown,key:string){if(!Array.isArray(v)||v.length>100)fail();const rows=v.map(x=>{const r=fields(x,[key,'revision']);return {[key]:id(r[key]),revision:revision(r.revision)};});if(new Set(rows.map(r=>r[key])).size!==rows.length)fail();return rows;}
function projection(history=false){return contexts.map(c=>`COALESCE((SELECT json_group_array(json_object('${c.key}',a.id,'title',a.title,'revision',a.revision,'eligible',json(CASE WHEN ${c.eligibility} THEN 'true' ELSE 'false' END))) FROM documentation_metric_${history?'revision_':''}${c.name} l JOIN ${c.target} a ON a.installation_id=l.installation_id AND a.id=l.${c.column} WHERE l.installation_id=m.installation_id AND l.metric_id=m.${history?'metric_id':'id'} ${history?'AND l.revision=m.revision':''}),'[]') AS ${c.name}`).join(',');}
export async function metricRoute(db:ModuleDatabase,installation:string,actor:string,request:Request,input?:unknown){
 await requireModuleCapability(db,installation,actor,'documentation.manage');const url=new URL(request.url),path=url.pathname.replace('/admin/documentation/metrics',''),now=new Date().toISOString(),match=/^\/([A-Za-z0-9_-]{1,128})(\/history)?$/.exec(path);if(path&&!match)fail(404);const metricId=match?.[1];
 if(request.method==='GET'){
  const p=page(url,!!match?.[2]);
  if(!metricId){const rows=(await db.prepare(`SELECT m.* FROM documentation_metrics m WHERE m.installation_id=? AND m.id>? AND (?=1 OR m.archived=0) AND ${access} ORDER BY m.id LIMIT ?`).bind(installation,p.after,Number(p.archival),installation,actor,p.limit+1).all<Row>()).results??[];return {status:200,body:{metrics:rows.slice(0,p.limit).map(dto),next:rows.length>p.limit?rows[p.limit-1].id:null}};}
  if(match?.[2]){const results=await db.batch([db.prepare(`SELECT * FROM documentation_metrics WHERE installation_id=? AND id=? AND ${access}`).bind(installation,metricId,installation,actor),db.prepare(`SELECT m.*,${projection(true)} FROM documentation_metric_revisions m WHERE m.installation_id=? AND m.metric_id=? AND m.revision>? AND ${access} ORDER BY m.revision LIMIT ?`).bind(installation,metricId,p.after,installation,actor,p.limit+1)]);const header=results[0].results?.[0] as Row|undefined;if(!header)fail(404,'Metric unavailable');const rows=(results[1].results??[]) as Row[];return {status:200,body:{metricId,authorUserId:header.author_user_id,createdAt:header.created_at,revisions:rows.slice(0,p.limit).map(r=>({revision:r.revision,actorUserId:r.actor_user_id,title:r.title,kind:r.kind,value:r.value,unit:r.unit,periodStart:r.period_start,periodEnd:r.period_end,source:r.source,method:r.method,basis:r.basis,archived:Boolean(r.archived),createdAt:r.created_at,activities:JSON.parse(r.activities),initiatives:JSON.parse(r.initiatives)})),next:rows.length>p.limit?rows[p.limit-1].revision:null}};}
  const r=await db.prepare(`SELECT m.*,${projection()} FROM documentation_metrics m WHERE m.installation_id=? AND m.id=? AND ${access}`).bind(installation,metricId,installation,actor).first<Row>();if(!r)fail(404,'Metric unavailable');return {status:200,body:{metric:dto(r),activities:JSON.parse(r.activities),initiatives:JSON.parse(r.initiatives),readOnly:Boolean(r.archived)}};
 }
 if((metricId?request.method!=='PATCH':request.method!=='POST')||match?.[2])fail(405);
 const keys=['title','kind','value','unit','periodStart','periodEnd','source','method','basis','activities','initiatives'];const v=fields(input,metricId?[...keys,'revision','archived']:keys),current=metricId?await db.prepare(`SELECT * FROM documentation_metrics WHERE installation_id=? AND id=? AND ${access}`).bind(installation,metricId,installation,actor).first<Row>():null;if(metricId&&!current)fail(404,'Metric unavailable');
 const rev=metricId?revision(v.revision):0;if(metricId&&Object.keys(v).length===1)fail();if(Object.hasOwn(v,'archived')&&typeof v.archived!=='boolean')fail();if(current?.archived&&(v.archived!==false||Object.keys(v).some(k=>!['revision','archived'].includes(k))))fail(409,'Unarchive the metric before editing');
 const changed={...current,...v,period_start:Object.hasOwn(v,'periodStart')?v.periodStart:current?.period_start,period_end:Object.hasOwn(v,'periodEnd')?v.periodEnd:current?.period_end,archived:Object.hasOwn(v,'archived')?Number(v.archived):current?.archived??0},value=data(changed);
 const newId=metricId??crypto.randomUUID(),auditId=crypto.randomUUID(),requested=contexts.map(c=>Object.hasOwn(v,c.name)?parseLinks(v[c.name],c.key):metricId?null:[]);
 const gates:string[]=[],args:unknown[]=[],counts:string[]=[],countArgs:unknown[]=[];
 contexts.forEach((c,index)=>{const links=requested[index];if(links===null){counts.push(`(SELECT COUNT(*) FROM documentation_metric_${c.name} WHERE installation_id=? AND metric_id=?)`);countArgs.push(installation,newId);return;}counts.push('?');countArgs.push(links.length);gates.push(`NOT EXISTS(SELECT 1 FROM json_each(?) j WHERE NOT EXISTS(SELECT 1 FROM documentation_metric_${c.name} l WHERE l.installation_id=? AND l.metric_id=? AND l.${c.column}=json_extract(j.value,'$.${c.key}')) AND NOT EXISTS(SELECT 1 FROM ${c.target} a WHERE a.installation_id=? AND a.id=json_extract(j.value,'$.${c.key}') AND a.revision=json_extract(j.value,'$.revision') AND ${c.eligibility}))`);args.push(JSON.stringify(links),installation,newId,installation);});
 const gate=[...gates,`(${counts.join('+')})<=100`].join(' AND '),gateArgs=[...args,...countArgs],values=dataColumns.map(c=>(value as Row)[c]);
 const mutation=metricId?db.prepare(`UPDATE documentation_metrics SET ${dataColumns.map(c=>c+'=?').join(',')},revision=revision+1,updated_at=? WHERE installation_id=? AND id=? AND revision=? AND archived=? AND ${access} AND ${gate}`).bind(...values,now,installation,newId,rev,current!.archived,installation,actor,...gateArgs):db.prepare(`INSERT INTO documentation_metrics(installation_id,id,${dataColumns.join(',')},author_user_id,created_at,updated_at) SELECT ${Array(15).fill('?').join(',')} WHERE ${access} AND ${gate}`).bind(installation,newId,...values,actor,now,now,installation,actor,...gateArgs);
 const admitted='EXISTS(SELECT 1 FROM audit_log WHERE installation_id=? AND id=?)',admittedArgs=[installation,auditId];const statements=[mutation,db.prepare("INSERT INTO audit_log(id,installation_id,actor_user_id,action,target_type,target_id,created_at) SELECT ?,?,?,?,'documentation_metric',?,? WHERE changes()=1").bind(auditId,installation,actor,metricId?'documentation.metric.updated':'documentation.metric.created',newId,now)];
 contexts.forEach((c,index)=>{const links=requested[index];if(links!==null)statements.push(db.prepare(`DELETE FROM documentation_metric_${c.name} WHERE installation_id=? AND metric_id=? AND ${admitted}`).bind(installation,newId,...admittedArgs),db.prepare(`INSERT INTO documentation_metric_${c.name}(installation_id,metric_id,${c.column}) SELECT ?,?,json_extract(value,'$.${c.key}') FROM json_each(?) WHERE ${admitted}`).bind(installation,newId,JSON.stringify(links),...admittedArgs));});
 statements.push(db.prepare(`INSERT INTO documentation_metric_revisions(installation_id,metric_id,revision,actor_user_id,${dataColumns.join(',')},created_at) SELECT installation_id,id,revision,?,${dataColumns.join(',')},updated_at FROM documentation_metrics WHERE installation_id=? AND id=? AND ${admitted}`).bind(actor,installation,newId,...admittedArgs));
 contexts.forEach(c=>statements.push(db.prepare(`INSERT INTO documentation_metric_revision_${c.name}(installation_id,metric_id,revision,${c.column}) SELECT l.installation_id,l.metric_id,m.revision,l.${c.column} FROM documentation_metric_${c.name} l JOIN documentation_metrics m ON m.installation_id=l.installation_id AND m.id=l.metric_id WHERE l.installation_id=? AND l.metric_id=? AND ${admitted}`).bind(installation,newId,...admittedArgs)));
 const results=await db.batch(statements);if(results[1]?.meta?.changes!==1)fail(409,'Metric, association or authority changed; reload');return {status:metricId?200:201,body:{metric:dto({...value,id:newId,revision:metricId?rev+1:0,author_user_id:current?.author_user_id??actor,created_at:current?.created_at??now,updated_at:now})}};
}

export function validateMetricBackup(tables:Record<string,Row[]>){
 const bad=()=>fail(400,'Invalid metric backup'),stamp=(v:unknown)=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}T/.test(v)&&Number.isFinite(Date.parse(v));
 const users=new Set((tables.users??[]).filter(r=>r.installation_id==='primary').map(r=>r.id)),metrics=new Map<string,Row>(),histories=new Map<string,Map<number,Row>>();
 for(const r of tables.documentation_metrics??[]){id(r.id);revision(r.revision);data(r);if(r.installation_id!=='primary'||metrics.has(r.id)||!users.has(r.author_user_id)||!stamp(r.created_at)||!stamp(r.updated_at)||Date.parse(r.updated_at)<Date.parse(r.created_at))bad();metrics.set(r.id,r);}
 for(const r of tables.documentation_metric_revisions??[]){revision(r.revision);data(r);if(r.installation_id!=='primary'||!metrics.has(r.metric_id)||!users.has(r.actor_user_id)||!stamp(r.created_at))bad();const history=histories.get(r.metric_id)??new Map();if(history.has(r.revision))bad();history.set(r.revision,r);histories.set(r.metric_id,history);}
 const memberships=new Map<string,Set<string>>();
 contexts.forEach(c=>{const targets=new Set((tables[c.target]??[]).filter(r=>r.installation_id==='primary').map(r=>r.id));for(const historic of [false,true])for(const r of tables['documentation_metric_'+(historic?'revision_':'')+c.name]??[]){if(r.installation_id!=='primary'||!metrics.has(r.metric_id)||!targets.has(r[c.column]))bad();if(historic){revision(r.revision);if(!histories.get(r.metric_id)?.has(r.revision))bad();}const key=JSON.stringify([r.metric_id,historic?r.revision:'current']),member=c.name+':'+r[c.column],set=memberships.get(key)??new Set();if(set.has(member)||set.size>=100)bad();set.add(member);memberships.set(key,set);}});
 const members=(metric:string,rev:number|string)=>JSON.stringify([...(memberships.get(JSON.stringify([metric,rev]))??[])].sort());
 for(const [key,r] of metrics){const history=histories.get(key);if(!history||history.size!==r.revision+1)bad();let previous=0;for(let rev=0;rev<=r.revision;rev++){const h=history!.get(rev);if(!h||Date.parse(h.created_at)<previous)bad();previous=Date.parse(h!.created_at);if(rev&&history!.get(rev-1)!.archived){const prior=history!.get(rev-1)!;if(h!.archived!==0||dataColumns.filter(c=>c!=='archived').some(c=>h![c]!==prior[c])||members(key,rev)!==members(key,rev-1))bad();}}
  const first=history!.get(0)!,last=history!.get(r.revision)!;if(first.actor_user_id!==r.author_user_id||first.created_at!==r.created_at||first.archived!==0||last.created_at!==r.updated_at||dataColumns.some(c=>last[c]!==r[c])||members(key,'current')!==members(key,r.revision))bad();
 }
}
