import {HttpError} from './http-error.ts';
import {requireModuleCapability,type ModuleDatabase} from './platform-modules.ts';
type Row=Record<string,any>;
export const artifactFileColumns=['kind','file_id','file_root_id','file_generation','file_sha256','file_size','file_mime','validation_outcome'];
export const artifactPreservedColumns=['file_source_id','file_source_version','file_copied_at','file_version'];
const dataColumns=['title','caption','url','original_url','archived','review_decision','reviewed_revision','reviewer_user_id','reviewed_at'];
export const artifactColumns={
 documentation_artifacts:['installation_id','id',...dataColumns,...artifactFileColumns,...artifactPreservedColumns,'revision','author_user_id','author_member_id','source','created_at','updated_at'],
 documentation_artifact_revisions:['installation_id','artifact_id','revision','actor_user_id','actor_member_id',...dataColumns,...artifactFileColumns,...artifactPreservedColumns,'created_at'],
 documentation_artifact_activities:['installation_id','artifact_id','activity_id'],
 documentation_artifact_revision_activities:['installation_id','artifact_id','revision','activity_id'],
 documentation_artifact_initiatives:['installation_id','artifact_id','initiative_id'],
 documentation_artifact_revision_initiatives:['installation_id','artifact_id','revision','initiative_id'],
 documentation_artifact_reviews:['installation_id','artifact_id','revision','reviewed_revision','reviewer_user_id','decision','reviewed_at'],
} as const;
const contexts=[{name:'activities',key:'activityId',column:'activity_id',target:'hours_activities',eligibility:'a.archived=0 AND a.impact_relevant=1'},{name:'initiatives',key:'initiativeId',column:'initiative_id',target:'documentation_initiatives',eligibility:'a.archived=0'}] as const;
const access=`EXISTS(SELECT 1 FROM users u JOIN platform_module_configuration c ON c.installation_id=u.installation_id LEFT JOIN platform_module_grants g ON g.installation_id=u.installation_id AND g.user_id=u.id WHERE u.installation_id=? AND u.id=? AND u.active=1 AND c.hours_enabled=1 AND c.documentation_enabled=1 AND (u.role='admin' OR g.documentation_manage=1))`;
function fail(status=400,message='Invalid artifact request'):never{throw new HttpError(status,message);}
function fields(v:unknown,keys:string[]){if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).some(k=>!keys.includes(k)))fail();return v as Row;}
function id(v:unknown){if(typeof v!=='string'||!/^[A-Za-z0-9_-]{1,128}$/.test(v))fail();return v;}
function revision(v:unknown){if(!Number.isSafeInteger(v)||Number(v)<0||Number(v)>=Number.MAX_SAFE_INTEGER)fail();return Number(v);}
function text(v:unknown,max:number,required=true){if(typeof v!=='string'||(required&&!v.trim())||v.length>max||/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(v))fail();return v;}
export function artifactUrl(v:unknown){if(typeof v!=='string'||v.length>2048||/[\s\u0000-\u001f\u007f]/.test(v))fail();let u:URL;try{u=new URL(v);}catch{return fail();}if(u.protocol!=='https:'||u.username||u.password||!u.hostname)fail();return v;}
function data(v:Row){const r={title:text(v.title,200),caption:text(v.caption,4000,false),url:artifactUrl(v.url),original_url:artifactUrl(v.original_url),archived:v.archived,review_decision:v.review_decision,reviewed_revision:v.reviewed_revision,reviewer_user_id:v.reviewer_user_id,reviewed_at:v.reviewed_at};if(![0,1].includes(r.archived))fail();if(r.review_decision===null){if(r.reviewed_revision!==null||r.reviewer_user_id!==null||r.reviewed_at!==null)fail();}else{if(!['reviewed','rejected'].includes(r.review_decision)||r.archived!==0)fail();revision(r.reviewed_revision);id(r.reviewer_user_id);if(typeof r.reviewed_at!=='string'||!Number.isFinite(Date.parse(r.reviewed_at)))fail();}return r;}
const reviewDto=(r:Row)=>r.review_decision?{decision:r.review_decision,reviewedRevision:r.reviewed_revision,reviewerUserId:r.reviewer_user_id,reviewedAt:r.reviewed_at}:null;
const preservedDto=(r:Row)=>r.kind==='preserved-drive'?{preservedDrive:{id:r.file_id,rootId:r.file_root_id,generation:r.file_generation,mime:r.file_mime,sourceId:r.file_source_id,sourceVersion:r.file_source_version,copiedAt:r.file_copied_at,validation:{outcome:r.validation_outcome},...(r.validation_outcome==='native'?{}:{byteLength:r.file_size,sha256:r.file_sha256})}}:{};
const dto=(r:Row)=>({id:r.id,kind:r.kind??'external-link',title:r.title,caption:r.caption,url:r.url,originalUrl:r.original_url,archived:Boolean(r.archived),revision:r.revision,authorUserId:r.author_user_id,createdAt:r.created_at,updatedAt:r.updated_at,review:reviewDto(r),...preservedDto(r),...(r.kind==='file'?{file:{id:r.file_id,rootId:r.file_root_id,generation:r.file_generation,sha256:r.file_sha256,byteLength:r.file_size,mime:r.file_mime,validationOutcome:r.validation_outcome},contributor:{kind:r.author_member_id?'member':'staff',source:r.source}}:{})});
function page(url:URL,history=false){const seen=new Set<string>();url.searchParams.forEach((_,k)=>{if(!['after','limit','archival'].includes(k)||seen.has(k))fail();seen.add(k);});const limit=Number(url.searchParams.get('limit')??25),after=url.searchParams.get('after'),archival=url.searchParams.get('archival')??'false';if(!Number.isInteger(limit)||limit<1||limit>50||!['true','false'].includes(archival))fail();return {limit,after:history?after===null?-1:revision(Number(after)):after===null?'':id(after),archival:archival==='true'};}
function parseLinks(v:unknown,key:string){if(!Array.isArray(v)||v.length>100)fail();const rows=v.map(x=>{const r=fields(x,[key,'revision']);return {[key]:id(r[key]),revision:revision(r.revision)};});if(new Set(rows.map(r=>r[key])).size!==rows.length)fail();return rows;}
function projection(history=false){return contexts.map(c=>`COALESCE((SELECT json_group_array(json_object('${c.key}',a.id,'title',a.title,'revision',a.revision,'eligible',json(CASE WHEN ${c.eligibility} THEN 'true' ELSE 'false' END))) FROM documentation_artifact_${history?'revision_':''}${c.name} l JOIN ${c.target} a ON a.installation_id=l.installation_id AND a.id=l.${c.column} WHERE l.installation_id=m.installation_id AND l.artifact_id=m.${history?'artifact_id':'id'} ${history?'AND l.revision=m.revision':''}),'[]') AS ${c.name}`).join(',');}
export async function artifactRoute(db:ModuleDatabase,installation:string,actor:string,request:Request,input?:unknown){
 await requireModuleCapability(db,installation,actor,'documentation.manage');const url=new URL(request.url),path=url.pathname.replace('/admin/documentation/artifacts',''),now=new Date().toISOString(),match=/^\/([A-Za-z0-9_-]{1,128})(\/(?:history|review))?$/.exec(path);if(path&&!match)fail(404);const artifactId=match?.[1];
 if(request.method==='GET'){
  const p=page(url,match?.[2]==='/history');
  if(!artifactId){const rows=(await db.prepare(`SELECT m.* FROM documentation_artifacts m WHERE m.installation_id=? AND m.id>? AND (?=1 OR m.archived=0) AND ${access} ORDER BY m.id LIMIT ?`).bind(installation,p.after,Number(p.archival),installation,actor,p.limit+1).all<Row>()).results??[];return {status:200,body:{artifacts:rows.slice(0,p.limit).map(dto),next:rows.length>p.limit?rows[p.limit-1].id:null}};}
  if(match?.[2]==='/review')fail(405);
  if(match?.[2]==='/history'){const results=await db.batch([db.prepare(`SELECT * FROM documentation_artifacts WHERE installation_id=? AND id=? AND ${access}`).bind(installation,artifactId,installation,actor),db.prepare(`SELECT m.*,${projection(true)} FROM documentation_artifact_revisions m WHERE m.installation_id=? AND m.artifact_id=? AND m.revision>? AND ${access} ORDER BY m.revision LIMIT ?`).bind(installation,artifactId,p.after,installation,actor,p.limit+1)]);const header=results[0].results?.[0] as Row|undefined;if(!header)fail(404,'Artifact unavailable');const rows=(results[1].results??[]) as Row[];return {status:200,body:{artifactId,authorUserId:header.author_user_id,createdAt:header.created_at,revisions:rows.slice(0,p.limit).map(r=>({revision:r.revision,actorUserId:r.actor_user_id,actorMemberId:r.actor_member_id,kind:r.kind,...preservedDto(r),file:r.kind==='file'?{id:r.file_id,rootId:r.file_root_id,generation:r.file_generation,sha256:r.file_sha256,byteLength:r.file_size,mime:r.file_mime,validationOutcome:r.validation_outcome}:null,title:r.title,caption:r.caption,url:r.url,originalUrl:r.original_url,review:reviewDto(r),archived:Boolean(r.archived),createdAt:r.created_at,activities:JSON.parse(r.activities),initiatives:JSON.parse(r.initiatives)})),next:rows.length>p.limit?rows[p.limit-1].revision:null}};}
  const r=await db.prepare(`SELECT m.*,${projection()},COALESCE((SELECT files_enabled FROM documentation_sections WHERE installation_id=m.installation_id),1) AS files_enabled,COALESCE((SELECT revision FROM documentation_sections WHERE installation_id=m.installation_id),0) AS section_revision FROM documentation_artifacts m WHERE m.installation_id=? AND m.id=? AND ${access}`).bind(installation,artifactId,installation,actor).first<Row>();if(!r)fail(404,'Artifact unavailable');return {status:200,body:{artifact:dto(r),activities:JSON.parse(r.activities),initiatives:JSON.parse(r.initiatives),filesEnabled:Boolean(r.files_enabled),sectionRevision:r.section_revision,readOnly:Boolean(r.archived)||!r.files_enabled}};
 }
 const reviewing=match?.[2]==='/review';
 if(reviewing?request.method!=='POST':(artifactId?request.method!=='PATCH':request.method!=='POST')||!!match?.[2])fail(405);
 const keys=['title','caption','url','activities','initiatives','sectionRevision'];const v=fields(input,reviewing?['revision','sectionRevision','decision']:artifactId?[...keys,'revision','archived']:keys),current=artifactId?await db.prepare(`SELECT * FROM documentation_artifacts WHERE installation_id=? AND id=? AND ${access}`).bind(installation,artifactId,installation,actor).first<Row>():null;if(artifactId&&!current)fail(404,'Artifact unavailable');
 const rev=artifactId?revision(v.revision):0,sectionRevision=revision(v.sectionRevision);if(artifactId&&!reviewing&&Object.keys(v).every(k=>['revision','sectionRevision'].includes(k)))fail();if(Object.hasOwn(v,'archived')&&typeof v.archived!=='boolean')fail();if(reviewing&&!['reviewed','rejected'].includes(v.decision))fail();if(current?.archived&&(reviewing||v.archived!==false||Object.keys(v).some(k=>!['revision','sectionRevision','archived'].includes(k))))fail(409,'Unarchive the artifact before editing');
 if(['file','preserved-drive'].includes(current?.kind)&&Object.hasOwn(v,'url'))fail(400,'An original file cannot be replaced through metadata editing');
 const changed={...current,...v,caption:Object.hasOwn(v,'caption')?v.caption:current?.caption??'',original_url:current?.original_url??v.url,archived:Object.hasOwn(v,'archived')?Number(v.archived):current?.archived??0,review_decision:reviewing?v.decision:null,reviewed_revision:reviewing?rev:null,reviewer_user_id:reviewing?actor:null,reviewed_at:reviewing?now:null},value=data(changed);
 const newId=artifactId??crypto.randomUUID(),auditId=crypto.randomUUID(),requested=contexts.map(c=>Object.hasOwn(v,c.name)?parseLinks(v[c.name],c.key):artifactId?null:[]);
 const gates:string[]=[`COALESCE((SELECT files_enabled FROM documentation_sections WHERE installation_id=?),1)=1 AND COALESCE((SELECT revision FROM documentation_sections WHERE installation_id=?),0)=?`],args:unknown[]=[installation,installation,sectionRevision],counts:string[]=[],countArgs:unknown[]=[];
 contexts.forEach((c,index)=>{const links=requested[index];if(links===null){counts.push(`(SELECT COUNT(*) FROM documentation_artifact_${c.name} WHERE installation_id=? AND artifact_id=?)`);countArgs.push(installation,newId);return;}counts.push('?');countArgs.push(links.length);gates.push(`NOT EXISTS(SELECT 1 FROM json_each(?) j WHERE NOT EXISTS(SELECT 1 FROM documentation_artifact_${c.name} l WHERE l.installation_id=? AND l.artifact_id=? AND l.${c.column}=json_extract(j.value,'$.${c.key}')) AND NOT EXISTS(SELECT 1 FROM ${c.target} a WHERE a.installation_id=? AND a.id=json_extract(j.value,'$.${c.key}') AND a.revision=json_extract(j.value,'$.revision') AND ${c.eligibility}))`);args.push(JSON.stringify(links),installation,newId,installation);});
 const gate=[...gates,`(${counts.join('+')})<=100`].join(' AND '),gateArgs=[...args,...countArgs],values=dataColumns.map(c=>(value as Row)[c]);
 const mutation=artifactId?db.prepare(`UPDATE documentation_artifacts SET ${dataColumns.map(c=>c+'=?').join(',')},revision=revision+1,updated_at=? WHERE installation_id=? AND id=? AND revision=? AND archived=? AND ${access} AND ${gate}`).bind(...values,now,installation,newId,rev,current!.archived,installation,actor,...gateArgs):db.prepare(`INSERT INTO documentation_artifacts(installation_id,id,${dataColumns.join(',')},author_user_id,created_at,updated_at) SELECT ${Array(14).fill('?').join(',')} WHERE ${access} AND ${gate}`).bind(installation,newId,...values,actor,now,now,installation,actor,...gateArgs);
 const admitted='EXISTS(SELECT 1 FROM audit_log WHERE installation_id=? AND id=?)',admittedArgs=[installation,auditId];const statements=[mutation,db.prepare("INSERT INTO audit_log(id,installation_id,actor_user_id,action,target_type,target_id,created_at) SELECT ?,?,?,?,'documentation_artifact',?,? WHERE changes()=1").bind(auditId,installation,actor,reviewing?'documentation.artifact.reviewed':artifactId?'documentation.artifact.updated':'documentation.artifact.created',newId,now)];
 contexts.forEach((c,index)=>{const links=requested[index];if(links!==null)statements.push(db.prepare(`DELETE FROM documentation_artifact_${c.name} WHERE installation_id=? AND artifact_id=? AND ${admitted}`).bind(installation,newId,...admittedArgs),db.prepare(`INSERT INTO documentation_artifact_${c.name}(installation_id,artifact_id,${c.column}) SELECT ?,?,json_extract(value,'$.${c.key}') FROM json_each(?) WHERE ${admitted}`).bind(installation,newId,JSON.stringify(links),...admittedArgs));});
 statements.push(db.prepare(`INSERT INTO documentation_artifact_revisions(installation_id,artifact_id,revision,actor_user_id,${dataColumns.join(',')},${[...artifactFileColumns,...artifactPreservedColumns].join(',')},created_at) SELECT installation_id,id,revision,?,${dataColumns.join(',')},${[...artifactFileColumns,...artifactPreservedColumns].join(',')},updated_at FROM documentation_artifacts WHERE installation_id=? AND id=? AND ${admitted}`).bind(actor,installation,newId,...admittedArgs));
 contexts.forEach(c=>statements.push(db.prepare(`INSERT INTO documentation_artifact_revision_${c.name}(installation_id,artifact_id,revision,${c.column}) SELECT l.installation_id,l.artifact_id,m.revision,l.${c.column} FROM documentation_artifact_${c.name} l JOIN documentation_artifacts m ON m.installation_id=l.installation_id AND m.id=l.artifact_id WHERE l.installation_id=? AND l.artifact_id=? AND ${admitted}`).bind(installation,newId,...admittedArgs)));
 if(reviewing)statements.push(db.prepare(`INSERT INTO documentation_artifact_reviews(installation_id,artifact_id,revision,reviewed_revision,reviewer_user_id,decision,reviewed_at) SELECT installation_id,id,revision,reviewed_revision,reviewer_user_id,review_decision,reviewed_at FROM documentation_artifacts WHERE installation_id=? AND id=? AND ${admitted}`).bind(installation,newId,...admittedArgs));
 const results=await db.batch(statements);if(results[1]?.meta?.changes!==1)fail(409,'Artifact, association or authority changed; reload');return {status:artifactId?200:201,body:{artifact:dto({...current,...value,id:newId,revision:artifactId?rev+1:0,author_user_id:current?current.author_user_id:actor,created_at:current?.created_at??now,updated_at:now})}};
}

export function validateArtifactBackup(tables:Record<string,Row[]>){
 const bad=()=>fail(400,'Invalid artifact backup'),stamp=(v:unknown)=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}T/.test(v)&&Number.isFinite(Date.parse(v));
 const memberIds=new Set((tables.members??[]).filter(r=>r.installation_id==='primary').map(r=>r.id));
 const fileValid=(r:Row)=>{if(r.kind==='preserved-drive')return typeof r.file_id==='string'&&typeof r.file_root_id==='string'&&typeof r.file_generation==='string'&&typeof r.file_mime==='string'&&typeof r.file_source_id==='string'&&typeof r.file_source_version==='string'&&typeof r.file_version==='string'&&stamp(r.file_copied_at)&&(r.validation_outcome==='native'?r.file_size===null&&r.file_sha256===null:/^[a-f0-9]{64}$/.test(r.file_sha256)&&Number.isSafeInteger(r.file_size)&&r.file_size>0&&r.file_size<=4194304&&['embedded','linked-only'].includes(r.validation_outcome));if(artifactPreservedColumns.some(k=>r[k]!==null))return false;if(r.kind==='external-link')return artifactFileColumns.slice(1).every(k=>r[k]===null);return r.kind==='file'&&typeof r.file_id==='string'&&typeof r.file_root_id==='string'&&typeof r.file_generation==='string'&&/^[a-f0-9]{64}$/.test(r.file_sha256)&&Number.isSafeInteger(r.file_size)&&r.file_size>0&&r.file_size<=4194304&&typeof r.file_mime==='string'&&['embedded','linked-only'].includes(r.validation_outcome);};
 const users=new Set((tables.users??[]).filter(r=>r.installation_id==='primary').map(r=>r.id)),artifacts=new Map<string,Row>(),histories=new Map<string,Map<number,Row>>();
 for(const r of tables.documentation_artifacts??[]){id(r.id);revision(r.revision);data(r);if(r.installation_id!=='primary'||artifacts.has(r.id)||!((r.source==='staff'&&users.has(r.author_user_id)&&r.author_member_id===null)||(['public','discord'].includes(r.source)&&r.author_user_id===null&&memberIds.has(r.author_member_id)))||!fileValid(r)||!stamp(r.created_at)||!stamp(r.updated_at)||Date.parse(r.updated_at)<Date.parse(r.created_at))bad();artifacts.set(r.id,r);}
 for(const r of tables.documentation_artifact_revisions??[]){revision(r.revision);data(r);if(r.installation_id!=='primary'||!artifacts.has(r.artifact_id)||!((users.has(r.actor_user_id)&&r.actor_member_id===null)||(r.actor_user_id===null&&memberIds.has(r.actor_member_id)))||!fileValid(r)||!stamp(r.created_at))bad();const history=histories.get(r.artifact_id)??new Map();if(history.has(r.revision))bad();history.set(r.revision,r);histories.set(r.artifact_id,history);}
 const memberships=new Map<string,Set<string>>();
 contexts.forEach(c=>{const targets=new Set((tables[c.target]??[]).filter(r=>r.installation_id==='primary').map(r=>r.id));for(const historic of [false,true])for(const r of tables['documentation_artifact_'+(historic?'revision_':'')+c.name]??[]){if(r.installation_id!=='primary'||!artifacts.has(r.artifact_id)||!targets.has(r[c.column]))bad();if(historic){revision(r.revision);if(!histories.get(r.artifact_id)?.has(r.revision))bad();}const key=JSON.stringify([r.artifact_id,historic?r.revision:'current']),member=c.name+':'+r[c.column],set=memberships.get(key)??new Set();if(set.has(member)||set.size>=100)bad();set.add(member);memberships.set(key,set);}});
 const members=(artifact:string,rev:number|string)=>JSON.stringify([...(memberships.get(JSON.stringify([artifact,rev]))??[])].sort());
 for(const [key,r] of artifacts){const history=histories.get(key);if(!history||history.size!==r.revision+1)bad();let previous=0;for(let rev=0;rev<=r.revision;rev++){const h=history!.get(rev);if(!h||Date.parse(h.created_at)<previous)bad();previous=Date.parse(h!.created_at);if(rev&&history!.get(rev-1)!.archived){const prior=history!.get(rev-1)!;if(h!.archived!==0||['title','caption','url','original_url'].some(c=>h![c]!==prior[c])||members(key,rev)!==members(key,rev-1))bad();}}
  const first=history!.get(0)!,last=history!.get(r.revision)!;if(first.actor_user_id!==r.author_user_id||first.actor_member_id!==r.author_member_id||first.created_at!==r.created_at||first.archived!==0||last.created_at!==r.updated_at||[...dataColumns,...artifactFileColumns,...artifactPreservedColumns].some(c=>last[c]!==r[c])||members(key,'current')!==members(key,r.revision))bad();
 }
 const reviews=new Map<string,Row>();for(const r of tables.documentation_artifact_reviews??[]){revision(r.revision);revision(r.reviewed_revision);const h=histories.get(r.artifact_id)?.get(r.revision),prior=histories.get(r.artifact_id)?.get(r.reviewed_revision),key=JSON.stringify([r.artifact_id,r.revision]);if(r.installation_id!=='primary'||reviews.has(key)||!h||!prior||r.revision!==r.reviewed_revision+1||r.reviewer_user_id!==h.actor_user_id||!users.has(r.reviewer_user_id)||r.decision!==h.review_decision||r.reviewed_revision!==h.reviewed_revision||r.reviewer_user_id!==h.reviewer_user_id||r.reviewed_at!==h.reviewed_at||r.reviewed_at!==h.created_at||prior.archived!==0||['title','caption','url','original_url','archived'].some(c=>prior[c]!==h[c])||members(r.artifact_id,r.revision)!==members(r.artifact_id,r.reviewed_revision))bad();reviews.set(key,r);}
 for(const [key,r] of artifacts){const history=histories.get(key)!;if(history.get(0)!.review_decision!==null||history.get(0)!.url!==r.original_url)bad();for(const [rev,h] of history){if([...artifactFileColumns,...artifactPreservedColumns].some(c=>h[c]!==r[c])||h.original_url!==r.original_url||Boolean(h.review_decision)!==reviews.has(JSON.stringify([key,rev])))bad();}}

}
