import type {Env} from './index.ts';
import {HttpError} from './http-error.ts';
import {googleCapability,googleConnectionRow,googleHash} from './google-connection.ts';
import {decryptIntegration} from './integration-crypto.ts';
import {pickerProvider} from './google-drive-picker.ts';
export const storageColumns={google_drive_storage:['installation_id','revision','root_id','root_name','generation','verified_iv','verified_at']} as const;
const admin="EXISTS(SELECT 1 FROM users WHERE installation_id='primary' AND id=? AND active=1 AND role='admin')";
function fail(status=409):never{throw new HttpError(status,'Shared Drive storage could not be confirmed; reload and select the private root again');}
const validId=(v:unknown)=>typeof v==='string'&&/^[A-Za-z0-9_-]{1,128}$/.test(v);
export async function storageRoute(env:Env,request:Request,actor:{userId:string;expiresAt:number},input?:unknown){
 const db=env.DB;if(!db)fail(503);const authorized=await db.prepare(`SELECT 1 AS ok WHERE ${admin}`).bind(actor.userId).first();if(!authorized)fail(403);
 const current=await db.prepare("SELECT * FROM google_drive_storage WHERE installation_id='primary'").first<Record<string,any>>();
 if(request.method==='GET'){
  let capability:Awaited<ReturnType<typeof googleCapability>>|undefined;try{capability=await googleCapability(env,'drive');}catch{}
  const snapshot=await db.prepare("SELECT s.*,CASE WHEN s.verified_at IS NOT NULL AND s.generation=? AND s.verified_iv=? AND EXISTS(SELECT 1 FROM google_connections c WHERE c.installation_id=s.installation_id AND c.active_iv=s.verified_iv AND c.grant_error IS NOT 'revoked') THEN 1 ELSE 0 END AS verified FROM users u LEFT JOIN google_drive_storage s ON s.installation_id=u.installation_id WHERE u.installation_id='primary' AND u.id=? AND u.active=1 AND u.role='admin'").bind(capability?.generation??'',capability?.signature??'',actor.userId).first<Record<string,any>>();if(!snapshot)fail(403);
  return {configured:!!snapshot.root_id,revision:snapshot.revision??0,rootId:snapshot.root_id??null,rootName:snapshot.root_name??null,verifiedAt:snapshot.verified_at??null,verifiedForConnection:snapshot.verified===1};
 }
 if(request.method!=='PUT')fail(405);if(!input||typeof input!=='object'||Array.isArray(input))fail(400);const v=input as Record<string,unknown>;if(Object.keys(v).some(k=>!['revision','pickerIntentId','connectionRevision'].includes(k))||!Number.isSafeInteger(v.revision)||Number(v.revision)<0||Number(v.revision)>=Number.MAX_SAFE_INTEGER||!Number.isSafeInteger(v.connectionRevision)||!validId(v.pickerIntentId))fail(400);
 if(v.revision!==(current?.revision??0)||actor.expiresAt<=Date.now())fail();
 const session=request.headers.get('cookie')?.split(';').map(s=>s.trim()).find(s=>s.startsWith('lancerlogin_session='))?.slice('lancerlogin_session='.length);if(!session)fail(401);const sessionHash=await googleHash(session);
 const capability=await googleCapability(env,'drive'),connection=await googleConnectionRow(env);if(!connection||connection.revision!==v.connectionRevision||connection.active_iv!==capability.signature)fail();
 const intent=await db.prepare("SELECT * FROM google_picker_intents WHERE installation_id='primary' AND id=? AND actor_user_id=? AND session_hash=? AND purpose='root' AND status='selected' AND expires_at>?").bind(v.pickerIntentId,actor.userId,sessionHash,Date.now()).first<Record<string,any>>();if(!intent||intent.generation!==capability.generation||intent.connection_revision!==connection.revision||!env.INTEGRATION_KEY)fail();
 const selected=await decryptIntegration(intent.ciphertext,intent.iv,env.INTEGRATION_KEY);if(selected.installation!=='primary'||selected.purpose!=='drive-picker'||!validId(selected.fileId))fail();
 const token=await capability.accessToken(),headers={authorization:'Bearer '+token};
 const file=await pickerProvider('https://www.googleapis.com/drive/v3/files/'+selected.fileId+'?fields=id,name,mimeType,trashed,driveId,ownedByMe,capabilities(canAddChildren)',{headers}, env);
 if(file.id!==selected.fileId||file.mimeType!=='application/vnd.google-apps.folder'||file.trashed!==false||file.driveId||file.ownedByMe!==true||(file.capabilities as any)?.canAddChildren!==true||typeof file.name!=='string'||!file.name||file.name.length>255)fail();
 const permissions=await pickerProvider('https://www.googleapis.com/drive/v3/files/'+selected.fileId+'/permissions?fields=permissions(type,role),nextPageToken&pageSize=100',{headers}, env);if(!Array.isArray(permissions.permissions)||permissions.permissions.length!==1||permissions.nextPageToken||permissions.permissions.some((p:any)=>p.type!=='user'||p.role!=='owner'))fail();
 const now=new Date().toISOString(),auditId=crypto.randomUUID();
 const results=await db.batch([db.prepare(`DELETE FROM google_picker_intents WHERE installation_id='primary' AND id=? AND actor_user_id=? AND session_hash=? AND purpose='root' AND status='selected' AND iv=? AND expires_at>? AND generation=? AND connection_revision=? AND ${admin} AND ?>CAST(unixepoch('subsec')*1000 AS INTEGER) AND EXISTS(SELECT 1 FROM google_connections WHERE installation_id='primary' AND revision=? AND active_iv=? AND grant_error IS NOT 'revoked') AND COALESCE((SELECT revision FROM google_drive_storage WHERE installation_id='primary'),0)=?`).bind(intent.id,actor.userId,sessionHash,intent.iv,Date.now(),capability.generation,connection.revision,actor.userId,actor.expiresAt,connection.revision,capability.signature,v.revision),db.prepare("INSERT INTO google_drive_storage(installation_id,revision,root_id,root_name,generation,verified_iv,verified_at) SELECT 'primary',1,?,?,?,?,? WHERE changes()=1 ON CONFLICT(installation_id) DO UPDATE SET revision=google_drive_storage.revision+1,root_id=excluded.root_id,root_name=excluded.root_name,generation=excluded.generation,verified_iv=excluded.verified_iv,verified_at=excluded.verified_at").bind(selected.fileId,file.name,capability.generation,capability.signature,now),db.prepare("INSERT INTO audit_log(id,installation_id,actor_user_id,action,target_type,target_id,created_at) SELECT ?,'primary',?,'drive.storage.configured','shared_drive_storage','primary',? WHERE changes()=1").bind(auditId,actor.userId,now)]);
 if(results[2]?.meta?.changes!==1)fail();return {saved:true,revision:Number(v.revision)+1,rootId:selected.fileId,rootName:file.name,verifiedAt:now};
}
export function prepareStorageRestore(tables:Record<string,Record<string,any>[]>){const rows=tables.google_drive_storage??[];if(rows.length>1)fail(400);for(const row of rows){if(row.installation_id!=='primary'||!Number.isSafeInteger(row.revision)||row.revision<1||row.revision>=Number.MAX_SAFE_INTEGER||!validId(row.root_id)||typeof row.root_name!=='string'||!row.root_name||row.root_name.length>255||typeof row.generation!=='string'||!row.generation||row.generation.length>100||(row.verified_iv===null)!==(row.verified_at===null)||row.verified_iv!==null&&(typeof row.verified_iv!=='string'||!/^[A-Za-z0-9+/_=-]{12,100}$/.test(row.verified_iv)||typeof row.verified_at!=='string'||!Number.isFinite(Date.parse(row.verified_at))))fail(400);row.verified_iv=null;row.verified_at=null;}}
